### ISSUE TITLE
Cuaderno Bomber error textura al volver al menú

### ISSUE THREAD

**Issue by caldivargas** [mupen64plus-ae/mupen64plus-ae#1006]
En la versión de Legend of Zelda, The - Majora's Mask (Europe) (GameCube).z64 Big Endian con parche de Aroenai, ozidual (https://www.romhacking.net/hacks/2962/) que revierten los cambios de gamecube a n64. Ocurre un error al volver del cuaderno bomber al menú.
![Screenshot_20220216-152731](https://user-images.githubusercontent.com/78030406/154363422-e8cd5320-8692-4a68-895c-915cd2b6cb81.jpg)
![Screenshot_20220216-152733](https://user-images.githubusercontent.com/78030406/154363465-420bfadb-6069-4f77-b124-666743156bb1.jpg)
![Screenshot_20220216-152736](https://user-images.githubusercontent.com/78030406/154363484-e261a297-938a-49c5-8641-a8bb51d51d10.jpg)

En la versión norteamericana de Majora's Mask n64 no ocurre el problema.

![Screenshot_20220216-152510](https://user-images.githubusercontent.com/78030406/154363728-9fb8c16a-2a42-46c3-a285-3f8d9102dc43.jpg)
![Screenshot_20220216-152516](https://user-images.githubusercontent.com/78030406/154363790-845d14fa-1f6d-4b8e-b5c6-14d39424bb5b.jpg)

Mi configuración de FBe
Swap FB: On VI updated call
Copy Color Buffer to RDRAM: Async mode(2 buffers)
Copy depth buffer to RDRAM: Software Rendered
Copy Auxiliary Buffers to RDRAM: YES

Creo que ocurre el error debido a esto:

1. Creo que el fallo puede ser por la región de la rom.
2. Que sea de la versión de Gamecube.
3. Que sea el parche, aunque tengo entendido que esta rom funciona en una N64 real. 
4. Probablemente debe asignarle un delay a la pantalla para que tenga tiempo que el FB dibuje la imágen detrás del menú.
5. Que no registre las count per op por default como una rom de n64 convencional.
6. Registrar a la rom gamecube/pal como cualquier rom de n64/ntsc/pal.

Mi dispositivo: Oneplus 3T
SO: Android 9
Snapdragon 821
Ram: 6 Gb
Adreno 530
OpenGL Es 3.2

**Comment by fzurita** [comment]
Ok, gracias, investigaré.

**Comment by caldivargas** [comment]
Revisando las notas del parche, el error del cuaderno Bomber está presente en el parche y no en el emulador.

Notas:

Issues planned to be addressed:

> 3rd Quick Spin attack combo cannot trigger in OoT due to a coding glitch (the animation exceeds the expected time required to complete the combo). This was fixed in subsequent games.

> Port the Russian translation patches from Zelda64RUS

> Port the 3DS OoT Spanish Translation text (in progress)

> Screen corruption switching between the Bomber's notebook and the pause screen (problem with the MM GC roms, need someone with the skills to fix)

> Pause screen background does not have anti-aliasing applied (problem with the OoT/MM GC roms, need someone with the skills to fix)

https://krikzz.com/forum/index.php?topic=5161.0

Fue un error en mi traducción.
