### ISSUE TITLE
[Issue]: Installation problem

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#1009]
### Describe the bug

When I try installing the latest Nightly build on a Nvidia Shield TV I am getting an error: Blocked by play protect

### Steps to reproduce

- Download the latest Nightly Build
- Try to install it on a Nvidia Shield TV

### Expected behavior

That the installation is successful.

### Add screenshots

![20220220_205844](https://user-images.githubusercontent.com/24655170/154861948-b3e1e81f-f031-4c3e-9213-c20c12f655d3.jpg)

**Comment by fzurita** [comment]
Well, choose to install anyways. There is not much I can do about that error box.

**Comment by bladeoner** [comment]
I didn't mention that I was trying the 'Install anyway' option. That didn't work at first but after the fifth time it works.

Thanks for the quick response.
