### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by clondy999** [mupen64plus-ae/mupen64plus-ae#1015]
### Describe your question

![image](https://user-images.githubusercontent.com/73311186/157663626-fb854064-3140-4cd9-ba37-de3ac288f18e.png)

sorry. I really don't understand.
I have set up the awk environment.

FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mupen64plus-core:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using F:\Code\mupen64plus-ae\mupen64plus-core\Android.mk: Build command failed.
  Error while executing process F:\Android\SDK\ndk\23.1.7779620\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\Code\mupen64plus-ae\mupen64plus-core\Android.mk NDK_APPLICATION_MK=F:\Code\mupen64plus-ae\mupen64plus-core\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-23 NDK_OUT=F:\Code\mupen64plus-ae\mupen64plus-core\build\intermediates\cxx\Debug\732w5z42/obj NDK_LIBS_OUT=F:\Code\mupen64plus-ae\mupen64plus-core\build\intermediates\cxx\Debug\732w5z42/lib APP_CPPFLAGS+=-fexceptions NDK_APPLICATION_MK:=Application.mk -j11 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
  Compiling asm_defines.c
  Generating asm_defines_nasm.h and asm_defines_gas.h
  
  F:/Code/mupen64plus-ae/mupen64plus-core/mupen64plus-core.mk:180: *** multiple target patterns.  Stop.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by liuwen56** [comment]
I have the same problem like this, is there a solution?

**Comment by fzurita** [comment]
If you look at the build instructions:

If running Windows, make sure you install Git, Python, awk and required Microsoft Visual C++ Redistributable (i.e. cmake 3.18.1 requires Microsoft Visual C++ Redistributable 2015) and that the binaries are in your path environment variable.
