### ISSUE TITLE
[Question]: Black Screen powerpuff girls and some aleck 64 ports

### ISSUE THREAD

**Issue by AngelofMe** [mupen64plus-ae/mupen64plus-ae#1018]
### Describe your question

PPG black screen for a long time
I tested some aleck 64 ports for nintendo 64 by Zoinkity
ok: vivid dolls, tower & shaft, star soldier, kuru kuru fever, eleven beat, donchan puzzle, magical tetris(en-translated)
black screen: tower & shaft(en-translated), magical tetris and others
Aleck64 Arcade.zip(10 aleck 64 .z64 files)
Including coin button for Project64/MupeN64/RetroArch
<Link removed>
Zoinkity's YouTube channel
https://m.youtube.com/user/Zoinkity/videos

**Comment by AngelofMe** [comment]
> I'm sorry, I had to delete your link to Internet archive since this project can't be associated with piracy.
> 
> Have you tried different different video plugins? Glide64mk2 is very old and unmaintained.
> 
> I would try GLideN64 or the Software renderer. To change the plugin, you can change it globally for all games by going to profiles then "select profiles" and change the "emulation profile" there. You can also change it for a specific game by selecting the game, going to settings, and changing the emulation profile there.

Yes, nothing happened. Emulation Profile is very important like playing Kirby 64.I changed it for all games

**Comment by AngelofMe** [comment]
Powerpuff Girls, The - Chemical X-Traction
RetroArch Libretro
Parallel-N64: good
Mupen64Plus-Next(GLES 2.0 and GLES 3.0): not good, black screen
Parallel-N64 is the only one core to play this game
Libretro Mupen64plus-Next Github Repositoryhttps://github.com/libretro/mupen64plus-libretro-nx
Libretro Parallel-N64 Github Repository
https://github.com/libretro/parallel-n64

**Comment by fzurita** [comment]
Can you select the game, then go to advanced. From there, can you try different count per operation values?
