### ISSUE TITLE
Banjo-Kazooie, text slow or missing, pop-ups cause black-screen

### ISSUE THREAD

**Issue by cannon1349** [mupen64plus-ae/mupen64plus-ae#102]
Speech text is slow or sometimes not shown.  Some things that indicate value that pop up at the bottom of the screen (such as jiggies, chimpy's orange, etc) cause the screen to render black until the icon goes away. I know this game front and back, and will be looking for anything and everywhere for more.  Email me if you want me to look for more problems Paul, I will gladly help!

**Comment by fzurita** [comment]
Upstream issue
