### ISSUE TITLE
[Issue]: Startup problem

### ISSUE THREAD

**Issue by clondy999** [mupen64plus-ae/mupen64plus-ae#1020]
### Describe the bug

I'm using my own front-end. I start mupen64 plusae through the shell. After I quit the game, I found that my front-end was also closed

Platform: Android

### Steps to reproduce

null

### Expected behavior

Just close mupen64plusae and return to my front end

**Comment by fzurita** [comment]
I don't see how this app could cause your front end to close. They are two completely separate applications, do it's really impossible for this app to cause that.
