### ISSUE TITLE
[Feature request]: Official discord server for mupen64ae

### ISSUE THREAD

**Issue by YOSHI200567** [mupen64plus-ae/mupen64plus-ae#1021]
### Describe the feature

Here is a official discord for mupen64ae because dev where lazy ass and never made one so made one here link to it
https://discord.gg/xBDFszd2Qg

**Comment by YOSHI200567** [comment]
Also will give owner dev made mupen64 fz if what it

**Comment by fzurita** [comment]
This is not an official ditches server for the app, do don't advertise or here. Also, it's a little rude too come in here and start calling a developer "lazy ass".
