### ISSUE TITLE
[Issue]: sin and punishment does not shown boxact in gui of mupen64plus ae/fz

### ISSUE THREAD

**Issue by YOSHI200567** [mupen64plus-ae/mupen64plus-ae#1023]
### Describe the bug

Shown put sin and punishment on mupen64plus ae put on showing up on app what is english patch

### Steps to reproduce

Put rom folder see thier is no boxact so guys put for database make app shown thier.

### Expected behavior

Should show this boxact
![sin-and-punishment-na-box-art large](https://user-images.githubusercontent.com/102778335/161409874-1a372ee4-5e67-407f-a1f9-4b0898227dfc.jpg)

### Add screenshots

![sin-and-punishment-na-box-art large](https://user-images.githubusercontent.com/102778335/161409819-a310487a-49ea-4dd6-ad01-81dbb7c62648.jpg)
But shows this instead 
![Screenshot_20220402-231904_M64Plus AE](https://user-images.githubusercontent.com/102778335/161409832-1c5e14e8-c4a8-42ea-90c3-734c24b7dc30.jpg)
One show mupen64 with no boxact.
Here link to wiki page
https://github.com/mupen64plus-ae/mupen64plus-ae-meta/wiki/Sin_and_Punishment_-_Successor_of_the_Earth

**Comment by YOSHI200567** [comment]
@fzurita this fyl bug in emulator at last 5 years not showing boxact so please fixed in mupen64plus ae and fz.

**Comment by fzurita** [comment]
Hello, I don't have cover art for most patches out there, specially if they change the ROM header in any way. Can you link me to the patch? and maybe I can add this one then.

**Comment by YOSHI200567** [comment]
@fzurita problem rom patch does not have just patch whole rom and problem real rom patch just a textures pack mod. What tell you is add sin and punishment to mupen64plus ae meta.

**Comment by YOSHI200567** [comment]
So tell how to get rom harder for game file.

**Comment by YOSHI200567** [comment]
@fzurita problem for patch site needed textures pack.
https://www.romhacking.net/translations/920/ but one have rom patch if taking my guess probably ebay english rom one. Also boxact should some as jupan ver just english patch or take put mupen64plus ae database one upload.
