### ISSUE TITLE
[Feature request]: add Guilde-64 mid

### ISSUE THREAD

**Issue by YOSHI200567** [mupen64plus-ae/mupen64plus-ae#1024]
### Describe the feature

So made 2 custom guide 64 configure which is call Guilde 64 mid and Guilde 64 interpreter. So guys added this official build because interpreter need for sin and punishment english patch rom hack to load up. And mid has read Framebuffer every frame turn on fixed mario kart 64 pc motor glitch.

### Add screenshots

![Screenshot_20220403-115442_M64Plus_FZ_Pro](https://user-images.githubusercontent.com/102778335/161436802-1ba0aa59-b27d-4040-8758-d09be9d3b5f3.jpg)

**Comment by YOSHI200567** [comment]
Here Config files if need for testing 
[mupen64.zip](https://github.com/mupen64plus-ae/mupen64plus-ae/files/8404954/mupen64.zip)

**Comment by fzurita** [comment]
This is not really an issue, of anything this should go under discussion.

**Comment by YOSHI200567** [comment]
How hand would he add pugins into emulator it self.

**Comment by fzurita** [comment]
That question had a very broad answer. You would have to ask about the very specific plugin you are talking about.

**Comment by YOSHI200567** [comment]
@fzurita check discussions added staff to it when more information why you should add it to master build of mupen64plus fz and ae
