### ISSUE TITLE
Touchscreen, only A and B buttons work

### ISSUE THREAD

**Issue by skrapz21** [mupen64plus-ae/mupen64plus-ae#103]
I updated the mupen64plus app and now when i try to play any game the touchscreen controller won't work except for the A and B buttons. I am using an LG Motion 4G that had never had this issue before in previous updates and yes i tried uninstalling and reinstalling the app, didn't work. Please help, I love bring able to play my old 64 games on my phone!

**Comment by fzurita** [comment]
Not enough detail
