### ISSUE TITLE
[Feature request]: Seta - Aleck64 no-intro romsets

### ISSUE THREAD

**Issue by AngelofMe** [mupen64plus-ae/mupen64plus-ae#1032]
### Describe the feature

https://datomatic.no-intro.org/index.php?page=search&s=227
BigEndian: Not verified  Eleven Beat (Japan)
ZHAJ
BigEndian: Not verified  Hanabi de Doon! - Don-chan Puzzle (Japan)
BigEndian: Not verified  Hi Pai Paradise (Japan)
BigEndian: Not verified  Kuru Kuru Fever (Japan)
BigEndian: Not verified  Magical Tetris Challenge (Japan)
ZCAJ
BigEndian: Not verified  Mayjinsen 3 (Japan)
ZSCJ
BigEndian: Not verified  Star Soldier - Vanishing Earth (Japan)
ZHBJ
BigEndian: Not verified  Super Real Mahjong VS (Japan)
ZSEJ
BigEndian: Not verified  Tower & Shaft (Japan)
BigEndian: Not verified  Vivid Dolls (Japan)
ZSAJ
BigEndian: Trusted (1) (Not Verified)  Hi Pai Paradise 2 (Japan)
BigEndian: Trusted (1) (Not Verified)  Pachislo DX (Japan)
ZSFJ
BigEndian: Trusted (1) (Not Verified)  Slosseum Dual (Japan)
BigEndian: Trusted (1) (Not Verified)  Super Real Mahjong VS (Japan) (Rev 1)
ZSEJ
Loaded: 14 item(s). 

Format: BigEndian   ByteSwapped

Standard DAT
https://datomatic.no-intro.org/index.php?page=download&op=dat&s=227
P/C XML
https://datomatic.no-intro.org/index.php?page=download&op=xml&s=227

**Comment by fzurita** [comment]
Can you describe what the exact problem is?
