### ISSUE TITLE
[Issue]:  Shadows gets messed up when using stretch option on banjo tooie

### ISSUE THREAD

**Issue by matheusstaffa** [mupen64plus-ae/mupen64plus-ae#1055]
### Describe the bug

When i activated the option for stretch screen for banjo tooie (USA) the shadows under banjo stays as a black box. I am using mupen 64 plus FZ pro on latest version with the 4K resolution with a ultrawide android phone and i want to use stretch to apply a ultrawide screen cheat (the cheat was disabled when the bug happened).

### Steps to reproduce

1 - activate the stretch screen option.
2 - use the native resolution option.
3 - activate widescreen on ingame options.
4 - begin the gameplay.

### Expected behavior

Shadows properly rendered.

### Add screenshots

![Screenshot_20220819-013116](https://user-images.githubusercontent.com/23277952/185543363-f7804382-beb6-4247-80ed-4577fc415bfb.png)

**Comment by fzurita** [comment]
Have you tried switching the emulation profile? I would use the GLideN64 ones.

**Comment by matheusstaffa** [comment]
Yes, i did. Changing to GlideN64 fixes the shadows but it does not support 4k resolution and not stretch the entire screen (there's a black bar at the right and left side of the screen).

**Comment by fzurita** [comment]
GLideN64, parallel, and software renderer (angrylion-rdp-plus) are the only real supported video plugins now a days. Ask the others have a lot of random issues like this one that will never be addressed.

Why do you say that GLideN64 doesn't support 4k resolution? It should support it just fine.

GLideN64 if also not accurate which is probably why you have the black bars. You can eliminate them by selecting the game, going to settings, and using the zoom option.

**Comment by matheusstaffa** [comment]
In the options the gliden64 supports up to 4X resolution. Since banjo tooie renders at 304×226 it would scale up to 1216x904. The zoom option cropped a little at the top and bottom but in this game works ok. Maybe a zoom option for separate width and height should be better.

**Comment by fzurita** [comment]
You can turn off the native resolution factor and it will use your chosen render resolution.

The zoom option simulates overscan.

**Comment by matheusstaffa** [comment]
Thanks, the game is looking great. I was just confused with the options.
