### ISSUE TITLE
[Question]: Do you know how we can fix the artifact name in the workflows?

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#1069]
### Describe your question

Hi @fzurita the Github Actions jobs are showing the following message that the 'set-output' command is deprecated. I tried using the link to fix it but I didn't manage to get it done. The uploaded artifact name is missing a part of the name. Before the branch name and sha where added to the name. Do you have any idea how we can fix it?

_The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands_

Thanks in advance.

**Comment by fzurita** [comment]
Hmm, interesting, not of the top of my head. I'll have to look into it.
