### ISSUE TITLE
[Issue]: Netplay black screen when start

### ISSUE THREAD

**Issue by jiujitiancai** [mupen64plus-ae/mupen64plus-ae#1075]
### Describe the bug

When start Netplay It is black screen.

I find it is caused by this commit: 
4345bea25db8766d67bf29e6adf24c4486725f69

please fix it

### Steps to reproduce

1, click a game 
2, start netplay server
3, click start

### Expected behavior

No black screen

**Comment by OhThomas** [comment]
@jiujitiancai Does this happen even when you change video plugins? I can only recreate this when using the gln video plugin specifically

**Comment by fzurita** [comment]
Oh, nice catch, I had not noticed that this was happening with the glN64 emulation profile, but sound keeps playing.

Of the many people mentioning this issue nobody has mentioned what plugin they were using.

**Comment by fzurita** [comment]
This should be fixed here: 8be2de35c9f6e84df26c80047e0de38386708e69

**Comment by EndangeredNayla** [comment]
Nope
