### ISSUE TITLE
[Feature request]: Single/Multiple Player Checkbox

### ISSUE THREAD

**Issue by soundsnow** [mupen64plus-ae/mupen64plus-ae#1085]
### Describe the feature

Virtual Gamepad Player
P1 Checkbox
P2 Checkbox
P3 Checkbox
P4 Checkbox
![image42](https://user-images.githubusercontent.com/109885044/210162732-5c561b30-f157-461e-a48f-6a749dc79523.png)

P2 On, P4 On
P2 Up, P4 Up

**Comment by fzurita** [comment]
This is already available. Go to settings then input and choose three "multiplayer" option. In the select which controllers are connected. Then enable "all emulated controlled are always attached" or disable it based on preference.
