### ISSUE TITLE
Glover- Rendering issues, screen doesn't show, game doesn't play correctly

### ISSUE THREAD

**Issue by cannon1349** [mupen64plus-ae/mupen64plus-ae#109]
Glover does not start with the original plug-in. The gles2rice plug-in shows the first menu before any animation, then crashes.  I switched to the cached interpretor, got to the main menu, and the game is extremely glitchy and the castle is blocked by the game fonts.  The pure interpretor makes it much worse.

**Comment by fzurita** [comment]
Upstream issue
