### ISSUE TITLE
[Feature request]: fix START button position worse than real controller

### ISSUE THREAD

**Issue by soundsnow** [mupen64plus-ae/mupen64plus-ae#1102]
### Describe the feature

@fzurita Why make us go so far? so tired
![image75](https://user-images.githubusercontent.com/109885044/219642073-a21bd885-e7f6-4d94-b9c1-3e208898e8bf.png)

**Comment by fzurita** [comment]
It's already adjustable. Go to profiles then touchscreen. Select "Everything" and hit copy. Give it a name and hit ok.

You will be able to modify positions there.

Once done, just select your profile under "select profiles".
