### ISSUE TITLE
[Question]: Game Folder Name

### ISSUE THREAD

**Issue by soundsnow** [mupen64plus-ae/mupen64plus-ae#1104]
### Describe your question

Game File Name instead of sha/md/crc
SUPERMARIO64 (J) 2D727C3278AA232D94F2FB45AEC4D303
Filename: Super Mario 64 (Japan) (Rev 3) (Shindou Edition).z64
Folder: Super Mario 64 (Japan) (Rev 3) (Shindou Edition)
I don't know what's its revision(Rev ?)

**Comment by fzurita** [comment]
Hmm, what's the actual issue here?

**Comment by fzurita** [comment]
Game holder name is "good name" + md5.

This way you can remember your ROM, and after finding it again, your save states would still work.
