### ISSUE TITLE
Pokemon Stadium, distorted graphics

### ISSUE THREAD

**Issue by monsieur-deal** [mupen64plus-ae/mupen64plus-ae#111]
Frames in the menu have distorted graphics in all three video plugins.

**Comment by fzurita** [comment]
Upstream issue

**Comment by bear91** [comment]
I know this thread is years old but im having trouble once i get to the point where you select your 6 pokemon and when you choose the tree to battle

**Comment by fzurita** [comment]
Did you try switching video plugins? Specifically, if you are using Mupen64plus FZ, try GLideN64.

**Comment by bear91** [comment]
I tried all three and im using AE.

**Comment by fzurita** [comment]
Ok, do you have access to the play store and have Android 4.4 and up? Try this link:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

That is the newest version of Mupen64Plus-AE with FZ branding because I'm maintaining it.

**Comment by bear91** [comment]
Im trying it out now. So far the graphics are perfext until i get to the selection process. I wish i knew how to upload a screen shot to show you

**Comment by fzurita** [comment]
Try the GLideN64-Medium emulation profile.

**Comment by bear91** [comment]
Got it! You totally rock!
