### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by master1274** [mupen64plus-ae/mupen64plus-ae#1110]
### Describe the bug

In the latest builds, I observe a regression in the game Gex 3 - Deep Cover Gecko (U) on the plugin GlideN64 (any accurate). Black screen, the sound of the running game sounds. Device Shield Tablet, Android 7.0, armeabi-v7a.

### Steps to reproduce

Game launch

### Expected behavior

Availability of video

**Comment by fzurita** [comment]
This could be a shader cache issue. Go to tools in the app and choose to clear the shader cache. Then try the game again.

**Comment by master1274** [comment]
Clearing the shader cache did not solve the problem. It turns out that the problem in this game on my device appeared a very long time ago. I checked previous versions of the app. Everywhere found the same problem. We managed to get normal display on a very old version Mupen64Plus FZ_3.0.222 (beta) I was interested in the community, in current versions arm64-v8a there is no problem with this game.

**Comment by fzurita** [comment]
Ok, from that it sounds like it was an update to GLideN64 that caused the problem.

You could try creating a custom profile of GLideN64 and try toggle different options on and off to try to track down the problem.

**Comment by master1274** [comment]
Ok, I'll try. But there are a lot of options. Maybe from this video, as a developer, you will understand the direction of what exactly I should switch? https://drive.google.com/file/d/1lmWjOYZZIiqN_JAP7Lv36RYJLwLFqyQs/view?usp=drivesdk

**Comment by master1274** [comment]
In interpreter mode with cache, the image is there, of course the game is slow. I don't think this can be called a bug.

**Comment by fzurita** [comment]
It's really hard to say. It looks like either a texture format issue or a shader compilation issue.

Did you say that non accurate profiles work ok? 

Is that's the case, if you make a copy of the accurate profile or medium profile, you can then see what options are set by editing it.

There is not much different between medium and accurate. You can then just try making a copy of medium and try enabling each option at a time that is present in the accurate profile until you find the option that causes the issue.

**Comment by master1274** [comment]
Inaccurate profiles also have exactly the same problem. Therefore, I have nothing to compare in their settings.

**Comment by fzurita** [comment]
Gotcha, so it's always broken no matter what. My previous comment still applies. A texture format issue or shader compilation issue.

Your best bet world be to make a bug updated here:
https://github.com/gonetz/GLideN64/issues

But, without access to the device, it's unlikely to every get fixed.

**Comment by master1274** [comment]
Shield Tablet 32GB/LTE, Tegra K-1, Android 7.0, ARMv7, 320 dpi(1920х1200), OpenGL ES 3.2, Vulkan 1.0, Core 4x ARM Cortex-A15 - 2218 MHz. 
[null.txt](https://github.com/mupen64plus-ae/mupen64plus-ae/files/10841117/null.txt)

**Comment by master1274** [comment]
Exactly the same problem on the device Redmi 8A, Android 10 (64-bit processor, 32-bit instruction set). The problem is general in nature of the dynamic recompiler armeabi-v7a. Because it doesn't exist in interpreter mode. Can you move the issue upstream to the appropriate branch?

**Comment by master1274** [comment]
It is very difficult for me to communicate on the topic of emulation through Google Translate. The problem occurs on different devices ARMv7.
![Screenshot_2023-03-01_14-25-56](https://user-images.githubusercontent.com/20639709/222127363-e323ef59-eac1-4ac4-88cd-56f47232a3ed.png)
![Screenshot_2023-03-01_14-26-40](https://user-images.githubusercontent.com/20639709/222127422-82b2f5b1-1cfe-4eb7-80dc-e436d02e917b.png)

**Comment by master1274** [comment]
If there is no 32-bit device to test the problem, then you can catch the problem by installing the emulator assembly with the library only armeabi-v7a on the 64-bit device

**Comment by fzurita** [comment]
Yeah, a device would had been an issue if it only affected tegra GPUs.

This seems to be a dynarec issue. So obtaining a device is not an issue. This is unfortunately not an area I'm an expert in. It's an upstream issue.

I will make an issue upstream, but not sure when it will get fixed.

**Comment by master1274** [comment]
https://github.com/gonetz/GLideN64/issues/2781
Is there really no confirmation in the universe that the game is completely broken for emulation, on the current version of the core, on all 32-bit ARM devices?

**Comment by fzurita** [comment]
I created an upstream issue: https://github.com/mupen64plus/mupen64plus-core/issues/1024 

It will be tracked there if anyone decides to fix it there.
