### ISSUE TITLE
Shadowman N64, unable to climb waterfalls

### ISSUE THREAD

**Issue by teryonandjunk** [mupen64plus-ae/mupen64plus-ae#115]
This emulator is fantastic but theres a problem...the reason i downloaded this emulator is  to play a game called shadowman that i never finished as a kid. I made it my goal to and this emulator got my hopes up. The game runs smooth and everything is fine.,however im at a certain point the game where i need to climb waterfalls in order to progress. All i have to do is run foward to climb the waterfall but the character wont climb. Hell start for maybe a milisecond  then stop and fall  right back down.,ive  tried different roms to make sure that its the emulator and im correct. I even tried mapping the foward button to the volume button on my phone. No dice its really sad. Is there anything you can do? Please whatever way i can assist i will you said on your FAQS a link to the save slot would help, if you can tell me how to give you a link ill even do that., i just really really want to finish this. Its been,a long time goal of mine.

**Comment by fzurita** [comment]
Upstream issue
