### ISSUE TITLE
[Issue]: Crash when launching any games.

### ISSUE THREAD

**Issue by master1274** [mupen64plus-ae/mupen64plus-ae#1156]
### Describe the bug

When starting any game, it crashes. In the last two builds. Latest working build - Use parallel-rsp for RSP-HLE fallback #47
Device:
Shield Tablet 32GB/LTE, Tegra K-1, Android 7.0, ARMv7, 320 dpi(1920х1200), OpenGL ES 3.2, Vulkan 1.0, Core 4x ARM Cortex-A15 - 2218 MHz.

### Steps to reproduce

Launch any game

### Expected behavior

Performance

**Comment by master1274** [comment]
It seems I found how to open the log.
[--------- beginning of main_[ 11-09 16﹕28﹕41.189 1.txt](https://github.com/mupen64plus-ae/mupen64plus-ae/files/13308618/---------.beginning.of.main_.11-09.16.28.41.189.1.txt)

**Comment by fzurita** [comment]
Unfortunately that doesn't help much. Do you have adb installed on your computer? And are you able to put your tablet on developer mode while it's connected to your computer?

**Comment by master1274** [comment]
There's a little more information here. But I'm not sure that's enough
[--------- beginning of main_[ 11-09 16﹕33﹕45.491 1.txt](https://github.com/mupen64plus-ae/mupen64plus-ae/files/13308705/---------.beginning.of.main_.11-09.16.33.45.491.1.txt)
Unfortunately, I do not have root rights or a personal computer to use adb

**Comment by fzurita** [comment]
That's not great. I'm going to try to find some more older devices to see if I can reproduce the crash.

It's looking like the newest android SDK or NDK may have broken older android version support in some way.

**Comment by master1274** [comment]
Does the warning on the build page in the version where the problem appeared make sense in the context of the problem?
![Screenshot_20231113-061417](https://github.com/mupen64plus-ae/mupen64plus-ae/assets/20639709/d8c12c69-8ec3-4f9d-a663-013c989315ca)

**Comment by fzurita** [comment]
Possibly, if a corrupt build was made. Let me double check that.

**Comment by fzurita** [comment]
So it seems like the release version of the app has some necessary libraries being stripped out. I have been testing with the debug build which didn't have that issue. It should not be difficult to resolve.

**Comment by fzurita** [comment]
Ok, try the latest one when it's done building.

**Comment by master1274** [comment]
Update some libraries and make sure proguard doesn't remove needed ones. #63 
Without changes. Still crashes when trying to launch any game on any profile.

**Comment by master1274** [comment]
Pain! The problem with previous builds was confirmed on the device Huawei P8 Android 6.0.1 (Custom). But the latest build is already running on this device. I have on Shield Tablet the problem hasn't gone away. Pain!
![Screenshot_2023-11-13_10-45-42](https://github.com/mupen64plus-ae/mupen64plus-ae/assets/20639709/ca3aae90-cef6-4db7-9389-a671a7e0eaea)

**Comment by master1274** [comment]
Device Huawei P8 Unlike mine it turned out to be 64-bit. I doubt that it will help in any way, but I will attach detailed information about the devices.
[Huawei P8-report-2023-11-12-21-48-17.txt](https://github.com/mupen64plus-ae/mupen64plus-ae/files/13332768/Huawei.P8-report-2023-11-12-21-48-17.txt)
[Shield Tablet-report-2023-11-13-11-45-25.txt](https://github.com/mupen64plus-ae/mupen64plus-ae/files/13332769/Shield.Tablet-report-2023-11-13-11-45-25.txt)

**Comment by fzurita** [comment]
I'm thinking it's related to it being a 32 bit arm device.

**Comment by master1274** [comment]
Update Java action to v3 #65 
Unfortunately, this also did not fix the problem on my device.

**Comment by fzurita** [comment]
I'm able to reproduce similar issues now with Android versions 7 and older.

The latest, Gradle release definitely broke something with older android versions. 

This may take a bit to figure out.

**Comment by fzurita** [comment]
Can you try the latest commit once it's done compiling?

**Comment by master1274** [comment]
Latest commit works fine. Thank you!
