### ISSUE TITLE
Conker's Bad Fur Day - Timing bugs related to lag

### ISSUE THREAD

**Issue by cannon1349** [mupen64plus-ae/mupen64plus-ae#118]
I'm at the part after you beat the haybot and the room begins to flood.  There is a set amount of seconds in between times that you get shocked, and the game lag causes you to jump and swim/walk a bit more slowly.  I have no idea what to do about this in the settings.

**Comment by DildoBargains** [comment]
The solution doesn't work (anymore?). I'm using a galaxy s4, and have been trying all three emulators. The shocks just happen too often. Anyone around to have a look at it?

**Comment by fzurita** [comment]
Are you using this?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita
