### ISSUE TITLE
Zelda OOT, no video after leaving Link's treehouse

### ISSUE THREAD

**Issue by sixsk8er** [mupen64plus-ae/mupen64plus-ae#134]
When entering ocarina of time the game runs fine but at the first part of the game after i exit links room the screen turns black although the sound still runs.
The weird thing is is that when i use the controls i can still hear link moving but the picture does not show up.

I had also tried fixing this problem by adjusting the graphical settings but then the app would crash

i also don't think the issue is my tablet, unless its under powered because of the fact that it is brand new and mupen 64 was the first app i bought as well as tried out.

**Comment by fzurita** [comment]
Upstream issue
