### ISSUE TITLE
High audio latency

### ISSUE THREAD

**Issue by BiotechBum** [mupen64plus-ae/mupen64plus-ae#147]
At least in the most current release (2.3.0), there appears to be delayed audio (roughly half of a second) in all games I've tried using all graphics plugins.  The easiest place for comparison is in the character selection screen in Mario kart when moving between character portraits.  I compared this to n64oid and noticed right away a sizeable delay.  Again, this applies to all games regardless of plugin or emulation speed.

**Comment by fzurita** [comment]
Obe
