### ISSUE TITLE
Indiana Jones and the Infernal Machine does not work

### ISSUE THREAD

**Issue by mm5242** [mupen64plus-ae/mupen64plus-ae#185]
First of all I'd like to say that your emulator is one of the best on the market, having probably the highest comparability and playability with the exception being maybe n64oid. That said, I have had some difficulty playing certain games, the one most troubling being Indiana Jones. Being one of the more graphically impressive, not to mention an all together fun game, I was disappointed not being able to play it. If you can somehow find time, please do try to fix it. Thank you for reading. 
BTW, I am playing this on a Google nexus 7, if that is helpful.

**Comment by fzurita** [comment]
Upstream issue
