### ISSUE TITLE
Majora's Mask, black walls (gles2rice)

### ISSUE THREAD

**Issue by SPJero** [mupen64plus-ae/mupen64plus-ae#189]
Hi Paul, i've already purchase tour emulator..i trust on the work u are doing..zelda majoras mask is running ver y well..but the only issue ive found its the black walls..it runs fluid bit that walls are everywhere..im using a x86 processir (Motorola XT890  Razr i..thats the mexican name) and the gles2rice plugin..its the one that works bst for me.

**Comment by fzurita** [comment]
Upstream idle
