### ISSUE TITLE
Using two controllers

### ISSUE THREAD

**Issue by disferente** [mupen64plus-ae/mupen64plus-ae#191]
I have an adapter to connect two ps2 controllers to usb.
It works with recognizing the controllers and in Controller diagnostics the buttons map as the same KeyCode (X is KeyCode 190 on both controllers) but it shows as different devices, one as device 22, the other as 23.
The problem I have is that I can't find a way to map a physical controller to just one controller.
It does not matter what controller I press on it acts as one and the same, and if I start a game both controllers act as controller 1.
Any way for me to fix this?

**Comment by realquink** [comment]
I have the same issue. I'm running on Android and when I check settings > input all I see is "none" and "input-android". Maybe I need an additional plugin?

**Comment by fzurita** [comment]
Download the latest version of the app here:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

Then go to profiles and select profiles. In there enable:
"Automatic player mapping" and "All emulated controllers are always attached"

**Comment by realquink** [comment]
Wow thanks for the fast response. I was actually just downloading this one. I will try this then. I just can't seem to get to the /storage root folder to access my usb drive? It won't let me go past /storage/emulated/0/

**Comment by fzurita** [comment]
Don't go to settings then data to search for games. Use the "Refresh ROMs" button on the top right when you first start the app.

**Comment by realquink** [comment]
Wow perfect, all working now, great emulator and support. Thanks!
