### ISSUE TITLE
mugen64 Zelda Ocarina of Time - no longer working

### ISSUE THREAD

**Issue by elley1818** [mupen64plus-ae/mupen64plus-ae#202]
The game has been working fine until I saved just before entering the Forest Temple. Now whenever I start the game, I can play the game for 5 seconds or less before the screen goes black and I am exited out of the game. 

I can load the game again but the same thing happens... Screen goes black and the game closes.

Not sure if this happens for everyone when you reach this point or there's just something wrong with the app now.

If this helps...
Currently using version 3.2.1
Code 27

Any help is appreciated!

**Comment by fzurita** [comment]
Upstream issue
