### ISSUE TITLE
zelda oot everything black in water temple

### ISSUE THREAD

**Issue by cbkaufmann210** [mupen64plus-ae/mupen64plus-ae#204]
I am playing the game on a Motorola RAZR and it was working great till I got to the water temple. When I drain the water in the temple everything that was under water is now black except the character and enemy's. I am using the gles2rice plug in because it is the only one that works. Any tips would be great I love the emulator and want to keep playing. And I have tried multiple downloads of the rom

**Comment by fzurita** [comment]
Upstream issue
