### ISSUE TITLE
Paper Mario, flashing screen

### ISSUE THREAD

**Issue by jjennings1** [mupen64plus-ae/mupen64plus-ae#217]
The  background and screen keeps flashing! I don't know if its a setting that I have to change or if its the game! Please help:(

**Comment by fzurita** [comment]
Upstream issue

**Comment by fadedwithyourchick** [comment]
Step by step how do I fix it I just an account almost paid for some be ill never use I bought your app and everything It flickers it glitches and sometimes I don't understand what's happening why is that please explain I've tried to fix but the all start the same so if you could be more explicit it would be nice

**Comment by fadedwithyourchick** [comment]
Frameskip only let's you check it mine was not on but it still doesn't work why you gotta be like that

**Comment by fzurita** [comment]
Please download this version of the app: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

If you paid for it, you shouldn't had since this app is free.
