### ISSUE TITLE
Banjo-Kazooie - game stops responding in Freezy Peak

### ISSUE THREAD

**Issue by Gilder** [mupen64plus-ae/mupen64plus-ae#226]
Hi,
I have a very strange issue with banjo kazooie. When I am playing in the snow stage, the game just stops responding to any command. It does not freeze but the character won't move or do anything. What is strange is that everything was working perfectly so far. I can go to all the other stages but when I go to Freezy Peak this problem begins.

**Comment by fzurita** [comment]
Upstream issue
