### ISSUE TITLE
Problem With CyanogenMod 10.1 running Mupen

### ISSUE THREAD

**Issue by yneos** [mupen64plus-ae/mupen64plus-ae#230]
I'm using a Samsung S2 and a buddy of mine has the same phone, only he has stock, not nightly. I uploaded the same games and using your emulator as specified by the website I got the games from (--reference removed--), so the files aren't corrupted, avoiding glitch problems, and tried all graphics settings. Nada. Obviously the problem must be the phone's OS that's making it glitch right back to the home screen. Any ideas?  Thanks

**Comment by fzurita** [comment]
No follow-up
