### ISSUE TITLE
Zelda OOT and Mask sometimes got mapping error when go into another scene.

### ISSUE THREAD

**Issue by answermj** [mupen64plus-ae/mupen64plus-ae#239]
gles2n64 and gles2rice cannot work well on Zelda OOT and Mask, they always got static pictiure errors. So I tried gles2glide64, it seems work well. But when I test for a short time(about 1 hour), I often got mapping errors when go from one scene into another. Sometimes Z-targeting notice, sometimes the magic slot, sometimes even the ground. These errors did not always happen, they would come out when you test for sometime.

**Comment by fzurita** [comment]
Upstream issue
