### ISSUE TITLE
Must have feature

### ISSUE THREAD

**Issue by jericho2** [mupen64plus-ae/mupen64plus-ae#241]
Hi, it's not exactly a bug, but it drives me nuts:
When playing with a gamepad, there's no way to assign gamepad buttons to a MENU button. I save and load states once in every 3-4 minutes and i have to manualy reach out to phone every time, which is very inconvenient, because my phone is hooked to TV.

Suggestion: make "quick save" and "quick load" functionality and make them assignable to gamepad buttons. GENPLUSDroid has this feature and it is extremely useful. Thank you!

**Comment by TemporalOnline** [comment]
I know this is closed like 3+ years, but I believe this should be the default behavior or some kind of button or icon or anything clickable should indicate this somewhere. I tried the help, I tried a quick look at the store page, I tried a quick look at the presentation page at paulscode, and I had to find it here, hidden in a closed thread on its github.

**Comment by fzurita** [comment]
Are you using the latest version of the app? It can be found under "Mupen64plus FZ" in the play store. It's much simpler there.
