### ISSUE TITLE
Opening the app

### ISSUE THREAD

**Issue by ThaJman** [mupen64plus-ae/mupen64plus-ae#244]
When I'm opening the app, after it goes through all those files. It says that something went wrong when extracting the app data. I tried unplugging the the USB (my charger), rebooting the app, and rebooting my devise. It still didn't work. I had my hopes high for this, considering my childhood was wrapped around the Nintendo 64. I hope you see and will help me get this app running so I can revisit my childhood and play  a N64 again.

**Comment by fzurita** [comment]
No follow-up
