### ISSUE TITLE
"Not installed properly" message, Xperia Z

### ISSUE THREAD

**Issue by nscxp2005** [mupen64plus-ae/mupen64plus-ae#245]
Emulator crashes when try to play a game. The emulator starts with an error saying 'Mupen64Plus AE may not have been installed properly' 

This issue is happening on my Xperia Z with 4.2.2 but not on my HTC One 4.2.2.

**Comment by RodrigoZid** [comment]
Same error in Samsung Galaxy S9 Plus Andoroid 10

**Comment by fzurita** [comment]
Hello, try uninstalling then reinstalling the app.
