### ISSUE TITLE
OoT ground is flickering and blotchy, NEED help!!

### ISSUE THREAD

**Issue by Techanine** [mupen64plus-ae/mupen64plus-ae#246]
So I am using a Samsung Galaxy tab 2 7.0 tab, I downloaded the newest version of mupen64plus-ae off paulscode.com today, running rice plugin and playing Zelda OoT and Majora's Mask. My issue of right now is OoT the first screen when loading up OoT the Nintendo screen the word nintendo is blurry and so is the title zelda after that, once i log in to my game everything seams ok, u8ntill im outside and the ground flickers mainly on  the trails flickers and looks distorted. I would appreciate any help you have thanks!

**Comment by fzurita** [comment]
No follow-up
