### ISSUE TITLE
gauntlet legends audio not working

### ISSUE THREAD

**Issue by Dieshi** [mupen64plus-ae/mupen64plus-ae#257]
No audio in gauntlet legends.I have changed the resampling algorithm to every type available. 

Video did not work at first either, had to change to Gles2rice to get video. Currently running HTC one.Tried to load a different rom,still nothing. Is there another audio setting I am missing or is this just an app issues? (also, all other games run fine, it's just gauntlet legends with no sound)

and after characther selection, the game black screens and the app must be force stopped to end session (normal exit displays "auto saving game" and does nothing). maybe this game is a lost cause? :-(

**Comment by fzurita** [comment]
Upstream issue
