### ISSUE TITLE
Frambuffer Effects are almost all broken

### ISSUE THREAD

**Issue by vgf89** [mupen64plus-ae/mupen64plus-ae#262]
Framebuffer effects, especially in, say, Banjo Kazooie, don't work at all with gles2n64 and gles2rice. In gles2glide64, some framebuffer effects works while others don't.

For example: the pause screen background shows static on gles2n64 and gles2rice, and it works in gles2glide64.
gles2n64:
![gles2n64 and gles2rice bugged](https://f.cloud.github.com/assets/5163157/908285/40eea1ca-fd8c-11e2-9466-e50206c21c19.png)

gles2glide64:
![gles2glide64 correct](https://f.cloud.github.com/assets/5163157/908287/4b8f4544-fd8c-11e2-9b4b-6ced60257dc8.png)

The framebuffer effect for the puzzle-piece transitions (like after the intro screen) don't work at all in any plugin:
![all_plugins](https://f.cloud.github.com/assets/5163157/908294/901cc61e-fd8c-11e2-805a-5517cd8898a4.png)

These bugs, or lacks of implementation, affect other games as well, but I can't provide any examples at the moment. Glide64 on the PC performs exquisitely with framebuffer effects enabled, and that feature enables a lot of thing to be rendered correctly (pause-screens, puzzle-transitions, the puzzle minigames in Banjo Kazooie and Banjo Tooie, among other things). Perhaps it's possible to implement those functions on gles2glide64. If it can be implemented, and there is a performance hit for it, make framebuffer effects optional.

**Comment by fzurita** [comment]
Upstream issue
