### ISSUE TITLE
Kirby 64 graphical issues

### ISSUE THREAD

**Issue by Newbie13XD** [mupen64plus-ae/mupen64plus-ae#265]
There is some graphical problems in Kirby 64 that's quite annoying. Using the default video plugin the little bar on the bottom of the screen that shows healh and other stuff won't be visible. Using the other built-in plugin this bar will be visible, but there will be lots of strange "stuff" on the borders.

I hope you understand, if you don't, please tell me and I will try to explain better

I got a HTC One S

/Stefan

**Comment by fzurita** [comment]
Upstream issue
