### ISSUE TITLE
Zelda MM Debug ROM- Crash at Stock Pot Inn

### ISSUE THREAD

**Issue by GManWillis** [mupen64plus-ae/mupen64plus-ae#276]
Hey guys, I'm experiencing a lock up anytime I try to enter the Stock Pot Inn in the Debug build of Zelda Majora's Mask.

I noticed if I switch graphical plugins, it works fine, however I'm stuck with the first option plugin which blacks out a lot of textures as well as pretty serious flickering everywhere. 

Any other work around?? 

Thanks guys. Besides this, I am absolutely loving this emulator. Fantastic work. Thanks so much!

-G

**Comment by fzurita** [comment]
Upstream issue
