### ISSUE TITLE
Majora's Mask gles2glide pluggin problem on Galaxy tab 2 7.0

### ISSUE THREAD

**Issue by ShadowLinkMan** [mupen64plus-ae/mupen64plus-ae#277]
I have galaxy tab 2 7.0 and ok so with gles2glide pluggin for majora's mask everythong is messed up. The menu sequence with the mask has does not pop up instead it is replaced with a bunch of lines. The title pop up, but the bottom half flickers. When I load a game andwhen it tells me what day both seem to work fine,  but when it goes into the game I see that only the background and the deku's eyes render.

**Comment by fzurita** [comment]
Upstream issue
