### ISSUE TITLE
Paper Mario video problem 

### ISSUE THREAD

**Issue by Dmireles1** [mupen64plus-ae/mupen64plus-ae#283]
The game is a little laggy and when I press the start button the game will freeze up for a short minute before going to the start screen if it doesn't freeze all together. At that point the only thing I can do is go home and re enter the app and restart very frustrating in paper Mario. I have a galaxy s4 and have tried all three plug ins the last definitely shows the best graphics and doesn't mess with the color scheme. You talk about changing the frame skip setting which I can't find so that might help but not to sure. As well as the fact the color scheme can get real messed just from entering a battle. I have played super Mario 64 all the way through with not a single problem and banjo kazooie but it had a couple graphics issues. Thank you.

**Comment by fzurita** [comment]
No follow-up
