### ISSUE TITLE
Conkers Bad Fur Day: Graphical bug in chapter mad pitchfork

### ISSUE THREAD

**Issue by ghost** [mupen64plus-ae/mupen64plus-ae#29]
![Screenshot_2013-01-16-17-43-52](https://f.cloud.github.com/assets/3249062/71925/6c0752fe-5ffc-11e2-8fe9-e265948fb7a0.png)
![Screenshot_2013-01-16-17-44-06](https://f.cloud.github.com/assets/3249062/71929/775838f8-5ffc-11e2-92bb-f23957c66253.png)

The problem happens with the plugin gles2rice. Every combination with the visual settings like fast texture loading have been set or unset, but the problem has always happened. Everything seems too be working just  fine until you have the first encounter with Franky the mad pitchfork. After you spoke with him, he should start chasing you, but he's not even visible anymore, although he was displayed before without any problems. Additionally the previously moving hey bales don't move anymore.

**Comment by fzurita** [comment]
Upstream issue.
