### ISSUE TITLE
Black screen and app closes

### ISSUE THREAD

**Issue by Anechan** [mupen64plus-ae/mupen64plus-ae#295]
I was playing Harvest Moon a few weeks ago and everything was alright, but yesterday when I tried to play again the app started to closes by itself everytime i try to move to other scenario. The screen goes black and the app closes
What could be the problem?
(I downloaded the upgrade today but not solved)
*and sorry for my terrible english, but hope you can help me

**Comment by fzurita** [comment]
Upstream issue

**Comment by sleonlome** [comment]
I've got the same problem. what should I do?

**Comment by fzurita** [comment]
Are you running the playstore version? Have you tried the latest build from here? http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/Mupen64PlusAE_master_201604240803_2474cf1.apk
