### ISSUE TITLE
Sprite rendered graphics shows black backgrounds

### ISSUE THREAD

**Issue by Kirbologist** [mupen64plus-ae/mupen64plus-ae#300]
Not sure if this happens to all games, but the sprite rendered graphics in Mario Kart 64 (e.g. in-game character sprites and numerous other objects) always shows a black backdrop, which can be very distracting during gameplay. I checked the settings to make sure anything that might have caused the backdrop were closed, but they were still there. Not sure whether I am doing something wrong or whether it's a reoccurring  bug.

**Comment by fzurita** [comment]
No follow-up and upstream issue
