### ISSUE TITLE
Star Wars episode 1 racer, pod and character graphics don't show.(edit: not a bug, altered option behaviour)

### ISSUE THREAD

**Issue by thedicemaster** [mupen64plus-ae/mupen64plus-ae#31]
the pod doesn't show in a race(the engines do show), the character and pod don't show in character select, and the movement of the podracer in character select seems to be inverted.
this is something most emulators have some difficulty with.
the current play store version handles this fine if all video settings are enabled(compatibility rather than speed), but in the latest RC(RC5) this doesn't work.
this is using the n64 video plugin.
the rice plugin does show them properly, but a lot of menus don't show properly(a lot is off-screen)
EDIT: solved.
the depth hack option had to be enabled to fix this problem on older versions of mupen, but it has to be disabled in newer versions.
it's a bit confusing when options are inverted like this.

**Comment by 32Dexter** [comment]
@thedicemaster I am using RetroPie on Raspberry Pi 3 B.
I am using Mupen64plus and i have the same problem with Star Wars Racer.
What is the "depth hack option"? What is the ling in mupen64plus.cfg i have must to change?
Thanks

**Comment by Krathoon** [comment]
Yeah. Where is this option? The problem is showing up in Emuelec 4.5 too.
