### ISSUE TITLE
(glN64) Fix for Diddy Kong Racing / Mickey's Speedway Racing / Jet Force Gemini

### ISSUE THREAD

**Issue by twinaphex** [mupen64plus-ae/mupen64plus-ae#310]
This fixes the graphics in DKR/Mickey's Speedway Racing/JFG for glN64.

https://github.com/libretro/mupen64plus-libretro/commit/a4352f310def07c183311a4bcf996937d8746aab

Feel free to cherry-pick it.

BTW paulscode - it would really help if you could make some kind of writeup where you detail exactly what changes you made to the GLES2 versions of Rice/glN64/Glide so that I will have an easier time regression testing (and fixing stuff along the way).

**Comment by fzurita** [comment]
No follow-up
