### ISSUE TITLE
Mario party 1 minigame bug

### ISSUE THREAD

**Issue by deltaroyale** [mupen64plus-ae/mupen64plus-ae#315]
Nothing happens when you play the "Mushroom mix-up" minigame. The platforms are supposed to go underwater but they do not. There is no way to finish the minigame because the cpu doesnt move at all and there is no time limit, so you have to reset the game. I tried all the video plugins included with the emulator to see if it worked but it didnt.
My cell phone is a galaxy s4

**Comment by fzurita** [comment]
Upstream issue
