### ISSUE TITLE
Kirby 64 The Crystal Shards graphical/video errors

### ISSUE THREAD

**Issue by MrCythos** [mupen64plus-ae/mupen64plus-ae#323]
The game is playable. But parts of the game are rendering incorrectly (excuse my redundancy in using the word "rendered").

gles2n64: borders are not rendered in game and some textures are not properly rendered

gles2rice: borders are rendered but are replaced by chunks of the game and some textures are not properly rendered in the in game (rendered) cinematics

gles2glide64: exhibits the same border problem with rice

There may be more problems, I have not fully tested or looked at what is wrong.

I am using the Samsung Galaxy Note 3 (stock). 2.3 GHz krait CPU and 3 GB ram. Android 4.3.

**Comment by fzurita** [comment]
Upstream issue.
