### ISSUE TITLE
Pokemon Stadium 2 Graphics: Minigames, Quiz Questions, Stats

### ISSUE THREAD

**Issue by MasterZ1** [mupen64plus-ae/mupen64plus-ae#325]
idk if this issue was brought up but this game has some major visual problems.
1. Minigames- the pictures are all messed up on the outer edge and its hard to figure out which options to choose when setting them up.
    -The quizes have questions that should have pictures but are only black boxes.
2.selecting pokemon- when you go to select a pokemon their stats flash for a second, their attacks are still able to be read using the c-buttons. Also you can exit off of the pokemon and reselect it many times to look at everything.
These are the only things i have to submit right now and the graphic problems vary between the different plugins but are still a big problem in them all

**Comment by fzurita** [comment]
Upstream issue
