### ISSUE TITLE
Impulse controller problem

### ISSUE THREAD

**Issue by funfunislandguy** [mupen64plus-ae/mupen64plus-ae#328]
Most of the time I use my Impulse controller none of the buttons work. The Impulse is a bluetooth controller and d-pad directions work fine, but most of the time I use it none of the buttons I mapped work. If I map the dpad to a button it will work. I dont have this problem in any other app, Also when I hold down a button it sometimes acts like I pressed it after around 30 seconds. I know the impulse works as a keyboard for the buttons because I can type using its a or b button. I don't understand what is wrong and I've tried everything I can think of.

**Comment by fzurita** [comment]
No follow-up
