### ISSUE TITLE
pokemon puzzle?

### ISSUE THREAD

**Issue by cmdrryan** [mupen64plus-ae/mupen64plus-ae#332]
First I want to say that this emulator is amazing! the only problem that I have is with pokemon puzzle. when I try to play this game it doesn't even bring up the Nintendo logo in the beginning and then never continues so its just a blank screen. Is it a game that is still not supported or do I just need to change some settings around? I have change the setting a lot but with no luck.

**Comment by fzurita** [comment]
Upstream issue
