### ISSUE TITLE
gameshark ?

### ISSUE THREAD

**Issue by jdws-zz** [mupen64plus-ae/mupen64plus-ae#337]
How do you activate the game shark ? Ex in Zelda oot?

**Comment by alpharulesirulee** [comment]
it won't open

**Comment by Lion4K** [comment]
Sorry, but I can't seem to find this folder.
I tried adding codes via the GUI but it's not saving the codes.
So I though i'd add them manually, so I came here to find it's location, but that address is not present here.

**Comment by fzurita** [comment]
Which version of the app are you using?
