### ISSUE TITLE
zelda - majoras mask freeze with rice plugin

### ISSUE THREAD

**Issue by kaymez** [mupen64plus-ae/mupen64plus-ae#344]
hey :)

first: sry for my bad english, i'm german ^^

well, i have a big problem by playing "zelda majoras mask"
every time when i pressed the "start" button, suddenly the game freezes. 
sure, i can use a different plug-in, but then i doesn't can play with highres textures :(
and the original graphic-look still sucks, it is simply no longer contemporary.

i will not complain, the app is great, and also i have buy the paid version, to assist the project, but i would be happy, when you can fixed this bug. 

my device: samsung galaxy tab 3, 8.0
                    dual-core 1,5 ghz, 1,5 gb ram
                    mali 400MP gpu

android version: 4.2.2 jelly bean

i say thank you in advance and hope you can help me! :)

best regards, kaymez.

**Comment by fzurita** [comment]
Upstream issue
