### ISSUE TITLE
HUGE PROBLEM - Zelda OOT

### ISSUE THREAD

**Issue by Kokuna** [mupen64plus-ae/mupen64plus-ae#349]
Everytime when I save the game, go to my homescreen without ending the emulator and try to restart the game i just see the controller and a black background. And when I close it completely and start it a few minutes later I have all my rubys and stuff but I'm back in my home in koriri forest. There are huge graphic bugs too. How can I fix that?

(Sorry for my bad english..)

**Comment by fzurita** [comment]
No follow-up, upstream issue
