### ISSUE TITLE
Zelda OOT, extreme texture problems

### ISSUE THREAD

**Issue by LightMaldor** [mupen64plus-ae/mupen64plus-ae#35]
I was playing The Legend of Zelda: OoT. It ran fine. But after updating my Galaxy Tab 2 I got a graphical glitch. Everything looks low res and rooms are pixelated. Can you fix this please!

Ex: No "intendo" at Nintendo logo, Blocky backgrounds, Pixelated rooms, glitchy textures.

![Screenshot_2013-01-14-15-32-17](https://f.cloud.github.com/assets/3268777/65739/1f641c66-5e8a-11e2-93ef-bcad3a8fc11f.png)
![Screenshot_2013-01-14-15-33-29](https://f.cloud.github.com/assets/3268777/65741/2e5bcae8-5e8a-11e2-8932-46a7cd9e82c7.png)
![Screenshot_2013-01-14-15-32-40](https://f.cloud.github.com/assets/3268777/65742/34d7564e-5e8a-11e2-9e14-b06bb2b4f728.png)
![Screenshot_2013-01-14-15-33-43](https://f.cloud.github.com/assets/3268777/65743/3c277802-5e8a-11e2-99bd-37ca863ff786.png)
![Screenshot_2013-01-14-15-32-33](https://f.cloud.github.com/assets/3268777/65744/410f2f54-5e8a-11e2-9875-ec735c9a5a8a.png)

**Comment by fzurita** [comment]
Upstream Plugin issue
