### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by fredd29** [mupen64plus-ae/mupen64plus-ae#354]
I can't load any game I only get a black screen every time I start the emulation, what should I do? I have a samsung galaxy s4

**Comment by fzurita** [comment]
Won't fix

**Comment by moeiscool** [comment]
i get black screen after a few times of playing. The game that i want to play is actually Mario 64 USA verison. Any idea on how to resolve this? even if its temporary.. i just wanna play!

GPad 8.0 v522, Android 6.0.1

**Comment by fzurita** [comment]
That's a very old build. The play store version is very outdated. Please try the latest beta version from here:

https://drive.google.com/file/d/0B57Ioy26LWegdnNfa0FON09maW8/view?usp=sharing

**Comment by moeiscool** [comment]
thank you!!
