### ISSUE TITLE
Recognizes DualShock 4 properly in Diagnostics, but does not properly map buttons. 

### ISSUE THREAD

**Issue by Aaaboy97** [mupen64plus-ae/mupen64plus-ae#369]
The app recognizes all DualShock 4 (using an OTG cable) inputs under the controller diagnostics menu, but when attempting to map the buttons, it fails to recognize the hat/POV switch and the right stick (using axis z and axis rz). It also does not stop recognizing axis rx- (left trigger) but this is caused because the controller keeps it at -1.00 while unpressed.

**Comment by Nick515** [comment]
This is still happening for me. I installed the version linked, but it's the same. It doesn't do it in the newest alpha version on your website, but the game seems to run slower. Which version would be best to use or is there some update?

**Comment by Nick515** [comment]
It says Xbox 360 compatible in the analog info.

**Comment by fzurita** [comment]
Latest alpha is probably the best to use. Have you tried different video plugins? It may help performance.
