### ISSUE TITLE
Share touchscreen controls for multiplayer

### ISSUE THREAD

**Issue by littleguy77** [mupen64plus-ae/mupen64plus-ae#37]
http://www.paulscode.com/forum/index.php?topic=833.msg8060#msg8060

xavouine said:
Just tried RC6 on my TF300 (JB 4.1) and it is super smooth.

The only issue I've come up with is that you can't use the "share controller" with the on-screen input. In turn-based games for example, it would be nice to be able to both use the controls on-screen for those who don't have an external controller. ( Like I thought I was part of until I remembered my keyboard) .

I'm not a pro at programming but I was wondering if it was perhaps possible to integrate a "switch controller" in the in-game mini-menu.

**Comment by fzurita** [comment]
Not implementing.
