### ISSUE TITLE
Video/Input Frozen, Audio Works fine (OOT)

### ISSUE THREAD

**Issue by TheWizKid95** [mupen64plus-ae/mupen64plus-ae#376]
Video and input is frozen on all three video plugins. This happens randomly with no certain trigger and then the game freezes, but the audio still plays. I can restart the game just fine, but I'd lose a lot of progress. Resuming doesn't help anything. The only save slot I have is messed up like this as well. 

Ive tried messing around with some settings, but I've had no luck. This has happened to me before, but I usually just have a working save slot handy, but in this case I don't. I'd really like to resume where I'm at right now.

**Comment by fzurita** [comment]
Upstream issue
