### ISSUE TITLE
Paper mario issue

### ISSUE THREAD

**Issue by mudge6** [mupen64plus-ae/mupen64plus-ae#389]
When using gles2n64 or gles2glide64, the screen constantly flickers and lags in Shy Guy's Toy Box, virtually making it unplayable.

EDIT: with gles2rice, screen flickers and transition is junk when opening any menu or selecting anything in battle.

EDIT: in battle, screen constantly flickers when selecting an attack, im on a galaxy s3 if that helps. nether the rice issues make it unplayable, just very annoying.

**Comment by fzurita** [comment]
Upstream issue
