### ISSUE TITLE
usb game controller joystick not setting up properly

### ISSUE THREAD

**Issue by u6bkep** [mupen64plus-ae/mupen64plus-ae#391]
When I try to map the joystick of my game controller to the analog stick, the first and second direction I try maps properly, but when I try to map the third direction, it instead re maps the second direction I tried to map. It does not matter what order I map them in. also, whenever I have any direction of the joystick mapped, and I move the joystick, the controller plugin acts as though I am holding them down. The diagnostic menu indicates that the buttons are working properly and I don't have any problems with this controller on my computer.
Device: Droid Bionic
OS: CyanogenMod 10.2.1-targa
USB Setup: powered OTG with USB 2.0 hub.
game controller: off brand-http://www.ebay.co.uk/itm/2x-lot-SPIN-MASTER-47004-USB-PC-GamePad-video-game-CONTROLLER-computer-games-/121355352331?pt=US_Video_Game_Controllers&hash=item1c4157b90b

**Comment by fzurita** [comment]
Are you still having issues with this with the latest alpha build?

**Comment by u6bkep** [comment]
Not entirely sure. that phone stopped working a while ago, but I can test it with another device and get back to you on that.

also I just noticed that the link I have on there is no longer good. the game pad in question is a USB PlayStation nockoff. I can post what the app says about it when I test it again.

**Comment by fzurita** [comment]
I'm going to go ahead and close this. If you find that it's still an issue, I'll reopen.
