### ISSUE TITLE
Castlevania crashes with Dynarec

### ISSUE THREAD

**Issue by Al4ris** [mupen64plus-ae/mupen64plus-ae#393]
I tried to play Castlevania both USA and Europe versions, but the game crashes in some points with my Ramos i10 tablet, and only with Dynarec plugin, if I play with cache interpreter the game doesn't crash but it's unplayable, too slow.

With my Xperia Neo V the game works well with Dynarec but this phone can't handle the emulator.

**Comment by Gillou68310** [comment]
https://github.com/Gillou68310/mupen64plus-core/commit/174c407112d9c83caa0f06ca5edb6af7ce7582e8
