### ISSUE TITLE
Fire TV menu buttons not remappable

### ISSUE THREAD

**Issue by DrSammyD** [mupen64plus-ae/mupen64plus-ae#394]
On the FireTV, when changing the mapping of the start buttons for any controller, you are unable to set the start button on an xbox controller to the start button of the emulator.  This is because the start button on controllers for the firetv map to the menu button. Enable using the menu button for this purpose in game as many other emulators do the same.

**Comment by fzurita** [comment]
Fixed: 40f85c880c6d377e7250d65ae18f8c2310cd1ddb
