### ISSUE TITLE
No ARM dynarec code?

### ISSUE THREAD

**Issue by Xiaomita** [mupen64plus-ae/mupen64plus-ae#406]
I sifted through this whole project and can't find any of the code for the MIPS-to-ARM dynarec that this program uses, nor the interpreters. Where are they?

**Comment by BonzaiThePenguin** [comment]
Did you run a search for [MIPS](https://github.com/mupen64plus-ae/mupen64plus-ae/search?utf8=✓&q=MIPS), [ARM](https://github.com/mupen64plus-ae/mupen64plus-ae/search?utf8=✓&q=ARM), or [Dynarec](https://github.com/mupen64plus-ae/mupen64plus-ae/search?utf8=✓&q=dynarec)?

**Comment by Xiaomita** [comment]
Oh. My. God. Is this it? It's over 11,000 lines of code?! 

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/02025b3f400c33f3cd54c9208ac41dac817e277a/jni/mupen64plus-core/src/r4300/new_dynarec/new_dynarec.c

Also, what's the difference between the cached interpreter and non-cached one, with regards to the dynarec blocks?

**Comment by littleguy77** [comment]
Yes, that's it.  There's only one or two people in the world who understand it ;P

**Comment by Xiaomita** [comment]
You and Paul?

**Comment by littleguy77** [comment]
No Ari64 and @Gillou68310
