### ISSUE TITLE
Glover doesn't work with the dynarec

### ISSUE THREAD

**Issue by ghost** [mupen64plus-ae/mupen64plus-ae#408]
It is fully playable with either interpreter core, but it will not get past the title screen with the dynarec. I am using version 2.4.3, the latest archived version on Paul Lamb's post on his website. I would not complain about this on any modern device as it would be non-existent, but my phone is not powerful enough to get fullspeed with the interpreters (1.5 GHz Cortex A9; I can only get 30 FPS with the cached core).

My concern is: What's the problem? Why does this one game and few others not work with the dynarec but hundreds of others do just fine? What is so different about this game? It's the one game I want to play fullspeed but I can't as of now. >.< So disappointing.

**Comment by littleguy77** [comment]
There are bugs in the dynarec, particularly with version 2.x.  Try the version 3 alpha releases:
http://www.paulscode.com/forum/index.php?topic=1818

**Comment by Xiaomita** [comment]
I'll report back ASAP.

**Comment by michaelr095** [comment]
Hey ghost, idk if you'll get this but I have just figured out how to get Glover to run perfectly. So I started Glover up with cached core and played for a little bit on that. I then closed the app completely and when it started up again I changed it back to dynarec. Worked (almost) flawlessly. Hope I was some help! 
Also, I'm running 2.3 GHz Snapdragon 800

**Comment by Gillou68310** [comment]
https://github.com/Gillou68310/mupen64plus-core/commit/4623ba3f4fe98aa66efe735472f1e25016931935

**Comment by reinventedz** [comment]
Why was this closed? The game still won't work on Mupen64PlusAE with the dynarec, and on the latest builds there is no way to change the core from the frontend; so it's 100% unplayable as of recently.

**Comment by Gillou68310** [comment]
I closed it because I found the cause of the crash, I just didn't merge the patch yet. In the meantime you can change to cache interpreter or pure interpreter inside emulation profile.

**Comment by reinventedz** [comment]
I'm not the one with the issue -- I meant for anyone else wondering why Glover doesn't work or can't get it to work. I don't want to come off as pedantic, but an issue isn't fixed if a recent build still won't run it.

I would think an issue would be closed (at least) when it's fixed & merged to master or the main branch/repo; not just when a fork was made and a patch was implemented, but is still left hanging.

But it's not my repo; just saying it doesn't make any sense to me for one to consider closing an issue when the problem isn't fixed (especially for people who can't compile this themselves, which is most).
