### ISSUE TITLE
Donkey Kong 64 - target camera angle when running slightly left is off by 90 degrees

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#409]
This is a strange one, but I've played Donkey Kong a ton on a real N64 and the behavior of the camera is definitely off. When running at any angle to the left, the "target" camera angle (the angle the camera moves to over many frames) is off by 90 degrees. When running at any angle to the right, the target angle is calculated correctly.

In practice this means the camera will veer to the left and right as you attempt to walk straight, and if you deliberately walk forward and slightly left the camera will swing over to show DK's left side (a.k.a. 90 degrees off). Walking forward and slightly right will place the camera behind DK.

Using dynarec and the latest version, of course.

**Comment by BonzaiThePenguin** [comment]
Not sure where to start looking for this one, but trig functions specific to DK64's code base seem like a good candidate. For some reason Banjo-Tooie doesn't have this issue (you'd think it'd have the exact same code for the camera system), but I think I read that DK64 and Tooie were developed at the same time by different teams and they didn't like to share code.

**Comment by littleguy77** [comment]
Thanks @BonzaiThePenguin it's nice to have new devs looking at the code.

For quirks in logic, the most likely candidate is the dynarec.  This theory can be tested in version 3 by creating a new Emulation Profile whose R4300 emulation is set to cached or pure interpreter (they *should* both behave identical, with the former a little faster).  The game will run a lot slower (probably unplayable) but it does allow you to diagnose whether the dynarec is the issue.  If the issue doesn't appear in interpreted mode, then it is definitely the dynarec.

As an aside, the core has very little "game specific" logic at as high a level as trig functions.  Most game-specific tweaks are implemented by twiddling bits in the memory, like how cheats (gameshark) codes are applied.  The dynarec basically converts the original raw MIPS assembly directly to raw ARM assembly at run-time, bypassing any high-level logic.

**Comment by littleguy77** [comment]
Also, we have a (lengthy) general discussion thread on the latest alpha builds here:
http://www.paulscode.com/forum/index.php?topic=1818

In particular, I suggest you ask user retroben if he noticed the camera issues.  He's the first user to play DK64 all the way through on mupen64plus-ae, and I'd be curious if he noticed the issue.

**Comment by BonzaiThePenguin** [comment]
I was thinking more along the lines that the low-level logic for one of the trig functions is triggering a bug in the dynarec core or something, and that scanning DK64's ROM for things that resemble trig functions would reveal candidates to run against the dynarec and interpreter to figure out exactly where the calculations start to differ.

But it turns out the interpreter behaves exactly the same way! I may have to whip out the cartridge again and make sure the camera wasn't always this bad. The game is fully playable, but any slight left movements cause the camera to rotate 90 degrees and show the left side of DK.

**Comment by BonzaiThePenguin** [comment]
...Okay, and now the camera is working perfectly. Not a clue what changed; I was just toying with the different emulation and video settings before ultimately reverting to the settings I originally had (dynarec and glide64), and now I can't reproduce the wonky camera behavior. It follows behind DK perfectly regardless of whether I move left or right!

**Comment by littleguy77** [comment]
Very strange.  Have you been running the same build of mupen64plus-ae the whole time?  Or did you rebuild recently?  Are you using touchscreen, or a controller?

**Comment by BonzaiThePenguin** [comment]
Running the same version – I'm still using the version I built a few days ago, actually. It's too annoying switching between APKs with different codesigns. Using the touchscreen.

**Comment by BonzaiThePenguin** [comment]
I'll close this one for now. If I can reproduce it consistently I'll open it again with a better description. Right now there's really not enough for anyone to go on.

**Comment by trigrab** [comment]
I had the same issue on linux and for me it helped to change the video plugin to glide64mk.
