### ISSUE TITLE
No cover art for Beetle Adventure Racing!

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#414]
Wikipedia has it:
http://upload.wikimedia.org/wikipedia/en/b/b4/BAR_gamebox.PNG

Where are you guys getting the cover arts from?

**Comment by BonzaiThePenguin** [comment]
NFL Blitz Special Edition is missing as well.

**Comment by fzurita** [comment]
This has been fixed server side.
