### ISSUE TITLE
Impossible to edit the visible buttons in phone portrait view

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#416]
It's currently impossible to edit the visible buttons in the touchscreen controller editor when the Buttons menu item is forced into the ... overflow menu, which for me happens when using a phone in portrait view. The problem is that selecting the Buttons menu item also causes the ... overflow menu to close, which calls `onWindowFocusChanged(true)`, which calls `hideSystemBars()` and ultimately hides menus that are currently open.

One solution is to simply set a flag when the user chooses the Buttons menu, and skip calling `hideSystemBars()` when the flag is set.

**Comment by littleguy77** [comment]
Thanks for spotting this.  Unfortunately my phone (Samsung Galaxy Victory, android 4.1.x) cannot reproduce the behavior for whatever reason (e.g. screen too large, samsung touchwiz, etc.).  If you have a solution, please by all means submit a PR.

**Comment by BonzaiThePenguin** [comment]
Alright, I'll implement a fix in a bit. I wanted to make sure that part of the app wasn't going through any large changes soon since the proposed fix is essentially a hack. Although I suppose it'd be easy enough to rip back out when the time comes.

**Comment by littleguy77** [comment]
Thanks.  Currently nobody is really working hard on any front-end stuff.  Paul's work on a new GalleryActivity is occurring in isolation on a personal branch.  My work as late has been mostly to just keep things in sync with all the upstream activity that's going on right now.  That means I'm mostly working in the c/c++ code under the jni directory.  But honestly I'm not doing a whole lot right now... real life is just too busy atm.

**Comment by BonzaiThePenguin** [comment]
Fixed it, although I just realized I committed it to the previous Pull Request again. D'oh!
