### ISSUE TITLE
Why is the ROM info retrieved using an MD5 rather than via the ROM header?

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#418]
The ROM header contains the ROM name and region code, and Mupen seems to parse it out just fine, but the app ignores all that and uses an MD5 against a massive database to retrieve that exact same information. Why is that?

**Comment by littleguy77** [comment]
The database file is maintained by the upstream core developers, so firstly it comes "for free":
https://github.com/mupen64plus/mupen64plus-core/tree/master/data

Upstream uses it for the following:
 - It provides an absolute identity for different rips of the same ROM (e.g. some rips are "bad" or are hacked with cheats/bugfixes after they are ripped).  Having an absolute identity of the rip (via md5) is important when reproducing error reports.
 - It uses a consistent naming convention for the friendly (user-facing) name of each ROM.  Again useful when isolating and reproducing bugs from user reports.
 - It contains a bunch of additional meta info, like
    - original method of saving data (SRAM, mempak, etc.) (critical to core operation)
    - number of players (minimize unnecessary controller polling)
    - rumble support
    - a subjective rating of emulation quality (though I haven't seen this used much)
    - game-specific tweaks (CountPerOp)

The ROM header does not provide all this extra information, nor does it sufficiently differentiate rip variants.  The header is also very inconsistent in the names.  They are good enough for development purposes, but not pretty enough to display to a user.  Here are the header names for some common games:
 - Banjo-Kazooie
 - BANJO TOOIE
 - CONKER BFD
 - Diddy Kong Racing
 - DONKEY KONG 64
 - GOLDENEYE
 - JET FORCE GEMINI
 - Kirby64
 - MARIOKART64
 - MarioParty
 - PAPER MARIO
 - Perfect Dark
 - SMASH BROTHERS
 - STAR WARS EP1 RACER
 - STARFOX64
 - SUPER MARIO 64
 - TUROK_DINOSAUR_HUNTE
 - Turok 2: Seeds of Ev
 - Turok 3: Shadow of O
 - THE LEGEND OF ZELDA
 - ZELDA MAJORA'S MASK

So we use the same database in the front-end, mostly for the same reasons:
 - Consistent, meaningful user-facing names that can also be used to determine the exact rip variant from user reports
 - Consistency with upstream naming conventions, in case a user submits a bug report upstream
 - Number of players and rumble support is used in the front-end to present the proper menu options to users (number of controllers in play menu, pak options in in-game menu)

We wrap the database info in a java class, which we use to hold additional derived meta-info, like URLs for the cover art and wiki entries.

**Comment by BonzaiThePenguin** [comment]
Say no more, thanks a ton for that info. :)

**Comment by BonzaiThePenguin** [comment]
Actually, is that info documented anywhere in the project? It should probably be included in a README or in a comment in the code. Really nifty.

**Comment by littleguy77** [comment]
No but I suppose it should be.  Probably as a header comment for RomDatabase.java would be the best place to put it.
