### ISSUE TITLE
Building new branch using appcompat library

### ISSUE THREAD

**Issue by littleguy77** [mupen64plus-ae/mupen64plus-ae#419]
@BonzaiThePenguin 
I saw you made some changes to the README, but I was not successful following them.  I develop on Windows and Eclipse Luna and have always been able to just press Run (ctrl-F11) to build and run the app.  Now when I open Eclipse I get all sorts of error messages.  Looks to be just a project setup thing, but I was hoping you could point me in the right direction.

![image](https://cloud.githubusercontent.com/assets/2266445/6483985/66581f02-c245-11e4-988c-9f96beacaccd.png)

**Comment by BonzaiThePenguin** [comment]
The Android website seems to have setup instructions for Eclipse:
https://developer.android.com/tools/support-library/setup.html

I build from the command line so I mostly just had to guess how to get it working from there. Should be noted that the command I have in the README doesn't actually seem to work, and I have to modify the project.properties file on my own. Haven't really looked into that yet.

**Comment by littleguy77** [comment]
I followed that link already but it was useless (like so much official Android documentation).

But I did manage to resolve the problem :)  I realized that you had imported entire eclipse projects into the libs folder.  So I went to Eclipse -> File -> Import and imported the appcompat, gridlayout, and recyclerview projects *from `mupen64plus-ae/libs`* rather than from `<sdk-location>/extras/android/...`.  That solved it!

Finally getting a chance to see all your handiwork.  I am beyond swamped at work right now but I really want to give you all the support I can on this, since this is such a much-needed injection of fresh blood.

**Comment by BonzaiThePenguin** [comment]
Aye, I actually had to modify the projects before copying them to the libs folder because they weren't configured properly for whatever reason. That's probably why they weren't working for you either.

**Comment by ocdtrekkie** [comment]
Guess I'll have to keep an eye when this gets merged and get a final copy before that. :/ AppCompat/Material is a pain to get rid of once you're on it.

**Comment by BonzaiThePenguin** [comment]
Why would you want to get rid of it?

**Comment by ocdtrekkie** [comment]
AppCompat now forces Material or whatever garbage they come up with next.

**Comment by BonzaiThePenguin** [comment]
Well, yeah. It's a first-party framework for making your app look and feel native.

**Comment by ocdtrekkie** [comment]
Material isn't native for the 90% of folks on 4.x. Like all of my devices.

**Comment by BonzaiThePenguin** [comment]
I'm on 4.x and all of my apps are Material-y. Which ones are you talking about?

**Comment by ocdtrekkie** [comment]
Nothing in the OS of Android 4.x is Material. Google has shoved Material on their apps in the Play Storr, but the Android 4.x UI for the entire platform is Holo.

**Comment by littleguy77** [comment]
@ocdtrekkie We try to use GitHub issues for detailed bug reporting and tracking, and discussing gory implementation details.  Please use the paulscode forum if you want to weigh in on design philosophies and stuff that end-users might want to discuss.  This topic would be well suited to the following thread:
http://www.paulscode.com/forum/index.php?topic=1130
