### ISSUE TITLE
Animal Forest (Doubutsu No Mori) english patch rom crash

### ISSUE THREAD

**Issue by figuresk8er** [mupen64plus-ae/mupen64plus-ae#43]
Hi, I am a big fan of this emulator, but i have run into an issue. I used to use n64oid, because of its compatability, but i switched over to mupen64 because it is nicer and more user friendly. There is just one problem, i used to play animal forest (full english patch version) on n64oid with no problem, but when I play on mupen64 it crashes before it even loads. Please fix this, I paid for the donation version on google play store and I rated 5 stars. There is no doubt in my mind that you wont fix this soon. Thanks :)

**Comment by fzurita** [comment]
Upstream issue

**Comment by User77111** [comment]
Download is here https://web.archive.org/web/20130624040053/http://www.fileden.com/files/2012/3/28/3284379/AFProjectDistro.zip

**Comment by User77111** [comment]
It's the latest version of the patch.

**Comment by fzurita** [comment]
If the unpatched version works, but the unpatched one doesn't, then it's most likely a problem with the patch.

**Comment by fzurita** [comment]
You could request support for this patch upstream. Since the unpatched version works, it would most likely require some sort of hack. This is upstream: https://github.com/mupen64plus/mupen64plus-core
