### ISSUE TITLE
Paper mario constanly flickers

### ISSUE THREAD

**Issue by thiskid12345** [mupen64plus-ae/mupen64plus-ae#430]
on any android device.  paper mario will flicker. i have a samsung galaxy tab s 8.4(very powerful tab). i had a tab 2 before so just thought my device was too weak to run paper mario. even on my new tab s it does the same thing.  i dont want to change settings because im afraid i might fuck something up.  can you guys try paper mario 64 on the software and see what you guys can do.

**Comment by fzurita** [comment]
Upstream issue
