### ISSUE TITLE
Kirby 64: Multiple displays where the borders should be.

### ISSUE THREAD

**Issue by cmexp** [mupen64plus-ae/mupen64plus-ae#431]
Kirby 64's borders aren't there, extending the game to render in multiple displays. In the version on the Play store, this doesn't happen when using glN64. However, in the latest alpha builds it ends up happening with every plugin. It looks like this:

![screenshot_2015-04-02-21-14-07](https://cloud.githubusercontent.com/assets/6110397/6976832/9c125da2-d97d-11e4-9a1d-142d8ddfd3ff.png)

**Comment by easyaspi314** [comment]
Yeah I love Kirby 64 but I have had the same issue. The desktop version works with Glide64mk2 (I think) which is not here. Maybe it mk2 was added it would work.

**Comment by littleguy77** [comment]
android has all the same video plugins as the desktop version, and then some.  Including mk2

**Comment by fzurita** [comment]
Upstream issue
