### ISSUE TITLE
Option to hide navigation bar (immersive mode)

### ISSUE THREAD

**Issue by PaulFreund** [mupen64plus-ae/mupen64plus-ae#439]
This is more or less a feature request but I could implement it myself if it is feasible. In my opinion it would be optimal to always hide the navigation bar in game view and make it possible to swipe it up from the bottom of the screen like in other applications.

If feasible a few pointers on where to start would be nice :)

**Comment by BonzaiThePenguin** [comment]
There should be an option for hiding the navigation bar in the settings, if it wasn't already enabled.

**Comment by BonzaiThePenguin** [comment]
Here's how it's implemented in the code:
https://github.com/mupen64plus-ae/mupen64plus-ae/search?utf8=✓&q=immersive

**Comment by littleguy77** [comment]
It's already implemented in both the published version and the alphas posted on paulscode.  You have to enable it in the global settings.  It also requires a KitKat device, because that's when the immersive mode feature was introduced.

**Comment by PaulFreund** [comment]
Okay found the Problem, I habe bought the Version from the store and my device runs lollipop, but immersive is only enabled with kitkat

**Comment by PaulFreund** [comment]
Okay found the Problem, I habe bought the Version from the store and my device runs lollipop, but immersive is only enabled with kitkat, See GlobalPerfsActivity.java

**Comment by BonzaiThePenguin** [comment]
IS_KITKAT is defined as KitKat *or newer*:

    IS_KITKAT = Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT;

**Comment by PaulFreund** [comment]
Hmm then I dont know. Maybe I am just blind, how would you navigate to this setting? I really searched but who knows.

**Comment by BonzaiThePenguin** [comment]
Have you tried using the latest version of Mupen? The source code here isn't for the last Play Store release.

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/

**Comment by PaulFreund** [comment]
Okay that was the Problem, thank you :)
