### ISSUE TITLE
multiplayer help please

### ISSUE THREAD

**Issue by emazing33** [mupen64plus-ae/mupen64plus-ae#445]
Every time I connect two controllers and try to play a game it says you need to define your controllers and I already mapped all keys for both players and when I do define it it will only define player 1 what do I do please respond

**Comment by easyaspi314** [comment]
Welcome to GitHub!
Did you switch the P2 controller on (Settings/Input)? And can you please give some information, like what steps you did, device model, Android version, app version, and what controllers/adapters you used? The info you gave us really isn't enough to correctly identify and solve your problem.
