### ISSUE TITLE
gles2rice and Smash 64 visual glitches

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#454]
When using Rice to emulate SSB, (I want texture packs.) there are a few graphical glitches. 
Glide64 works perfect, but it really needs texture packs and options in general.

First of all, the graphics are glitchy with frame skip on (and laggy if off). First primitive draw works well except it freezes the menus and you have to force a refresh by (for example) opening and cancelling the game speed dialog. All settings have a weird border around it.

Additionally, shaders (I think) are not working, so team battles have no tint to differentiate, you cannot see invincibility frames (white flashes) and characters don't glow red when their shield breaks. This also happens in glN64.

It also seems that there is no speed limit when auto frame skip is on, forcing me to decide between fast or slow.
And this happens with Smash HD texture pack when 2 or more Kirbys are on the screen. The face texture covers all of the Kirby's except the original one (not necessarily pink).

![smash_brothers-029](https://cloud.githubusercontent.com/assets/6258309/9777851/f47680c2-5736-11e5-906a-5e65895eba36.png)

Samsung Galaxy S II Skyrocket i727
SAMSUNG-SGH-I727
Android 4.1.2

Qualcomm Adreno 220 @ 266 MHz
OpenGL ES 2.0

1.51GHz dual-core Qualcomm Snapdragon S3 QCT MSM8X60
1GB RAM

Mupen64 Plus AE v3 Alpha 2015-09-08 19:03 autobuild

**Comment by fzurita** [comment]
Upstream issue, GLideN64 also probably improves the situation with this game.

**Comment by easyaspi314** [comment]
Yeah. Glide64mk2 is flawless (but no hires textures.) I thought Glide64mk2
could do that.

GLideN64 is slooow on my phone, but that is likely because it only supports
OpenGL ES 2.0, and isn't usable at all.

**Comment by fzurita** [comment]
Glide64mk2 does support high res textures, but we left them disabled for some reason. It would take a lot of work to bring them back.

How does glN64 work for you performance wise? It's what the GLideN64 2.0 variant is based off.

**Comment by easyaspi314** [comment]
glN64 is fast, but it has weird alignment glitches, where characters' faces
are too high on their model. It also, IIRC, didn't have shading
(invincibility flashing, team color brightness, etc).

I don't really know why. I am using an S3 and that should have more than
enough power to run it, but even at a lower resolution, the max on gliden64
is about 2/3 speed, sometimes slower. :(

**Comment by fzurita** [comment]
Have you tried messing around with settings? For example, have you tried disabling frame buffer emulation?

**Comment by easyaspi314** [comment]
Disabling HWFBE helped a bit.

I really am fine with Glide64mk2 and Rice. I just wished Glide64 had more
options. I *know* there are options, like high res; more than just
frameskipping.

– Devin Hussey

On Tue, Apr 12, 2016 at 12:10 PM, Francisco Zurita <notifications@github.com

**Comment by fzurita** [comment]
There are more options, they are just not exposed in the UI. You have to manually edit a file.

**Comment by easyaspi314** [comment]
### Exactly.

**Comment by fzurita** [comment]
Great idea for your next pull request :-)

**Comment by easyaspi314** [comment]
I see what you did there…

**Comment by fzurita** [comment]
Because we are inconsistent.

**Comment by easyaspi314** [comment]
That is the number 1 problem with this app.

**Comment by fzurita** [comment]
Glide64 had way too many options. We would have to go through the effort to try to figure out which options are useful to the user. We would then also have a million bug reports because tweaking the options cause bugs to araise.

**Comment by easyaspi314** [comment]
Look at GlideN64. 

That doesn't have way too many options?

**Comment by easyaspi314** [comment]
![tmp_4383-screenshot_2016-04-12-05-49-361780949400](https://cloud.githubusercontent.com/assets/6258309/14467798/ea4c3556-00aa-11e6-85d2-cf655be8969d.png)
This was from messing with the in-app GLideN64 settings. I don't really believe that.

**Comment by fzurita** [comment]
That's pretty impressive. You could file a bug report upstream in the GLideN64 project: https://github.com/gonetz/GLideN64

Changes are that it would never get addressed though due to lack of man power. This is probably a device specific bug due to really bad OpenGL ES drivers.

**Comment by easyaspi314** [comment]
I say, put the settings in. We do it just like GLideN64. We put in raw values, then slowly put in names and take out the non-working ones.

**Comment by fzurita** [comment]
One thing that really sucks with android is VERY bad OpenGL ES drivers. It's impossible to get everything working in every device because of how many variations there are. It's commonly called "fragmentation."

**Comment by easyaspi314** [comment]
Trust me, I know what fragmentation (and how ironic that the Android Support Library tried to battle fragmentation by adding the Fragment class).

**Comment by fzurita** [comment]
That's not a bad idea. Can you write a new issue? Make it very specific though. You can call it: "Expose Glide64mk2 Settings in the UI".

**Comment by easyaspi314** [comment]
Done.
