### ISSUE TITLE
Zip file scan not working

### ISSUE THREAD

**Issue by stephenwiebe** [mupen64plus-ae/mupen64plus-ae#456]
With the latest alpha build (and at least some of the previous builds I've tried as well), zip file scanning seems to be broken for me. I point Mupen64 at either a directory containing zipped roms, or a single zipped rom and a brief scanning bar shows up but then nothing more happens after the scan is completed - no games show up. If I unzip one of the zip files, the unzipped game then shows up when I scan. I'm running on a Shield TV device.

**Comment by fzurita** [comment]
Hmmm,  this seems to be working ok for me. Do you know how to capture the logcat?

**Comment by fzurita** [comment]
Can you try this version?

https://dri​ve.google.co​m/file/d/0B5​7Ioy26LWegRj​dpSExpUmQwSm​c/view?usp=s​haring

**Comment by stephenwiebe** [comment]
I tried to access your link, but it seems to be inaccessible or the file has been deleted. As for the logcat, I can view it, but I can't figure out how to successfully save it to a file. I click the Share button and select a directory but no file shows up in the directory. In any case, when I scan a directory that contains zipped ROMs, I see a bunch of messages in the logcat output like:

[09-24 22:49:59.402 7995:8475 I/CacheRomInfoTask]
Found zip file Mario Party (USA).zip

[09-24 22:49:59.402 7995:8475 I/CacheRomInfoTask]
Found zip file Donkey Kong 64 (USA).zip

... etc. ...

and so on. I don't see anything obviously out of the ordinary. I do see a number of log messages that say "Attempted to finish an input event but the input event receiver has already been disposed.", but I think those are unrelated.

**Comment by fzurita** [comment]
I posted an incorrect link. Try this:https://drive.google.com/file/d/0B57Ioy26LWegRjdpSExpUmQwSmc/view?usp=sharing

**Comment by fzurita** [comment]
I think I may see the problem. We have some unnecessary checks when extracting zip files, that *could* be causing your issue. Can you tell me if this build fixes your problem?

https://drive.google.com/file/d/0B57Ioy26LWegaFQwNGhVYVJLeTA/view?usp=sharing

**Comment by stephenwiebe** [comment]
That one works, thank you!

**Comment by fzurita** [comment]
Ok, I'll make a pull request to include this fix on the official build
