### ISSUE TITLE
Rayman 2 has no in-game text

### ISSUE THREAD

**Issue by Cockie** [mupen64plus-ae/mupen64plus-ae#46]
Device: Odys Next
CPU: Cortex A8 1.2 GHz (1 core)
RAM: 1 GB
Resolution: 800x600
Rom: ICS 4.0.3
App Version: Current market release
Plug-ins: Both gles2n64 and gles2rice
no soundplugin (enabling sound is too much to handle for my poor device)
standard plugins for the rest

Description: 
Before I start, I love the app, great work! :)
Rayman 2: The Great Escape: the game itself is perfectly playable (thus far, I'm not that far yet) but there is one minor (yet slightly annoying) problem: none of the in-game text is showing up, not the dialogue, not the help texts, not the storytelling texts. The only text I get is in the stats that show up when you press R and text in the menus.
I have tried several ROMs and all of them do this.
I have also tried it with gles2rice (I normally always use gles2n64 since gles2rice either crashes or gives 1 fps) and it appears to do the same.
It's not a really large bug (the game plays fine), it's just quite annoying that you don't really know what's going on and what you're supposed to do.
Thanks in advance.

**Comment by fzurita** [comment]
Upstream issue
