### ISSUE TITLE
Unable to choose and configure input controller profile in TV mode

### ISSUE THREAD

**Issue by ahochsteger** [mupen64plus-ae/mupen64plus-ae#469]
I was able to install and run Mupen64+ AE 2.4.4 on Nexus Player (on Android 6.0 preview 3) but was unable to play any games since the start button was missiong on the Asus Gamepad which is the main controller for the Nexus Player.
I was able to configure it on a smartphone, store the profile and transfer it to the Nexus Player but there's no possibility to select a stored profile. The actions to load a saved profile is just missing (among some others). 

In case you're interested to support the controller by default - here is some information:
Stored profile for "ASUS Gamepad":
```
4:-37,5:-35,3:-34,2:-33,1:-32,0:-31,11:-30,10:-29,9:-24,8:-23,19:-4,18:-3,17:-2,16:-1,7:96,6:97,6:99,13:102,12:103,
0
100
```

**Comment by ahochsteger** [comment]
Update: It seems that the bigscreen mode is not detected correctly on the Nexus Player.
If I change the accessibility mode to big-screen I get the list of controller buttons in the input settings and can change them.
So if auto-detect works correctly, it may resolve this issue.
But I found one more problem in combination with TV mode:
If I want to enable multi-player mode and click on "Player 2" I get into the controller button configuration screen which then works as expected. But when I exit it the second player is still shown as "OFF". I didn't find a way to turn it to ON in TV mode since there's no touch input to change the switch.

**Comment by fzurita** [comment]
can you install the latest alpha build and see if you still have those problems? Here is the link:

https://github.com/mupen64plus-ae/mupen64plus-ae/commit/b2be8ff

**Comment by ahochsteger** [comment]
Thanks for the link!
The configuration and selection of the controller profiles works fine with the latest alpha build.
What does not work tough is adding ROMs to the library. After scanning for files the library is still empty, so I was not able to test, if the controllers work as expected.

**Comment by fzurita** [comment]
The latest auto build has issues with scanning for games. Try this build instead: https://drive.google.com/file/d/0B57Ioy26LWegaFQwNGhVYVJLeTA/view?usp=sharing

**Comment by fzurita** [comment]
Also, you will have to uninstall the alpha build before you can install that one due to a different signature.

**Comment by ahochsteger** [comment]
Thanks, this version works perfectly!
