### ISSUE TITLE
Occasional OOM error on rom settings?

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#476]
Sometimes, when I click the ROM settings, (I can't consistently reproduce this), Mupen crashes with an OutOfMemoryError. Logcat:

```
10-02 14:47:20.876 E/AndroidRuntime(5741): FATAL EXCEPTION: main
10-02 14:47:20.876 E/AndroidRuntime(5741): java.lang.OutOfMemoryError
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at java.lang.String.<init>(String.java:432)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at java.io.BufferedReader.readLine(BufferedReader.java:363)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.cheat.CheatFile$CheatSection.<init>(CheatFile.java:349)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.cheat.CheatFile$CheatSection.<init>(CheatFile.java:336)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.cheat.CheatFile.reload(CheatFile.java:140)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.cheat.CheatFile.<init>(CheatFile.java:105)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.persistent.GamePrefsActivity.buildCheatsCategory(GamePrefsActivity.java:337)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.persistent.GamePrefsActivity.refreshCheatsCategory(GamePrefsActivity.java:293)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at paulscode.android.mupen64plusae.persistent.GamePrefsActivity.onCreate(GamePrefsActivity.java:194)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.Activity.performCreate(Activity.java:5177)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.ActivityThread.access$700(ActivityThread.java:143)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.os.Looper.loop(Looper.java:137)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at android.app.ActivityThread.main(ActivityThread.java:4950)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-02 14:47:20.876 E/AndroidRuntime(5741): 	at dalvik.system.NativeStart.main(Native Method)
```

I do have Xposed installed, but nothing directly modifies it. 
Edit: I do have a lot of custom cheats, but I didn't click the cheats menu directly.
Samsung Galaxy S II Skyrocket SGH-i727
Android 4.1.2 rooted
1 GB RAM (788 MB recognized)

**Comment by fzurita** [comment]
Are you using the latest alpha build?

**Comment by easyaspi314** [comment]
I was using the one you gave me with the volume key fix

– Devin Hussey

**Comment by fzurita** [comment]
Ok, I haven't personally seen this, but my devices do have 2GB of RAM. Based on the stack trace, it looks like the cheat code may be using too much memory. I'm going to have to profile this to see where this is happening, but it does sound like the cheat code is doing something inefficiently.

**Comment by easyaspi314** [comment]
I think it is reading the cheat file at the same time that it is loading
the UI. We should probably only load the cheats when we load the cheats
menu; and lazily load them. Can you maybe try an emulator with say 512 MB
RAM and a ton of cheats?

– Devin Hussey

**Comment by fzurita** [comment]
Yeah, that's a good idea.

**Comment by easyaspi314** [comment]
Doing a traceback, what I see is it is reading the cheat file and looking for CRCs like this: 

```
        /**
         * Constructs a {@link CheatSection} object, populating its fields by reading from disk.
         * 
         * @param key the key (ROM CRC and country code) for this ROM section
         * @param reader the object providing disk read access
         * @throws IOException if a read error occurs
         */
        private CheatSection( String key, BufferedReader reader ) throws IOException
        {
            this.key = key;
            this.blocks = new LinkedList<CheatBlock>();
            this.elements = new LinkedList<CheatElement>();
            this.fullLines = new LinkedList<String>();
            
            if( !key.equals( NO_KEY ) )
            {
                elements.add( new CheatLine( "crc " + key ) );
            }
            
            String fullLine;
            while( ( fullLine = reader.readLine() ) != null )
            {
                if( fullLine.startsWith( "crc " ) )
                {
                    // Start of the next cheat section, return
                    nextKey = fullLine.substring( 4 );
                    return;
                }
                else
                {
                    fullLines.add( fullLine );
                }
            }
        }
```

I bet that the `fullLines.add( fullLine );` is the culprit. We seem to be putting thousands of cheats in one LinkedList __in memory__. Maybe what we should do is either do this once and make seperate cheat files with that game's codes only in each game's folder __or__ have an online database and prompt for an internet connection when a new rom is detected and download it,

**Comment by fzurita** [comment]
I think I agree with you. It's possible that we are loading all the cheats for all games whenever we enter any game's preferences.

**Comment by littleguy77** [comment]
That cheat file is 1.2 MB.  With overhead I wouldn't expect that list to occupy more that 1.5MB of memory.  I wouldn't look there for the culprit.

Please dig into the git history for all of this cheat handling, and read the git messages.  Saving the linked list of raw lines is a significant performance optimization.

That said, you're welcome to write new game-specific cheat files on the fly, as you propose.  This would fit logically with the per-game directory structure used in the alphas.  Just beware, I would bet this is not the source of the OOM error, so that would really just be another performance optimization to make per-game cheat files.

**Comment by easyaspi314** [comment]
Well it seemed that it mostly happened when I opened it right after closing a rom. That is why we should load the cheats after we start the prefs so we have time to let the rom get out of memory.

**Comment by fzurita** [comment]
I'm profiling using Eclipse. I'm not seeing any memory leaks so far. CPU wise, what hurts the most in the java code is reloading the RomDatabase on every activity.

I'm trying to see what our biggest memory heavy hitter is right now. I have the feeling it's going to be that RomDatabase class.

**Comment by fzurita** [comment]
The biggest memory culprits right now seem to be the native libraries that we load into memory.

**Comment by fzurita** [comment]
This is some weird stuff. I'm analyzing a heap dump, and I found this in the dump:

```
REGISTER sip:nist.gov SIP/2.0
Via: SIP/2.0/UDP 129.6.55.182:14826
Max-Forwards: 70
From: <sip:mranga@nist.gov>;tag=6fcd5c7ace8b4a45acf0f0cd539b168b;epid=0d4c418ddf
To: <sip:mranga@nist.gov>
Call-ID: c5679907eb954a8da9f9dceb282d7230@129.6.55.182
CSeq: 1 REGISTER
Contact: <sip:129.6.55.182:14826>;methods="INVITE, MESSAGE, INFO, SUBSCRIBE, OPTIONS, BYE, CANCEL, NOTIFY, ACK, REFER"
User-Agent: RTC/(Microsoft RTC)
Event:  registration
Allow-Events: presence
Content-Length: 0

INVITE sip:littleguy@there.com:5060 SIP/2.0
Via: SIP/2.0/UDP 65.243.118.100:5050
From: M. Ranganathan  <sip:M.Ranganathan@sipbakeoff.com>;tag=1234
To: "littleguy@there.com" <sip:littleguy@there.com:5060> 
Call-ID: Q2AboBsaGn9!?x6@sipbakeoff.com 
CSeq: 1 INVITE 
Content-Length: 247
```

Where is this coming from? I couldn't find it anywhere in the code

**Comment by littleguy77** [comment]
WTF?

BTW that's not my email address...

**Comment by easyaspi314** [comment]
Is the 6fcd5c7ace8b4a45acf0f0cd539b168b a commit?

**Comment by fzurita** [comment]
I'm not sure how anything to do with a commit would make it into the compiled apk

**Comment by easyaspi314** [comment]
Nope it isn't a commit. I dunno why but [doing a search on github](https://github.com/search?q=6fcd5c7ace8b4a45acf0f0cd539b168b&ref=reposearch&type=Code&utf8=%E2%9C%93) shows it is not us.

**Comment by fzurita** [comment]
It seems to come from this app: https://github.com/Mobicents/jain-sip 

I don't think I even have that installed on my phone. I wonder how it would even get into a heap dump for Mupen64plus-ae

**Comment by fzurita** [comment]
Well... back on topic. If there is a memory leak somewhere, it's not showing it self to me. And it doesn't seem like anything is taking an inappropriate amount of memory in the heap dump.

I'm tempted to just set this in the AndroidManifest.xml file.

android:largeHeap="true"

**Comment by fzurita** [comment]
I created a test build with that parameter set. It can be found right here:

https://drive.google.com/file/d/0B57Ioy26LWegaVdXS0ZhWTdrZUU/view?usp=sharing

Can you try that out and let me know if you still get out of memory errors?

**Comment by fzurita** [comment]
Hmm.... loading cheats for a couple of games caused my heap size to peak at around 57MB from 45MB without cheats.

**Comment by easyaspi314** [comment]
The apk says Application not installed. It looks like the dex is unsigned.

**Comment by fzurita** [comment]
You may have to uninstall your current version and then install the one I posted due to a different signature.

Either way, I don't think it's a true fix. I can see that cheat loading causes the VM heap size to grow by over 10MB. We are currently loading all cheats for all games when we entered the game preferences activity.

I bet I can lower the RAM usage by only loading the specific cheats for a game.

**Comment by easyaspi314** [comment]
Yeah I tried that. I also tried mucking with XInstaller... nothing.

**Comment by easyaspi314** [comment]
Honestly, I think that the for loop was the straw that broke the camel's
back.

**Comment by fzurita** [comment]
Strange, maybe the apk is corrupt. I won't be able to make another one until about 15 hours from now.

**Comment by easyaspi314** [comment]
Okay take your time

**Comment by easyaspi314** [comment]
I looked in the APK and all of the files have a timestamp of Jan 14 1970.

**Comment by fzurita** [comment]
Yeah, sounds like something is corrupt with it.

**Comment by xperia64** [comment]
@littleguy: The weird stuff in the heap dump originates from part of Java itself: https://github.com/cybertk/nist-sip-for-blackberry/blob/master/src/test/tck/factory/FactoryTestHarness.java

**Comment by fzurita** [comment]
@easyaspi314 : Try re-downloading the APK. I just downloaded it to my phone from google drive and it installed correctly. Maybe the file got corrupt when you were downloading it.

**Comment by easyaspi314** [comment]
It works now. However, there is no real way to test this because I simply can't reliable reproduce it. Maybe I can reduce OOM levels but I don't know.

**Comment by fzurita** [comment]
Right, it was only meant to get you through and I have no idea if it will even work. The real solution I think will be to load cheats more efficiently. Currently enabling cheats add 30% more memory utilization.

**Comment by easyaspi314** [comment]
Maybe this will help with with GlideN64 on OpenGL ES 2.0... lol. 

But we should make sure we manage the RAM efficiently and not let the app just abuse it.

**Comment by fzurita** [comment]
It probably won't help with that. GLideN64 is mostly GPU/CPU/Memory bandwidth limitations. Although, Gonetz is doing something to improve Opengl ES 3.0+ performance, he is adding a shader cache. I have tried that branch and it does help a lot with stuttering.

**Comment by easyaspi314** [comment]
I know I was kidding. Besides, 3.0+ isn't really going to help us 4.1 users.

**Comment by fzurita** [comment]
Oh... lol

**Comment by easyaspi314** [comment]
I am trying to work on the cheat manager however I am waiting for ADT to download. Can't wait for NDK to come to AS.

**Comment by fzurita** [comment]
Cool, feel free to have a crack at it. I'll work on the many other issues I see.

**Comment by easyaspi314** [comment]
I just realized how much I __hate__ Eclipse ADT.

**Comment by fzurita** [comment]
It's not that bad once you get used to it

**Comment by easyaspi314** [comment]
I strongly prefer AS. I used ADT before and hated it, now that I have gotten used to AS, ADT is even worse. I complain a lot. 

Also, NDK compiling. boring

**Comment by fzurita** [comment]
I tried to import this project into Android studio, but I gave up with not much success.

**Comment by easyaspi314** [comment]
Yeah I have it worse: I am not admin so I am currently stuck with 1.2. :frowning: I also struggled to install ADT because of the firewall. Grr

**Comment by easyaspi314** [comment]
I opened a new issue that deals with just in general fixing the settings. #481

**Comment by fzurita** [comment]
@easyaspi314 can you try this build?

https://drive.google.com/file/d/0B57Ioy26LWegSDFwRzVkbHM5Qkk/view?usp=sharing

I did a series of performance optimizations. See this branch for details:

https://github.com/fzurita/mupen64plus-ae/tree/performance_optimizations

**Comment by easyaspi314** [comment]
Well at least with the build you gave me, everything seems to work except one NPE when the app process is killed but not swiped away (onStop() → onCreate()). This happens when you click on the rom settings: 

```
10-08 06:22:40.010 D/dalvikvm(27182): WAIT_FOR_CONCURRENT_GC blocked 52ms
10-08 06:22:40.010 D/AndroidRuntime(27182): Shutting down VM
10-08 06:22:40.010 W/dalvikvm(27182): threadid=1: thread exiting with uncaught exception (group=0x414fa360)
10-08 06:22:40.230 E/AndroidRuntime(27182): FATAL EXCEPTION: main
10-08 06:22:40.230 E/AndroidRuntime(27182): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mupen64plusae.v3.alpha/paulscode.android.mupen64plusae.persistent.GamePrefsActivity}: java.lang.NullPointerException
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread.access$700(ActivityThread.java:143)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.os.Looper.loop(Looper.java:137)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread.main(ActivityThread.java:4950)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at dalvik.system.NativeStart.main(Native Method)
10-08 06:22:40.230 E/AndroidRuntime(27182): Caused by: java.lang.NullPointerException
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at paulscode.android.mupen64plusae.util.RomDatabase.lookupByMd5(RomDatabase.java:169)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at paulscode.android.mupen64plusae.util.RomDatabase.lookupByMd5WithFallback(RomDatabase.java:134)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at paulscode.android.mupen64plusae.persistent.GamePrefsActivity.onCreate(GamePrefsActivity.java:142)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.Activity.performCreate(Activity.java:5177)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
10-08 06:22:40.230 E/AndroidRuntime(27182): 	... 12 more
```

**Comment by fzurita** [comment]
Ok, I'll look into that, thanks for the report.

**Comment by littleguy77** [comment]
Thanks for the optimizations @fzurita.  I had planned to do that once the architecture settled down but then got way too busy in real life.  Just be very careful because IIRC there are lots of corner cases where instances of the various data classes (AppData, GlobalPrefs, GamePrefs, Cheats.., Rom...) can become stale.  Weird stuff like if you press home, then rotate then screen, the moon is eclipsed by the sun, and it's a tuesday, the data becomes out of date.  Hence why I was dynamically loading a lot of stuff as the default course of action.  I'm sure you can work through any corner cases if you missed any, but just wanted to alert you to beware of those types of regressions.

Thanks again :+1:

**Comment by fzurita** [comment]
Yep, I'll keep my eye out for them. Hopefully nothing got broken, I did try to look out for that, but it's very hard to predict all the corner cases. I'm sure if there are any, they will show up in due time.

**Comment by fzurita** [comment]
New build, it should fix that crash:

https://drive.google.com/file/d/0B57Ioy26LWegckVXVWpYZnljaGc/view?usp=sharing

**Comment by fzurita** [comment]
This branch feels a lot more responsive in my phone personally, specially when cheats are loaded. I'll see if it's easy to optimize the cheat editor as well tonight.

**Comment by easyaspi314** [comment]
If only we could have ExpandableListView groups in groups.

– Devin Hussey

**Comment by easyaspi314** [comment]
Ok so I tried it and I noticed that it took 2sec to load the rom settings.
Is the app still loading the cheats in a PreferenceScreen or does it have
its own category? Plus maybe we should use the v4 PreferenceFragmentCompat
Library AAR at
https://jitpack.io/com/github/shkschneider/android_PreferenceFragmentCompat/1.0.0/android_PreferenceFragmentCompat-1.0.0.aar

Migrating to a PF is very easy. I can help if needed.
If only we could have ExpandableListView groups in groups.

– Devin Hussey

**Comment by fzurita** [comment]
Yeah, we are still loading cheats, but only the relevant section of the file. How long did it take before?

**Comment by fzurita** [comment]
There is going to be some lag no matter what we do because we are loading the cheats from a file in the main UI thread. Next step I will take is load the cheats from a async task.

With an async task, cheats will load as you are navigating the UI.

**Comment by easyaspi314** [comment]
Well if we do a preferencefragment, we can call the `ASyncTask` in `onResume()` of the  main pref fragment and load the cheats there into a PreferenceScreen public static variable but don't set it.



For loading the cheat thing, we have a Preference with an OnPreferenceClickListener that pops the fragment into thr foreground and then calls

**Comment by fzurita** [comment]
Yeah, that approach could work a think. Refactoring into a preference fragment feels like too much work with little benefit.

**Comment by fzurita** [comment]
Although, feel free to try to implement that your self.

**Comment by fzurita** [comment]
Ok, I made game preferences and cheats faster and more efficient. Can you try this one:

https://drive.google.com/file/d/0B57Ioy26LWegSlZUY2wtN1BEd28/view?usp=sharing

Also, can you make sure the cheat editor still works ok for you?

Next, I'm going to work in adding folders to the shared preferences next.

**Comment by fzurita** [comment]
I'm getting reports saying that not the right cheats are being loaded when a cheat is selected.

**Comment by easyaspi314** [comment]
When you select a code, it looks right but it is using the code that is in its place when not alphabetized. 

Additionally, when I hit back to exit before the game loads and  hit resume again, I get this:

```
10-09 07:07:27.351 E/AndroidRuntime(7368): FATAL EXCEPTION: CoreThread
10-09 07:07:27.351 E/AndroidRuntime(7368): java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at com.google.android.gles_jni.EGLImpl._eglCreateWindowSurface(Native Method)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:90)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at paulscode.android.mupen64plusae.game.GameSurface.createEGLSurface(GameSurface.java:358)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at paulscode.android.mupen64plusae.game.GameSurface.createGLContext(GameSurface.java:181)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at paulscode.android.mupen64plusae.jni.NativeSDL.createGLContext(NativeSDL.java:54)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at paulscode.android.mupen64plusae.jni.NativeExports.emuStart(Native Method)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at paulscode.android.mupen64plusae.jni.CoreInterface$1.run(CoreInterface.java:221)
10-09 07:07:27.351 E/AndroidRuntime(7368): 	at java.lang.Thread.run(Thread.java:856)
```

**Comment by fzurita** [comment]
New build, it fixes the wrong cheat being selected issue:

https://drive.google.com/file/d/0B57Ioy26LWegYlhNTVFKNkd2RWc/view?usp=sharing

**Comment by easyaspi314** [comment]
Better but it acts weirs when you rename a cheat

**Comment by fzurita** [comment]
Yeah, working on it. It also duplicates alp the cheats when you save. I still need to fix those issues. I'll make another build once I feel like everything is working right.

**Comment by easyaspi314** [comment]
Wait you can incorporate what iu are doig now and make it write to the game-specific file.

**Comment by easyaspi314** [comment]
Wow typos.

**Comment by easyaspi314** [comment]
And make it do rhat when you open the cheats pref. If possible.

**Comment by fzurita** [comment]
Ok, another version:

https://drive.google.com/file/d/0B57Ioy26LWegTG5XVXloRnZ3QUU/view?usp=sharing

It should fix the duplicate cheat issue.

**Comment by fzurita** [comment]
https://drive.google.com/file/d/0B57Ioy26LWegRGpNNzlaVjBCYUE/view?usp=sharing

This one fixes an issue with saving cheats.

**Comment by fzurita** [comment]
I think this issue should be all set. I will implement some of your suggestions in a future build. Specifically game specific cheat storage.

**Comment by easyaspi314** [comment]
No unless you changed something, it is still duping cheats, but only in the
enable/disable screen.

Sorry I couldn't reply, I was traveling vast spaces of no data coverage.

**Comment by fzurita** [comment]
No problem. You will have to manually delete the duped cheats in the CheatEditorActivity.

**Comment by easyaspi314** [comment]
You mean delete all of the default cheats, or just the ones that are
duplicated?

**Comment by fzurita** [comment]
If you delete the UserCheats file, it will delete every single cheat you have created (not built-in). If you don't want to do that, you will have to delete each dupe by hand in the cheat editor activity.

**Comment by easyaspi314** [comment]
Well can you at least make the cheat editor keep the adapter, just
remove/edit/overwrite the items and use

adapter.notifyDataSetChanged();

so it doesn't always scroll to the top? It would make things easier.

**Comment by fzurita** [comment]
Excellent idea. I did not realize it was scrolling to the top every time you deleted a cheat. Give me one sec and I'll make a build that does that.

**Comment by easyaspi314** [comment]
This would take longer, but a CAB with multi select would be nice. A later
feature though

**Comment by fzurita** [comment]
Ok, try this:

https://drive.google.com/file/d/0B57Ioy26LWegNkhjY3dfaWJYOVE/view?usp=sharing

It should no longer scroll to the top when you delete something.

**Comment by easyaspi314** [comment]
Still scrolling to the top. You have to change the data set only, if you do

adapter = new ListAdapter<>(foo);
adapter.notifyDataSetChanged();

it will still scroll to the top. You have to do something like this:

switch (result.type) {
case RESULT_EDITED:
//edit cheat
adapter.insert(mResultCheat, result.index);
case RESULT_ADDED:
adapter.add(mResultCheat);
case RESULT_DELETED:
// Delete cheat
adapter.remove(mOriginalCheat);
default:
return;
}

if (result.type == RESULT_ADDED || result.type == RESULT_TITLE_EDITED)
// if cheat title was edited, we rearrange it
adapter.sort(mComparator);

//Commit the changes and show the user.
adapter.notifyDataSetChanged();

When you finish editing the cheat, have it return its updated Cheat object,
its result, and its position. This is not real code but you get the gist,
right?

**Comment by fzurita** [comment]
Yeah... I'm surprised what I gave you didn't work,  I guess I don't have a really long cheat list to test it with. I will attempt your approach.

**Comment by easyaspi314** [comment]
This has a ton of codes for Smash (although you can rename the CRC header. :)

https://drive.google.com/file/d/0Bxk_L8QgNv7TNl9SWXh6cHRMT2M/view?usp=sharing

**Comment by fzurita** [comment]
Lol, thanks, that makes life easier. I'll input those into my file.

**Comment by easyaspi314** [comment]
Make a backup it still has the dupe cheats.

**Comment by fzurita** [comment]
I don't care about that, I don't have any custom cheats.

**Comment by fzurita** [comment]
Ok, your approach worked. I'll send you a build.

**Comment by fzurita** [comment]
https://drive.google.com/file/d/0B57Ioy26LWegWHMyMVY3b3NYY3M/view?usp=sharing

Try that one out. Let me know how it works for you.

**Comment by fzurita** [comment]
Also, if the out of memory errors are gone for you. I think we can close this issue.

**Comment by easyaspi314** [comment]
The list doesn't scroll to the top! :D

Can you make it so it sorts automatically when you rename the cheat?

With the buttons on the top, it is an Android Design no-no. Make the Toast
that says to long-press to edit show in onCreate(); put the Add in the
Action Bar, Save in the action bar in low priority (so it doesn't show in
portrait if it is too small); and Help in the overflow. And Add should show
a dialog before adding.

I had a fun time with this: Play Store bugged and would soft reboot
whenever it tried to install anything. I had renamed a cheat and the Play
Store did an automatic update and it crashed my phone. I was about to
report that, but it happened again. LOL it turned out to be the irritating
905 error.

Update: Yeah, we should close this. It is kinda getting off-topic.

– Devin Hussey

**Comment by fzurita** [comment]
Can you update https://github.com/mupen64plus-ae/mupen64plus-ae/issues/481 with some of the suggestions you have here that are not already in that issue?
