### ISSUE TITLE
Improve the preferences and cheat manager

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#481]
We need to assign this as high priority in my opinion, the prefs and cheat manager need some attention.
# General Prefs
- Categorize into sub-PreferenceScreens whenever possible. Currently it requires a lot of scrolling to navigate.
- Hide preferences instead of disable. It looks much better and it makes OpenGL ES 2.0 users feel a little bit better.
- Disable unsupported OpenGL ES versions from preferences, and remove it completely on 2.0 devices.
- Rename GlideN64 preferences and allow for a more friendly options screen
- Glide64 Final options?
- More Rice options.
# Game Prefs
- Add action bar icon to global prefs.
- Load cheats separately (see Cheats).
- Could we see warnings for incompatible ROM settings and set defaults per ROM?
  - This might take a while to set up but can be a huge boost in UX. Besides, most ROMs work perfectly with the default settings, except some ROMs………
  
  ![](http://findicons.com/files/icons/2297/super_mario/32/paper_mario.png) 
# Cheats

The cheat manager is rather unusable at the moment It needs to be fixed.

My ideal cheat manager (a little unrealistic, just a brainstorm)

<h4>General</h4>
- Updated to use the new v3 config format, to be lightning fast, and to prevent OOM crashes.
  - Loads separately from the rest of the settings so it doesn't lag.
  - `mupencheat.txt` is in ROM CoreConfig and only has the codes we want. (old one is mupencheat.default)
- Displays the cheats in a tree (like PJ64 does it)
  - Uses regex to separate the `\` into subcategories, preloads first child category 
  - Reads the cheats in order of the file and you can rearrange them to your liking.
  - ~~Stores cheats by name in the prefs and updates it in the editor.~~
  - Searchable.
  - Fast scroll `getListView().setFastScrollEnabled( true );`
- For variable cheat options, check shows the options but uncheck disables it instead of showing you the dialog again.
- Action Bar shows

```
Tablet/TV
Scrolls horizontally. 
|-----------------------------------------------------------------------|
|< Cheats                                                        EDIT / |
|-----------------------------------------------------------------------|
|Story Mode ########## \|Player 1 ############ \|Infinite lives      [ ]|
|Click to see more ### /|Click to see more ### /|(no notes)             |
|-----------------------|-----------------------|-----------------------|
|Unlock everything   [√]|Player 2              \|Skip to boss level  [√]|
|(no notes)             |Click to see more     /|Crashes in VS mode     |

Phone
Click HomeAsUp or Back to go back, on medium screens, shows 2 cols in landscape.
|-----------------------|   |-----------------------|
|< Cheats             / |   |< Story Mode/Player 1  |
|-----------------------|   |-----------------------|
|Story Mode            \|   |Infinite lives      [ ]|
|Click to see more     /|   |(no notes)             |
|-----------------------|   |-----------------------|
|Unlock everything   [√]|   |Skip to boss level  [√]|
|(no notes)             |   |Crashes in VS mode     |
```

<h4>Editor</h4>
- No longer in a separate Activity
- Long-press to see details, title, etc, - is a DialogWhenLarge in a ScrollView with separate containers for categories. (Kind of like an email app)
  - Edit button brings up editor
  - Smart checking - Fixes line breaks/extra spaces (makes it easier copying and pasting cheats) and tells you when there is an error without losing your work.
  - Easy button activator and variable management. 
  - ~~Updates automatically in the list and keeps your spot.~~ 
  - ~~Alphabetized~~  (Almost, doesn't update when you rename it)
- Import external cheat files with conversions. PJ64 and Nemu especially. (not required though)
- Move buttons to Action Bar
- Multi-select
- Merge duplicates
- Add shows a dialog to setup instead of adding one at the bottom.
- Manually edit cheats file

I would do this myself if I could, but I am only a novice developer and Eclipse hates me and I hate Eclipse.

**Edit:** I made it seem less offensive. I have a tendency to forget that other people made this. I really like the work done on this and I truly support it.

**Edit:** Updated.

**Comment by littleguy77** [comment]
For reference, here's a running discussion about the design decisions moving from 2.5 to 3.0:
http://www.paulscode.com/forum/index.php?topic=1130.0

Be careful about insulting the volunteers who wrote this software.  When you call their work "terrible" they may be less interested in listening.

**Comment by easyaspi314** [comment]
@littleguy77 Sorry for the insults, I updated it

**Comment by fzurita** [comment]
This issue is way to broad. Ideally, this should be split between many issues otherwise this will never be closed.

**Comment by fzurita** [comment]
I'm cleaning up old issues. The cheat manager for the game is usable as is, but I'm sure it could be improved. I will accept pull requests.
