### ISSUE TITLE
Polygon offset for shadows and decals

### ISSUE THREAD

**Issue by littleguy77** [mupen64plus-ae/mupen64plus-ae#5]
I see a lot of stitching in Super Mario 64 for Mario's shadow and the star decals on the doors.  Is this a core Mupen64 issue or is it something that can be addressed in Android?

Possible sources of the problem might be
- wrong polygon offset value in OpenGL?
- z-buffer only 16-bit, rather than 32-bit?

**Comment by fzurita** [comment]
Closing this. This has became much less of an issue as opengl es drivers have matured.
