### ISSUE TITLE
Zelda Bugs 

### ISSUE THREAD

**Issue by ghost** [mupen64plus-ae/mupen64plus-ae#50]
Hi there, 

Zelda OOT and MM have still some Bugs on my Nexus 7. I use the newest paid Version from Google Play -  2.0.3. 

Paul, in your Forums you told me to install the debug Version for doing some Tests for you. I hadnt Time for that until now - should i install it or is it integraded in the normal Version since 2.0 Release? 

- In OOT with gles2, all rooms inside a house are rendered green and blue.

- In OOT with Rice, there are some ugly strips at the right side of the screen when the Image transforms to a lighter or darker place. 

- In MM, the game doesn't Display anything else than the Nintendo Logo with gles2. With Rice, it works without any Major Bugs until link is thrown away from the horse. After doing some attacks with the swords in the air,  game hangs totally. 

Tell me what Information you need - i will Do some testing for you :) 

Greetings from Germany, 

Karsten 

![Screenshot_2012-12-23-13-49-51](https://f.cloud.github.com/assets/3242389/121839/ed9a2c5a-6e03-11e2-872a-e5df02b7bc10.png)

**Comment by fzurita** [comment]
Upstream issue.
