### ISSUE TITLE
64dd support

### ISSUE THREAD

**Issue by alpharulesirulee** [mupen64plus-ae/mupen64plus-ae#510]
can you add 64dd support i want to play f-zero x expansion kit on my phone

**Comment by fzurita** [comment]
This could probably be done if the core supports 64DD, it would just take some time and it's low in the priority list.

**Comment by alpharulesirulee** [comment]
cool but when its done apk download link?

**Comment by min050820** [comment]
@alpharulesirulee You can have recent build on Play Store. It's not regular, but I believe it's updated frequent enough. It's name is 'Mupen64Plus FZ (N64 Emulator)' and author is 'Francisco Zurita'.

**Comment by fzurita** [comment]
This is implemented now and it will track compatibility with the core.
