### ISSUE TITLE
Games crash on resume after display resolution change.

### ISSUE THREAD

**Issue by gannon345** [mupen64plus-ae/mupen64plus-ae#516]
If you back out of an in-progress game, go to settings, and then change the resolution from the current setting to a different resolution (native to 640x480, for example, or 640x480 to 800x600), the game will crash after reload. 

Then, if you try to relaunch, the emulator crashes completely. After this occurs, the game cannot be resumed, it must be restarted, as though the resolution change corrupts the savestate. This can be replicated with any game, as far as I can tell, with a savestate at any point in-game.

**Comment by fzurita** [comment]
Which video plugin are you using? I'm not seeing this with GLideN64.

**Comment by fzurita** [comment]
Also, can you check if you have any files here?

/sdcard/mupen64plusae-v3-alpha/CrashLogs

If so, can you post them?

**Comment by gannon345** [comment]
Will post over the weekend if I have crash logs. I'll check as soon as I
can.

**Comment by gannon345** [comment]
Actually, no crash logs in that location. Issue is occurring with glide64
in both fast and accurate mode. I'll test the other plugins and see if it
happens with those too.

**Comment by fzurita** [comment]
Ok, I just tried this with Glide64 Accurate profile and it didn't crash for me. Maybe I'm not doing something that you are doing. What android device do you have?

**Comment by gannon345** [comment]
Tegra 4 tablet (HP Slate 7 Extreme). I'll test the latest version of Mupen
to see if the issue is ongoing and if I can replicate the exact
circumstances. Last autobuild I used was from 11/15 I think. Issue was very
repeatable for me at the time I was testing it, I was testing with F-Zero X.

**Comment by fzurita** [comment]
There haven't really been many updates since the 11/15 build. I'll try that game specifically, maybe it's related to that.

**Comment by fzurita** [comment]
No luck getting it to crash here. I'm using an unreleased build though, maybe it has been fixed since then.

**Comment by fzurita** [comment]
@gannon345 the builds are working again. Can you grab the latest AutoBuild and see if you get the issue?

**Comment by gannon345** [comment]
Downloaded the latest build for 12/13 and it's working great, no crashes
after changing to different resolutions and resuming several times.

Thanks!

On Sun, Dec 13, 2015 at 12:07 PM, Francisco Zurita <notifications@github.com

**Comment by fzurita** [comment]
No problem
