### ISSUE TITLE
More variable zoom levels?

### ISSUE THREAD

**Issue by xperia64** [mupen64plus-ae/mupen64plus-ae#524]
So I was playing around with the zoom levels and found that it might be better to have a SeekBar or something to allow for more fine zoom level percentages and perhaps a greater range. For instance, Super Mario 64 seems like it should be between 105% and 110% while Paper Mario looks like it should be closer to 120% which isn't an option.

**Comment by Gillou68310** [comment]
Good idea, feel free to add this on master branch ;-)

**Comment by fzurita** [comment]
See this commit:

https://github.com/mupen64plus-ae/mupen64plus-ae/commit/22c5a203e27efae346bb912c76ab4df7a776d9e7
