### ISSUE TITLE
DS4 Controller mapping

### ISSUE THREAD

**Issue by Starius65** [mupen64plus-ae/mupen64plus-ae#532]
I am having an issue trying to connect my ds4 to mupen64, where Every time I try to map a directional button it gets stuck on AXIS_RX (-).
Is there any way to fix this?

**Comment by fzurita** [comment]
Are you using the alpha?

**Comment by Starius65** [comment]
I got the version from the play store, and this was the most relevant message board I could find. I know this was a problem with this a while ago, but the solved issue says that under "analog info" that it is "Xbox 360 Compatible" instead of "PS4 Compatible."

**Comment by fzurita** [comment]
That version is not really supported that well anymore. Try installing the latest apk from here:

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/

**Comment by Starius65** [comment]
I got that version, and it appears to be having the same issue. Looking at the analog info, it appears that the triggers are causing the problem, with the axis value going from -1 to +1

**Comment by fzurita** [comment]
Are you using the ds4 through Bluetooth or hooked directly through USB?

**Comment by Starius65** [comment]
Bluetooth.

**Comment by fzurita** [comment]
I have the ds4 but I use it through USB and I don't have that problem. Are you using sixaxis?

So everyone time you try to map a directional button it maps it to the trigger instead?

**Comment by Starius65** [comment]
I have been paranoid to root my system since it destroyed it a year ago. If I'm correct' sixaxis requires a root. And yes for the directional buttons, since each of the triggers have their own axis the default position for an impressed trigger is -1.

**Comment by fzurita** [comment]
Interesting, I thought sixaxis was required to use the ds4 through Bluetooth. I guess not. I'm not sure why you have that problem and I don't.

What device are you using? Maybe it's an issue specific to Thai device.

**Comment by Starius65** [comment]
I am currently using an LG G4.

**Comment by fzurita** [comment]
Ok, it seems that the g4 has a built in Bluetooth profile for the ds4. I wonder if they didn't implement it quite right. 

Do you have a USB OTG adapter? You can try mapping while connected through USB, then once done mapping, connect through Bluetooth.

**Comment by fzurita** [comment]
I've been doing some googling and it seems like your issue is a common one with this emulator and a DS4 paired through Bluetooth. It seems like you are the first to report it though. I'll see if I can come up with a fix.

**Comment by fzurita** [comment]
Ok, it seems like we already have a fix for this in the code, but we are only applying it to the DS4 when it's connected through USB and not Bluetooth. I can come up with a fix I think.

**Comment by fzurita** [comment]
Please try this build:

https://drive.google.com/file/d/0B57Ioy26LWegYVVfNkRua2VrbzA/view?usp=sharing

I think it should fix it for you. You will have uninstall your current version for the app before you can install this one.

**Comment by Starius65** [comment]
That worked, thanks for all your help! And, Merry Christmas.

**Comment by fzurita** [comment]
Thanks, same to you.
