### ISSUE TITLE
Multi-player assignment does not persist

### ISSUE THREAD

**Issue by faustomorales** [mupen64plus-ae/mupen64plus-ae#538]
It would appear that something is going wrong with persisting the multi-player assignments. The assignments are lost just after entry (even before trying to play a game). I've tried 5a317b8 and 7bc14f1 with the same results (there was a change to allow for global multi-player preferences in between). I  admit I can't quite figure out why this is happening. I'm using Amazon FireOS 5 (Bellini / Lollipop).

**Comment by fzurita** [comment]
I'll take a look, it's possible that one of the recent updates for player assignments broke something. In the mean time, can you go to the general settings and try assigning controllers there?

**Comment by faustomorales** [comment]
@fzurita First, thanks for all the work you've put into this. I did try using both approaches: (1) Main Menu > Settings > Multi-Player and (2) Open a game  > Settings > Multi-Player with identical results. The menu responds as expected, hit OK. However, if you reopen the menu, the settings are gone (unlike what occurs in 2.4.4). I run the game to confirm that it's not a mere UI issue and get the warning about assigning multi-player controls (with neither controller being operational at that point within the game). The only way I've found to get functionality back for either controller is to clear the data and cache.

Do let me know if there's something additional I should try for diagnostic purposes in helping to identify the problem. I have tried logcat but didn't notice anything particularly interesting.

As additional background, this is using two Xbox 360 Controllers via Microsoft Dongle. The controllers do work in 2.4.4 (with multiplayer). I would test this on other hardware but, alas, I don't have a way of connecting the controllers to anything other than the Fire TV.

**Comment by fzurita** [comment]
No problem, and thanks for the report. I'm wondering if recent changes on how we identify controllers is causing this issue. Can you try the the 12/18/2015 build?

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/Mupen64PlusAE_master_201512180203_3b21f54.apk

**Comment by faustomorales** [comment]
That build worked perfectly! Looks like that was it.

**Comment by nicklauslittle** [comment]
It looks like some devices (like the wireless dongle) are only given a single descriptor even when multiple controllers are connected. (see https://github.com/moonlight-stream/moonlight-android/issues/64) I think I will try to change the key in the settings to try to use both the device id and device descriptor to determine which device to use. Hopefully, I can get a fix in sometime this weekend.

**Comment by fzurita** [comment]
Thanks @nicklauslittle

**Comment by fzurita** [comment]
@faustomorales please try the latest auto build if you get a chance:

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/Mupen64PlusAE_master_201601100103_33036d5.apk

**Comment by faustomorales** [comment]
Just tried with no luck, unfortunately. Same behavior as before. Let me know if there's some additional diagnostic information I can gather.

**Comment by fzurita** [comment]
Thanks for trying it. This may be hard to fix without the actual setup to try it with.

**Comment by faustomorales** [comment]
I think you're right. Though I've never worked on the Android platform, I have worked in Java quite a bit. Maybe this will be a good experiment to dip my foot into the Android pool. I'll see if I can compare the code from the 12/18/2015 build to the current build and diagnose on my own. If it works out, I'll submit a pull request. Otherwise, maybe another person with the same setup will have more luck later down the line. More to come (hopefully)!

**Comment by fzurita** [comment]
Now we have another person in the forum having the same issue. It seems to be specific to the Fire OS platform and completely unrelated to controllers. It seems to have to do with the way we serialize controller settings into the SharedPreferences.

**Comment by fzurita** [comment]
Ok, I was able to borrow a Fire OS tablet. It had the exact same issue. I was able to fix it. See this commit:

53f95c4f72a2c04b5c309cb323b78ab063fd7c8d

**Comment by faustomorales** [comment]
Yep, works great! Thanks so much.
