### ISSUE TITLE
"Failed to attach core library" on Marshmallow

### ISSUE THREAD

**Issue by nicklauslittle** [mupen64plus-ae/mupen64plus-ae#540]
I get a "Failed to attach core library" on my Nexus Player running Marshmallow on all builds after 12/09. I think this is just a generic marshmallow issue, but I could be wrong.

I did a little bit of digging, and I think I know what the problem is. (No guarantees.) It looks like the mupen64plus-ui-console library is failing to load the mupen64plus core library. I did a quick search and found that on apps that target pre-Marshmallow versions attempting to load a library with text relocations would issue a warning but still succeed. When targeting Marshmallow, this fails with an error. To attempt to verify this I built two apks based off commit 33036d5f. The first targeted version 23 (AndroidManifest.xml:18) of the SDK and issued the error above. The second targeted version 22 and it loaded the core and worked just fine.

I don't have a clear view of how to fix this. My guess would be that it would require modifying some of the core source or some compile options, or both. I do plan on looking into it at some point, but I figured I would post it here in case someone knows what needs to be done.

**Comment by fzurita** [comment]
Right after that we switched everything to SDK version 23. Oddly enough, I tried it on my nexus player running marshmallow and I don't get that error. The difference may be that I'm running a custom ROM that disables leanback.

**Comment by fzurita** [comment]
Can I get your log cat output?

**Comment by nicklauslittle** [comment]
Maybe. I had two items in the "Share" list (from ES File Explorer) and wasn't able to get it to export using either one. I may be able to pull them through adb, but I'm not familiar enough with Android development to easily accomplish this yet. I may try to tackle it this weekend. Let me know if you know of an easier way to do this.

However, I did look at the logs and can confirm that it is what I originally thought. I can run the target 22 build and see the "... has text relocations. This is wasting memory and is a security risk. Please fix." message as a warning. When I load the target 23 version I see the message as an error and more errors follow it indicating it could not load the core.

I found some sites that talk about this. (One is https://code.google.com/p/android/issues/detail?id=67770) I may attempt some of the recommended actions and see if I can get anything to work correctly that targets version 23.

**Comment by fzurita** [comment]
In Android.mk under the jni directory, add ```-fPIC``` to ```COMMON_CFLAGS```.

I got this from the link you posted.

**Comment by nicklauslittle** [comment]
I made that change and I still get the error. I did a clean before the build. I could see it clean and build all the files (twice for arm, once for x86), so I think I did it right. I saw some other people say something about updating the NDK, but I'm running r10e, so I don't think that's the problem.

I will keep looking into it and posting updates here.

**Comment by nicklauslittle** [comment]
Update: After adding -fPIC to jni/Android.mk, jni/SDL2/Android.mk, and jni/png/Android.mk and getting nowhere, I did some digging using the NDK toolchain for x86. I ran readelf -S on the mupen64plus-core library and found the sections .data.rel.ro and .data.rel.ro.local, which I believe are the culprits.

I found that sometimes -fPIC doesn't always take care of text relocations when there is assembly code involved (https://wiki.gentoo.org/wiki/Hardened/FAQ, Section 3.4).

Lastly, I found an issue in the mupen64plus-core repo that I think is a related issue: https://github.com/mupen64plus/mupen64plus-core/issues/119, but it only deals with the arm architecture, not x86.

**Comment by fzurita** [comment]
Nice research. The issue even includes a pull request with the fix. But it makes CBFD crash.

**Comment by fzurita** [comment]
I may just have to revert the API level to a lower version. It seems that Android got a little more strict for security reasons.

And I think I know why my Nexus player runs it fine. It probably has some SE Linux checks disabled.

**Comment by nicklauslittle** [comment]
Yeah, based on what I read, I think the SE Linux issue might have something to do with it. All I had to do to build it was change the target API from 23 to 22. All the other changes should be fine to stay in until somebody can figure this one out.

I think some of my initial analysis regarding the sections might be incorrect. (But I still think the rest of it is accurate.) I'm thinking about trying to follow the guide here: https://wiki.gentoo.org/wiki/Hardened/Textrels_Guide (This is what the Android Development Team recommends on http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html). Maybe I can isolate the exact assembly code (assuming the problem is with the assembly code) causing the issue.

**Comment by fzurita** [comment]
This is very curious, the issue you linked fixes the arm version. I wonder if your Nexus player is trying to run the arm version instead of the x86 version.

**Comment by nicklauslittle** [comment]
My thinking is that it exists in the x86 version as well. The log cat shows my Nexus player is trying to load the x86 version.

**Comment by fzurita** [comment]
I wonder why I have not seen any complaints of people running marshmallow in arm devices with issues. The only complaint I have seen is of the app being unable to extract assets which I already fixed.

**Comment by nicklauslittle** [comment]
The arm version is fixed. It even works on my Nexus Player using houdini (if I disable building the x86 binaries). It looked like even though the commit referenced in  was reverted, the same code was later added in.

I think the reason why the x86 binaries have the error is because the assembly code uses the ebx register, which is required to be available for PIC. I have been trying to build for x86_64 to see if that will resolve the issues. But it may take me a while to figure out how to do it.

**Comment by fzurita** [comment]
Í meant to respond to this earlier but forgot. Trying to compile 64 bit binaries would be quiet an achievement. 

To use 64 bit binaries, everything must be compiled as 64 bit. Unfortunately, I don't think the core and plugins are portable code, so it may compile, but may not run very reliably or at all.

**Comment by nicklauslittle** [comment]
I was able to get the SDK to compile for x86_64 and package the libraries, but I couldn't get the package installed on the Nexus Player. The arm libraries were installed instead and using Houdini, so I was unable to test it. I'm assuming the only change I needed to make for Android to use the x86_64 libraries is to add "x86_64" to the Application.mk file? (And correct any build errors or compiler flags.)

The normal Makefile for the core has a section for x86_64, so I don't think it would have that many issues to work out. I copied all the appropriate options from the Makefile into the Android makefile and only had to fix a couple issues in the #ifdef ANDROID portions of the code to get it to compile.

I also tried a couple other things. I made an x86 build using the older dynamic recompiler, as well as one with just the interpreter. These both worked fine using the native x86 libraries (No errors about having text relocations, which to me validates that the text relocations are caused by the assembly file.)  The only issue I found was that I could not resume games, only restart them.

I also just removed the x86 and x86_64 libraries from Application.mk. This caused the arm version to be loaded using Houdini (I could see the messages in the log cat output), but it worked just fine, at least in my limited testing. This looks like a good alternative if reverting the Marshmallow API target is not desirable.

**Comment by fzurita** [comment]
If we load the arm versions using Houdini, we are not taking advantage of x86 specific optimizations. I would rather revert the API level before removing those optimizations, at least until a real fix is found.

**Comment by fzurita** [comment]
I'm not 100% sure if the Nexus player is running 64 bit Android (even though it has a 64 bit CPU). If you built x86_64 and the Nexus player is not running 64 bit Android, it would just load whatever version it can load.

**Comment by fzurita** [comment]
Can you try this on your Nexus player?

https://software.intel.com/en-us/blogs/2014/12/16/how-to-identify-the-image-is-32-bit-or-64-bit-user-space

**Comment by Gillou68310** [comment]
@fzurita I already fixed CBFD crash when using the TEXTREL patch on ARM (https://github.com/mupen64plus/mupen64plus-core/pull/123)

Concerning TEXTREL issue on x86, this is the intended functionality and not a bug, Google is to blame here! The current x86 new dynarec is not PIC compatible and even if we add the compatibility we should definitely expect worse performances.

Also the new dynarec isn't working on x86_64 atm, I started working on it a few month back but never got time to finish it.

For the moment the best solution if you're running Android Marshmallow on a 64bit CPU is to use the x64 old dynarec.

**Comment by nicklauslittle** [comment]
@fzurita Yes, you are correct. I ran that command and the stock Nexus Player runs 32-bit Android.

@Gillou68310 I haven't been able to get any of the 64bit stuff to work (since I've apparently been running on 32bit Android). However, I have been able to get the old dynamic recompiler and the pure interpreter to work for x86. The only problem is that resuming a game fails on both. It looks like it is going to start fine, but only a black screen comes up with no sound. It works just fine if I restart the game each time. Any ideas on what could be causing this?

The log looks fine. I even see a "State loaded from: ..." debug message from the core. I looked through the previous and current issues in the core repo and couldn't find anything that might be causing this.

**Comment by fzurita** [comment]
Have you tried manually saving and loading a save a slot? It's the exact same mechanism as the resume option.

**Comment by nicklauslittle** [comment]
Saving and loading a slot appears to work perfectly! I wonder why that works but resuming does not? Is that good enough of a solution? If so, I can commit the changes I have for the build files.

**Comment by fzurita** [comment]
do you have a branch? I can try to figure out what's wrong with the loading of save states when resuming.

**Comment by Gillou68310** [comment]
> However, I have been able to get the old dynamic recompiler and the pure interpreter to work for x86

With or without PIC?

> The only problem is that resuming a game fails on both

I always hated the resuming feature because the loadstate could happen before all plugins are initialized. I suggest using the restart option + manual loadstate/savestate (That's what I'm using BTW)

**Comment by nicklauslittle** [comment]
@fzurita Yes, I just uploaded it under text-relocation-fix.

@Gillou68310 With PIC. (No text relocation errors.)

I think there might be some issues with with this version, though. It's crashed a couple of times when I was first messing around with it. It seemed like it would only crash in the first couple minutes. If it didn't crash then, it keeps going. But I'm wondering if maybe my system was low on memory or something, because I've tried to reproduce it without success.

**Comment by Gillou68310** [comment]
Considering the fact that PIC is disabled by default when building for x86 in the NDK and adding the fact that PIC is usually slower on x86, I expect a lot of other x86 apps to be impacted with this issue. This is total nonsense IMO, I still hope google will revert this in the next release.

**Comment by fzurita** [comment]
So it's sounding a lot like we are going to have some kind of logic that loads the old dynarec core if the system is x86 and the android version is marshmallow or greater.
