### ISSUE TITLE
Ocarina of Time (mupen64plus-ae)

### ISSUE THREAD

**Issue by sephfire** [mupen64plus-ae/mupen64plus-ae#541]
I've been having issues with the game freezing from the start, here and there, but after restarting the game, it would fix it. However, now it's freezing at the boss battle in the Forest Temple (adult Link). As I shoot an arrow at the boss, it freezes. The music is playing and I've sat for 5 or so mins just to see if a message would appear, but nothing happens. I tried switching plug-ins, but the same thing happens, once I shoot my first arrow at the boss, it freezes. I've tried this several times with each plug-in to no avail.

Here's my set up:

- Plug-Ins - 

Video: gles2rice

Input: input-android

Audio: mupen64plus-audio-sdl, v2,0

I currently using Version: 2.4.4 and the code is 36

My phone info is: Android Version 5.0 and it's a Galaxy 5.

I hope I gave all the correct info. Thank you for your help in advanced!

**Comment by fzurita** [comment]
Try there latest build from here:

http://www.paulscode.com/auto-builds/

You will have to manually import your save from the Mupen64plus directory into the Mupen64plus-v3-alpha directory.

Also, they're is a known issue with the audio plugin freezing up the emulator, you can also try switching it.

**Comment by sephfire** [comment]
Hmm.. I'm quite new to this, so hopefully I won't mess anything up. Thank you for your help~

**Comment by sephfire** [comment]
I tried it without sound, and it still freezes when I shot my first arrow. I'll try the website and hope that works~

**Comment by sephfire** [comment]
@fzurita - I moved my saved files into the folders on the alpha, however when I load the game, the save files aren't there. I moved the files in their respective folders as how they were in the plus folders. Is there another folder I suppose to move them to? Sorry for the bother.

**Comment by fzurita** [comment]
Run the game once and save within the game. It will create a directory under /sdcard/mupen64plusae-v3-alpha/GameData/THE LEGEND OF ZELDA (U) [hash]/SramData/. Replace the file in there with the version generated within mupen64plus 2.5. Make sure the file name matches exactly.

**Comment by sephfire** [comment]
@fzurita - The file for the mupen64plus 2.5 is in the SlotSaves folder correct? Cause that's the one fold containing the same file name as the one created when I saved within game through the Alpha. I replaced the file, and reboot the game, however it didn't work.

**Comment by fzurita** [comment]
Yes, the one in the slot saves folder. Make sure you copy the file while the mupen64plus 3.0 emulator is closed down and the game is exited. I just tried doing that and it worked just fine.

**Comment by sephfire** [comment]
@fzurita - Okay, it worked!~ Hopefully it won't freeze now~ Thank you sooo much for your help!

**Comment by fzurita** [comment]
No problem, let me know how it goes and I'll close this issue if it's fixed. Also, if you have a newer device with nice specs, you try the GLideN64 3.0 series of video plugins to get more accurate emulation.

**Comment by sephfire** [comment]
@fzurita - Nope, same issue. It freezes when I first shoot an arrow at the boss. Is the ROM I'm using outdated maybe?

And my phone is almost 2 years old, so I'm not sure if that's considered newer device or not lol.

**Comment by sephfire** [comment]
@fzurita  - You can close this, I've figured it out. There was a cheat code one and once I turned it off, it didn't freeze. Thanks again for all your help!

**Comment by fzurita** [comment]
Yep, they can dedicatedly do that....
