### ISSUE TITLE
N64 controller A button always produces power menu on Razer Forge TV

### ISSUE THREAD

**Issue by kethinov** [mupen64plus-ae/mupen64plus-ae#547]
I plugged in a few N64 controllers via USB dongles via a USB hub to a Razer Forge TV and the A button is impossible to map because it always produces the power button menu that you would see if you pressed the power button on the Razer Serval controller (the menu which shows return to game, exit game, rate game, purchase, etc).

I have confirmed this is an issue OS-wide, as it will happen in any games/emulators on the Razer Forge TV, however I was wondering is it possible to suppress this default mapping from within Mupen64 itself so the button can be mapped in the emulator for use in-game?

**Comment by fzurita** [comment]
Hmm... Is the "A" button acting like a power button? I wonder if we are even being notified if the button press is happening at all or if it's being overriden at the OS level.

Do you know of any other apps that are able to map that button? I could probably see what they do.

**Comment by kethinov** [comment]
So far I haven't found any apps that are capable of mapping the button. It's entirely possible that it's being overridden at the OS level. Do you know a simple way I could see if the action emits a capturable event though? Maybe install some app that dumps all events emitted by various inputs to the screen?

**Comment by fzurita** [comment]
I'm not really aware of such an app. This may require some research.

**Comment by fzurita** [comment]
Ok, if you can get root access to your device, you may be able to fix it yourself. See here:

https://source.android.com/devices/input/key-layout-files.html

**Comment by fzurita** [comment]
Closing since we can't do much about this.
