### ISSUE TITLE
LoZ: Ocarina of Time randomly crashes when opening in-game menu

### ISSUE THREAD

**Issue by Voron3DD** [mupen64plus-ae/mupen64plus-ae#548]

**Comment by fzurita** [comment]
This is a known issue with the GLideN64 plugin. An issue needs to be made upstream.

**Comment by fzurita** [comment]
Ok, I made the upstream bug report. See here:

https://github.com/gonetz/GLideN64/issues/950

**Comment by Voron3DD** [comment]
Thanks) Waiting for updates.

**Comment by Voron3DD** [comment]
Problem solved. Emulator incorrectly defined version of rom. And this has led to crash the game.

**Comment by fzurita** [comment]
Interesting. Which ROM version are you using? The problem hasn't gone away for me.

**Comment by Voron3DD** [comment]
LoZ:OoT (U) [1.0]. Emulator defined it as unknown. Perhaps I had a bad version of rom.

**Comment by fzurita** [comment]
Fixed for GLideN64:

https://github.com/gonetz/GLideN64/pull/959#issuecomment-208865048
