### ISSUE TITLE
White Dualshock 4 right analog not mapping

### ISSUE THREAD

**Issue by demshrimp** [mupen64plus-ae/mupen64plus-ae#549]
Hi guys, so im trying to configure my white DS4 to work with Mupen, I shoild mention ive managed to map it perfectly with other emus so it's not a hadware issue.

I'm on a samsung galaxy tab s and am connected by Bluetooth. I can map everything perfectly with the exception of the right analog stick which seems to always map to one direction.

Any ideas?

![screenshot_2016-04-02-10-58-32](https://cloud.githubusercontent.com/assets/18228539/14225664/7815d19e-f8c2-11e5-9e29-a81e055bdf81.png)
![screenshot_2016-04-02-10-58-42](https://cloud.githubusercontent.com/assets/18228539/14225665/7d07e746-f8c2-11e5-85cd-474dc2f8bcbd.png)
![screenshot_2016-04-02-10-58-46](https://cloud.githubusercontent.com/assets/18228539/14225667/81b272de-f8c2-11e5-8cdc-606ad4ada371.png)

**Comment by fzurita** [comment]
Can you tell me if you get the same issue when you plugin the controller through USB OTG?

**Comment by fzurita** [comment]
Actually, from the screenshots, I can see you are running an older version.

Please try side loading the latest master version from here:

http://www.paulscode.com/auto-builds/

I believe the problem is already fixed there.

**Comment by demshrimp** [comment]
Fzurita. Thats great, it's all working perfectly on the latest master. Thanks!
