### ISSUE TITLE
POLL: Icons

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#550]
Right now, the icon is identical to the desktop Mupen64Plus, and the splash screen is a little goofy.

I was thinking a Material (flat) Android green n64 cartridge with Android antennae. The label, dark green or any good contrasting color will have a small Mupen64plus M icon on it. I can design it in my free time. 

And for the splash screen, we use a dark material splash, á la Google Apps only dark (#333).
At the top it says 
Mupen64Plus-AE
Middle is the icon
Bottom, it is blank unless an asset copy is running, then it says:

Loading…
===========-------------- 64% ←progress bar
mupen64plus.ini

The Mario-themed splash will be removed from here. It is funny to see, but looks out of place, especially when the app strives to be dark-themed. Instead, they look at the app icon. Instead, it will go into the **app version** dialog as an Easter egg. 

This will make M64+AE seem more professional, in my opinion, and look better with its Material Design theme.

Also, I can update some of the in-app icons to the latest designs.

+1 = Yes, I like that idea!
0 = Keep it the way it is. 
-1 = Don't like it, but I have a different idea. Tell me what you would like.

**Comment by ZAD-Man** [comment]
-1

I actually _really_ like the current logo, but I would get behind a Material Design version of that. Nevertheless, I would want to see how the logo you proposed looks before giving a solid vote. It does sound like it could be cool too. :)

**Comment by fzurita** [comment]
I would love to see new designs if you want to contribute.

**Comment by easyaspi314** [comment]
I can make a rough one tonight or tomorrow; a good one will have to wait
till next week when I am at my Illustrator computer. I'm replacing some
action icons right now.

**Comment by easyaspi314** [comment]
OK. I found a bunch of better icons for the settings, so we don't have all those duplicates. 

For a cheat code, which do you like best?
![ic_vpn_key_black_24dp_1x](https://cloud.githubusercontent.com/assets/6258309/14261771/3167f910-fa80-11e5-8881-63d6ae49bc82.png) ![ic_lock_open_black_24dp_1x](https://cloud.githubusercontent.com/assets/6258309/14261925/0552daec-fa81-11e5-99ce-8116cd829623.png) ![ic_code_black_24dp_1x](https://cloud.githubusercontent.com/assets/6258309/14261781/45c72534-fa80-11e5-82ed-126ab684bd49.png)

**Comment by fzurita** [comment]
Hmmm, personally, I like the key that we have right now for cheats. Although, I do agree with you. The splash screen is ugly.

**Comment by easyaspi314** [comment]
You agree that it should go in the app version though? Because it still deserves to be in the app. I like it.

**Comment by fzurita** [comment]
You mean in the app version dialog or the menu item that you have to click to get into the app version dialog?

We don't currently have any icons in the about section of the dialog. So one item having an icon while the other two don't would make the other two feel out of place.  IMO.

**Comment by easyaspi314** [comment]
App version dialog. It will be right above the text. I can put together the layout.

**Comment by fzurita** [comment]
Gotcha, in that case it makes sense. Yes, that dialog seems like it could have more stuff on it. An icon would make it look nicer. Feel free to submit a new layout for it as a pull request and I'll consider it.

**Comment by easyaspi314** [comment]
I'll also deorange the gallery. 

Also, my **rough** app icon is ready. (I'm OCD. It *will* be much better than this.):
![m64pae_mockup](https://cloud.githubusercontent.com/assets/6258309/14263417/78133c82-fa88-11e5-86e2-572d2567d028.png)

**Comment by fzurita** [comment]
Not bad! You definitely have some skills. Now, I wish other team members would comment. But please keep refining this. @littleguy77 @Gillou68310 @paulscode 

Maybe they will comment if it gets more refined.

**Comment by easyaspi314** [comment]
I can't really refine it much right now. I am only using Inkscape, I won't have access to Illustrator until next Monday.

**Comment by fzurita** [comment]
Ok, I'm sure it would be worth the wait.

**Comment by easyaspi314** [comment]
@ZAD-Man what do you think ↑

**Comment by easyaspi314** [comment]
I found that either a black or a white label works best. Also, I tweaked the colors a bit, fixed some alignment and added a long shadow. 
![m64pae_mockup-2](https://cloud.githubusercontent.com/assets/6258309/14265869/030bf6c2-fa92-11e5-8eb2-f29fcd6bafed.png)

**Comment by easyaspi314** [comment]
I still need to work on the Mupen logo, the inside is a bit awkward.

**Comment by fzurita** [comment]
I think black looks nicer.

**Comment by ZAD-Man** [comment]
Oh nice! I agree with the black background - I prefer it too. :) Is it safe to assume it will be squattier in the improved version? That's all I would say to change. The shadow was a nice addition too.

**Comment by easyaspi314** [comment]
@ZAD-Man this is a rough. Alignment will be better next week when I can get to Illustrator. I'll even use an actual N64 cartridge for accuracy. Inkscape just isn't the best in the alignment department.

Hey, I was wondering:
Maybe, in-app and in the app drawer, we should reference the app name as just "Mupen64+". 
That will help with identity as well, because the AE is not necessary. You look in the Play Store for Mupen64+ and you get this. 
It is like naming Firefox "Firefox for Android" or "Fennec". It isn't, it is just Firefox. Or like saying, "My computer runs Windows 7 Professional. I really like Windows 7 Professional, it is a lot better than Windows Vista Home Premium". You just say Windows 7.

**Comment by ZAD-Man** [comment]
@easyaspi314 Oh, OK! I thought "alignment" just meant centering the label better or something, haha. OK, great. :)

Also, I absolutely agree about the AE. I've removal - I've actually edited that off on my phone.

**Comment by fzurita** [comment]
Yes, I agree, the AE is redundant. You are obviously Android edition if you are already running in Android.

**Comment by easyaspi314** [comment]
And it isn't even saying, "Android Edition".
What else could it mean? "Angry elephants?" XD

**Comment by easyaspi314** [comment]
Also, this would make the app icon label not look unsure or incomplete:
![t06255999](https://cloud.githubusercontent.com/assets/6258309/14266525/e9f4dfe6-fa96-11e5-8e82-23b30610cded.png)

**Comment by fzurita** [comment]
Well, that depend a lot in your launcher.

**Comment by easyaspi314** [comment]
But still, 18 out of the 122 apps in my app drawer are are truncated **and the launcher uses the condensed font.** Most of those are small indie utility apps, only one or two big-name ones are truncated.

Some people use the full width font and they might see Mupen64 Plu..

**Comment by fzurita** [comment]
I'm OK with making the app name be just Mupen64Plus. As long as at least someone else in the team agrees.

**Comment by easyaspi314** [comment]
No, Mupen64+.

**Comment by fzurita** [comment]
In reality, we are very loosely associated with Mupen64plus at this point. All the core changes are made in the upstream project. We have been reduced to just a front end with a couple of plugins that we maintain which are the audio and input.

**Comment by easyaspi314** [comment]
Yep. Good point.

Wait... "M64". Just that.

**Comment by fzurita** [comment]
All good suggestions I think. I would rather get input from others before making a drastic change.

**Comment by easyaspi314** [comment]
We are basically pulling a TD Bank.

**Comment by easyaspi314** [comment]
Any ideas?

**Comment by fzurita** [comment]
For renaming the app?

**Comment by easyaspi314** [comment]
Just anything in general. 

Mupen64+ should be the name. It is the first result in the Play Store, and it shouldn't change much to the users.

For the icon, any suggestions? What about the colors for the M? These are the recommended colors:
http://www.google.com/design/spec/style/color.html

Should we maybe use a complete recolor?

**Comment by fzurita** [comment]
Maybe a flatter icon with the material colors. Flatter icons for the material design better.

**Comment by easyaspi314** [comment]
How about a controller? The N64/M64 logo is 3D, and not much can be done to flatten it.

**Comment by fzurita** [comment]
You mean like the Google play games icon?

**Comment by easyaspi314** [comment]
No, like this:
![m64pae_controller](https://cloud.githubusercontent.com/assets/6258309/14298425/e1f4f134-fb52-11e5-9b0d-310a026d6414.png)

**Comment by easyaspi314** [comment]
It'll be pretty difficult to put the N64 logo in flat.

What about an n64 controller?

**Comment by easyaspi314** [comment]
Oh wow. Now my reply email sends.

**Comment by easyaspi314** [comment]
I also realized that I had snapping in Inkscape off. No wonder. Now things are snapped.

**Comment by fzurita** [comment]
Oh, for the splash screen you mean. I was talking about the app icon.

For the span screen I don't personally like that very much.

**Comment by BonzaiThePenguin** [comment]
Flat doesn't mean the removal of 3D perspective, it means the removal of gradients. These are flat icons:

![](http://i.istockimg.com/file_thumbview_approve/71381937/6/stock-illustration-71381937-school-university-and-education-isometric-3d-flat-icons.jpg)

**Comment by easyaspi314** [comment]
True, true.

**Comment by BonzaiThePenguin** [comment]
IIRC I recommended changing the splash screen a long time ago, but whoever was in charge at the time said we need to ask Paul what he thinks.

**Comment by easyaspi314** [comment]
@paulscode where are you?

**Comment by BonzaiThePenguin** [comment]
Here was my recommendation, back in March 2015:

![](http://i.imgur.com/tDNS6M0.png)
http://www.paulscode.com/forum/index.php?topic=1130.msg14954#msg14954

Remove the gradients and boom. Had this suggestion for what to do with the old splash screen in case Paul actually cared:

![](http://i.imgur.com/Z8JXZo1.png)
http://www.paulscode.com/forum/index.php?topic=1130.msg14956#msg14956

**Comment by ZAD-Man** [comment]
Ooo, I like that recommendation a lot.

**Comment by BonzaiThePenguin** [comment]
What does the current splash screen look like? I haven't updated my copy of Mupen64 in over a year.

**Comment by easyaspi314** [comment]
Neither has the splash screen. :cry: 
![:(](https://cloud.githubusercontent.com/assets/6258309/14299244/4f77c4b2-fb57-11e5-9dc9-58c9dc8d37c8.png)

**Comment by fzurita** [comment]
BonzaiThePinguin's idea is not bad either. If you want to do that easyaspi314. I wonder if I would lose my team member status if I just pushed on with those changes without asking :P.

**Comment by easyaspi314** [comment]
@paulscode hasn't been active on GitHub since December 9th, 2015; according to his profile. I'll try shooting him an email.

**Comment by BonzaiThePenguin** [comment]
Yeah, Paul tends to disappear a lot for long periods of time.

**Comment by BonzaiThePenguin** [comment]
Wow, the splash screen hasn't changed a bit!

**Comment by easyaspi314** [comment]
I know, right?

**Comment by BonzaiThePenguin** [comment]
I think the M logo is pretty integral to the project, though – the Play Store has a lot of Mupen64 clones that use an N64 controller as its icon. Your flattened version of the M logo looks quite nice, though, @easyaspi314.

For my mockup I just took the image that was used for missing cover art at the time and slapped it into Inkscape, so the design for that is of course nowhere near set in stone. I think that image was originally designed for tablets running *Jellybean* too, hence the gradients and thick fonts.

**Comment by easyaspi314** [comment]
Sometimes, I miss posting screenshots with #HOLOYOLO #33b5e5.

Though, Material is a lot better.

**Comment by easyaspi314** [comment]
If only he had a copy without the watermarking. 

I am remaking (or at least attempting to) the M logo to the isometric pixel angle grid. (26.565°; y=1/2x)

This guarantees a nice, clean image on all screens.

**Comment by fzurita** [comment]
There may be a copy. Look in the drawables in this branch:

https://github.com/mupen64plus-ae/mupen64plus-ae/tree/2.x-bugfixes/res/drawable-nodpi

**Comment by easyaspi314** [comment]
@fzurita I forgot to reply: Nope. But the logo would be Easy as Pi to edit the watermark out of.

**Comment by easyaspi314** [comment]
Well got some good news and bad news:

### Good news
I have a pixel-aligned logo that is *almost* ready.

### Bad news
The school website blocks blocked me from uploading the art to GitHub and now it is April Vacation. *Well **that** just happened.*

**Comment by fzurita** [comment]
Fun!

**Comment by paulscode** [comment]
FYI, we have done competitions where the current logos and spash images were voted on and selected by the user community.  I am a little reluctant to change them as it may appear to be a dis to the original artists.  Is there a problem with clashing themes or something?

**Comment by fzurita** [comment]
I wouldn't personally mind changing the splash screen. Everything is going "material" now a days and the splash screen doesn't seem "material" enough for me. 

BonzaiThePinguin did suggest using the current splash screen as part of the "about" dialog. So it wouldn't go to waste.

**Comment by paulscode** [comment]
In case anyone is curious, the reason for two different application icons is because we held a separate competition for the OUYA port of the app (as part of the Kickstarter rewards).

**Comment by fzurita** [comment]
I think we should at least let easyaspi314 show us what he has.

**Comment by easyaspi314** [comment]
Do you know who the original artist is? Besides, I am not dissing him (or
her). Dissing them would be saying that the logo sucks. I am saying that it
is a little out of place and dated.
On Apr 15, 2016 8:55 PM, "Paul Lamb" <notifications@github.com> wrote:

FYI, we have done competitions where the current logos and spash images
were voted on and selected by the user community. I am a little reluctant
to change them as it may appear to be a dis to the original artists. Is
there a problem with clashing themes or something?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/550#issuecomment-210699989>

**Comment by paulscode** [comment]
Since I haven't been involved much in the project lately, final decision probably shouldn't be up to me anyway.  Just saying that there is history behind the current artwork, and that the decision probably should not be made in a silo.  Original artists are listed in the credits.

**Comment by easyaspi314** [comment]
@fzurita @paulscode
you are gonna have to wait. :(

It is on the school computer. School is closed for the week. Can't get it until then.

The rough is above. It isn't much different.

**Comment by easyaspi314** [comment]
God I am slow.

**Comment by fzurita** [comment]
I do think that is a fair point that the community should be involved in updating art. Although, I'm not entirely sure how to go about doing that since the community does feel very sparse now a days.

**Comment by easyaspi314** [comment]
Basically, we just have to pray Dolphin (GC/Wii emulator) doesn't get support for OpenGL ES 2.0, or we will be screwed. :D

**Comment by paulscode** [comment]
Good point, @fzurita about the community being sparse (mainly my fault for being a workaholic as of late).  WRT the name, I don't mind tweaking if necessary, but I would personally be against naming it anything other than a variation of Mupen64Plus (abbreviating to fit certain character limits is fine).  I think it is important to give credit where due, and this app nothing without the Mupen64Plus.

**Comment by fzurita** [comment]
@paulscode do you think it's appropriate to drop the ”AE" from the app name? I feel like it's redundant since it's a given that it's ”Android editiob" since it's running in Android.

**Comment by paulscode** [comment]
No problem with that.  I named it that originally (plus the disclaimer in the description that it is not officially supported by the Mupen64Plus team), due to of the multitude of original issues that ARM and GLES brought to the emulator, to try and prevent folks from bombarding Richard and the upstream team with issues that needed to be addressed by us.  Since all of that maturation has happened and we really are just a front-end, I don't see any problem with downplaying the distinction.

**Comment by fzurita** [comment]
Cool, I'm on it :)

**Comment by paulscode** [comment]
You know, for revitalizing the community to talk about artwork updates, what we could do is publish the update with a message in the notes dialog inviting folks to visit the website to discuss.  Maybe come up with something to catch their attention.

**Comment by easyaspi314** [comment]
It is worth a try.

Those school blocks are so annoying: They block Wikipedia, scripts, images,
and other random stuff. (Yet it is terrible at blocking what it *should*
block, like half of the forum sites out there).

**Comment by easyaspi314** [comment]
If it wasn't for those blocks,  I would have near-final drafts by now.

**Comment by fzurita** [comment]
@paulscode that wouldn't be a bad way to go about it.

**Comment by easyaspi314** [comment]
@paulscode @fzurita @ZAD-Man @BonzaiThePenguin 

The wait is finally over. I have made the flat version of the current logo. I don't have the cartridge finished, though. 

School blocked file upload; so I have a Drive link. 

https://drive.google.com/open?id=0Bxk_L8QgNv7TZ1JGbC1zRGw2Zzg

**Comment by fzurita** [comment]
I like it!. Here it is for reference.
![mupen no cartridge](https://cloud.githubusercontent.com/assets/11581687/14954794/1fdcb0fe-1043-11e6-9e51-2bd58a02b82c.png)

**Comment by easyaspi314** [comment]
And, I made sure that they scaled good to all densities, using the pixel art angles. 

https://drive.google.com/open?id=0Bxk_L8QgNv7TeFRrdE0tT3ZVT0k

**Comment by easyaspi314** [comment]
I also uploaded the .ai file.

**Comment by BonzaiThePenguin** [comment]
Looks great!

**Comment by easyaspi314** [comment]
I am open for suggestions on the inside color and any other color.

[Here is the official Material color palette.](https://www.google.com/design/spec/style/color.html#color-color-palette)

**Comment by easyaspi314** [comment]
I updated the drive folder with the MDPI version (downscaled for the OUYA icon) upscaled using nearest neighbor (so each pixel is 4x4 with no smoothing). 

It looks a lot better.

**Comment by fzurita** [comment]
One thing I have noticed about material icons are that all corners are round. It's a very subtle rounding. Maybe we can do the same here?

**Comment by easyaspi314** [comment]
I mean I *could*, but those are not 90° angles, and they are meant to
resemble a 3D object with multiple colored faces joining to a point. You
can't easily round those logically. Because then you would have to round
all the corners and that would make things weird.

It is already an unorthodox Material design icon. Maybe very small rounded
corners would work.

**Comment by easyaspi314** [comment]
If you want to see the rounded icon, here it is. 

I don't personally like it. https://drive.google.com/open?id=0Bxk_L8QgNv7TcDByWnluQW1NdHM

**Comment by fzurita** [comment]
That one seems to be the low res version. Do you have the high res version?

**Comment by easyaspi314** [comment]
It is going to be the detail on the high res smartphones. No Android is going to use a bigger icon. Except for the Play store maybe.

**Comment by easyaspi314** [comment]
@fzurita 
How about we put in the new icons and I make a quick [Google Form](https://docs.google.com/forms/d/1F2stkHvb0Rx5vfmaz50OtTfT73XjHK2GEXZj9a_x-yw/viewform?entry.356261308).

```java
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
    if (!prefs.getBoolean("seen_survey", false)) {
        LinearLayout dialogLayout = new LinearLayout(this);
        dialogLayout.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT));
        dialogLayout.setOrientation(LinearLayout.VERTICAL);
        TextView message = new TextView(this);
        message.setLayoutParams( new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT));
        message.setText("We have recently changed our icon and we want your feedback.\n\n" +
            "Please take a few moments to fill out this feedback form so we can make improvements.");
        dialogLayout.addView(message);
        ImageView icon = new ImageView(this);
        icon.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT));
        icon.setAdjustViewBounds(true);
        icon.setImageResource(R.drawable.ic_launcher_play);
        dialogLayout.addView(icon);
        AlertDialog dialog = new AlertDialog.Builder()
            .setTitle("We want your feedback!")
            .setView(iconLayout)
            .setPositiveButton(getString(android.R.string.ok), new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialog, int which) {
                    Intent i = new Intent(Intent.ACTION_VIEW, 
                        Uri.parse("https://docs.google.com/forms/d/1F2stkHvb0Rx5vfmaz50OtTfT73XjHK2GEXZj9a_x-yw/viewform?entry.356261308"));
                    SplashActivity.this.startActivity(i);
                }
           })
           .setNegativeButton(getString(android.R.string.cancel), null)
           .create();
           prefs.edit().putBoolean("seen_survey", true);
           dialog.show();
    }
...
}
```

**Comment by fzurita** [comment]
Hmm, well, right now they have to go to paulscode website to download the app anyways, we might as well put a link to the poll in that page. Your idea would make sense of the app was downloaded through the play store.

**Comment by fzurita** [comment]
Also, your idea also makes sense if we can't get collaboration from Paul to update the site..... He seems to be MIA.

**Comment by easyaspi314** [comment]
Here are the icons in their respective folders: 
https://drive.google.com/open?id=0Bxk_L8QgNv7TRmtJRlktVklPSEE

**Comment by easyaspi314** [comment]
If you do it, responses will be viewable here. 

https://docs.google.com/spreadsheets/d/1ZoeGbTRFqLcrrdGiEg-qPAWnT08dxEa5D8NK9V5Mp24/edit?usp=sharing

**Comment by easyaspi314** [comment]
@fzurita are you going to do it or should I? 

I will take the blame if you get in trouble. :smirk:

**Comment by fzurita** [comment]
Make a pull request with this change and I'll merge it.

**Comment by easyaspi314** [comment]
I will try tonight. I am busy today.

**Comment by easyaspi314** [comment]
@fzurita 

Can you attempt to make a build and see if the dialog and the launcher icon work?

**Comment by fzurita** [comment]
Yep, I'll check it tonight.

**Comment by easyaspi314** [comment]
@fzurita I am looking at the new icon on my phone's screen and now that I think about it, the colors are a little…dark?

Maybe I will try lightening the colors.

**Comment by fzurita** [comment]
That can depend a lot on phone screen. It looked ok on my phone.

**Comment by easyaspi314** [comment]
![screenshot_20160504-032901](https://cloud.githubusercontent.com/assets/6258309/15007632/806b6080-11a8-11e6-8051-673df0b05a58.png)

Huh. And the icon is tiny in comparison. 

Hold off the merge.

**Comment by fzurita** [comment]
You are right, I hadn't noticed that.

**Comment by fzurita** [comment]
You probably put the wrong resolution images in the folders.

**Comment by easyaspi314** [comment]
No that is right. I was more interested on sharp edges that I forgot about size. :sad:

**Comment by daguil68367** [comment]
I fixed it for you guys! 
![mupenmaterial](https://cloud.githubusercontent.com/assets/11461536/17214810/44685eea-54a0-11e6-9d5f-b97f708ccaa8.png)

**Comment by fzurita** [comment]
Cool, what changes did you make? Is that fixing the size issue?

**Comment by daguil68367** [comment]
I removed the barely visible translucent padding around it. Thought I'd give back to this project for once since you fixed the app not installing on ICS devices.

**Comment by fzurita** [comment]
Gotcha, thanks! I think I'm going to make my play store version use this icon.

**Comment by fzurita** [comment]
So it seems that Mupen64plus FZ has been tagged for violating the "impersonation" policy of the Google play store.

This is what I got when I tried to submit the last update:

> Hi Francisco Zurita,

> Thank you for the reply.

> After further review, we found out that your app Mupen64Plus FZ (N64 Emulator) is still in violation of Google Play policy. **Your app icon is currently similar to Nintendo 64.**

> You can read through the Policy Coverage and Impersonation and Intellectual Property policy page for more details.

> Please update or change your app icon to fix this issue and submit your app for another review.

> Let me know if you require further assistance.

> Thank you for your time and have a great day.

> Regards,

> Dennis

I have been using the same icon for around three years now and it had never been an issue, but now they are refusing the update until I change the app icon. So I guess we need a new icon. I may ask my wife for some help since she is pretty good a graphical design.

**Comment by xperia64** [comment]
I'm wondering if the color scheme is to blame here. There could be a reason why upstream Mupen uses that red and white logo.

If they think upstream Mupen's logo is too similar, then yeah, that's overreaching on their part by far.

I guess it might be safer to just do some other random stylized M.

**Comment by fzurita** [comment]
It could be, I have no idea how they came to their conclusion. I can't believe they are confusing an M for an N. It is what it is though. We are going to need a new icon.

**Comment by littleguy77** [comment]
That sucks.  Dealing with google on these matters is usually painful and slow.  

I was thinking the same thing about the color scheme and upstream's use of red and white.  I recommend getting in touch with Richard and seeing if he's ok with us using the red and white scheme.  Or, if we still want to differentiate ourselves from upstream (so that Richard isn't flooded with Android-related help requests), we could use a green and white scheme or something.  Green like the android logo.

**Comment by xperia64** [comment]
I'd be wary of green or blue, only because those are the primary colors of the front of the N64 logo.

**Comment by fzurita** [comment]
Also, I'm going to have to change the app name as well due to the impersonation policy. Mupen64Plus FZ is too similar to Mupen64plus AE which was in the play store before me, which they don't like. Although, this is probably not too relevant here is it's technically my own build of the app.

**Comment by fzurita** [comment]
I simply updated the icon and app name in the playstore. I will change nothing here since it's definitely fair use.

**Comment by fzurita** [comment]
Google is making my life really hard all the sudden.

```
Hi Francisco,

Thanks for contacting the Google Play team. 

Status: Latest app update not available on Google Play

I’ve reviewed your appeal request and found that your app (org.mupen64plusae.v3.fzurita) still violates Google Play Policy. If you submitted an update to an existing app, the version published prior to the update is still available on Google Play. I’ve included details below about the specific issue with your app and what you can do to get your app back on Google Play.

Step 1: Fix the policy violation with your app

During review, we found that your app violates Google Play policy, and determined your app to be a high risk profile. Google Play identifies high risk profiles by using signals such as:

apps that contain assets prone to abuse
previous app enforcements
relations to other previously suspended apps or accounts
user rating and uninstall data
You can read through the Policy Coverage page for more details.

For example, your app currently contains an unclear affiliation with Nintendo.

If you are authorized by the content owner to redistribute the content in this manner, please reply with verifiable documentation with the following examples: distribution agreement, authorization contract (PDF file).

If you are not authorized, you'll need to make modifications to the the store listing including icon, images, description, app title etc in order to avoid any confusions with the content owner.

Please update your app to fix this issue. You may also want to double check that your app complies with all other policies listed in the Developer Policy Center as additional enforcement could occur if there are further policy violations.

Step 2: Submit your updated app or APK

To submit an update to your app’s metadata:

Sign in to your Play Console.
Select the app with the policy violation.
Select Store presence > Store listing.
Make changes to bring your app into compliance.
Click Submit update or Resubmit app.
To submit an updated APK:

Review the checklist to prepare your APK.
Sign in to your Play Console.
Select the app with the policy violation.
On the left menu, select Release management > App releases.
Next to the release type you want to create, select Manage. 
To create a new release, select Create release. 
Follow the on-screen instructions to add APKs. For additional information, please visit the Play Console Help Center.
Please let me know if you have any other questions. Thanks for working with us to fix the policy issue and for your continued support of Google Play.

Regards,
Jon
The Google Play Team
```

**Comment by fzurita** [comment]
Closing old issues.
