### ISSUE TITLE
Now that we have the cheat dialog resize to the keyboard, we get dialogs too small for phones.

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#553]
![screenshot_2016-04-09-23-31-12](https://cloud.githubusercontent.com/assets/6258309/14407940/f8bdb3f4-feab-11e5-8074-fe429f8bd702.png)
Gah! @fzurita 
[![htismpc](https://cloud.githubusercontent.com/assets/6258309/14407955/94f6e894-feac-11e5-8452-3fcb5b192abe.jpg)](http://m.imgur.com/gallery/HTisMpC)

I think, at this point, we should convert the DialogFragment to not use AlertDialog and follow [this guide](https://developer.android.com/guide/topics/ui/dialogs.html#FullscreenDialog) to make it fullscreen on phones.

**Comment by fzurita** [comment]
Hmmm, unintended consequences. I recommend making both dialogs be full screen activities, no matter the screen size. Feel free to take on the task, it shouldn't be too hard.

**Comment by easyaspi314** [comment]
I thing a full screen cheat editor on a tablet is a *little* overkill.

Why do you need to have a full width screen for something that is only going to be 13 characters wide?

And we can use the textPassword to hide suggestions.

**Comment by fzurita** [comment]
Yeah, I think you are right. It would look ugly on tablets. Feel free to implement the solution you suggested.

**Comment by BonzaiThePenguin** [comment]
I rewrote the cheat editor last year to use the sidebar, but it looks like it's back to using nested activities and dialogs? The project manager at the time somehow managed to kill progress on this project it seems. :angry:

**Comment by fzurita** [comment]
I think when I came on board he was more relaxed. I also redid the cheat editor UI. I didn't make it use the side bar though. Feel free to look at what I did, it's in the latest nightly. I'm sure others could do better than me since I'm not a UI kind of person. I just care about making things usable.

**Comment by easyaspi314** [comment]
I like layouts; I am just not the best at the code.

**Comment by easyaspi314** [comment]
@BonzaiThePenguin @fzurita

I agree. @fzurita, you're fired. :) (JK, obviously)

What we need to do is *plan*. Put our heads together.

Let's think about the perfect UI/behavior, then slowly work towards that goal.

**Comment by fzurita** [comment]
Anything you come up with, as long as is better, won't have any opposition from me.

**Comment by easyaspi314** [comment]
**No.** 

One person coming up with ideas causes chaos. If, let's say, I leave because I am busy, if you guys don't have a clear idea about what we all want, one of two things will happen:
* We all start going off on our own paths and that leads to a messy app. 
* Nobody tries to improve it and it never improves.

**Comment by fzurita** [comment]
I think what he did was in a separate branch and it never made it to the main branch.

**Comment by easyaspi314** [comment]
What I am essentially saying is that if we don't all have an input, we will
forget.

**Comment by fzurita** [comment]
Yes. That's a fair point still.

**Comment by easyaspi314** [comment]
How's this for an idea?

![dark cards yeaaaaaah](https://cloud.githubusercontent.com/assets/6258309/14440046/30322e5e-fffc-11e5-8038-e4aba1fc7f14.png)

**Comment by easyaspi314** [comment]
This is only a rough layout, using a linear layout, not an adapter.

**Comment by fzurita** [comment]
That's not bad. Similar to a card layout.

**Comment by easyaspi314** [comment]
That *is* a card layout. :)

**Comment by fzurita** [comment]
Closing old issues.
