### ISSUE TITLE
Show Glide64 options in the UI

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#554]
Currently, and for a really long time, Glide64mk2 has had no options besides frameskipping shown in the settings. There are many options available in config files. 

Especially since we have more than enough options that do crazy things in Rice and GLideN64, we should have more options exposed. Even if we add them like we added GLideN64 settings, adding raw values and slowly putting in the real names, that would be great.

So far, Glide64mk2 appears to be the best for most OpenGL ES 2.0 devices and games, such as Smash, OOT and SM64.

**Comment by easyaspi314** [comment]
@fzurita …anything?

You put the raw options in, I can help put user-friendly names in.

**Comment by fzurita** [comment]
I hadn't had much time lately. The names is the easy part.

**Comment by easyaspi314** [comment]
Here you go.

![thyme](https://cloud.githubusercontent.com/assets/6258309/15451328/afd2364c-1f8a-11e6-8f66-3f53102da6dc.jpg)
```










```

Oh, wait. Maybe it was the wrong thyme for this. :stuck_out_tongue_winking_eye:

**Comment by fzurita** [comment]
I don't get it, but lol :P

**Comment by easyaspi314** [comment]
> I hadn't had much **time** lately.

Now you have **thyme**.

**Comment by fzurita** [comment]
Oh, lol, now I get it

**Comment by easyaspi314** [comment]
Also, Use the Schwartz, Lone Starr!
(*Spaceballs* reference if you didn't get it)

**Comment by fzurita** [comment]
Lol. I watched that movie once. I barely remember it though.

**Comment by easyaspi314** [comment]
I saw it a few times. It made me further appreciate *Star Wars*.

But lol, let's get back on topic…

**Comment by fzurita** [comment]
Done:
dd565bb781d36ebe0fc5bd099e482745e92f9cb3
fa5738e9f7f7e00b58990ade151234d784f0f33a
26c169f41306f434b0adb27c308d542ef424203b
