### ISSUE TITLE
Add manual screen rotation option that only rotates the game but not phone

### ISSUE THREAD

**Issue by TheExplodingLabs** [mupen64plus-ae/mupen64plus-ae#555]
My game turns 90° when I have glide on
![screenshot_2016-04-24-07-37-24](https://cloud.githubusercontent.com/assets/18639095/14765770/1a627170-09f1-11e6-98f3-ccbedf84203a.png)

**Comment by fzurita** [comment]
We really are just a front end for the plugin. Please make an issue here instead:

https://github.com/mupen64plus/mupen64plus-video-glide64mk2/issues

Also make sure to specify what device you are using.

**Comment by fzurita** [comment]
Actually, I'll reopen this. For rotation specific bugs that are device specific, we should probably work around in the front end.  What device do you have?

**Comment by TheExplodingLabs** [comment]
I have a Huawei Y530-U00

**Comment by TheExplodingLabs** [comment]
And i use glide because other the game would get glitchy

**Comment by fzurita** [comment]
@TheExplodingLabs, if you are still around, if you set the screen rotation to portrait mode under display settings does it make the issue any better?

Some old Adreno drivers have issues with landscape mode.

**Comment by fzurita** [comment]
Support for Android versions less than 4.4 is being dropped. This shouldn't be an issue with those devices.
