### ISSUE TITLE
Feature request: Loading screen for emulator activity

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#556]
Right now, the current implementation when you launch the emulator is you get a direct cut to a black screen with controls and a few `Toast` messages. Coming from a user who dealt with a slooow phone, there is NOTHING more irritating than a blank screen. You can't directly tell it is doing anything.
#### Easy:
- Screen shows with ROM box art. 
- It is dimmed with a spinner.
#### Hard:
- Box art expands Material-esque style from either the sidebar or the gallery item if it is a clean start.
- As it grows, it dims and a spinner shows
- Controls fade into view
- When it is ready, the box are fades out.
#### Easy:
- Same as for restart.
#### Medium:
- Game takes a screenshot as it is exiting.
- Sets background as that screenshot, dimmed with spinner.
- When the game is ready, it fades out, leaving the emulator view.
#### Hard:
- Starts like restart
- Fades to screenshot

**Comment by fzurita** [comment]
All these things would take time to implement. Maybe when I have time. This is not really something that's critical for functionality.

**Comment by easyaspi314** [comment]
I never said I wanted it now.

**Comment by easyaspi314** [comment]
@fzurita

Is there any way I can get a `Drawable` for the cover art for a specific ROM?

**Comment by fzurita** [comment]
Do you mean this?

http://paulscode.com/downloads/Mupen64Plus-AE/CoverArt/

**Comment by easyaspi314** [comment]
No. Though that is nice...

I could probably implement a basic ROM box art view.
To be sure, do we have a set of fired events when the emulator is ready, or
better, an AsyncTask for when the ROM starts (because that would make
things a HELL of a lot easier)?

Also, this is what I want for the code:
From the emulator activity:

Drawable d = getBoxArtDrawableSomehow(thisRom);
A Bitmap will also do.

*Also, for best results, is there a way to start the emulator paused on
*frame 1* (so it shows the first frame) and then play it when ready?*

**Comment by fzurita** [comment]
Probably what takes the longest is extracting the zip file if it hasn't been extracted already. The zip extraction is a simple method call that happens in the UI thread, so it's not async.

If the zip file has been extracted then you are just waiting on the core to load the ROM. There are no callbacks for that, only way to know is when the frame rate is I longer 0 FPS. A callback for Thai would require modifying on of the plugins to send JNI message after the ROM load happens.

This is not easy stuff.

**Comment by fzurita** [comment]
Ok, actually, ```CoreInterface.addOnStateCallbackListener``` may be able to do the job, but I'm not 100% sure. You could try experimenting with that.

**Comment by easyaspi314** [comment]
Dammit, this is more complex than i thought…

**Comment by easyaspi314** [comment]
@fzurita, we also have ANOTHER problem. I am assuming that the link you
sent me was where we were getting the in-app cover art.

Those are 256×177 — WAY too small to grow to full screen! I wonder if we
can get permission to gather high res versions and scale them in app.

Will that break anything?

**Comment by easyaspi314** [comment]
@fzurita Sigh.

gamesdbase.com has picture-perfect box art for what looks like every ROM at 1440x1052…but they watermark it. I might send the site owner an email and ask if we can use the content; even if we have to direct link to it.

**Comment by easyaspi314** [comment]
I sent him an email.

**Comment by fzurita** [comment]
Ok

**Comment by easyaspi314** [comment]
![ @fzurita  ](https://cloud.githubusercontent.com/assets/6258309/15103222/bf4789c4-1576-11e6-85a1-c48075af0410.png)

It looks like we struck gold. The gamesdbase developer linked me to [this](http://emumovies.com/files/file/1035-nintendo-64-2d-box-pack/).

I will ask them permission first. I haven't downloaded it yet; I am on LTE right now and the download is 80MB.

**Comment by fzurita** [comment]
I wonder if they would mind if we grab their data. I'm sure they pay for their upload bandwidth.

**Comment by easyaspi314** [comment]
Well turns out the box art on that one was low res. I found an archive that looked promising, but this:
![ @fzurita screenshot_20160509-061157](https://cloud.githubusercontent.com/assets/6258309/15110097/fe17d33a-15ac-11e6-9992-c78efa676698.png)

**Comment by RenaKunisaki** [comment]
Maybe you can contact them and see if there's a way to get the entire database. They probably have that limitation just because of bandwidth; maybe they'd be able to arrange something.

**Comment by easyaspi314** [comment]
Yeah, I'll see what I can do.

**Comment by fzurita** [comment]
I implemented by a very basic loading screen for now when unzipping ROMs. It's just a dialog box with a rotating spinner. I may add cover art to it as well, it wouldn't take long to add that at this point.

Also, this "issue" is very hard to close as written. Issues should be very specific. I think you could make an issue with additional things you would like implemented to the dialog box with a spinner.
