### ISSUE TITLE
[POLL] Gallery + Palette library = Material Awesomeness!

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#557]
@fzurita @BonzaiThePenguin @ZAD-Man @paulscode what do you think? Not an actual _implementation_ yet, but personally I think it is pretty awesome!

Tada!
![screenshot_20160426-100723](https://cloud.githubusercontent.com/assets/6258309/14821116/83e4ca24-0b97-11e6-8e82-e5b1e62a01c6.png)

**Comment by fzurita** [comment]
Not bad, it looks better than what we have now.

**Comment by easyaspi314** [comment]
Here are how some other roms look.

![screenshot_20160426-104320](https://cloud.githubusercontent.com/assets/6258309/14822217/cac551b2-0b9b-11e6-848b-29d660527777.png)

**Comment by fzurita** [comment]
How are you coming up with the color behind the game name?

**Comment by easyaspi314** [comment]
Palette generates them. It tales a bitmap and spits out a bunch of colors from that image that match a category.

**Comment by ZAD-Man** [comment]
Sweet! I like it :)

Is the name font part of the Material spec? If it's swappable, I'd like to see a few different fonts just to compare. I think it's great though!

**Comment by easyaspi314** [comment]
Oh no, it is a custom system font called "Fira Sans" I installed. Ignore it.

If you have root access or CyanogenMod I can show you how to replace the
default font.

**Comment by easyaspi314** [comment]
This is the same thing in Roboto. I changed how it selects colors, so it is a bit different.

![screenshot_20160426-153905](https://cloud.githubusercontent.com/assets/6258309/14831755/0f05425a-0bc5-11e6-9896-9d328bb2302d.png)

**Comment by ZAD-Man** [comment]
Ah, excellent! I love it now. ^_^

**Comment by easyaspi314** [comment]
Yeah, that is what my demo would look like on your device (if you are on
Lollipop or higher).

**Comment by ZAD-Man** [comment]
Yeah, makes sense. I always forget about system fonts.

Just had another thought, I wonder if having only white or black (depending on each background) would be an improvement or not. I generally prefer higher contrast for reading.

Oh, and I missed your earlier edits - I don't blame you for replacing the font, haha. I've done so several times on computers where I've wanted to switch things around. :)

And actually, now that I'm comparing them, I actually don't mind it in Fira Sans... Hm. Maybe something else threw me off...

**Comment by easyaspi314** [comment]
What Android version do you run?

**Comment by fzurita** [comment]
@easyaspi314 I like your new layout, if you submit a pull request even if incomplete, I can help you integrate it (if you need help).

**Comment by easyaspi314** [comment]
I'll see what I can do.

**Comment by easyaspi314** [comment]
I am gonna be busy this week, sadly.  Got an overnight field trip.

**Comment by easyaspi314** [comment]
@fzurita

Were you able to make anything out of it?
I removed padding, and added the palette code. Ignore the BitmapCropper and MainActivity.

**Comment by fzurita** [comment]
I haven't tried yet. It would save me a lot of time if you try to integrate it with the current gallery. I have very limited time lately.

**Comment by easyaspi314** [comment]
Well I guess we are all gonna have to wait until Saturday.

**Comment by fzurita** [comment]
Cleaning up old issues. @easyaspi314 If you ever want to see this integrated, I would recommend you make a pull request.
