### ISSUE TITLE
Zelda OOT - Gles2rice crash

### ISSUE THREAD

**Issue by ElectricPulze** [mupen64plus-ae/mupen64plus-ae#558]
New to github bit think I found the right place...

I am attempting to play "The Legend of Zelda: The Ocarina of Time" with the HD Retexture. The only way I think it's possible is by using Gles2rice to load the textures. It doesn't matter if I try with or without them, as long as I use Gles2rice the game crashes after trying to exit the pause menu...
https://youtu.be/gH2mg1wgoW0

**Comment by fzurita** [comment]
Please try the latest auto build from here:

http://www.paulscode.com/auto-builds/

**Comment by ElectricPulze** [comment]
Works great. Thank you!
Why isn't this a part of the official free or paid app on google play? 
/Owner of the paid version

**Comment by fzurita** [comment]
Because the owner of the play store listing hasn't gotten around to updating it.
