### ISSUE TITLE
WWF No Mercy for Nintendo 64 Bug fix

### ISSUE THREAD

**Issue by jbird7977** [mupen64plus-ae/mupen64plus-ae#559]
I have downloaded many emulators and it doesn't work on any. You can't choose anything or even move your person while playing the game because you dont have an analog stick to play it. The analog stick is there and it moves but it doesn't do anything. All you can do is a handful of attacks and punch your opponent! Please fix so we all can enjoy a great game on a great emulator app

**Comment by fzurita** [comment]
This is not an issue. Don't use the analogue, use the digital touchscreen profile.
