### ISSUE TITLE
Mario Party 3 Issues

### ISSUE THREAD

**Issue by Iceman4193** [mupen64plus-ae/mupen64plus-ae#56]
Mario Party 3 on my Asus tf300t is having some graphic issues.

All seems to work fine until you actually start playing where the characters become invisable once you start to play and some of the board pieces fall out of view as well.

Checked the cheat options for any fixes but I have not found any. 
Other that this the game seems to work ok up until you actually start rolling the dice.

**Comment by fzurita** [comment]
Upstream issue.
