### ISSUE TITLE
Strange colours with glide64 or gln64

### ISSUE THREAD

**Issue by sirviktoors** [mupen64plus-ae/mupen64plus-ae#561]
I am getting strange colours (looks like negative but it isn't) with every game I have tested. I'm using android (xiaomi redmi note 3 pro) and this hasn't happened with my earlier devices. I wonder what is causing it. And I have tried to make my own glide64 profile with no help. Any solutions?

**Comment by fzurita** [comment]
Probably a bug with the GPU drivers in your device. Android GPU drivers are generally pretty bad except for NVidia.

We have a lot of workarounds in the code for bad GPU drivers. Without the device in hand though, it would be difficult to debug that issue.

**Comment by fzurita** [comment]
Does this build by any chance fix the issues with those plugins? https://drive.google.com/file/d/0B57Ioy26LWegV1RUTVVWTzhPVnc/view?usp=sharing

**Comment by sirviktoors** [comment]
No difference. Here is picture when using the
''global default''
Thanks very much for trying to help!
On May 28, 2016 21:44, "Francisco Zurita" <notifications@github.com> wrote:

Does this build by any chance fix the issues with those plugins?
https://drive.google.com/file/d/0B57Ioy26LWegV1RUTVVWTzhPVnc/view?usp=sharing

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/561#issuecomment-222323530>,
or mute the thread
<https://github.com/notifications/unsubscribe/ASZRllFMC3EM6RiwPnELqCdNn7U93xmJks5qGIz8gaJpZM4IbK7P>
.

**Comment by fzurita** [comment]
I'm going to close this since there is not much we can do about it. Specially if it's just one specific device.
