### ISSUE TITLE
legend of Zelda oot

### ISSUE THREAD

**Issue by Jaecer** [mupen64plus-ae/mupen64plus-ae#563]
was playing legend of Zelda ocarina of time and just got done speaking with the fairy on top of mount whatever it's called I didn't pay attention I get flown down by the owl jump off the building then all of sudden black I've force closed the app exited then reentered and even deleted and reinstssd but it won't change from all back and it doesn't even show the start up screen anymore

**Comment by fzurita** [comment]
What version of the app are you using?

**Comment by RenaKunisaki** [comment]
Do other games work? Check that it's not loading an automatic save from after the game blacked out.

**Comment by Jaecer** [comment]
I don't know anything about it and it was only the game it played the music from the town I was in had to reset it and after I did it worked again but idk if it would last

**Comment by fzurita** [comment]
Your GPU driver may have crashed.
