### ISSUE TITLE
GLES3 slower than GLES2

### ISSUE THREAD

**Issue by min050820** [mupen64plus-ae/mupen64plus-ae#564]
In GlideN64 backend, gles3 mode is slower than gles2. To test, I disabled all options that is unique in gles3. But gles3 was still way slower than gles2. I also tried enabling options that could boost gles3 backend, but it was still WAY slower.

I have no idea whether it's driver issue or backend's issue. My phone's gpu is Adreno320, and I should be using Freedreno since I don't remember putting any binary blob when compiling my kernel. (Or binary blob was already in my rom. I'm not 100% sure about my driver)

**Comment by fzurita** [comment]
I have tried to narrow down why GLES 2.0 is so much faster than the 3.0 version with not much luck. Maybe it's better to make an issue in the GLideN64 Github page here:

https://github.com/gonetz/GLideN64/issues

**Comment by fzurita** [comment]
Do you see any improvements with this build?

https://drive.google.com/file/d/0B57Ioy26LWegWGFma1E5WUtWdDQ/view?usp=sharing

**Comment by min050820** [comment]
No, I don't see any inprovements. And I'll open an issue there. Hope it can be fixed, which is good for everyone :D

Please close this issue if needed.

**Comment by min050820** [comment]
I opened the issue. [https://github.com/gonetz/GLideN64/issues/1000#issuecomment-221508198]
It seems framebuffer copy could be the reason.

**Comment by fzurita** [comment]
Cool, thanks. I did see the issue. This for reference:

https://github.com/gonetz/GLideN64/issues/1000#issuecomment-221511312

I'll go ahead and close this.
