### ISSUE TITLE
Disney's Tarzan frezee after 1 minute into gameplay

### ISSUE THREAD

**Issue by brujo5** [mupen64plus-ae/mupen64plus-ae#565]
For whatever reason this game frezee after 1 minute into gameplay. I tried it out multiple times and it kept freeezing in the same spot. 

tried the interpreter or cache interpreter but still the same. also tested all emulation profiles but nothing change.

my device is galaxy S6 5.1.1, tested using latest build from buildbot

another user tested in shield tv but crases at same point
https://www.youtube.com/watch?v=56UbWV-jURc.﻿

**Comment by fzurita** [comment]
Does it crash if you use interpreter?

**Comment by brujo5** [comment]
frezee in galaxy s6 

another user in shield tv experince crash

**Comment by fzurita** [comment]
Yep, I got that, but does it crash if you switch your emulation profile from dynarec to interpreter?

**Comment by brujo5** [comment]
in dynarec and cache interpreter frezee with sound loop.

in pure interpreter is frezee with no sound

**Comment by fzurita** [comment]
Cool, which graphics plugins have you tried? I'm trying to narrow it down to see if it's a core issue or graphics plugin issue.

**Comment by brujo5** [comment]
gln64-acurate

glide, rice, cause black screen in game

**Comment by fzurita** [comment]
Have you tried GLideN64 3.0?

**Comment by brujo5** [comment]
GLideN64 3.0  cause black screen after menu.

this only work fine.
gln64-acurate
gln64-fast

**Comment by fzurita** [comment]
Hmmm, interesting. I wonder if Mupen64plus on PC had the same problem

**Comment by brujo5** [comment]
I see, thanks for taking time to help.

**Comment by fzurita** [comment]
I created this issue upstream:

https://github.com/mupen64plus/mupen64plus-core/issues/161

**Comment by fzurita** [comment]
I'll close this one now since it's redundant.

**Comment by brujo5** [comment]
thank you.
