### ISSUE TITLE
Android Studio 2.2 C++ compilation

### ISSUE THREAD

**Issue by tjmille2** [mupen64plus-ae/mupen64plus-ae#566]
When will Mupen64 finally make the transition to Android Studio from god awful Eclipse now that it has support for ndk-build and C++ support?

**Comment by fzurita** [comment]
It already does. I've been using it for months. Go to the tools/android-studio directory in the code.

**Comment by fzurita** [comment]
By the way, I haven't tried it under 2.2 (is it out yet?), But it works ok under 2.1. 

I'm using the current ”mk” files to build the jni code, not the built in gradle because it would take too long to migrate them all. Because of that, it doesn't recognize all the c/c++ files correctly, but it builds fine.

With the new 2.2 version, proper ”mk” come support will come, so everything  will be 100%.

**Comment by tjmille2** [comment]
@fzurita How does one import the project into Android Studio given the non-standard source code layout?

**Comment by fzurita** [comment]
In the standard src directory I created a main directory and checked out the source to that main directory.

In the directory one up from the second directory, I placed the tools/Android studio/mobile/build.gradle

In the directory one up from the src directory, I placed the tools/Android studio/mobile/build.gradle

In the directory two up from the src directory, I placed the tools/Android studio/build.gradle

**Comment by tjmille2** [comment]
@fzurita Thanks for the quick reply. When following the standard Android Studio import project prompt, a preference -> preference cyclical dependency is thrown. From research, it seems like more than one person is experiencing this issue with Android Studio. http://www.paulscode.com/forum/index.php?topic=9624.msg23796#msg23796

How to solve the cyclical dependency issue?

**Comment by fzurita** [comment]
Don't use the import project prompt. Create a new project and manually checkout the whole project to "mobile/src/main" and place the gradle files where I said they should go.

**Comment by fzurita** [comment]
I'm going to wait until the final version of Android Studio 2.2 is released before I adapt it to that one. It seems like you are using the preview version of it. Currently I'm using 2.1, so I'm not 100% sure if the above steps will work for you.

**Comment by tjmille2** [comment]
I'm following your guide. "In the directory one up from the second directory, I placed the tools/Android studio/mobile/build.gradle"

This directory is ambiguous to me, to which directory are you referring?

**Comment by tjmille2** [comment]
After setting up the project, when compiling the following error occurs:
Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build''

I am running Android Studio 2.1.1 for reference.

**Comment by fzurita** [comment]
You need to make sure that the ndk-build script is in your PATH environment variable.

**Comment by fzurita** [comment]
"In the directory one up from the second directory, I placed the tools/Android studio/mobile/build.gradle"

This is the root directory of the project.

**Comment by TimboMachimbo** [comment]
I have the ndk linked to Android Studio under Project Structure. How do I verify the ndk-build script is in the PATH environment variable? I am on OSX

**Comment by fzurita** [comment]
I'm not very familiar with how OSX is setup. Try a Google search?

**Comment by TimboMachimbo** [comment]
Yeah I found where to add to PATH http://hathaway.cc/post/69201163472/how-to-edit-your-path-environment-variables-on-mac

So from here I need to append <PATH TO NDK>/ndk-build to the file?

**Comment by fzurita** [comment]
No, only PATH_TO_NDK
