### ISSUE TITLE
Use KHR_gl_texture_2D_image and related functions in GlideN64

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#567]
This is more of a question since I'm pretty new at this.

Have you looked into using these extensions in GlideN64 to replace glTexImage2D calls?

https://www.khronos.org/registry/egl/extensions/KHR/EGL_KHR_gl_image.txt
https://www.khronos.org/registry/gles/extensions/OES/OES_EGL_image.txt

I've read a few things like this:
https://vec.io/posts/faster-alternatives-to-glreadpixels-and-glteximage2d-in-opengl-es

That seem to indicate the performance is better. I don't really know if it would give much of a benefit, but I saw that you used the OES_EGL_image_external in a recent change to GlideN64 so I wondered if it was possible to do a similar thing for all the glTexImage2D calls on EGL devices

**Comment by fzurita** [comment]
I have looked at those related functions in Android and they provide a sizable speedup. I actually used the related extensions right here: https://github.com/gonetz/GLideN64/blob/master/src/BufferCopy/ColorBufferToRDRAM_GLES.cpp

Search for EGLImage in that file.

There may be more places where this extension can provide additional speedups, but that was the one that made the biggest difference, at least on my device.

**Comment by fzurita** [comment]
I searched GLideN64 sources for glTexImage2D and it's only being used to initialize texture. So replacing that call in those instances would not provide any performance advantages in my opinion.

**Comment by loganmc10** [comment]
I believe glTexImage2D is used more than you think. If you look in ```TextureCache::_load()``` it is used, and I believe that is called every time a texture is read, whether it's cached or new. Anyway I don't really know what the performance difference would be. It might not make much of a difference since most the textures are already cached in GPU memory? I don't really know how all this stuff works, I was just reading a bit and it seemed like it might work.

**Comment by fzurita** [comment]
It may lead to less stutters when new areas are being loaded. But it's hard to tell without trying.
