### ISSUE TITLE
Touchscreen controls - Please allow us to break up the C-buttons

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#569]
In many games, ex. Ocarina, the C-buttons have different usages. Also, mapping the C-buttons right next to A makes double jump cancel or multishine combos really easy. 

However, the C buttons are stuck together. Could we have the option to break them apart?

**Comment by fzurita** [comment]
Yeah, that's possible. Low priority though.

**Comment by jonathanmasseurca** [comment]
Pull requests https://github.com/mupen64plus-ae/mupen64plus-ae/pull/953

**Comment by jonathanmasseurca** [comment]
Can be closed
