### ISSUE TITLE
Problem with inputs

### ISSUE THREAD

**Issue by Erevlys** [mupen64plus-ae/mupen64plus-ae#570]
Hi,

I don't really know if I should really write here. But anyway, I'd like to report a bug in MegaN64.
Let me explain : it's about the input. When you hold Z or R, if you move your joystick (or c-buttons or D-pad), the app bug, and the button you hold (Z or R) blink and sometimes stops being considered as held. It's a minor issue, but it's really disturbing when you want to move while holding Z or R (in Lylat wars for example, you can't turn fast, cause when you turn the Z or R stops being held in the app). I tried several mix, and it is really the Z or R mapping and not my controler : when i link the Z or R button in the app to another IRL button on my controler, it does the same.

So here it is, if you want more info i can provide them, and sorry if you don't understand all i wrote, english is not my native language.
Thanks for what you'll do,
Erevlys

**Comment by fzurita** [comment]
Yeah, this is the wrong place. Even though they are based on this, I have no idea what modifications they could have done. And if I fix a bug here, how can I force them to take the fix....

**Comment by fzurita** [comment]
You could try our latest build right here and see if you have the same issue:

http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/Mupen64PlusAE_master_201604240803_2474cf1.apk

**Comment by Erevlys** [comment]
So where could i report this bug ? I'm sorry but i don't know what to do with your file either.
Thanks anyway for your answer

**Comment by fzurita** [comment]
Get the email of the author from the playstore listing. You will have to email him directly.

**Comment by fzurita** [comment]
Here, I looked up the email from you:  Callmonstter@gmail.com. The file I posted is the official apk. You download the file then install it to your phone.

**Comment by Erevlys** [comment]
Well, thanks for what you've done. I'll email the author.
Thanks again !
