### ISSUE TITLE
Commit 977022a makes Mupen crash.

### ISSUE THREAD

**Issue by blackman91** [mupen64plus-ae/mupen64plus-ae#571]
I am using an Archos Gamepad 2 with Android 4.2.2 and that commit makes mupen crash when starting any game, the build just before that one works perfectly and all builds after that one have the same issue.
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/977022a

**Comment by blackman91** [comment]
I am talking of course about the auto builds in paulscode.com

**Comment by fzurita** [comment]
That commit has already been reverted. Try this build instead:

https://drive.google.com/file/d/0B57Ioy26LWegMk1kYldXYWUxTlk/view?usp=sharing

**Comment by blackman91** [comment]
Yo thanks a lot man that one works perfect, could you share the latest build again please?
