### ISSUE TITLE
Ipega Right Analog Stick

### ISSUE THREAD

**Issue by Darth-Cthoras** [mupen64plus-ae/mupen64plus-ae#572]
Made this ( http://www.paulscode.com/forum/index.php?topic=9173.0 ) over on the forums but got redirected to here by a member...

I have the Ipega 9025 bluetooth controller, and both Mupen64 AE 2.4.4 version code 36 and the latest auto builds have been unable to map or read the horizontal input of my right analog stick. The vertical movement is functioning properly, from -1 to 1 on the Axis_RZ.

**Comment by fzurita** [comment]
Thanks for making this here. Also, this doesn't work correctly in the 3.0 version as well, right?

**Comment by Darth-Cthoras** [comment]
Finally found out with some other programs that apparently my right analog stick is stuck full right (axis_z) 1.0. Tugging it left doesn't change that, so looks like the left sensor is busted.

**Comment by fzurita** [comment]
Since this is not a true problem, I'm going to close this.
