### ISSUE TITLE
Update/specify gamepad deadzone values?

### ISSUE THREAD

**Issue by gannon345** [mupen64plus-ae/mupen64plus-ae#573]
Would it be possible to specify the flat values for gamepad sticks in the emulator? I notice Android's default values for the stick deadzone is really high, like 4096, and this causes sticks to not be very sensitive, as that's a very high deadzone. The default value is used when the application doesn't specify a value, so I was wondering if it would be possible to specify within the emulator, or set a lower flat value, like 1024 or something?

Some info on how Android handles joystick deadzones in this XDA thread: http://forum.xda-developers.com/showthread.php?t=2492251

**Comment by fzurita** [comment]
I believe you can already do this in the latest beta builds. When you setup a custom controller profile, where you assign keys, there is as menu on the top right corner. In there, you can specify a custom dead zone .

**Comment by gannon345** [comment]
Oh interesting. I'll review the settings and check, I didn't know about that.

**Comment by gannon345** [comment]
Okay, tested it out and you're right, it's got deadzone and sensitivity settings. I tested a few configurations (deadzone between 5 and 10, very high and very low sensitivity). Seems like a deadzone of 5 and ~70%-75% sensitivity is the sweetspot for my controller. F-Zero X is infinitely more controllable now, before the slightest flick of the stick would send me skidding in a hard turn. Thanks for the info, and feel free to close the issue.
