### ISSUE TITLE
Lag in Smash Bros with GLideN64 even though GPU is not maxed?

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#574]
I just got a new Android phone (has an Adreno 304). I am testing out some different games.

When I use the Rice-Fast profile with Smash Bros, it works perfect, audio sounds good, etc.. FPS shows a consistent 30

When I use GLideN64, GLES2 or 3, its laggy, it is slow, the audio is choppy, but the FPS still shows a consistent over 30, but it actually can go much higher like 40+, but it still seems laggy.

What am I experiencing here? Am I doing something wrong? I don't have all my debugging tools setup yet so I haven't dug too deep into it, but I looked at the GPU frequency, and scales to 200 MHz when I play, and it can get as high as 450 MHz, so I assume the GPU isn't maxed out?

I'm using the latest build from https://github.com/mupen64plus-ae/mupen64plus-ae/issues/562

**Comment by loganmc10** [comment]
This is what the monitors look like in Android Studio:

![untitled](https://cloud.githubusercontent.com/assets/848146/16965264/9d166b1c-4dbc-11e6-8887-4a488032ed1c.png)

**Comment by fzurita** [comment]
Hmmm.... what happens if you have Frame Buffer emulation disabled?

**Comment by fzurita** [comment]
That seems consistent with having frame buffer emulation enabled and the "Swap frame buffers" option set to either "On VI update call" or "On VI origin change."

**Comment by loganmc10** [comment]
That is with Framebuffer emulation off actually, with it on I get about 20-22 FPS (with On Buffer Update, the default)

**Comment by fzurita** [comment]
Super smash brother actually runs at 60 FPS. And it runs slow even on my "little" stronger phone, which has an Adreno 330.

**Comment by loganmc10** [comment]
Are you sure? When I run it with Rice-Fast it says the FPS is 30 and the game is running at full speed with no audio lag

**Comment by fzurita** [comment]
I wonder if it's skipping frames. But I'm very sure that Super smash brothers is a 60FPS game.

**Comment by loganmc10** [comment]
hm ok, I guess thats why its nice to have multiple graphics plugins. Thanks for the info, I'll play around with it over the next few days and figure out how to probably figure out what the GPU is doing.

I guess there must be something up because the Adreno 304 is a pretty weak GPU, it's just strange that the GPU frequency reported by Android is 200 MHz most of the time if it really is working at its max.

**Comment by fzurita** [comment]
It's possible that GLideN64 is stalling the GPU somewhere. For example, the glReadPixels call will stall the GPU for a significant amount of time. There may be other copy operations that may be doing similar things.

**Comment by loganmc10** [comment]
I assume that must be the case, there must be something that is blocking it somewhere, or maybe I am not reading the tools right. I'm going to try and play around with the Adreno GPU Profiler tonight and see what I can come up with.

**Comment by loganmc10** [comment]
Sorry one other question about mupen64plus-ae (this is my first time using it)

Is it normal to have a strange "border" around the image?:

![screenshot_2016-07-19-15-02-47](https://cloud.githubusercontent.com/assets/848146/16966494/0c2ab382-4dc2-11e6-9c08-573d3c8ed156.png)

It seems to happen no matter what graphics plugin I use, but doesn't happen for every game.

**Comment by fzurita** [comment]
Hmm.... interesting, I don't have that issue. It's probably an issue with the version of the Adreno driver that you have.

See this page for additional information on GPU stalling:

https://www.opengl.org/wiki/Synchronization

**Comment by loganmc10** [comment]
Ok one more question, what is the best way to go about building this? I'm ok building it from the commandline, I was going to modify the auto-build.sh script to build it locally, or should I be using gradle?

Is that too old school? Should I be doing this from Android Studio?

**Comment by fzurita** [comment]
You can use Android Studio or Eclipse. Eclipse is potentially easier to setup since there are better instructions here: https://github.com/mupen64plus-ae/mupen64plus-ae

With Android studio there are no instructions, but if you want to work with that, there are two gradle files in the tools directory of the project.

**Comment by loganmc10** [comment]
Ok thanks, I guess I'll just have to play around with it. It just seems strange to me, with gln64-fast for instance, GoldenEye runs at near perfect framerate for me, and even when there is a bit of a slowdown, the FPS will show like 15-20, but it still seems to run decent, and the audio is smooth. With GLideN64 even if the FPS shows like 25, it is still very choppy and laggy it seems. I guess it's just a matter of finding the right video plugin for the right game.

**Comment by loganmc10** [comment]
gln64-fast also shows Smash Bros as 30 FPS for me (and that is smooth)
