### ISSUE TITLE
Typo in NativeConfigFiles.java

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#575]
This line has a typo:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/1f997c29c09bdd771dec3e16ce36ab1696dabab1/src/paulscode/android/mupen64plusae/jni/NativeConfigFiles.java#L191

It shouldn't have "game.gliden64EnableNativeResTexrects"

**Comment by fzurita** [comment]
Yep, it is indeed. I had it correct locally but somehow committed an older version!

**Comment by fzurita** [comment]
It's correct now. I rebased it, so commit history shows like it never happened.

**Comment by loganmc10** [comment]
I was looking at the shaders in the Adreno GPU profiler and noticed it was using the slower blending code even though I told it not to. Then I spent a while wondering how all these people were testing it out, I figured there must be some difference between the git version that I compiled and the apk that was posted lol

**Comment by fzurita** [comment]
yep!
