### ISSUE TITLE
mupen64 deleted my savegame

### ISSUE THREAD

**Issue by treakiandroid** [mupen64plus-ae/mupen64plus-ae#576]
Hi, i ised mupen64 to pläy a game on android for a week, i had made really good progress. Then, as my sdcard was full, i wanted to reset to the saved game so i ended the emulator, pressed the reset button and then started it again. As i seen the intro again and then the language questions i realized that my precious save game was gone for good. So please build in a check for io errors and dont make it so that on full storagr things get lost. It had been ok if it couldn't save another change but that my old, before saved

**Comment by treakiandroid** [comment]
, game was deleted/districted is unacceptable. Maybe you create a backup before writing changes or every hours or so automatically.

Thanks

**Comment by fzurita** [comment]
By default we have 4 auto saves. It's possible your last auto save was corrupted, but you should have 4 good auto saves as long as you don't keep playing and overwrite those as well.

**Comment by fzurita** [comment]
To open up one of your previous auto saves, go in game and open up the side bar. Scroll down until you see ”load from auto save”

**Comment by fzurita** [comment]
OK, fixed here: 661f5f39073b721f6105f1a726d99a5c559bb8b3

**Comment by treakiandroid** [comment]
Thanks a lot, hope that will get to fdroid soon so that wount happen again here;)

**Comment by treakiandroid** [comment]
I cant find a load from autosave option...

![screenshot_20160830-134435](https://cloud.githubusercontent.com/assets/7935237/18088037/77537efc-6eb8-11e6-8564-a9e8beac283b.png)
![screenshot_20160830-134440](https://cloud.githubusercontent.com/assets/7935237/18088047/86db656a-6eb8-11e6-9c69-892f394f250a.png)

**Comment by fzurita** [comment]
That's because you have a very old version that didn't have auto saves yet. Hehe is the latest one:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by treakiandroid** [comment]
I dont use google, can you do something to update the fdroid version? Mupen64 Plus AE (Nintendo 64 emulator) - https://f-droid.org/app/paulscode.android.mupen64plusae

Thanks

**Comment by fzurita** [comment]
No, I didn't put that version on fdroid up. Here is a link to the APK:

https://drive.google.com/file/d/0B57Ioy26LWegU29sX2JtZ3RCTEE/view?usp=sharing

**Comment by treakiandroid** [comment]
thanks for your helo, i have created an issue there to get it fixed: https://gitlab.com/fdroid/fdroiddata/issues/523

**Comment by fzurita** [comment]
I tried updating myself over there with not much luck. This is because we have a ton of libraries that are not open source. Removing these libraries should be fixable, it's just going to take a lot of time.

Here are the libraries we need to remove before the project if accepted on fdroid:

Ouya library: Easy, just remove ouya support
Android frameworks
ui library: Use run time loading of library calls
GLES 3 libraries: Switch all library calls to EGL calls in GLideN64.

These are not easy things and it's probably better done by someone in the team. It really is just me right now, and they would take some time. I really doubt they will take the time to do all that.

**Comment by treakiandroid** [comment]
ok, how bad that this is so much technical work to do. I would of cause be happy to see it in fdroid and as faar as i know there are still apps with non free libs and a read warning note about that....

but if that is such a big deal, an other question, can i switch to your app without loosing my save games? And can you provide an official release page beside that googleplay thing and that drive download where updates are pushed? It is also possible to host a froid repository which could be added to the client to get updates in a cebtral way (just like on Debian repositorys...)

**Comment by treaki** [comment]
hi,

it lookes like i have just managed to create a fdroid repo ( https://lfdroid.github.io/ ) using this guide:

https://f-droid.org/manual/fdroid.html#Simple-Binary-Repository

and add your current app, i have invited you to the github project so that you can update your app there...

**Comment by fzurita** [comment]
Hello, thanks, I will take a look at that.
