### ISSUE TITLE
resident evil 2 (galaxy S6 graphics bug)

### ISSUE THREAD

**Issue by brujo5** [mupen64plus-ae/mupen64plus-ae#577]
here using global glide64 fast
![screenshot_20160902-124643](https://cloud.githubusercontent.com/assets/4172898/18215660/7e775d58-710f-11e6-9d26-f4f95749baf9.png)

here using glide64 GL2.0
![screenshot_20160902-131235](https://cloud.githubusercontent.com/assets/4172898/18215681/9b738558-710f-11e6-9d59-f287173c2a81.png)

other perfils like glide64 GL3.0/3.1  cause game run in black screen

also i dont know why most games run slow using glide64 GL3.0/3.1

my device 
galaxy s6 android 6.0.1
gpu mali760

tested in latest build by @fzurita

**Comment by fzurita** [comment]
Set video plugin to Glidr64 and RSP to CXD4 HLE.

**Comment by brujo5** [comment]
using glide64 GL2.0  with CXD4 HLE. still the same 

using global glide64 fast with CXD4 HLE work now but run very slow in game.

why idea what settings could cause slowdowns in glide64 GL3.0/3.1 for malit760

thanks

**Comment by fzurita** [comment]
GLideN64 won't work with it. The CXD4 RSP requires a high end processor.

**Comment by brujo5** [comment]
oh i see. just like shield tv for android.

**Comment by fzurita** [comment]
Pretty much. It only runs full speed for me there.

**Comment by brujo5** [comment]
any idea what setting cause that most games run slow in glide64 GL3.0/3.1 for mali gpu.

i cant use those profiles since few time.

**Comment by brujo5** [comment]
the old builds from paulscode site work fine using those profiles.

**Comment by fzurita** [comment]
Not sure. I'm not sure RE2 every worked with GLideN64. You can make a bug report in the GLideN64 GitHub page if you want.

**Comment by brujo5** [comment]
ok thanks sir for the help.
