### ISSUE TITLE
Wow my saves are gone.

### ISSUE THREAD

**Issue by fridgebeatz** [mupen64plus-ae/mupen64plus-ae#583]
Hey I went to play OOT one day and my saves are gone? Looking at the files on my phone with a file manager, they appear to be there, but I've tried loading my file a million times and it either crashes or comes up with a blank cartridge. Please help me figure this, cuz theres no way I'm starting over again(this keeps happening on my phone with different emulators) I had nine hearts as kid link, that's pretty good. I'm not redoing all this bullshit so please help!

**Comment by fzurita** [comment]
A few questions. Which version of the app are you using?

Do you have the clean master app?

Did you ever save while you were in-game?

Can you check /sdcard/mupen64plus/GameData/THE LEGEND O ZELDA, in there game data is stored, are your SramData and AutoSaves empty?

**Comment by cleon456** [comment]
well im actually using cleanmaster lite, and i saw that in the residual junk files that the mupen64plus folder is actually checked by default meaning if i don't uncheck it i can easily delete everything.

**Comment by fzurita** [comment]
Yep....

**Comment by cleon456** [comment]
um why is that?

**Comment by fzurita** [comment]
No idea

**Comment by RenaKunisaki** [comment]
That app doesn't know that those "junk" files are your game saves. You need to be careful when deleting things you aren't sure about. 


Does Android provide some standard place/method to store save files, that we aren't using? Maybe this situation can be prevented.

**Comment by fzurita** [comment]
Yes it does, it's the app private storage. Unfortunately, if you put the files there, the user won't be able to get to them unless we add some kind of export functionality.

Maybe that's the right answer.

**Comment by fzurita** [comment]
The way I think Google would love us to do it is to store everything in private storage and have the option of backing up to google drive.

**Comment by fzurita** [comment]
Closing this for now since the original issue probably turned out to be using clean master.
