### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by nebleb18** [mupen64plus-ae/mupen64plus-ae#584]
I have tried to play my games on my tablet  I can go into the emulator but all I get is the audio of my games I have version 3.0.11(beta) version code 87 I have Android version 6.0.1 model number K88

**Comment by fzurita** [comment]
Does switching the emulation profile fix the issue fit you?

Open up the sidebar, go to profiles, select emulation profile, select one of the GLideN64 ones, and make it default.

Let me know if that helps.

**Comment by fzurita** [comment]
No response, so I'm closing this.
