### ISSUE TITLE
Missing 2D textures

### ISSUE THREAD

**Issue by alex47** [mupen64plus-ae/mupen64plus-ae#587]
This bug came up with playing Mortal Kombat 4 only while using gliden64-gles-2.0
I use gliden64-gles-2.0 because this performs the best on my phone (xiaomi redmi note 2) compared to others. Rice show black screen and others are sub 45fps, while gliden64-gles-2.0 is constant 60fps no matter what settings I use.
The only problem is that while playing the healthbars, menu and other 2d textures (images?) are simply missing.
Example:
[http://i.imgur.com/5xEE8IW.png](http://i.imgur.com/5xEE8IW.png)

**Comment by fzurita** [comment]
Ok, thanks, I will report the issue.

**Comment by loganmc10** [comment]
I think that just doesn't work with GLES2, it works with GLES3+ I believe.

**Comment by fzurita** [comment]
Interesting. I wonder which feature in GLES 3.0 that is using.

**Comment by alex47** [comment]
made a correction on this topic in #588 
please disregard this issue thread
