### ISSUE TITLE
Vanishing elements (correction to #587)

### ISSUE THREAD

**Issue by alex47** [mupen64plus-ae/mupen64plus-ae#588]
I made the issue #587 yesterday but I was a bit mistaken what the problem was.
I'd like to correctly report the problem once again.

I stated that the problem only occurs on OpenGL ES 2 which after testing again is not true.
What I found was is that it's present in OpenGL ES 3.0 as well. 

I discovered that disabling the "Enable frame and/or depth buffer emulation" option using the GLideN64 beta + OpenGL ES 3.0 gives the same performance as OpenGL ES 2 (from 35fps to 60fps lock) so now we can exclude the option that this problem exists because of the obscurity of OpenGL ES 2
(While this option is enabled the issue still remains)

I'm currently using version 3.0.14 (beta), code 92

I also discovered that setting the RSP to CXD4 LLE from HLE actually solves my issue. The only problem is that while using it the framerate is below 8fps constantly.

I recorded the issue on my phone:
https://www.youtube.com/watch?v=hqQvEQzKKUQ
(fps drops only because of recording)

You can see at the beginning the healthbars are there and then they just vanish.
Also notice the red "Fight!" text is also vanishing before reaching it's location then reappearing again as it goes away.

I'm not an expert on the topic but could this be because of depth or z-axis issues?

**Comment by fzurita** [comment]
Not sure what it is yet. I have yet to write the issue in the GLideN64 GitHub page. If it works in LLE mode, it means that it's an issue with the HLE portion of the plugin.

**Comment by fzurita** [comment]
@alex47 I created this issue in the GLideN64 github page:
https://github.com/gonetz/GLideN64/issues/1155

It will be tracked there now. I'll close this one since there is no point in having more than one issue open for the same thing. Thanks for the report.
