### ISSUE TITLE
Add netplay

### ISSUE THREAD

**Issue by ThiagoAndrade33766** [mupen64plus-ae/mupen64plus-ae#590]
should upgrade to play multiplayer but each player on your phone, so this faltanfo this in Mupen64.

**Comment by fzurita** [comment]
Yes, once the core implements net play, this will be possible.

**Comment by ThiagoAndrade33766** [comment]
is already in development?

**Comment by fzurita** [comment]
Someone made an attempt about a year ago but didn't finish.

**Comment by ThiagoAndrade33766** [comment]
Ok

**Comment by fzurita** [comment]
Here is the link for reference:
https://github.com/mupen64plus/mupen64plus-core/issues/112

**Comment by ThiagoAndrade33766** [comment]
Thank you
