### ISSUE TITLE
Building the project (Need to update README)

### ISSUE THREAD

**Issue by alex47** [mupen64plus-ae/mupen64plus-ae#591]
I tried to build this project myself by following the guide in the readme but I got stuck at a point.
After cloning it the next step would be executing:
`cp .project.init .project`
the problem is there is no such file in the project (or I just can't find it)
and without a .project file I can't load the project in Eclipse that easy

Also:
`Select File → Import → Android → Existing Android Code Into Workspace, and press Next`
There is no Android menu in the selection: http://i.imgur.com/46zaQg6.png
Did I install Eclipse incorrectly?

I swear every project on github I want to compile myself has some kind of problem in the guide so I can never do it.
Please help :(

**Comment by fzurita** [comment]
Hello, the README is way out of date. 

The project now builds with Android Studio.

You have to download Android Studio 2.2 along with the SDK and NDK. Then all you have to do is import the project from Android Studio and it should work.

**Comment by fzurita** [comment]
Done
