### ISSUE TITLE
Implement software reset

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus-ae/mupen64plus-ae#593]
I'm currently working on the new dynarec interrupts https://github.com/Gillou68310/mupen64plus-core/commit/88540604b4e5ce948fdf4540fbc0aba951e89263, I still have some tests to do before opening the PR but soft reset should be fixed by this commit.

You can now reset a game by using this command `coreDoCommand(M64CMD_RESET, 0, NULL)`.
So the following hack can be replaced by a `NativeExports.emuReset()`

```
public static synchronized void restartEmulator()
{
    CoreInterface.shutdownEmulator();
    CoreInterface.startupEmulator(null);
}
```

**Comment by fzurita** [comment]
Cool, that will be good.

**Comment by Gillou68310** [comment]
The new dynarec reset fix has been merged to master, you can now safely use the M64CMD_RESET in order to reset emulation ;-)

**Comment by fzurita** [comment]
Cool, I have a lot in my TODO list right now. I'll try to get to it.

**Comment by fzurita** [comment]
Ok, I just attempted to do this without much luck. I get this error:
```
03-01 01:29:13.954 19958-20011/org.mupen64plusae.v3.alpha E/Core: Compile at bogus memory address: 80800000
```

**Comment by fzurita** [comment]
Hmmm, I don't see how that would be any different. Here is the logic in the core:
```
        case M64CMD_RESET:
            if (!g_EmulatorRunning)
                return M64ERR_INVALID_STATE;
            if (ParamInt < 0 || ParamInt > 1)
                return M64ERR_INPUT_INVALID;
```

**Comment by Gillou68310** [comment]
Let me check on my computer I'm starting it right now

**Comment by fzurita** [comment]
Oops, I didn't look one line further. That gets then passed to ```main_reset```. I'll try 0 instead.

**Comment by Gillou68310** [comment]
No problem ;-)

**Comment by fzurita** [comment]
Ok, 0 works great! I'll merge to master.

**Comment by Gillou68310** [comment]
Cool :-)

**Comment by fzurita** [comment]
Implemented hete:
04dc3a303eeec373e954eacacf894bbe19d6de84
