### ISSUE TITLE
Cache Recent Games toggle not working

### ISSUE THREAD

**Issue by trickytree** [mupen64plus-ae/mupen64plus-ae#594]
ROMs are cached even if Cache Recent Games is unticked.

**Comment by fzurita** [comment]
They are deleted every time the library is loaded when that setting is enable. How are you loading the games?

**Comment by trickytree** [comment]
I use the standard frontend included with the emulator.

I see that the 'Unzipped ROMs' folder is cleared, but only when the frontend is exited then restarted. I expected the folder to be cleared when exiting a game if 'Cache Recent Games' is unticked.

Thanks for your hard work BTW.

**Comment by fzurita** [comment]
Yes, that is the case.

**Comment by trickytree** [comment]
Ok, behaviour is slightly different than expected but it works.
