### ISSUE TITLE
GLideN64 crop mode option

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus-ae/mupen64plus-ae#595]
The default crop mode is set to auto. Maybe we should add an option to disable screen cropping.

**Comment by fzurita** [comment]
Yeah, sure, I'll expose the option.

**Comment by fzurita** [comment]
I exposed the option, but only for auto and disabled. I'm not allowing custom cropping parameters because we already have the game specific zoom option.

**Comment by Gillou68310** [comment]
Thanks ;-)
