### ISSUE TITLE
Controller Mapping issues

### ISSUE THREAD

**Issue by Buddyp19023** [mupen64plus-ae/mupen64plus-ae#597]
So I have a Bluetooth controller (Gamesir g2u), and I'm having trouble mapping the analog sticks and d-pad. I played Zelda-majoras mask with no issues by using one of the preset layouts and mapping the input buttons. Recently started playing Kirby 64 and mapping the d-pad to the analog sticks (also tried using the d-pad), but the issue issue the game seems to recognize a reverse input at the same time. As in, hold the analog stick right and you will move right for a moment then stop, let go of the stick and you move left for a moment the stop. The same is true for both axis. Note: using the controller diagnostic screen, all inputs register correctly. Please advise.

**Comment by fzurita** [comment]
Interesting issue. Have you tried using the latest mupen64plus FZ in there play store?

**Comment by Buddyp19023** [comment]
Originally I was running the mega n64 version, but I just tried that one and got the same issues. I checked the controller diagnostics and it's not showing any input other than what it should. however the difference between the two versions is the mapping screen shows a picture, and on that screen I can see the inputs are not acting properly.


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: Francisco Zurita <notifications@github.com> Date: 10/28/16  11:42 PM  (GMT-05:00) To: mupen64plus-ae/mupen64plus-ae <mupen64plus-ae@noreply.github.com> Cc: Buddyp19023 <buddyp19023@aol.com>, Author <author@noreply.github.com> Subject: Re: [mupen64plus-ae/mupen64plus-ae] Controller Mapping issues (#597) 
Interesting issue. Have you tried using the latest mupen64plus FZ in there play store?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mupen64plus-ae/mupen64plus-ae","title":"mupen64plus-ae/mupen64plus-ae","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mupen64plus-ae/mupen64plus-ae"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fzurita in #597: Interesting issue. Have you tried using the latest mupen64plus FZ in there play store?"}],"action":{"name":"View Issue","url":"https://github.com/mupen64plus-ae/mupen64plus-ae/issues/597#issuecomment-257068642"}}}

**Comment by fzurita** [comment]
Have you tried increasing the dead zone?

**Comment by Buddyp19023** [comment]
Yes, I've tried various deadzone and sensitivity ranges and it doesn't seem to have an effect

**Comment by fzurita** [comment]
Interesting problem. It seems like we are detecting input from some axis when we shouldn't. Can you share you controller diagnostic?

**Comment by Buddyp19023** [comment]
I only have an option to share hardware info, not the actual diagnostic screen. But I can screenshot it if you like.

Device: Gamesir-G2u
Type: Default
Signature: 0,1,11,14,15,16,22,23
Hash: 1245841466
  AXIS_X: Stick
  AXIS_Y: Stick
  AXIS_Z: Stick
  AXIS_RZ: Stick
  AXIS_GAS: Trigger
  AXIS_BRAKE: Trigger
  AXIS_HAT_X: Stick
  AXIS_HAT_Y: Stick

Device: Virtual
Id: -1
Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
Class: BUTTON

Device: sec_touchscreen
Id: 3
Descriptor: 0fa9d3d0d40f7f5b316320876742e00ad5eb1ba9
Class: BUTTON, POINTER
Axes: 9
  AXIS_X (touchscreen): ( 0.0 , 1439.0 )
  AXIS_Y (touchscreen): ( 0.0 , 2559.0 )
  AXIS_PRESSURE (touchscreen): ( 0.0 , 1.0 )
  AXIS_SIZE (touchscreen): ( 0.0 , 1.0 )
  AXIS_TOUCH_MAJOR (touchscreen): ( 0.0 , 2937.2095 )
  AXIS_TOUCH_MINOR (touchscreen): ( 0.0 , 2937.2095 )
  AXIS_TOOL_MAJOR (touchscreen): ( 0.0 , 2937.2095 )
  AXIS_TOOL_MINOR (touchscreen): ( 0.0 , 2937.2095 )
  AXIS_DISTANCE (touchscreen): ( 0.0 , 255.0 )

Device: gpio_keys.30
Id: 5
Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
Class: BUTTON

Device: Headset
Id: 6
Descriptor: e9fbccb20aa36714786b4afad1fe05a9b8b78370
Class: BUTTON

Device: sec_touchkey
Id: 7
Descriptor: af4d26ea4cdc857cc0f1ed1ed51996db77be1e4d
Class: BUTTON

Device: Gamesir-G2u
Id: 216
Descriptor: 6b0ebc0952bd5223ef48f5c163737df8b808dfc3
Class: BUTTON, JOYSTICK
Axes: 8
  AXIS_X (joystick): ( -1.0 , 1.0 )
  AXIS_Y (joystick): ( -1.0 , 1.0 )
  AXIS_Z (joystick): ( -1.0 , 1.0 )
  AXIS_RZ (joystick): ( -1.0 , 1.0 )
  AXIS_GAS (joystick): ( 0.0 , 1.0 )
  AXIS_BRAKE (joystick): ( 0.0 , 1.0 )
  AXIS_HAT_X (joystick): ( -1.0 , 1.0 )
  AXIS_HAT_Y (joystick): ( -1.0 , 1.0 )

Processor	: AArch64 Processor rev 0 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
processor	: 6
processor	: 7
Features	: fp asimd aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: AArch64
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 0

Hardware	: SAMSUNG Exynos7420

Board: universal7420
Brand: samsung
Device: zerofltespr
Display: MMB29K.G920PVPS4CPI3
Host: SWDD6321
ID: MMB29K
Manufacturer: samsung
Model: SM-G920P
Product: zerofltespr

**Comment by fzurita** [comment]
Those is good for now. I'll take a look later.

**Comment by fzurita** [comment]
Ok, you can probably get around this issue by manually editing the controller.cfg file. You will see any layouts you created in that text file.

Unfortunately, the controller diagnostic is not giving me enough information to figure out the problem. It seems like one of the axis in your device is taking over the one that you are intending to press. This will be hard to figure out without the device in hand.

**Comment by fzurita** [comment]
@Buddyp19023  is this still an issue with the latest version of the app?

**Comment by fzurita** [comment]
I didn't get a response back, so I will assume fixed until I hear otherwise. I will re-open if necessary.
