### ISSUE TITLE
GLideN64 GLES3.1 option not showing up.

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#598]
I have a Sony Xperia XA (Android 6). It supports ES 3.1, but I don't see the open to enable the GLideN64 ES 3.1 plugin.

**Comment by loganmc10** [comment]
This is with the FZ version from the play store

**Comment by fzurita** [comment]
That means that Android is not reporting the device as GLES 3.1 capable.

**Comment by loganmc10** [comment]
How does it determine that? When I open the Mali Graphics Debugger App it says:

GL_RENDERER: Mali-T860
GL_VERSION: OpenGL ES 3.1 v1.r7p0...................

The "OpenGL Extensions Viewer" app reports the same.

**Comment by fzurita** [comment]
Here is how we check:
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/1699aabc5b39c30b14255e08810e8661a9cb11fd/app/src/main/java/paulscode/android/mupen64plusae/persistent/AppData.java#L551

My device reports 3.1.

**Comment by loganmc10** [comment]
Interesting, I guess it's a device bug then? I've used GLES 3.1 features on the phone (glDrawElementsIndirect) in some of my testing with GLideN64, so I know it supports it, I guess it just isn't reporting it properly then.

Is there any way to see the output from that check? Maybe it is reporting 3.01 or something.

**Comment by fzurita** [comment]
It's probably reporting "3.0" otherwise the GLES-3.0 version of these plugin wouldn't show at all.

**Comment by loganmc10** [comment]
Ya that is probably the better way to do it, but you need a valid OpenGL context for that to work.

I'm not sure how the code gets executed, but it looks like this wouldn't work if the device reported something weird like 3.01:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/profile/EmulationProfileActivity.java#L194-L206

But you are probably right that it is just reporting 3.0.

**Comment by loganmc10** [comment]
Just tried the play store version and now the 3.1 plugins show up, thanks!

**Comment by fzurita** [comment]
Yep, no problem!
