### ISSUE TITLE
Give us a way to invert theanalog Y axis or X axis

### ISSUE THREAD

**Issue by draki50** [mupen64plus-ae/mupen64plus-ae#600]
It'sometimes difficult to play when it's needed, please, if you can add that, I'd be really thankful

**Comment by fzurita** [comment]
Do you mean in the touchscreen controls?

**Comment by draki50** [comment]
Yes, I can't seem to find where to invert the axis, all I can find is to invert the tilt sensor axis. You think you could help me find out where it is?

**Comment by fzurita** [comment]
You won't find it because it doesn't exist. I'll add the option soon.

**Comment by Jef2i** [comment]
I would appreciate this feature too !
Happy to hear it will be added :)

**Comment by fzurita** [comment]
This is done.
