### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by nburt95** [mupen64plus-ae/mupen64plus-ae#601]
The game crashed and now everytime I load it its stuck in the rashes state, as a result all my progrest has been lost. Pretty f******g annoying when you've almost completed the game!!! Loz OoT Shadow Temple blowing up a wall.

**Comment by nburt95** [comment]
Stuck in the crashed* state.

**Comment by fzurita** [comment]
Were you using cheats?

Are you able to restart the game and continue from your last in-game save?

**Comment by nburt95** [comment]
I was not using cheats. No Mupen doesn't work at all... I have reset all settings to default, I was abe to restart and contune from my last save but it's stuck in a constant freezed state.

**Comment by fzurita** [comment]
So you are saying that you were able to start up the game from the beginning by choosing the restart option instead of resume. Then you were able to load your in-game file from inside the game and when you load that, the game crashes?

**Comment by nburt95** [comment]
Yes even when I reload and contine from my last save it's still stuck in the frozen state, I was NOT using cheats just to clarify.

**Comment by fzurita** [comment]
Which version of the app are you using? Mupen64Plus FZ or Mupen64Plus AE?

**Comment by nburt95** [comment]
FZ

**Comment by fzurita** [comment]
Did you try the "Load from autosave" option by opening up the in-game sidebar? By default, the emulator keeps 4 auto saves that are stored each time you exit a game.

**Comment by nburt95** [comment]
Yes, they all load in my previous soot, right where it crashed.

**Comment by nburt95** [comment]
Spot* forgive me the auto correct on my phone is awful

**Comment by fzurita** [comment]
Did you ever save in-game by pushing start and hitting B to save?

**Comment by nburt95** [comment]
Yes, the crash has obviously corrupted it because it loads from where the game crashed. All of the auto saves also do.

**Comment by fzurita** [comment]
I guess you didn't use any slot saves?

It's possible that there is bug in the emulator that caused the game to crash in the Shadow temple. If that's the case, it will have to be addressed. Unfortunately, if none of those backup methods to recover your progress worked, then there is not much you can do. Your best bet would be to find a save state online for mupen64plus around the same area where you were.

**Comment by nburt95** [comment]
Id rather not waste my time on yet the 50th poorly coded emulator ive come across. No issue with crashes right up until that point. Corrupted all auto-saves and regular in-game saves. Another copy and paste job done by "emulator developers" as if no one would notice.

**Comment by fzurita** [comment]
In the interesting of figuring out the issue so that it doesn't happen to others, can you zip up your /sdcard/mupen64plus-fz folder and post it here? It will contain your save state as well in-game save data.

I'm sorry to have disappointed you, but this is a BETA open source app, and we need user input to help make it better.

It would be extremely appreciated if you can help by providing that folder in a zip file.

**Comment by nburt95** [comment]
I'd love to help out but as iv wasted 18 hours my time Im not in the helping mood.

**Comment by nburt95** [comment]
Easy fix, delete emulator, delete all corresponding files. Never use a copy & pasted emulator again... simple.

**Comment by loganmc10** [comment]
Nobody cares what emulator you use

**Comment by nburt95** [comment]
Doesn't matter anyway, they're all copy and paste jobs of the exact same emulator! As if you people haven

**Comment by fzurita** [comment]
@nburt95 please educate yourself before making broad assumptions.
