### ISSUE TITLE
Glide64mk2: Missing Visuals,Please Flesh Out These Features Into The UI

### ISSUE THREAD

**Issue by retrobenny** [mupen64plus-ae/mupen64plus-ae#603]
The main thing I would highly suggest is to bring back the "read every frame" option so visual effects can be rendered properly such as SM64's warp/vanish cap effects,it was initially omitted from being used a long time ago because most devices would chug with it enabled,so it could be added as an option in the UI so stronger devices can use it along with fleshing out all other possible options available if you kindly would.
If wrpAnisotropy can be used (this feature existed since before Napalm),please hook that part in as well so it can be functional too.
On windows,it is merely a checkbox for Anisotropy without stating the multiplier used,most likely the maximum supported one automatically.

**Comment by fzurita** [comment]
Done:
dd565bb781d36ebe0fc5bd099e482745e92f9cb3
fa5738e9f7f7e00b58990ade151234d784f0f33a
26c169f41306f434b0adb27c308d542ef424203b
