### ISSUE TITLE
Mupen64plus Android sarges hero's 1 and 2

### ISSUE THREAD

**Issue by brownie0183** [mupen64plus-ae/mupen64plus-ae#604]
I'm using the Android mupen 64 plus ae on a droid turbo and the game speed has been setting itself to game speed of 250% any suggestions I've already reinstalled and deleted the game files

**Comment by fzurita** [comment]
Are you using Mupen64Plus FZ or Mupen64Plus AE in there play store?

**Comment by brownie0183** [comment]
Mupen64plus FZ

**Comment by fzurita** [comment]
Interesting, is this the only game doing this? 

Can you try opening the sidebar while in game and selecting "desync audio"?

**Comment by brownie0183** [comment]
I've tried when it speeds up the sound goes out I reset the game it starts working normally then it does it again I've tried desync audio but it doesn't do anything and so far it is the only game

**Comment by fzurita** [comment]
Ok, another thing to try, go to settings, then audio. Change the audio plugin to SDL. Does that help?

**Comment by brownie0183** [comment]
So far after I reset the game haven't had it speed up again but there is a 2 or 3 second delay in the sound and gameplay I'll keep you posted if it happens again

**Comment by fzurita** [comment]
Sounds like there is some kind of issue with that game and the SLES plugin then.

**Comment by brownie0183** [comment]
K I do have another issue rogue squadron doesn't work is that a common issue

**Comment by fzurita** [comment]
Yes, it doesn't work due to unimplemented ucodes.
