### ISSUE TITLE
Ability to change FPS position

### ISSUE THREAD

**Issue by min050820** [mupen64plus-ae/mupen64plus-ae#608]
It'd be nice to make FPS box position configurable like Steam's in-game FPS counter option. (up-left, up-center, up-right, down-left, etc) And if it's possible, I would suggest putting that setting in where you modify touchscreen profile.

In case it _was_ configurable, we might want to change its position in settings, because I couldn't find it when I looked for it like 3 times.

**Comment by fzurita** [comment]
Yeah, I don't thinking about this, except I was thinking about putting the option in the same place where the FPS country is enabled.

**Comment by min050820** [comment]
That is also reasonable, since it's impossible to control wether to show FTS counter per-profile basis. I'm okay with either way.

**Comment by fzurita** [comment]
This is done: https://github.com/mupen64plus-ae/mupen64plus-ae/commit/092ec2e4917f757de173e312ce61cc9e78cfe862
