### ISSUE TITLE
Improve initialising speed

### ISSUE THREAD

**Issue by M-a-r-k** [mupen64plus-ae/mupen64plus-ae#610]
After updating the app, on launching it there's an initialisation process where various files are unpacked. That can take quite a long time; about 90 seconds on my phone, surely longer on slower devices. The time taken probably depends mainly on storage speed, whether writing to internal or external SD card etc.

Does the app (or Android) do the equivalent of fsync() after writing each file?

Most of the time, most of the files being unpacked will be identical to the already-present ones. So it could greatly improve initialisation time if instead of blindly writing out all files, you check if each file already exists with the same contents, and skip that file if so.

**Comment by fzurita** [comment]
Interesting, it takes less than 5 seconds in my device. What device do you have? Your storage write speed seems to be lacking.

**Comment by fzurita** [comment]
Interesting, it takes less than 5 seconds in my device. What device do you have? Your storage write speed seems to be lacking.

**Comment by M-a-r-k** [comment]
I'm using a Huawei G620S phone with 128GB SanDisk microSD card. I think the files are being unpacked to the SD card.

**Comment by fzurita** [comment]
I have been thinking of implementing such a feature, but it has been very low priority due to it taking so little time to unpack everything. Maybe I should move it up the priority list.

**Comment by M-a-r-k** [comment]
That would be great. Even on devices with faster I/O, minimising writes to flash is a good idea.

**Comment by fzurita** [comment]
This is done
