### ISSUE TITLE
Maping controller

### ISSUE THREAD

**Issue by HamsterBro** [mupen64plus-ae/mupen64plus-ae#611]
When i was mapping to my controller (ps4 controller) it was all good , but when i was trying to play (I traid legend of zelda ocarina of time, super smash brothers and diddy kong racing) none of the buttons work.It wasn't reacting to up, down square nothing.Please repair this error.

**Comment by fzurita** [comment]
It sounds like you forgot a step along the way. After you map the controller, go to settings and input and select the profile you created for controller 1.

**Comment by HamsterBro** [comment]
Thanks for help and replaying

29.01.2017 4:34 PM "Francisco Zurita" <notifications@github.com> napisał(a):

**Comment by fzurita** [comment]
Ok, was your problem fixed?

**Comment by HamsterBro** [comment]
Yes it's all working now thanks

29.01.2017 4:43 PM "Francisco Zurita" <notifications@github.com> napisał(a):
