### ISSUE TITLE
Kirby 64 texture and framerate issues

### ISSUE THREAD

**Issue by Dontejohnson468** [mupen64plus-ae/mupen64plus-ae#612]
When I play Kirby 64, some of the 3d models and environments have polygons turning white, and some of the game's textures look really rough. The sand texture when it pours down looks hideous in stage 2-1! 

As for framerate, the game constantly fluctuates between 24-30 frames in game, especially during boss fights.

The most stable plug-in I used was the GlideN64-GLES-3.0 for my Galaxy S5, whereas any or plug in was even worse. Lastly, I even disabled the sound and nothing did not happen either.

I was wondering if the device team could please fix these issues, and many others in this game, because I would love to play Kirby 64 on the go.

Thank you for listening to this post.

**Comment by fzurita** [comment]
Hello, GLideN64 is going to be the most accurate plugin, but it will require the most resources.

Your best bet is to reduce the resolution if you are having performance issues.

Also, to fix graphics bugs, I would take screenshots and make an issue in the plugin's GitHub page, GLideN64 is here:

https://github.com/gonetz/GLideN64/issues

This GitHub page is for the front end, SLES audio plugin, and input plugin.
