### ISSUE TITLE
Game Speed Stuck

### ISSUE THREAD

**Issue by Ghostmij17** [mupen64plus-ae/mupen64plus-ae#616]
I was off and on changing the gamespeed, until it got stuck at 300%.  Now, even after toggling it off, restarting the app, and trying to load app assets again, it's still stuck at this speed whenever I load my save up.  Not sure how to fix this; I would reinstall, but I don't want to lose my control layout.

**Comment by fzurita** [comment]
Are you using the Mupen64Plus FZ version of the app?

**Comment by Ghostmij17** [comment]
Ah, didn't even realize this was a general thread for mupen and not the app I was using, sorry bout that.  But I'm using Tendo64

**Comment by fzurita** [comment]
Ok, I wouldn't use that. They ripped off our app and put ads on it then gave it a different name. You can probably install our app (Mupen64Plus FZ), then rename your /sdcard/tendo64 folder to /sdcard/mupen64plus-fz

**Comment by Ghostmij17** [comment]
Oh wow, dang, yeah, same exact app pretty much.  Well, I'll definitely use this one instead then, I only was using that one because it's the first I've come across that allows portrait and customizing layout the way I want.  But anyway, I'll reply again if it for some reason ends up doing the same thing.  Thank ya!

**Comment by Ghostmij17** [comment]
So oddly enough, it's doing the exact same thing after moving all the files over

**Comment by fzurita** [comment]
What game is it?

**Comment by Ghostmij17** [comment]
It's Majora's Mask

**Comment by fzurita** [comment]
Try opening up the sidebar while in-game then select "Desync audio" does it help?

**Comment by Ghostmij17** [comment]
Yes it does!  Something so simple but I wouldn't have thought to try that.  Thanks for the ridiculously super speedy help!

**Comment by fzurita** [comment]
You can permanently set that by going to settings, then audio, and uncheck "Synchronize audio and video".
