### ISSUE TITLE
When i play madden 2000

### ISSUE THREAD

**Issue by mainer24** [mupen64plus-ae/mupen64plus-ae#617]
It moves in slow motion i have lgsm323 on gliden64 can u help me out

**Comment by fzurita** [comment]
I'm sorry, your phone is probably not fast enough to run GLideN64.

**Comment by BonzaiThePenguin** [comment]
Can verify, only a dual core 1.2 GHz. My ancient bargain bin phone is quad core 1.2 GHz.

**Comment by mainer24** [comment]
What does that mean

**Comment by BonzaiThePenguin** [comment]
Your phone is probably not fast enough to run GLideN64.

**Comment by mainer24** [comment]
Damn

**Comment by BonzaiThePenguin** [comment]
Try FPse, maybe?

**Comment by mainer24** [comment]
Wat is dat

**Comment by mainer24** [comment]
What is fpse
