### ISSUE TITLE
My screen is glitched

### ISSUE THREAD

**Issue by mainer24** [mupen64plus-ae/mupen64plus-ae#619]
Hi i just updated the app and now my screen is glitched on half of my screen on gliden64 my phone is an lg323 android wat do i do to correct this

**Comment by fzurita** [comment]
Can you send a screenshot?

**Comment by mainer24** [comment]
How do u screenshot

**Comment by fzurita** [comment]
Open up the sidebar while in-game and select the screenshot option.

**Comment by mainer24** [comment]
Ok i did dat wat do i do next

**Comment by fzurita** [comment]
Using a file manager, navigate to /sdcard/mupen64plus-fz/GameData/[game name]/Screenshots. You can post that file here.

**Comment by mainer24** [comment]
Did u get it

**Comment by fzurita** [comment]
I don't see it.

**Comment by mainer24** [comment]
content://media/external/file/6949

**Comment by mainer24** [comment]
Do u c it

**Comment by fzurita** [comment]
No, I don't unfortunately. What game do you need GLideN64 for? Maybe you can use another plugin.

**Comment by mainer24** [comment]
When i use other plugins they arent as accurate as gliden64

**Comment by fzurita** [comment]
Try copying the picture to your PC then use your PC to post it.

**Comment by mainer24** [comment]
I dnt have a pc

**Comment by mainer24** [comment]
The gliden64 is the only accurate one

**Comment by RenaKunisaki** [comment]
Are you posting these messages on Github or email?

On Apr 15, 2017 16:17, "mainer24" <notifications@github.com> wrote:

The gliden64 is the only accurate one

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/619#issuecomment-294315591>,
or mute the thread

**Comment by mainer24** [comment]
Both

**Comment by RenaKunisaki** [comment]
OK, on Github you should see a button to attach a file. You can add the
screenshot that way.

**Comment by fzurita** [comment]
I think I know the issue here. GLideN64 is broken right now when frame buffer emulation is disabled. I'll have to get around to reporting an issue upstream at some point.
