### ISSUE TITLE
Banjo Tooie Mupen AE V3 crash

### ISSUE THREAD

**Issue by HazardousMesa** [mupen64plus-ae/mupen64plus-ae#620]
In Jolly Rogers there's a certain place where the characters split up when you press A but whenever I go there and press A it crashes instantly.I cant change the interpreter because there is not an option in the settings for this.Any help is appreciated!

**Comment by fzurita** [comment]
Try using the FZ version of the app. It can be found here:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by HazardousMesa** [comment]
I did try but my save slots cannot be loaded on another emulator.The path is exactly the same as the AE V3 but I cant load it.

**Comment by fzurita** [comment]
Copy the /sdcard/mupen64plus-v3-alpha to /sdcard/mupen64plus-fz.

Alternately, on the FZ version, you can go to settings then data, and change your game data path.

**Comment by HazardousMesa** [comment]
It works!Thank you very much!
