### ISSUE TITLE
Core service running list of issues

### ISSUE THREAD

**Issue by fzurita** [mupen64plus-ae/mupen64plus-ae#622]
- [x] We should probably make GameActivity into a fragment as well
- [x] If the sidebar is open and the screen is rotated, then the game is unpaused and side bar is closed
- [x] Sometimes loading a game at the same time as rotating the screen causes a black screen until the screen is rotated again.
- [x] The service notification sticks when when rotating the screen on game exit
- [x] Notification says always paused, it should show the true state of emulation.
- [x] Put back shutdownEgl and figure out issues with it.
- [x] Black screen on rotation while paused. Not sure what's going on here, can't figure it out. Advance frame is called after rotation, but screen remains black....
- [x] Notification says "saving texture cache" at inappropriate times.
- [x] I shouldn't force auto rotation on all users, there could be some confusion for users that have rotation locked.
- [x] Fix exit not working when loading from notifcation
- [x] Resuming a game from the notification doesn't allow the game to exit.
- [x] Stretch screen option is not working correctly on rotation.
- [x] General instability after exiting a game for the first time. Loading a new game or exiting another loaded game crashes a lot. Crashes seem to occur in the ART JVM itself and not in our code, but I suspect our NDK code is doing some bad things to put the JVM in a bad state.
- [x] Use a better way to determine that the service is running since it now runs in a separate process. It's harder to detect if it's already running.
- [x] Add auto save when the home button is hit
- [x] Core fragment is being called on too early in the GameFragment.
- [x] Back button sometimes takes you back to the gallery

**Comment by loganmc10** [comment]
Also, is ```shutdownEgl()``` ever called? It's probably not a big deal, but there might be some kind of resource leak there if that stuff isn't shut down properly.

**Comment by fzurita** [comment]
It's not. Cleaning up the context was causing issues. I'll figure those out eventually as well.

**Comment by fzurita** [comment]
I think everything has been taken care of. @loganmc10 Let me know if you run into any issue if you happen to run the latest build.

**Comment by loganmc10** [comment]
Will do I'll try it out today

**Comment by loganmc10** [comment]
Everything seems to work really well. The only thing I notice is this:

If I have the game paused (by having the drawer open), and I swipe down the notification bar and clicked on the notification, it will say: "Please wait, saving texture cache".

Same if I have the game paused, and go to my home screen, and then return to the app using the notification, it will say "Please wait, saving texture cache". But it doesn't show that if I return to the app by clicking on the icon for the app.

**Comment by fzurita** [comment]
Interesting. Sounds like I have a bug there. It should only say "saving texture cache" after we have commanded a shut down.

**Comment by loganmc10** [comment]
There does seem to be a bit of stability issues as well. Sometimes when I exit a game it crashes (Mupen64Plus has stopped). I'm not sure how to reliability reproduce it, it seems a bit random. But if I mess around with it a bit (play, pause a few times, rotate the screen, close and open the app, etc..) it crashes on me at different times. It even crashes once after I exited a game, closed the app, and the opened the app, it crashed when the app first opened, before I even launched a game.

This is on a Shield Tablet.

**Comment by fzurita** [comment]
Ok, good to know. I may have an idea as to what may be happening.

**Comment by loganmc10** [comment]
I haven't updated to the last 2 commits, but it also does this thing where sometimes if I hit back, instead of opening the drawer, it takes me back to the game list, but the service/game is still running. If I click on the notification it takes me back to the game, but then the "exit" option in the drawer does nothing.

**Comment by fzurita** [comment]
Ok, yeah, there seem to be a lot of bugs to work out.

**Comment by fzurita** [comment]
The instability issues are baffling me. The ART JVM itself is crashing, I'm thinking that some JNI processes is corrupting memory, but finding where seems to be difficult.

**Comment by fzurita** [comment]
So I have narrowed down the instability to unloading the mupen64plus-core library. It corrupts the JVM. Unfortunately, if I never unload it and try to start a new game with the previous instance, the dynarec crashes...

**Comment by fzurita** [comment]
@loganmc10 Can you test stability again as well as for random bugs?

**Comment by loganmc10** [comment]
Yep I'll test it out tonight

**Comment by fzurita** [comment]
Cool, when you are testing, please turn on auto display orientation under display settings. It's off by default now to not confuse users.

**Comment by loganmc10** [comment]
It seems to work a lot better now. Everything seems to be working normally, good work.

Every now and then if I close the app while it's paused and re-open it, it will return to a black screen, instead of the last frame. I believe it did that before all these changes as well though. I actually prefer that to advancing the emulator to try to populate the screen, but I don't know what other people would want. Some people might be confused by the black screen.

**Comment by fzurita** [comment]
Ok, it's good that it's working as good if not better than before. I finished making the last couple of fixes, so I think this is good. Thanks for testing.
