### ISSUE TITLE
DS4 analog unmapable 

### ISSUE THREAD

**Issue by theShrike760** [mupen64plus-ae/mupen64plus-ae#625]
The PS4 ds4 controller analog sticks are unmappable. They are recognized in the controller diagnostics and to navigate menus but will not assign when mapping the control pad. I also tried bringing in a mapped set from mupen64ae and they would not function in game.

**Comment by fzurita** [comment]
Very strange issue. I have a PS4 controller and all axis map correctly in a NVidia Shield TV. This will be hard to debug, can you send me a screenshot of your controller diagnostic after using the analog sticks?

**Comment by theShrike760** [comment]
I can get it tonight. It's shows 0 for each and then +-1 as I move the sticks in each direction. Also to note I started back tracking versions and on .120 it recognized the sticks but mapped them as Dpad directions.

**Comment by theShrike760** [comment]
also to note the controller works flawlessly on the latest version of mupen64plus ae 2.4.4. That's where I borrowed the controller.cfg mapping to try.

**Comment by fzurita** [comment]
Ok, I'm interested in the axis that shows up as you move the controller around.

**Comment by theShrike760** [comment]
![img_8340](https://cloud.githubusercontent.com/assets/28708312/26082713/91aefbcc-398e-11e7-9d22-748460070848.JPG)
![Uploading IMG_8341.JPG…]()
![img_8342](https://cloud.githubusercontent.com/assets/28708312/26082714/91b23346-398e-11e7-9321-34101ff76ffd.JPG)
![Uploading IMG_8343.JPG…]()
![Uploading IMG_8344.JPG…]()
![Uploading IMG_8345.JPG…]()
![Uploading IMG_8346.JPG…]()
![Uploading IMG_8347.JPG…]()

**Comment by theShrike760** [comment]
This was left stick all directions then right.

**Comment by theShrike760** [comment]
![img_8342](https://cloud.githubusercontent.com/assets/28708312/26082777/ebbe3218-398e-11e7-9f59-3ec7cbc9d6dd.JPG)
![Uploading IMG_8343.JPG…]()

**Comment by theShrike760** [comment]
![img_8344](https://cloud.githubusercontent.com/assets/28708312/26082797/00512b54-398f-11e7-873a-c5990f250b97.JPG)
![Uploading IMG_8345.JPG…]()

**Comment by theShrike760** [comment]
![img_8346](https://cloud.githubusercontent.com/assets/28708312/26082808/11863d7e-398f-11e7-8ac0-3ff4a5818e8c.JPG)
![Uploading IMG_8347.JPG…]()

**Comment by fzurita** [comment]
They are showing up as regular MotionEvents. I wonder why we see them in the Controller diagnostic but not the GameActivity or ControllerProfileActivity. I'll look into it, I should be able to figure it out since we have a working case.

**Comment by fzurita** [comment]
@theShrike760 Can you let me know if this build fixes the mapping issues?

https://drive.google.com/file/d/0B57Ioy26LWegdVdlR1pIU292Z3M/view?usp=sharing

**Comment by theShrike760** [comment]
When I tried to create a new controller mapping it quick back to the main menu when you go to push any buttons. I then tried the xbox360 config and it didnt work. I checked the controller diagnostics and it showed the same as the pictures above.

**Comment by fzurita** [comment]
Ok, thanks. Sounds like it crashed. Can you send me the /sdcard/Mupen64plus/CrashLog file?

**Comment by fzurita** [comment]
Don't bother with the crash log, I see the problem already. I'll try to get another build tonight.

**Comment by theShrike760** [comment]
Thank you for the work on this. Any update?

**Comment by fzurita** [comment]
I haven't gotten around to it yet. Some time within the next few hours I'll have a break to do it.

**Comment by fzurita** [comment]
Ok, I have a new build:

https://drive.google.com/file/d/0B57Ioy26LWegczFSaUxGMWhnc0k/view?usp=sharing

Please let me know if controller mapping works in this build.

**Comment by theShrike760** [comment]
The app doesn't crash anymore but same behavior as before. Analog sticks are seen in the controller diagnostics screen but are not mappable.

**Comment by fzurita** [comment]
Ok, what I did didn't fix the issue then. It's a guessing game as to what the issue is, it's hard to find without having the actual device in hand. I'll do some more code inspection to determine what could break the Fire TV but not other Android devices.

**Comment by theShrike760** [comment]
Maybe I can try and help. Is the src code available on git? If you can point me to the file(s) that are used to capture mapping input ill take a look as well. It seems to me that it should be working fine. I wonder if it has to do with the analog sticks are read differently then hard button presses. Or something to do with the dialog that opens and is listening for user input to map the key.

**Comment by fzurita** [comment]
If you are interested, take a look at this:
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/dialog/PromptInputCodeDialog.java#L136

and this:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L62

I suspect that ```view.setOnGenericMotionListener(this);``` on not working correctly on your device for some reason. It almost seems like something is taking focus away from the view so that ```view.requestFocus();``` is not working.

**Comment by theShrike760** [comment]
This seems like a odd line:
Math.abs(strengths[i]) > maxStrength

Since the strength of any axis is +-1 and we are taking the abs of the value, at all times it will be greater than maxStrength which was set to -1.

**Comment by fzurita** [comment]
Yes, for the first iteration. When the analog stick is being held, that call is constantly happening. What that is doing is only taking the joystick input with the highest value since controllers can have many axis.

**Comment by theShrike760** [comment]
Is there any way for me to have a verbose log dumped during the attempted mapping so see which portions of code are executing? I didnt see any debug in the files you sent over.

**Comment by fzurita** [comment]
Yes. For example:
 ```Log.e("AxisProvider", "Strength=" + maxStrength );```

**Comment by theShrike760** [comment]
Wanted to verify. You created PromptInputCodeDialog.java? I could not find it in the original paulscode, i was also unable to find the line you highlighted: 'providers.add(new AxisProvider(view));' Did you create new code to capture mapping input or based it off the original somehow?

**Comment by fzurita** [comment]
Yeah, I created that class. It was based off the original that used to be in the Prompt class.

**Comment by theShrike760** [comment]
i was finally able to get a compiled version. Will the log.e function write to the log file that is written to the system? If not how do i ensure my debug gets written to that file? Thanks.

**Comment by fzurita** [comment]
Logs are written to the adb logs. That means that if you have your fire TV hooked up to your computer using adb, you will see logs in the adb output console within Android studio.

**Comment by theShrike760** [comment]
awesome! thank you for the info, ill give it a shot.

**Comment by theShrike760** [comment]
can you directly debug into the firetv via android studio? This would allow breakpoints and faster debugging.

**Comment by fzurita** [comment]
Yes, you should be able to. Either directly using a micro USB cable or remote adb over tcp/ip. Take a look at this:

https://developer.amazon.com/public/solutions/devices/fire-tv/docs/connecting-adb-to-fire-tv-device

Android studio already did the hard part for you (setup in the PC). All you should have to worry about is setting up the fire TV to work with it as described in the article.

**Comment by theShrike760** [comment]
TY! so i was able to get it to work and do on hardware debug here are some issues i see:
The input codes are just -1.......-100 and the strengths are are listed as 0.0. mStrengths.length = java null pointer. I also saw this in the log:
05-18 08:10:05.430 26207-26578/org.mupen64plusae.v3.alpha D/OpenGLRenderer: endAllStagingAnimators on 0xabe6e3e0 (RippleDrawable) with handle 0xabcb1a48
05-18 08:10:05.434 26207-26207/org.mupen64plusae.v3.alpha W/ViewRootImpl: Dropping event due to root view being removed: MotionEvent { action=ACTION_CANCEL, id[0]=0, x[0]=0.011764766, y[0]=-0.0039215097, toolType[0]=TOOL_TYPE_UNKNOWN, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1947927076, downTime=0, deviceId=15, source=0x1000010 }
05-18 08:10:05.434 26207-26207/org.mupen64plusae.v3.alpha I/AmazonViewRootImplCallback: unsupported controller
05-18 08:10:05.434 26207-26207/org.mupen64plusae.v3.alpha W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
05-18 08:10:05.532 26207-26207/org.mupen64plusae.v3.alpha E/MogaHack: Somebody is trying to intercept our intent. Disabling MOGA controller for security.

**Comment by fzurita** [comment]
The "Dropping event errors" as well as errors related to input seem concerning. Everything is not an issue.

Can you add some logging to here:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L107

Can you see if that method is being called. If it's never called, the joystick input will never work.

**Comment by theShrike760** [comment]
it hit that break and stopped.

**Comment by fzurita** [comment]
Interesting. So it sounds like there could be a bug in the processing of the input instead.

I wonder why it doesn't work only on the fire TV.

**Comment by fzurita** [comment]
Is the ```isJoystick``` parameter getting set to true in that same function?

**Comment by theShrike760** [comment]
isjoystick=true

**Comment by fzurita** [comment]
Ok, so it sounds like it's an issue in the processing of the axis strength value. Are you seeing values from -1 to 1 for each axis?

**Comment by theShrike760** [comment]
they are all 0 when i look at the array

**Comment by fzurita** [comment]
All the strengths values are zero? Can you put some logging or breakpoint here:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L177

Is that ever getting hit? Maybe we are never recognizing any of the axis as "sticks"

**Comment by theShrike760** [comment]
its not hitting that breakpoint

**Comment by fzurita** [comment]
Neither?

**Comment by theShrike760** [comment]
the inputlistener oninput function is getting an empty array of strength values passed to it. Who is one level above the call to oninput()?

**Comment by fzurita** [comment]
Follow this path: 

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L146

That ends up where you are looking.

**Comment by theShrike760** [comment]
its a hack but if i do this it fixes the issue:

if (range != null) {
            float flat = range.getFlat();

            //hack for fire tv
            if (flat > 10.0f)
            {
                flat = flat/100.0f;
            }
            
            final float value = event.getAxisValue(axis);
            // Ignore axis values that are within the 'flat' region of the
            // joystick axis center.
            if (Math.abs(value) > flat) {
                return value;
            }

**Comment by fzurita** [comment]
Yeah, it sounds like the fire TV doesn't have a good driver for the PS4 controller. Do any other games work your PS4 controller?

**Comment by fzurita** [comment]
I'm going to do a simple fix. If flat region is greater 1.0, then set it to zero. Thanks for looking into this problem. The root cause I believe is a bad driver for the controller that reported an invalid flat region.

**Comment by fzurita** [comment]
@theShrike760 I uploaded a fix. Feel free to try it when you get a chance.

**Comment by theShrike760** [comment]
Thanks. However I think flat=0 is a bad idea. Now any/all minor stick movements will be considered input. The point of the check is to remove non real movements correct? So if the x stick is say at .003 it'll think you moved it. Or is there another check somewhere else?

**Comment by fzurita** [comment]
Look at the change I made. I didn't make it zero, just a relatively small value.

**Comment by theShrike760** [comment]
Good news and bad news. Good is it worked on the mapping screen. Bad it goes crazy in game. I think there are more places flat is being used that its not accounting for the larger number. Ill take a look and make another debug build if i find any spots.

**Comment by fzurita** [comment]
I see a couple more places:
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L182
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/input/provider/AxisProvider.java#L189

Let me see if I can come up with a fix for those as well.

**Comment by theShrike760** [comment]
i put this in as a trial:
                            float localFlat = motionRange.getFlat();
                            //Some devices with bad drivers report invalid flat regions
                            if(localFlat > 0.5 || localFlat < 0.0)
                            {
                                localFlat = 0.05f;
                            }

**Comment by fzurita** [comment]
Check the latest commit. I fixed the other places where we used the flat region.

**Comment by theShrike760** [comment]
so the value of .05 is too sensitive im getting false binds when trying to bind the controller. Ill try bumping it up.

**Comment by fzurita** [comment]
Ok, let me know what a good value is and I'll update the code.

**Comment by theShrike760** [comment]
.25 works like a charm. That way a slight bump or jostle doesent accidentally map a key.

**Comment by fzurita** [comment]
Cool, I'll make that the override.

**Comment by fzurita** [comment]
No problem. I really appreciate your help in solving this.

**Comment by theShrike760** [comment]
Any time :) im trying to relearn java for work anyway and the best way is any way that is fun. This was fun and interesting and because i want to play zelda again :)
