### ISSUE TITLE
CBFD freezes when entering other stages using a saved state

### ISSUE THREAD

**Issue by joxeankoret** [mupen64plus-ae/mupen64plus-ae#626]
Hi,

I have a save state for Conker's Bad Fur Day that seems to be unstable. When entering any new zone or when dying, the game seems to get stuck. The music continues normally but it never gets into the new zone or re-spawns after being killed.

I tried entering into almost any new zone that could possibly "fix" the problem as well as disabled/enabled cheats, and tried other things, but it seems I'm unable to continue the game.

I can provide the save state files if required.

Any help would be appreciated!

PS: I'm a reverse engineer and programmer so I could debug myself the problem given some hint about what should I look into.

**Comment by joxeankoret** [comment]
Oops! Wrong mupen64plus-XXX repo. Closing it, my bad!

**Comment by fzurita** [comment]
No problem.
