### ISSUE TITLE
When i play no mercy

### ISSUE THREAD

**Issue by mainer24** [mupen64plus-ae/mupen64plus-ae#628]
Hello my screen still glicthes when i play no mercy

**Comment by fzurita** [comment]
Have you tried switching emulation profiles to GLideN64-Medium?

**Comment by mainer24** [comment]
I have a lg323 it doesnt work when i do that

**Comment by fzurita** [comment]
I looked at the specifications in your phone, and it's likely that it's driver issues.  I'll close it for now unless it can be reproduced in a phone with better drivers.
