### ISSUE TITLE
Oot Bug On Android

### ISSUE THREAD

**Issue by Dexonaut** [mupen64plus-ae/mupen64plus-ae#629]
I was trying to play it on my phone but I have a problem with some textures.
![screenshot_2017-05-24-21-22-50](https://cloud.githubusercontent.com/assets/28941011/26433438/639e012e-40c8-11e7-8bc4-b43ebe810449.png)
This is the Glide64 profile. I have tried the Gln64 and Rice but both crash in the menu pause. Is my phone the problem? Is a Samsung Galaxy Grand Prime.

**Comment by fzurita** [comment]
Maybe I'm missing the obvious. What texture problem do you see?

**Comment by fzurita** [comment]
Ok, I see it now. The fence is missing. That probably a problem work your phone's GPU drivers.

**Comment by Dexonaut** [comment]
Sorry, i should have specified which textures. Anyway some rocks and grass are missing too. Can I fix it?.

**Comment by fzurita** [comment]
You can switch the emulation profile to GLideN64-Medium, but it may be too slow in your device.
