### ISSUE TITLE
Using the remove texture feature does not remove textures

### ISSUE THREAD

**Issue by theShrike760** [mupen64plus-ae/mupen64plus-ae#630]
I tried using the remove/uninstall texture feature from the menu but neither the cached .htc file nor the .png files were removed from the user folder area. I had to go in and manually delete them.

**Comment by fzurita** [comment]
Ok, I'll look into this. I thought this was working correctly.

**Comment by fzurita** [comment]
@theShrike760 I just tried this and it worked ok. Texture packs were removed in my device. In fact, the whole "CoreConfig" folder should be deleted.

**Comment by theShrike760** [comment]
Awesome thanks for the update. I haven't tried the new updates in a few weeks. I'll let you know if the texture packs still crash the game when I get a chance.

**Comment by fzurita** [comment]
Ok, for this issue specifically, it was the "clear texture packs" option that you said wasn't working. So I would be interested in knowing if it really isn't working right now.
