### ISSUE TITLE
GLideN64 custom settings

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#631]
I haven't looked too closely at how mupen64plus-ae handles GLideN64.custom.ini, but I know it reads it currently.

Since https://github.com/gonetz/GLideN64/commit/eb3c5c07306dfae5024939f047ceb6d4687bf1dc, that stuff can probably be removed, since GLideN64 should be able to read the settings itself.

Also, right now, I believe the way it works is that GLideN64.custom.ini is only used if the user is using a built-in profile, is that right?

This should be changed (or that may just be removed altogether), and the setting ```EnableCustomSettings``` should be added, which controls whether GLideN64 uses GLideN64.custom.ini or not

**Comment by fzurita** [comment]
Yeah, I noticed that all that was merged. Mupen64plus-ae will read this file by itself and configure GLideN64 appropriately: https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/assets/mupen64plus_data/GLideN64.custom.ini

And like you said, it will only do it if a user picks a built in profile. I was planning to make it be more Glide64 where each setting has "Use game specific value".

Unfortunately, with the new way that it works, you get either all the custom settings overridden or none at all. There is no fine grained way to select which settings to override. I have to figure out a way to deal with that.

**Comment by loganmc10** [comment]
Typically those custom settings are there because they fix some serious bug, so usually they are preferred.

> Unfortunately, with the new way that it works, you get either all the custom settings overridden or none at all. There is no fine grained way to select which settings to override. I have to figure out a way to deal with that.

That is how it works on Project64 (and mupen64plus as well), Project64 just has a "Use GLideN64 per-game settings" checkbox, the tooltip says "When this option is checked some options may be overridden".

The only instance I can think of where GLideN64.custom.ini has a setting that probably isn't ideal for Android is Paper Mario, which has synchronous copies enabled to fix the pause menu background. It's probably better on Android to using async copies and have a wrong-looking background. But you can always maintain a slightly modified GLideN64.custom.ini

**Comment by fzurita** [comment]
Also, in some device even async copies are slow, which will be troublesome. I guess I can maintain a custom version of the GLideN64.custom.ini and make sure that copy color buffer to RDRAM is not set for any games.

**Comment by fzurita** [comment]
I'm not going to do this.
