### ISSUE TITLE
MegaN64 and Rayman 2 the great escape

### ISSUE THREAD

**Issue by BisnesMias** [mupen64plus-ae/mupen64plus-ae#632]
When I start Rayman 2 on megan64 i only get black screen and the music from the game

**Comment by fzurita** [comment]
Hello, you are reporting an issue for an unsupported fork of this app. Please try Mupen64plus FZ in the play store:
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

If the issue happens in that version, then the issue is valid, otherwise not.

**Comment by fzurita** [comment]
No response, closing.
