### ISSUE TITLE
My video and controls just went out while playing legend of zelda ocarina of time 

### ISSUE THREAD

**Issue by CadenK** [mupen64plus-ae/mupen64plus-ae#636]
I was just playing my game when it started to lag and then the video went black, I could still see my controls but I had no indication if they were working or not. I had the music still but that was it, I tried reseting it and the game ca me back but when I tried to reload my old save file it didn't the same thing again. Please help soon

**Comment by fzurita** [comment]
Are you using cheats?

**Comment by CadenK** [comment]
Nope

**Comment by fzurita** [comment]
Can you send me the save state?

**Comment by CadenK** [comment]
I'm not sure how to since it's on my phone

**Comment by fzurita** [comment]
Ok, I can show you how, but first are you using this version of the app?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by CadenK** [comment]
Okay and I was using a different app that had the same program installed let me try the app you sent me

**Comment by fzurita** [comment]
Which app are you using? Whatever it is, it's going to have the app data in a different folder. You will have to rename that folder to mupen64plus-fz.

**Comment by CadenK** [comment]
I was using Mega N64

**Comment by CadenK** [comment]
I tried the app you sent me and it did the same thing so how can I send you my save state

**Comment by fzurita** [comment]
Navigate to /sdcard/mupen64plus-fz/GameData using a file explorer app. Zip everything up in the, and post it here.

Also, now that you are using the right app, try restarting the game instead of resuming.

**Comment by CadenK** [comment]
Okay I'll try the restart but I know if I tried to load my old save it still does it

**Comment by CadenK** [comment]
file:///storage/emulated/0/Download/Legend%20of%20Zelda%2C%20The%20-%20Ocarina%20of%20Time%20(U)%20(V1.2)%20%5B!%5D.z64.zip

**Comment by CadenK** [comment]
I'm guessing that didn't work

**Comment by CadenK** [comment]
The restart makes my game work but I makes me have to start all over and I was trying to avoid that

**Comment by CadenK** [comment]
file:///storage/emulated/0/mupen64plus-fz/GameData/THE%20LEGEND%20OF%20ZELDA%20(U)%2057A9719AD547C516342E1A15D5C28C3D.zip

**Comment by fzurita** [comment]
Do you have an in-game save you can load after you restart the game?

**Comment by CadenK** [comment]
Let me try that

**Comment by CadenK** [comment]
It was from a little bit ago but not to far so I'm just going to use that, thank you so much for all the help

**Comment by fzurita** [comment]
Ok, np
