### ISSUE TITLE
Add -flto flag to linker

### ISSUE THREAD

**Issue by fzurita** [mupen64plus-ae/mupen64plus-ae#638]
This works fine in linux but in Windows it causes linker errors. Once the NDK is fixed, this should be fixed. See:

https://github.com/mupen64plus-ae/mupen64plus-ae/pull/637

**Comment by fzurita** [comment]
Hmm, I should probably look at this again. NDK 16 is out now, which should had fixed it.

**Comment by fzurita** [comment]
Still doesn't work in windows with NDK16. I will enable this for anything that is not windows for now.

**Comment by fzurita** [comment]
@loganmc10 I can't add it to ```COMMON_CPPFLAGS``` yet. I will have to wait until NDK17 because of this warning....
```
  /opt/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: warning: LLVM gold plugin: Linking two modules of different target triples: /home/fzurita/StudioProjects/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libEGLLoader.a.llvm.4100.EGLLoader.cpp' is 'armv7-none-linux-android19' whereas 'ld-temp.o' is 'thumbv7-none-linux-android19'
```

**Comment by loganmc10** [comment]
Ah gotta wait for r17 it looks like

**Comment by fzurita** [comment]
This is working now after upstream fixes.
