### ISSUE TITLE
 How Fix This --> fatal error: 'asm_defines_gas.h' file not found #include "asm_defines_gas.h"

### ISSUE THREAD

**Issue by osam20** [mupen64plus-ae/mupen64plus-ae#639]
Hi
when I was importing this project to Android Studio I was Encountered this error

`./mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.S:69:10: fatal error: 'asm_defines_gas.h' file not found
#include "asm_defines_gas.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [E:/workspace/nintendo64/mupen64plus/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/mupen64plus-core/./mupen64plus-core/src/device/r4300/new_dynarec/arm/linkage_arm.o] Error 1`

It says that this library file does not exist **"asm_defines_gas.h"**  but in this project it had used.
I want know how I can fix this error

**Comment by fzurita** [comment]
Hello, you need to add the directory where awk exists to your PATH environment variable. awk usually comes with the git client for windows.
