### ISSUE TITLE
Pause glitch on Ocarina of Time????

### ISSUE THREAD

**Issue by ChaseCXS** [mupen64plus-ae/mupen64plus-ae#640]
Whenever I use Glide64....(NOT GLIDEN64) Everytime I pause on Zelda: Ocarina of Time the screen flashes white! This really bugs me because I want to make a let's play of this game, and it won't seem authentic when I pause my game screen and It flashes white!!!! Please Help!!!
~Chase~

**Comment by fzurita** [comment]
Please make a bug report for that issue here:

https://github.com/mupen64plus/mupen64plus-video-glide64mk2

This app just acts as a front end for the plugin.
