### ISSUE TITLE
Slingshot/Bow glitch on Ocarina of Time.....

### ISSUE THREAD

**Issue by ChaseCXS** [mupen64plus-ae/mupen64plus-ae#641]
Whenever I use GlideN64....(NOT GLIDE64) Everytime I use the Slingshot you can see through the white sling thing, and whenever I use The Bow as adult Link you can see through his left hand.............PLEASE FIX!

**Comment by fzurita** [comment]
That is a bug with the GLideN64 video plugin. There is already a bug reported for that issue here:

https://github.com/gonetz/GLideN64/issues/1211

Unfortunately, that's not an easy to fix bug.
