### ISSUE TITLE
Load File on SM64 Maker

### ISSUE THREAD

**Issue by nancezaiaht** [mupen64plus-ae/mupen64plus-ae#642]
The load file option when I go in-game on Sm64 maker is not working, (ex: when I try to load another players level or zip file, it doesnt show any files, just a blank list)

**Comment by fzurita** [comment]
That's for loading save states. If you put a save state in /sdcard/mupen64plus-fz/GameData/[GAME FOLDER]/UserSaves it will show up there.

**Comment by nancezaiaht** [comment]
Now, its showing up, and says its loading but stays on the current save file that I have. Could you maybe help?

**Comment by fzurita** [comment]
I'm not sure exactly what you are trying to load. Is it a save state for Mario 64? A ROM hack?

**Comment by loganmc10** [comment]
It's a ROM hack (https://www.youtube.com/watch?v=XNZk4ggJkcc). People share levels via save states, but it looks like people are distributing Project64 save states, so I don't know if they work or if mupen64plus-ae has a process to convert them or something.

**Comment by fzurita** [comment]
Mupen64plus core itself should be able to convert them.
