### ISSUE TITLE
Can't access cheats

### ISSUE THREAD

**Issue by SnakeHugz** [mupen64plus-ae/mupen64plus-ae#643]
Whenever I try to use cheats, it doesn't work. Please help

**Comment by fzurita** [comment]
Can you be more specific? What doesn't work? Are you using the latest Mupen64plus FZ?

**Comment by SnakeHugz** [comment]
I'm playing Super Mario 64 on the latest version of Mupen64+AE on an LG V20

**Comment by fzurita** [comment]
That's a very old version. Please try the latest version at this address:
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

In the new version, to add cheats, select the game, go to settings,  and select cheats.
