### ISSUE TITLE
PS4 controller mapping issues

### ISSUE THREAD

**Issue by Kellogg70** [mupen64plus-ae/mupen64plus-ae#644]
I'm not able to map my PS4 controller because Axis RX and RY (L2 and R2 according to controller diagnostics) are pegged to -1. Half squeeze moved them to 0. Full Squeeze moves them to +1.

Controller hash is:

c4e0bdbedcb9054305ffe57b047dbd2677d65625:054c
09cc

**Comment by Kellogg70** [comment]
Mupen64plus AE 2.4.4

**Comment by fzurita** [comment]
You are using a very old version of the app. Please try using this one:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita
