### ISSUE TITLE
Crash on first boss Star fox 64 w/ cheats enabled

### ISSUE THREAD

**Issue by Universe34** [mupen64plus-ae/mupen64plus-ae#645]
Hello all,
I just got Star Fox 64 for use on Mupen64, but when I enable every cheat, and get to the first boss of the game, the entire app crashes. Any help would be appreciated.

**Comment by fzurita** [comment]
Does it crash when you don't enable cheats?

**Comment by Universe34** [comment]
Yes

**Comment by fzurita** [comment]
Are you using Mupen64plus FZ in the play store?

**Comment by Universe34** [comment]
I am

**Comment by fzurita** [comment]
Try not enabling any cheats and then restarting the game. See if it crashes then. Cheats can introduce in-game instability.

**Comment by Universe34** [comment]
It still crashes even without cheats.

**Comment by fzurita** [comment]
Did you start the game over without cheats? It makes a difference.

Also, try switching emulation profiles, it could be an incompatibility with your device.
