### ISSUE TITLE
Utilizing the A & B Buttons Simultaneously 

### ISSUE THREAD

**Issue by OnikoDono** [mupen64plus-ae/mupen64plus-ae#646]
I have recently downloaded your emulator, which is awesome by the way, but I am having trouble utilizing certain dynamics of the app itself. For example; there is no way to hold the A button down then press the Button button simultaneously. This is a problem because I will not be able to complete the Snowhead Temple in The Legend of Zelda - Majora's Mask without utilizing this exact button sequence to "ground pound". I don't know very much about emulators and such, but is there a way to solve this rather irksome problem?

**Comment by OnikoDono** [comment]
* B Button

**Comment by fzurita** [comment]
Go to settings then touchscreen and enable button auto-hold. You can also enable it on a it gave basis by selecting the game and going to settings.

**Comment by OnikoDono** [comment]
I tried it and it worked great. Thank you sir.
