### ISSUE TITLE
Paper Mario start button freeze

### ISSUE THREAD

**Issue by allisonic1** [mupen64plus-ae/mupen64plus-ae#647]
Hey I was playing last night and everything was fine but now today when I got the start button the game freezes and crashes and also when I save on the game and on the emulator it starts me from my save last night. Help!!

**Comment by fzurita** [comment]
Did you use in game saves? If so, you can restart the game and resume from the last in-game save. If not, resume the game, open the in-game menu, and select "load from auto save" and select an earlier auto save.

**Comment by allisonic1** [comment]
Restarting worked! My hero!!!!
