### ISSUE TITLE
ps4 controller not working too good

### ISSUE THREAD

**Issue by solstice003** [mupen64plus-ae/mupen64plus-ae#650]
Hello, I have a little issue. I started to connect my ps4 controller and tried mapping it with MegaN64, but the road won't work and the c buttons don't either. I used the road for the dpad, obviously, and I tried to use the right stick on the controller for the c buttons, however the road gets no response and the c buttons only go right and down, I've been trying to solve this all day, but got nothing so far. I would like if you respond as soon as possible because I'm lost on what I am doing. Thank you for your time.

**Comment by solstice003** [comment]
This was on an android device by the way, forgot to mention.

**Comment by fzurita** [comment]
We don't support MegaN64. They just take our app, clone it, and put ads on it. Please use this app instead:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita
