### ISSUE TITLE
fatal error: 'asm_defines_gas.h' file not found

### ISSUE THREAD

**Issue by tjmille2** [mupen64plus-ae/mupen64plus-ae#651]
The current build cannot compile in the latest stable Android Studio 2.3.3. It says
fatal error: 'asm_defines_gas.h' file not found

**Comment by fzurita** [comment]
Do you have the latest Git client for windows? You need it because it has awk for Windows. You just need to add the location of awk to your path environment variable,

**Comment by tjmille2** [comment]
I'm using macOS, and yes I have the latest git client installed.

**Comment by fzurita** [comment]
Ok, is awk park of your path environment variable? For example, can you open up a terminal window and type "awk" and not get an error about the command not being found?

**Comment by tjmille2** [comment]
Thanks for the clarification. My machine has awk on it but not gawk, I will try again with gawk installed.

**Comment by tjmille2** [comment]
Simply changing gawk to awk in mupen64plus-core.mk lets the project compile without problems.
