### ISSUE TITLE
Pokemon snap

### ISSUE THREAD

**Issue by lipeon** [mupen64plus-ae/mupen64plus-ae#653]
BUG fix in photos, dont work

**Comment by fzurita** [comment]
Try the GLideN64-Medium Emulation profile. It has better support for that game.

**Comment by lipeon** [comment]
Same , i cant see the photos on the end of run

**Comment by fzurita** [comment]
What device do you have?

**Comment by lipeon** [comment]
K6 plus lenovo

**Comment by fzurita** [comment]
You will have to create a custom GLideN64 Emulation profile. I would take the GLideN64-Medium and create a copy. In the copy, enable "Copy color buffer to RDRAM" and set it to Async.

**Comment by lipeon** [comment]
Little better, but when select Photo, dont open

**Comment by fzurita** [comment]
What do you mean by it doesn't open?

**Comment by lipeon** [comment]
Ok, Now I got it working. But not  ASYNC works well on SYNC mode.

but both slowdown emulation

**Comment by fzurita** [comment]
Yeah, that's what I would expect. Unfortunately, those can't be sped up, and it's the only way to get those games to work correctly.

**Comment by lipeon** [comment]
Needs a Quick option on site bar Lock/unlock that option

**Comment by fzurita** [comment]
It can't be changed while in game unfortunately. Soon (months?), the FBInfo API will be implemented and this will become a non issue.
