### ISSUE TITLE
Configuring axis deadzone for button mappings

### ISSUE THREAD

**Issue by loganmc10** [mupen64plus-ae/mupen64plus-ae#654]
Maybe I am missing it, but would it be possible to add an option to configure the deadzone for axis->button mappings?

For instance, usually the right analog stick is mapped to the c-buttons. I'm playing Rogue Squadron right now and I often find myself pressing the wrong c-button. It would be helpful to be able to configure a really high deadzone for the c-button mapped axis, but I wouldn't want that same deadzone for the left analog stick.

**Comment by fzurita** [comment]
That's a good point. There is no dead zone option right now for buttons mapped to analog axis.

I don't think I want to add an option, so I'll make the dead zone really high, like 50%.

**Comment by loganmc10** [comment]
Yeah I think that would be good, it's not as noticeable when the c buttons are just controlling the camera or something, but when they all performance distinct functions it can get frustrating lol

**Comment by fzurita** [comment]
So looking through the code, it seems like for buttons that use analog axis in a controller, we already have a dead zone set to 0.5. I guess I can make it larger. If you want to experiment, you can always modify:
```
    public static final float STRENGTH_THRESHOLD = 0.5f;
```

in AbstractProvider.java.

**Comment by loganmc10** [comment]
I would think 50% should be good, I could have sworn it was more sensitive than that but perhaps I've just become really sloppy when using an axis. Thanks for looking into it
