### ISSUE TITLE
Does anyone know how to fix the Wcw vs n

### ISSUE THREAD

**Issue by DjSheepz** [mupen64plus-ae/mupen64plus-ae#655]

**Comment by fzurita** [comment]
What problem do you have?

**Comment by DjSheepz** [comment]
Nwo revenge on mupen64 wii???

**Comment by fzurita** [comment]
I mean, what needs to be fixed?

**Comment by DjSheepz** [comment]
I accidentally pushed submit

**Comment by DjSheepz** [comment]
But it’s a black screen and won’t let me play it

**Comment by DjSheepz** [comment]
The sounds there but not the visual

**Comment by fzurita** [comment]
Ok, what version of the app are you using?

**Comment by DjSheepz** [comment]
Ummmmm

**Comment by DjSheepz** [comment]
Lemme check

**Comment by DjSheepz** [comment]
Lemme check

**Comment by fzurita** [comment]
Mupen64plus-AE or Mupen64plus FZ?

**Comment by DjSheepz** [comment]
How can I tell

**Comment by fzurita** [comment]
Where did you get it from?

**Comment by DjSheepz** [comment]
Wiibrew.org

**Comment by DjSheepz** [comment]
Sry about not knowing these tings

**Comment by fzurita** [comment]
Ok, can you download the version directly from the play store? It's the latest: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by DjSheepz** [comment]
Ok

**Comment by DjSheepz** [comment]
Will it work for Wii?

**Comment by DjSheepz** [comment]
Cause that’s what I’m looking for

**Comment by fzurita** [comment]
No, it won't. You are on the GitHub page for the Android version of Mupen64plus.

**Comment by DjSheepz** [comment]
Oh how could I get to the wii one

**Comment by DjSheepz** [comment]
Whoops

**Comment by DjSheepz** [comment]
sry for wasting your time

**Comment by fzurita** [comment]
I wouldn't be able to tell you where to find off the top of my head. I would try Google.

**Comment by DjSheepz** [comment]
Mmmk
