### ISSUE TITLE
Doesn't run rom

### ISSUE THREAD

**Issue by Lred247** [mupen64plus-ae/mupen64plus-ae#656]
Hi you guys... I've been trying to play Turok games specially 2 and 3 ...and when I start them...well, they just won't run... Any help?

**Comment by fzurita** [comment]
Have you tried the latest version on the play store? 

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Lred247** [comment]
Thanks for answering my call men...I just download the app from the
link... And still won't run... Have you tried to play those?

**Comment by fzurita** [comment]
Yeah, I have. They work fine on my device. What kind of device do you have?

**Comment by Lred247** [comment]
I got it on my cell phone... It's a Lenovo k5... It's weird... Cos all the
other games run just ok... You think it's my phone?

**Comment by fzurita** [comment]
I don't know if it's your phone. Can you tell me exactly what happens when you start the game? Do you get a black screen or does the game quit itself?

**Comment by Lred247** [comment]
It's just a black screen.... And it stays that way... That happens only
with those 2 games... Turok 2 AND Turok 3

**Comment by fzurita** [comment]
Have you tried restarting the game instead of resuming?

**Comment by Lred247** [comment]
Yeah... Same result... I have download different roms from different
sites... Unzipped the files from the app and before on my laptop, then
setting it back again on the SD card... And still black screen

**Comment by fzurita** [comment]
Ok, it's possible that your phone's GPU is having issues with the Glide64 plugin. 

Ok, try this: select the game, go to settings, and change the emulation profile GLideN64-Medium.

**Comment by Lred247** [comment]
Nop.... Same issue...

**Comment by fzurita** [comment]
Ok, can you share your logcat? Start the game until you get the black screen then exit. Open up the side bar then go to tools and choose logcat. Then select share and send it to my email.

**Comment by Lred247** [comment]
That log cat it's from the other version...the one that you send me says
this

**Comment by fzurita** [comment]
The Mupen64plus-FZ version should have a way to access the logcat by going to tools, them logcat.

**Comment by Lred247** [comment]
I did... This is what happens...

**Comment by fzurita** [comment]
I don't see anything.

**Comment by Lred247** [comment]
It's nothing attached?

**Comment by fzurita** [comment]
No, because you are replying to the GitHub email, not my personal email. You can also login to GitHub and create the attachment there.

**Comment by Lred247** [comment]
Well it says that unfortunately Mupen64 has stopped...

**Comment by fzurita** [comment]
Gotcha. A lot of people seem to have that problem when they try to view the logcat. I haven't quite figured out the issue yet.

That doesn't leave me with many options to try to figure out the issue in your case.

I would to a different ROM image of Turok 2 and Turok 3. That's all I can think of.

**Comment by Lred247** [comment]
All right...thank you so much for your time and help...I hope you can make
it work...good day...

**Comment by Lred247** [comment]
--------- beginning of main
[ 12-25 19:53:28.659 18688:18688 I/Timeline ]: Timeline:
Activity_launch_request id:org.mupen64plusae.v3.fzurita time:888942

[ 12-25 19:53:28.736 18688:18688 E/MogaHack ]: Somebody is trying to
intercept our intent. Disabling MOGA controller for security.

[ 12-25 19:53:28.767 18688:18688 D/wangcy9  ]: setStatusIcon occur wrong
theme!

[ 12-25 19:53:28.817 18688:18688 I/ViewRootImpl ]: CPU Rendering VSync
enable = true

[ 12-25 19:53:29.083 18688:18688 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@2e830fe8 time:889366

[ 12-25 19:53:49.938 18688:18688 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@36a7f6bf time:910220

[ 12-25 19:53:52.439 18688:18688 I/Timeline ]: Timeline:
Activity_launch_request id:org.mupen64plusae.v3.fzurita time:912722

[ 12-25 19:53:52.577 18688:18688 D/wangcy9  ]: setStatusIcon occur wrong
theme!

[ 12-25 19:53:52.598 18688:18688 I/ViewRootImpl ]: CPU Rendering VSync
enable = true

[ 12-25 19:53:52.723 18688:18688 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@3c0cb9f0 time:913006

[ 12-25 19:53:52.775 18688:18718 D/OpenGLRenderer ]: endAllStagingAnimators
on 0xaba4a748 (MenuListView) with handle 0xab6e1b48

[ 12-25 19:53:58.334 18688:18688 D/wangcy9  ]: setStatusIcon occur wrong
theme!

[ 12-25 19:53:58.379 18688:18688 I/ViewRootImpl ]: CPU Rendering VSync
enable = true

[ 12-25 19:54:01.113 18688:18718 D/OpenGLRenderer ]: endAllStagingAnimators
on 0xabc3f130 (RippleDrawable) with handle 0xabc86558

[ 12-25 19:54:05.538 18688:18688 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@36a7f6bf time:925821

[ 12-25 19:54:12.463 18688:18688 I/Timeline ]: Timeline:
Activity_launch_request id:org.mupen64plusae.v3.fzurita time:932746

[ 12-25 19:54:12.501 18688:18688 D/wangcy9  ]: setStatusIcon occur wrong
theme!

This is the catlog from Turok 2... Still can't make it run :(

**Comment by fzurita** [comment]
Hello. That is the logcat from before you actually started Turok 2. Can you try again to start the game, then exit it? Then go to tools then logcat, then hit share.

**Comment by Lred247** [comment]
--------- beginning of main
[ 12-25 20:57:57.288 29951:30029 I/qdutils  ]: PartialUpdate status:
Disabled

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Left Align: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Width Align: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Top Align: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Height Align: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Min ROI Width: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Min ROI Height: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Needs ROI Merge: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Dynamic Fps: Disabled

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Min Panel fps: 0

[ 12-25 20:57:57.289 29951:30029 I/qdutils  ]: Max Panel fps: 0

[ 12-25 20:57:57.356 29951:29951 I/GameActivity ]: surfaceCreated

[ 12-25 20:57:57.356 29951:29951 I/GameActivity ]: surfaceChanged

[ 12-25 20:57:57.356 29951:29951 I/CoreFragment ]: setSurface

[ 12-25 20:57:57.357 29951:29951 I/CoreFragment ]: startCore

[ 12-25 20:57:57.357 29951:29951 W/Adreno-EGL ]:
<qeglDrvAPI_eglBindAPI:2282>: EGL_BAD_PARAMETER

[ 12-25 20:57:57.433 29951:29951 I/NativeConfigFile ]: param=AspectRatio
value=0

[ 12-25 20:57:57.433 29951:29951 I/NativeConfigFile ]:
param=ForcePolygonOffset value=True

[ 12-25 20:57:57.433 29951:29951 I/NativeConfigFile ]:
param=PolygonOffsetFactor value=-3.0

[ 12-25 20:57:57.433 29951:29951 I/NativeConfigFile ]:
param=PolygonOffsetUnits value=-3.0

[ 12-25 20:57:57.433 29951:29951 I/NativeConfigFile ]: param=CropMode
value=1

[ 12-25 20:57:57.434 29951:29951 I/NativeConfigFile ]: param=MultiSampling
value=0

[ 12-25 20:57:57.434 29951:29951 I/NativeConfigFile ]: param=bilinearMode
value=0

[ 12-25 20:57:57.434 29951:29951 I/NativeConfigFile ]: param=MaxAnisotropy
value=0

[ 12-25 20:57:57.434 29951:29951 I/NativeConfigFile ]: param=EnableNoise
value=True

[ 12-25 20:57:57.435 29951:29951 I/NativeConfigFile ]: param=EnableLOD
value=True

[ 12-25 20:57:57.435 29951:29951 I/NativeConfigFile ]:
param=EnableHWLighting value=False

[ 12-25 20:57:57.435 29951:29951 I/NativeConfigFile ]:
param=CorrectTexrectCoords value=0

[ 12-25 20:57:57.436 29951:29951 I/NativeConfigFile ]:
param=EnableNativeResTexrects value=False

[ 12-25 20:57:57.436 29951:29951 I/NativeConfigFile ]:
param=EnableLegacyBlending value=True

[ 12-25 20:57:57.436 29951:29951 I/NativeConfigFile ]:
param=EnableFragmentDepthWrite value=False

[ 12-25 20:57:57.437 29951:29951 I/NativeConfigFile ]:
param=EnableBlitScreenWorkaround value=False

[ 12-25 20:57:57.437 29951:29951 I/NativeConfigFile ]:
param=EnableFBEmulation value=True

[ 12-25 20:57:57.438 29951:29951 I/NativeConfigFile ]: param=BufferSwapMode
value=2

[ 12-25 20:57:57.438 29951:29951 I/NativeConfigFile ]:
param=EnableCopyColorToRDRAM value=0

[ 12-25 20:57:57.438 29951:29951 I/NativeConfigFile ]:
param=EnableCopyAuxiliaryToRDRAM value=False

[ 12-25 20:57:57.439 29951:29951 I/NativeConfigFile ]:
param=EnableCopyDepthToRDRAM value=2

[ 12-25 20:57:57.439 29951:29951 I/NativeConfigFile ]:
param=EnableCopyColorFromRDRAM value=False

[ 12-25 20:57:57.440 29951:29951 I/NativeConfigFile ]:
param=EnableN64DepthCompare value=False

[ 12-25 20:57:57.441 29951:29951 I/NativeConfigFile ]:
param=UseNativeResolutionFactor value=0

[ 12-25 20:57:57.442 29951:29951 I/NativeConfigFile ]: param=txFilterMode
value=0

[ 12-25 20:57:57.442 29951:29951 I/NativeConfigFile ]:
param=txEnhancementMode value=0

[ 12-25 20:57:57.443 29951:29951 I/NativeConfigFile ]: param=txDeposterize
value=False

[ 12-25 20:57:57.443 29951:29951 I/NativeConfigFile ]:
param=txFilterIgnoreBG value=True

[ 12-25 20:57:57.444 29951:29951 I/NativeConfigFile ]: param=txCacheSize
value=128

[ 12-25 20:57:57.444 29951:29951 I/NativeConfigFile ]: param=txHiresEnable
value=False

[ 12-25 20:57:57.445 29951:29951 I/NativeConfigFile ]: param=txPath
value=/storage/sdcard0/mupen64plus-fz/CoreConfig/UserData/mupen64plus/hires_texture/

[ 12-25 20:57:57.446 29951:29951 I/NativeConfigFile ]:
param=txHiresFullAlphaChannel value=False

[ 12-25 20:57:57.446 29951:29951 I/NativeConfigFile ]:
param=txCacheCompression value=True

[ 12-25 20:57:57.447 29951:29951 I/NativeConfigFile ]: param=txForce16bpp
value=False

[ 12-25 20:57:57.448 29951:29951 I/NativeConfigFile ]: param=txSaveCache
value=False

[ 12-25 20:57:57.448 29951:29951 I/NativeConfigFile ]: param=txHresAltCRC
value=False

[ 12-25 20:57:57.449 29951:29951 I/NativeConfigFile ]: param=fontName
value=DroidSans.ttf

[ 12-25 20:57:57.450 29951:29951 I/NativeConfigFile ]: param=fontSize
value=18

[ 12-25 20:57:57.451 29951:29951 I/NativeConfigFile ]: param=fontColor
value=B5E61D

[ 12-25 20:57:57.453 29951:29951 I/NativeConfigFile ]:
param=ForceGammaCorrection value=False

[ 12-25 20:57:57.456 29951:29951 I/NativeConfigFile ]:
param=GammaCorrectionLevel value=1.0

[ 12-25 20:57:57.561 29951:29951 E/ConfigFile ]: IOException creating file
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg, error message:
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg: open failed:
ENOENT (No such file or directory)

[ 12-25 20:57:57.561 29951:29951 I/CoreFragment ]: actuallyStartCore

[ 12-25 20:57:57.726 29951:29951 I/GameActivity ]: onWindowFocusChanged:
true

[ 12-25 20:57:57.758 29951:29951 W/linker   ]: libae-exports.so: unused DT
entry: type 0x6ffffffe arg 0x1074

[ 12-25 20:57:57.758 29951:29951 W/linker   ]: libae-exports.so: unused DT
entry: type 0x6fffffff arg 0x2

[ 12-25 20:57:57.758 29951:29951 W/linker   ]: libae-vidext.so: unused DT
entry: type 0x6ffffffe arg 0x3020

[ 12-25 20:57:57.758 29951:29951 W/linker   ]: libae-vidext.so: unused DT
entry: type 0x6fffffff arg 0x3

[ 12-25 20:57:57.759 29951:29951 W/linker   ]: libc++_shared.so: unused DT
entry: type 0x6ffffffe arg 0x2b244

[ 12-25 20:57:57.759 29951:29951 W/linker   ]: libc++_shared.so: unused DT
entry: type 0x6fffffff arg 0x2

[ 12-25 20:57:57.759 29951:29951 W/linker   ]: libae-imports.so: unused DT
entry: type 0x6ffffffe arg 0x5e8

[ 12-25 20:57:57.759 29951:29951 W/linker   ]: libae-imports.so: unused DT
entry: type 0x6fffffff arg 0x2

[ 12-25 20:57:57.768 29951:29951 I/ae-bridge ]: Loading native libraries

[ 12-25 20:57:57.768 29951:29951 W/linker   ]: libmupen64plus-core.so:
unused DT entry: type 0x6ffffffe arg 0x2650

[ 12-25 20:57:57.769 29951:29951 W/linker   ]: libmupen64plus-core.so:
unused DT entry: type 0x6fffffff arg 0x3

[ 12-25 20:57:57.771 29951:29951 W/linker   ]: libSDL2.so: unused DT entry:
type 0x6ffffffe arg 0xb7d4

[ 12-25 20:57:57.771 29951:29951 W/linker   ]: libSDL2.so: unused DT entry:
type 0x6fffffff arg 0x3

[ 12-25 20:57:57.777 29951:29951 W/linker   ]:
libmupen64plus-ui-console.so: unused DT entry: type 0x6ffffffe arg 0x1588

[ 12-25 20:57:57.777 29951:29951 W/linker   ]:
libmupen64plus-ui-console.so: unused DT entry: type 0x6fffffff arg 0x2

[ 12-25 20:57:57.778 29951:29951 I/ae-bridge ]: Android_JNI_InitImports()

[ 12-25 20:57:57.863 29951:29951 I/ae-bridge ]: setNativeWindow: New
surface has been set

[ 12-25 20:57:57.864 29951:29951 I/CoreService ]: setCoreServiceListener

[ 12-25 20:57:57.864 29951:29951 I/GameActivity ]: onCoreServiceStarted

[ 12-25 20:57:57.865 29951:29951 W/linker   ]:
libmupen64plus-input-android.so: unused DT entry: type 0x6ffffffe arg 0xfcc

[ 12-25 20:57:57.865 29951:29951 W/linker   ]:
libmupen64plus-input-android.so: unused DT entry: type 0x6fffffff arg 0x1

[ 12-25 20:57:57.876 29951:29951 I/CoreFragment ]: getCurrentSpeed

[ 12-25 20:57:57.876 29951:29951 I/CoreFragment ]: getSlot

[ 12-25 20:57:57.988 29951:30034 I/input-android ]: init()

[ 12-25 20:57:57.991 29951:29951 I/CoreFragment ]: getFramelimiter

[ 12-25 20:57:57.993 29951:30034 E/CoreService ]: Pak type=2

[ 12-25 20:57:57.993 29951:30034 I/CoreService ]: emuStar args:

[ 12-25 20:57:57.993 29951:30034 I/CoreService ]: mupen64plus

[ 12-25 20:57:57.993 29951:30034 I/CoreService ]: --corelib

[ 12-25 20:57:57.993 29951:30034 I/CoreService ]:
/data/data/org.mupen64plusae.v3.fzurita/lib//libmupen64plus-core.so

[ 12-25 20:57:57.993 29951:30034 I/CoreService ]: --configdir

[ 12-25 20:57:57.994 29951:30034 I/CoreService ]:
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig

[ 12-25 20:57:57.994 29951:30034 I/CoreService ]: --nospeedlimit

[ 12-25 20:57:57.994 29951:30034 I/CoreService ]: --cheats

[ 12-25 20:57:57.994 29951:30034 I/CoreService ]:

[ 12-25 20:57:57.994 29951:30034 I/CoreService ]: /storage/sdcard0/64
games/Turok 2 - Seeds of Evil (Europe) (Esp).n64

[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]:  __
__                         __   _  _   ____  _


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]: |  \/  |_   _ _ __   ___ _
__  / /_ | || | |  _ \| |_   _ ___


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]: | |\/| | | | | '_ \ / _ \
'_ \| '_ \| || |_| |_) | | | | / __|


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]: | |  | | |_| | |_) |  __/
| | | (_) |__   _|  __/| | |_| \__ \


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]: |_|  |_|\__,_| .__/
\___|_| |_|\___/   |_| |_|   |_|\__,_|___/


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]:              |_|
http://code.google.com/p/mupen64plus/


[ 12-25 20:57:57.994 29951:30034 V/UI-Console ]: Mupen64Plus Console
User-Interface Version 2.5.0



[ 12-25 20:57:57.995 29951:29951 I/CoreFragment ]: isShuttingDown

[ 12-25 20:57:57.995 29951:29951 I/CoreFragment ]: resumeEmulator

[ 12-25 20:57:57.996 29951:30034 I/UI-Console ]: attached to core library
'Mupen64Plus Core' version 2.5.1

[ 12-25 20:57:57.996 29951:30034 I/UI-Console ]:             Includes
support for Dynamic Recompiler.

[ 12-25 20:57:58.068 29951:29951 I/CoreFragment ]: pauseEmulator

[ 12-25 20:57:58.093 29951:30034 I/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg'.  Using
defaults.

[ 12-25 20:57:58.093 29951:30034 W/Core     ]: No version number in 'Core'
config section. Setting defaults.

[ 12-25 20:57:58.170 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:57:58.170 29951:30034 W/Core     ]: No version number in
'CoreEvents' config section. Setting defaults.

[ 12-25 20:57:58.236 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:57:58.236 29951:30034 I/Core     ]: Using full mem base

[ 12-25 20:57:58.236 29951:30034 E/Core     ]: Unable to open rom database
file '(null)'.

[ 12-25 20:57:58.236 29951:30034 W/UI-Console ]: No version number in
'UI-Console' config section. Setting defaults.

[ 12-25 20:57:58.314 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:57:58.389 29951:29951 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@91e409b time:2719338

[ 12-25 20:57:58.428 29951:29951 I/CoreFragment ]: resumeEmulator

[ 12-25 20:57:58.458 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:57:58.523 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Goodname: Turok 2: Seeds of
Ev (unknown rom)

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Name: Turok 2: Seeds of Ev

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: MD5:
144B10A484A22367FD2679529DBD2FED

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: CRC: 2E0E7749 B8B49D59

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Imagetype: .v64 (byteswapped)

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Rom size: 33554432 bytes (or
32 Mb or 256 Megabits)

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Version: 1444

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Manufacturer: Nintendo

[ 12-25 20:57:59.287 29951:30034 I/Core     ]: Country: Europe (0x58)

[ 12-25 20:57:59.295 29951:30034 D/UI-Console ]: Cheat codes disabled.

[ 12-25 20:57:59.295 29951:30034 I/UI-Console ]: using Video plugin: <dummy>

[ 12-25 20:57:59.295 29951:30034 I/UI-Console ]: using Audio plugin: <dummy>

[ 12-25 20:57:59.295 29951:30034 I/UI-Console ]: using Input plugin: <dummy>

[ 12-25 20:57:59.295 29951:30034 I/UI-Console ]: using RSP plugin: <dummy>

[ 12-25 20:57:59.295 29951:30034 W/Core     ]: No video plugin attached.
There will be no video output.

[ 12-25 20:57:59.295 29951:30034 W/Core     ]: No RSP plugin attached.  The
video output will be corrupted.

[ 12-25 20:57:59.295 29951:30034 W/Core     ]: No audio plugin attached.
There will be no sound output.

[ 12-25 20:57:59.295 29951:30034 W/Core     ]: No input plugin attached.
You won't be able to control the game.

[ 12-25 20:57:59.347 29951:30034 I/Core     ]: Game controller 0 (Standard
controller) has nothing plugged in

[ 12-25 20:57:59.348 29951:30034 I/Core     ]: Using CIC type X102

[ 12-25 20:57:59.356 29951:30034 I/Core     ]: Initializing 4 RDRAM modules
for a total of 8 MB

[ 12-25 20:57:59.364 29951:30034 I/Core     ]: Starting R4300 emulator:
Dynamic Recompiler

[ 12-25 20:57:59.369 29951:30034 I/Core     ]: Init new dynarec

[ 12-25 20:57:59.377 29951:30034 I/Core     ]: ARM CPU Features:, Half,
Thumb, FastMult, VFP, ESDP, NEON, VFPv3, TLS, VFPv4, IDIVa, IDIVt

[ 12-25 20:58:00.926 29951:29951 I/CoreFragment ]: pauseEmulator

[ 12-25 20:58:00.926 29951:29951 D/Core     ]: Emulation paused.

[ 12-25 20:58:00.982 29951:29951 I/CoreFragment ]: getCurrentSpeed

[ 12-25 20:58:00.982 29951:29951 I/CoreFragment ]: getSlot

[ 12-25 20:58:00.982 29951:29951 I/CoreFragment ]: getFramelimiter

[ 12-25 20:58:01.406 29951:29951 I/CoreFragment ]: pauseEmulator

[ 12-25 20:58:01.471 29951:29951 I/CoreFragment ]: getCurrentSpeed

[ 12-25 20:58:01.472 29951:29951 I/CoreFragment ]: getSlot

[ 12-25 20:58:01.472 29951:29951 I/CoreFragment ]: getFramelimiter

[ 12-25 20:58:04.069 29951:30034 I/ae-bridge ]: VidExtFuncGLSwapBuf: New
surface has been detected

[ 12-25 20:58:04.069 29951:30034 E/libEGL   ]: validate_display:255 error
3008 (EGL_BAD_DISPLAY)

[ 12-25 20:58:04.069 29951:30034 E/ae-bridge ]: eglCreateWindowSurface()
returned error 12296

[ 12-25 20:58:06.341 29951:29951 I/CoreFragment ]: exit

[ 12-25 20:58:06.434 29951:29951 D/wangcy9  ]: setStatusIcon occur wrong
theme!

[ 12-25 20:58:06.480 29951:29951 I/ViewRootImpl ]: CPU Rendering VSync
enable = true

[ 12-25 20:58:06.608 29951:29951 I/GameActivity ]: onWindowFocusChanged:
false

[ 12-25 20:58:07.280 29951:29951 I/CoreFragment ]: onPromptDialogClosed

[ 12-25 20:58:07.280 29951:29951 I/GameActivity ]: onExitRequested

[ 12-25 20:58:07.280 29951:29951 I/GameActivity ]: shutdownEmulator

[ 12-25 20:58:07.291 29951:29951 I/CoreFragment ]: autoSaveState

[ 12-25 20:58:07.292 29951:29951 D/Core     ]: Emulation continued.

[ 12-25 20:58:07.343 29951:29951 I/CoreService ]: Saving file:
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/AutoSaves/2017-12-25-20-58-07.v2.sav

[ 12-25 20:58:07.349 29951:29951 I/CoreFragment ]: setCoreEventListener

[ 12-25 20:58:07.350 29951:29951 I/CoreFragment ]: destroySurface

[ 12-25 20:58:07.350 29951:29951 I/ae-bridge ]: emuDestroySurface: Deleting
surface

[ 12-25 20:58:07.409 29951:30034 D/Core     ]: Could not open state file:
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/AutoSaves/2017-12-25-20-58-07.v2.sav

[ 12-25 20:58:07.417 29951:30034 E/CoreService ]: Unable to save file due
to file write failure: /storage/sdcard0/mupen64plus-fz/GameData/Turok 2:
Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/AutoSaves/2017-12-25-20-58-07.v2.sav

[ 12-25 20:58:07.442 29951:30029 D/OpenGLRenderer ]: endAllStagingAnimators
on 0xab9c4db0 (RippleDrawable) with handle 0xab797c20

[ 12-25 20:58:07.468 29951:30034 D/Core     ]: Stopping emulation.

[ 12-25 20:58:07.490 29951:30034 I/Core     ]: R4300 emulator finished.

[ 12-25 20:58:07.500 29951:30034 D/Core     ]: Rom closed.

[ 12-25 20:58:07.582 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:58:07.663 29951:30034 E/Core     ]: Couldn't open configuration
file '/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/CoreConfig/mupen64plus.cfg' for writing.

[ 12-25 20:58:07.675 29951:30034 I/CoreFragment ]: onFinish

[ 12-25 20:58:07.683 29951:30034 I/Process  ]: Sending signal. PID: 29951
SIG: 9

[ 12-25 20:58:07.770 18688:18688 I/Timeline ]: Timeline: Activity_idle id:
android.os.BinderProxy@34f8f5e7 time:2728719

[ 12-25 20:58:21.739 18688:18688 I/Timeline ]: Timeline:
Activity_launch_request id:org.mupen64plusae.v3.fzurita time:2742688

[ 12-25 20:58:21.784 18688:18688 D/wangcy9  ]: setStatusIcon occur wrong
theme!

**Comment by fzurita** [comment]
Ok, the problem looks very simple. The app is unable to create a config file for that game. Did you give the app storage permissions?  Can you try deleting this folder?

/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/

**Comment by fzurita** [comment]
If we are unable to write to the SD Card, we will now show an error and stop the emulator:
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/6302b82dbf69330980410301ec4ad9af15f4226c

**Comment by Lred247** [comment]
How do I give permission to the app?  I couldn't found the file that you
ask me to delete...

**Comment by fzurita** [comment]
That means that the app is unable to create the folder. To add permissions, go to your phone settings, then applications, select mupen64plus FZ, select permissions, make sure storage permission is selected.

**Comment by fzurita** [comment]
You may want to try deleting the ```/storage/sdcard0/mupen64plus-fz/``` folder from your phone. Backup data in there that you may think is important of course.

**Comment by Lred247** [comment]
I deleted the files that you ask me... And I set the permissions for the
app but still can't make it work...

**Comment by fzurita** [comment]
Can you try using a file manager app and try creating this folder manually?
/storage/sdcard0/mupen64plus-fz/GameData/Turok 2: Seeds of Ev (E)
144B10A484A22367FD2679529DBD2FED/
What happens?

**Comment by Lred247** [comment]
I couldn't create the file... It appears a legend that says that I cannot
write a serial of a signs or characters... I'll keep trying do...

Could it be the ROM I download?
Maybe you can pass me the one you have...

**Comment by fzurita** [comment]
It's not the ROM, I can create that folder just fine. Can you tell me which characters it can't create?

**Comment by fzurita** [comment]
It almost sounds like your phone's internal storage is formatted as fat32.

**Comment by Lred247** [comment]
I thought the files were being stored in the SD card, not the internal
storage...

If is FAT3... What do I do?

On Jan 17, 2018 05:42, "Francisco Zurita" <notifications@github.com> wrote:

It almost sounds like your phone's internal storage is formatted as fat32.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/656#issuecomment-358292729>,
or mute the thread

**Comment by fzurita** [comment]
/sdcard0 should be your internal storage, at least that's what Android reported to the app. This app can only store save data to internal storage. If your internal storage is really formatted as fat32, there is nothing you can do. The app just won't work with certain ROMs that have invalid fat32 characters in the ROM good name.

**Comment by fzurita** [comment]
So, I made a workaround, if we are unable to create a path name for a ROM, we will create an alternate name. Let me know if that works for you.

**Comment by Lred247** [comment]
Dude..  you are a genius... It did work.  I just run the game and it seems
it's ok... Have some glitches, but it's ok...at least I can play it...
Thank you so much for your support and effort... You really makes us
remember the good time we had playing these games... Thank you.
