### ISSUE TITLE
Wheres the C button!??

### ISSUE THREAD

**Issue by sonnytheloler** [mupen64plus-ae/mupen64plus-ae#657]
i cant see it. Please Help!

**Comment by fzurita** [comment]
There is no C button. There is C up, C down, C left, and C right.

**Comment by sonnytheloler** [comment]
but how do i do that?

**Comment by fzurita** [comment]
When you use the app there are on-screen buttons.

**Comment by sonnytheloler** [comment]
Ok,i know that,and sorry for spamming. But,in Ocarina of time,a guy asked
to sell him stuff with the c button. How do i do that,when there is no C
button?

Again,sorry for spamming.

**Comment by fzurita** [comment]
No problem about spamming. You are asking a question about a specific game, not about the emulator. But any way, here is how you do it.

Open up the pause menu, go to your inventory, assign an item to one of your C buttons. Use that C button to be talk to that guy.

**Comment by sonnytheloler** [comment]
oooh,that is how it is doing! thanks!
