### ISSUE TITLE
Moga Pivot - Moga Pro 2 HID Controller Issue for Mupen64 plus FZ

### ISSUE THREAD

**Issue by salmmm22** [mupen64plus-ae/mupen64plus-ae#658]
Went to play donkey Kong 64 after several months. Suddenly, the L2 and R2 buttons had a glitch. Where Diddy flies with his fire barrels, you are supposed to hold down the L1 to fly. It used to work and now it just gets stuck as if you are clicking the L1 so he will not move in the air. NOW, I tried it with the onscreen controls and it does the exact same thing. However, switching to a button on the controller solves the problem. But I like the L1. Hope this makes sense. I also tried to reconfigure controls but no luck. Not sure why it decided to happen now after a few months back past since I last played. I am on Android 6.0.1.

**Comment by fzurita** [comment]
Were you able to resolve the issue?
