### ISSUE TITLE
Mupen64Plus FZ on Chromebook?

### ISSUE THREAD

**Issue by Jammster** [mupen64plus-ae/mupen64plus-ae#659]
Don't know how to say this, but is there a way to run Mupen64Plus FZ on a HP Chromebook 11 G4 using ARC? (no, my chromebook doesn't have the play store)

**Comment by fzurita** [comment]
I forgot to answer this earlier. I don't have a Chromebook so I don't know for sure, but I think it should work. ARC browser should have built in support for Mupen64plus-FZ, have you tried it?

**Comment by Jammster** [comment]
I believe you are confusing ARC Browser from Android Runtime for Chrome (aka ARC). But I'll try ARC Browser and see if it works.

**Comment by fzurita** [comment]
Oh, I got it now. I have no idea if it works. Let me know how it goes in
case anyone has the same question.

**Comment by Adenilson** [comment]
I'm unsure about Intel based chromebooks, but Mupen64Plus FZ for Android runs pretty well in an Acer R13 chromebook (quad-core MediaTek processor M8173C, A72@2Ghz + A53@1.7Ghz).

USB Joysticks work fine (e.g. gamecube controllers with USB adaptor) and it can run tough games in native resolution at the correct framerate.

Installing was through the regular Google Play Store.

**Comment by fzurita** [comment]
Cool!
