### ISSUE TITLE
How to run on Android Studio?

### ISSUE THREAD

**Issue by CbcWestwolf** [mupen64plus-ae/mupen64plus-ae#661]
I import this project following these steps in README.md but fail with AN ERROR:
Error:A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

It's my first time to import a project to Android Studio, please give me a hand.
And I hope that the README.md could be more  specific.

**Comment by fzurita** [comment]
The instructions in the README.md should really be all you need. I'm not sure why you are getting this error in Android Studio. Have you tried google? It works fine on my end with Windows and Linux. What OS are you running?

**Comment by fzurita** [comment]
I did a quick google search and it could be just a corrupted .gradle folder. Try deleting that folder at the root of the project:

https://stackoverflow.com/questions/39183674/java-lang-nullpointerexception-no-error-message

**Comment by CbcWestwolf** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
Yeah I've tried Google for several times but all failed at last. And I run it with Windows.



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 12/12/2017 11:16，Francisco Zurita<notifications@github.com> wrote： 


The instructions in the README.md should really be all you need. I'm not sure why you are getting this error in Android Studio. Have you tried google? It works fine on my end with Windows and Linux. What OS are you running?

**Comment by fzurita** [comment]
Did you try deleting the ".gradle" folder?

**Comment by CbcWestwolf** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
Thank you for the quick response!But I've tried this.And now I get the piece from idea.log :2017-12-12 11:21:25,536 [ thread 35]   INFO -  #git4idea.commands.GitHandler - [mupen64plus-ae] git -c core.quotepath=false rm --ignore-unmatch --cached -- .gradle/4.1/fileHashes/fileHashes.bin .gradle/4.1/fileHashes/fileHashes.lock .gradle/4.1/fileChanges/last-build.bin .gradle/buildOutputCleanup/built.bin .gradle/buildOutputCleanup/cache.properties .gradle/buildOutputCleanup/cache.properties.lock 2017-12-12 11:21:32,031 [se-915-b01]   INFO - build.invoker.GradleTaskFinder - Unable to find Gradle tasks for project 'mupen64plus-ae' using BuildMode REBUILD 2017-12-12 11:21:32,035 [se-915-b01]   INFO - ild.invoker.GradleBuildInvoker - About to execute Gradle tasks: [] 2017-12-12 11:21:50,749 [se-915-b01]   INFO - build.invoker.GradleTaskFinder - Unable to find Gradle tasks for project 'mupen64plus-ae' using BuildMode REBUILD 2017-12-12 11:21:50,749 [se-915-b01]   INFO - ild.invoker.GradleBuildInvoker - About to execute Gradle tasks: [] 2017-12-12 11:22:02,506 [se-915-b01]   INFO - ild.invoker.GradleBuildInvoker - About to execute Gradle tasks: [assemble] 2017-12-12 11:22:02,514 [ thread 35]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from E:/Android Studio/jre 2017-12-12 11:22:02,558 [ thread 35]   INFO - oject.common.GradleInitScripts - init script file sync.local.repo contents "allprojects {\n  buildscript {\n    repositories {\n      maven { url 'E:\\\\Android Studio\\\\gradle\\\\m2repository'}\n    }\n  }\n  repositories {\n      maven { url 'E:\\\\Android Studio\\\\gradle\\\\m2repository'}\n  }\n}\n" 2017-12-12 11:22:02,558 [ thread 35]   INFO - ild.invoker.GradleBuildInvoker - Build command line options: [--configure-on-demand, -Pandroid.injected.invoked.from.ide=true, --init-script, C:\Users\cbcwestwolf\AppData\Local\Temp\sync.local.repo1168.gradle] 2017-12-12 11:22:02,558 [ thread 35]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: --configure-on-demand -Pandroid.injected.invoked.from.ide=true --init-script C:\Users\cbcwestwolf\AppData\Local\Temp\sync.local.repo1168.gradle 2017-12-12 11:22:03,158 [se-915-b01]   INFO - ild.invoker.GradleBuildInvoker - Gradle build finished with 1 error(s) in 638ms 2017-12-12 11:22:45,198 [se-915-b01]   INFO - ide.actions.ShowFilePathAction - Exit code 1 



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 12/12/2017 11:17，Francisco Zurita<notifications@github.com> wrote： 


I did a quick google search and it could be just a corrupted .gradle folder. Try deleting that folder at the root of the project:
https://stackoverflow.com/questions/39183674/java-lang-nullpointerexception-no-error-message

**Comment by fzurita** [comment]
Ok, from the menus on top, try "Build"---> "Refresh Linked C++ projects"

**Comment by CbcWestwolf** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
Oh ! "Refresh Linked C++ projects" is unclickable for me ! I will try to solve this firstly.



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 12/12/2017 11:27，Francisco Zurita<notifications@github.com> wrote： 


Ok, from the menus on top, try "Build"---> "Refresh Linked C++ projects"

**Comment by fzurita** [comment]
Something is really wrong. Trying deleting your project folder completely and cloning again.

**Comment by CbcWestwolf** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
Ok, I will try this after I install NDK!I forget NDK ! Is it necessary for this project ?



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 12/12/2017 11:37，Francisco Zurita<notifications@github.com> wrote： 


Something is really wrong. Trying deleting your project folder completely and cloning again.

**Comment by fzurita** [comment]
Yes, NDK is required as stated in README.md

**Comment by CbcWestwolf** [comment]
font{
        line-height: 1.7;
    }
    ul,ol{
        list-style-position: inside;
    }


    
Yes it's a foolish mistake to miss the configuration of environment variables.But the "Refresh .." button is still unclickable. My NDK version is r14b. I will try to update NDK later.Thank you very much !



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    On 12/12/2017 11:43，Francisco Zurita<notifications@github.com> wrote： 


Yes, NDK is required as stated in README.md

**Comment by CbcWestwolf** [comment]
I am afraid that there is another error when I "Make Project":
Error:(69, 10) fatal error: 'asm_defines_gas.h' file not found.

I guess that maybe anything else necessary for the project ?

**Comment by fzurita** [comment]
Ok, you got much further. That error means that you don't have "awk" installed. If you downloaded the git app, it should already come with awk. All you have to do is add the location of awk to your PATH environment variable.

**Comment by CbcWestwolf** [comment]
Ok,I get it!
