### ISSUE TITLE
Run me through saving game data

### ISSUE THREAD

**Issue by vandamyou** [mupen64plus-ae/mupen64plus-ae#663]
How do you save games for Legend of Zelda games? I've tried the slot data save and the app keeps crashing...?

**Comment by fzurita** [comment]
When does it crash? When creating the slot save it when loading it?

**Comment by vandamyou** [comment]
When I'm trying to load the slot save. I've tried saving it as a file as well, but that gets the same crash result.

**Comment by fzurita** [comment]
Ok, are you using the latest version of the app?

**Comment by vandamyou** [comment]
Yes, just downloaded it the other day.

**Comment by fzurita** [comment]
Just to make sure. You downloaded the latest version right here, right?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by vandamyou** [comment]
Yessir.

**Comment by fzurita** [comment]
Can you post the save state here?

**Comment by fzurita** [comment]
I guess I should be more exact. In you phone, can you grab files in /sdcard/mupen64plus-fz/GameData/[Game_name] and lost them here in a zip file?

**Comment by vandamyou** [comment]
/storage/emulated/0/mupen64plus-fz for the game save folder and app data folder

**Comment by vandamyou** [comment]
my files are on my internal storage under the mupen64plus-fz folder

**Comment by fzurita** [comment]
Yes, can you post them here?

**Comment by vandamyou** [comment]
[Legend of Zelda, The - Majora's Mask (U) [!].zip](https://github.com/mupen64plus-ae/mupen64plus-ae/files/1590085/Legend.of.Zelda.The.-.Majora.s.Mask.U.zip)

**Comment by fzurita** [comment]
I was able to reproduce this issue internally. But thanks for the game data. In think a fix for this should come soon.

**Comment by fzurita** [comment]
It should be fixed now.
