### ISSUE TITLE
'asm_defines_gas.h' file not found

### ISSUE THREAD

**Issue by kurse** [mupen64plus-ae/mupen64plus-ae#664]
Trying to make the project results in 
Error:(69, 10) fatal error: 'asm_defines_gas.h' file not found on the "mupen64plus-ae\app\src\main\jni\mupen64plus-core\src\device\r4300\new_dynarec\arm\linkage_arm.S" file

**Comment by fzurita** [comment]
Do you have awk or gawk as part of the PATH environment variable?

**Comment by fzurita** [comment]
If you use windows, you can get awk from them command line git client.

**Comment by kurse** [comment]
That did the trick, but the project is still not building because of some path problems with the NDK, I guess Windows is not the best to do it, gonna switch on my Mac and hopefully get it up and running. Thanks @fzurita

**Comment by fzurita** [comment]
It builds fine in Windows for me. Although, you should have a folder like c:/workspaces to put the project. If you put it to deep, you may run into path name length issues.
