### ISSUE TITLE
Mapping Xbox One Wireless Controller Triggers

### ISSUE THREAD

**Issue by Majora-Luna** [mupen64plus-ae/mupen64plus-ae#665]
App version 2.4.4 (as reported by in-app "About")
Version code: 36 (Ditto)

Since Microsoft released an updated version of the XBone Wireless controller that has normal bluetooth built into it, playing games is really easy now. However, there seems to be an issue with the trigger buttons. Which, for clarity's sake, I mean the slender buttons that can be partially pressed (as opposed to the L/R shoulder buttons which just have a binary pressed/unpressed state)

Since the triggers appear to report a value of -1.00 when unpressed and +1.00 when pressed all the way,
 and all values in between when partially pressed (according to the diagnostics within the app.) trying to map any buttons will just have the app act/assume as if the nonzero value is what you are trying to map. While mapping, "AXIS_Z (-)" is what is shown. Unless it is pressed part of the way, then it will be "AXIS_RZ" which is what the right trigger shows up as in the diagnostics. 

Pressing buttons on the DPad will also cause "AXIS_Z (-)" to show up even though in the diagnostics it appears as "AXIS_HAT_X(or Y) (joystick)" with +1.00 when pressed. The triggers 

I used to be able to clear this by pressing another button, but now it just seems to be stuck on all the time so mapping buttons becomes impossible. 

Hopefully this isn't due to the XBone controller being designed stupidly (and thus out of the control of the developer(s) here) but I thought i'd mention this anyways. If something was unclear or more info is needed please tell me.

**Comment by fzurita** [comment]
You are using a very old version. Please try the latest version here: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Majora-Luna** [comment]
Oh, I paid a dollar for this version lol. But after switching to this new version, mapping buttons works now. "AXIS_Z (-)" still appears while mapping and won't go away, however, it is actually possible to properly map buttons before "AXIS_Z (-)" appears, including the triggers themselves. In-game (in this case, I tried with Star Fox 64 since you can just jump right into gameplay) all mapped buttons behave properly.

So uh, whoops. While googling about this "problem" I did come across FZ version but couldn't tell what actually differentiated it from AE version. 

Thanks for your help! Everything is good now.

**Comment by fzurita** [comment]
The AE version is very out of date. It's based on sources from 3 years ago. The FZ version is based on sources from just a few days ago.
