### ISSUE TITLE
[ENHANCEMENTE] - Scanline through overlay

### ISSUE THREAD

**Issue by ZacharyFoxx** [mupen64plus-ae/mupen64plus-ae#666]
Is it possible include a scanline effect using overlay, in the same way of Retroarch?

In retroarch is used a cfg file telling how the overlay will work.

For example, the scanline's overlay to wii has a cfg file called "scanlines.cfg" with this:

overlays = 1
overlay0_overlay = scanlines.png
overlay0_full_screen = true
overlay0_rect = "0.0,0.0,1.0,1.0"
overlay0_descs = 0

And the file scanline.png. Retroarch just "throw" the overlay above the game's screen and "voilà": we have scanlines without overcharges or drawbacks in emulation.

**Comment by fzurita** [comment]
Yeah, it's possibly in the same way that we draw the virtual joysticks. It's not a simple thing to do though.

**Comment by ZacharyFoxx** [comment]
Really? Ouch! =(

**Comment by fzurita** [comment]
There are now shaders available through the Shader options in the app that allow adding scan lines.
