### ISSUE TITLE
[PLUGIN] Rice - fast: frameskip problems

### ISSUE THREAD

**Issue by ZacharyFoxx** [mupen64plus-ae/mupen64plus-ae#667]
Hi,

Some games like Pilotwings have problems when we use rice vide plugin with framskip enable.

In pilotwings we can not see the pilot to choose. We have a similar problem in other games like Top Gear Rally or Top Gear Rally 2.

Could do you do something about?

**Comment by fzurita** [comment]
That is a side effect of hire frame skip works. It's skipping display lists. Unfortunately, it does break some games.
