### ISSUE TITLE
Cant change ingame speed

### ISSUE THREAD

**Issue by TheGreatfulLuvex** [mupen64plus-ae/mupen64plus-ae#668]
I change it and it shows the number i chose but the game runs just at normal speed

**Comment by fzurita** [comment]
That means that your device doesn't have enough CPU/GPU per to run it that fast.

**Comment by TheGreatfulLuvex** [comment]
But i want to run it at 10%

Am 10.02.2018 23:14 schrieb "Francisco Zurita" <notifications@github.com>:

**Comment by fzurita** [comment]
Ok, that's strange. I just tried it and it worked ok. What if you do something like 50%?

**Comment by TheGreatfulLuvex** [comment]
It says 50% in the menu but its runs on normal speed

Am 10.02.2018 23:27 schrieb "Francisco Zurita" <notifications@github.com>:

**Comment by fzurita** [comment]
Are you using this version of the app?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by TheGreatfulLuvex** [comment]
Now i do thx works out

Am 10.02.2018 23:35 schrieb "Francisco Zurita" <notifications@github.com>:
