### ISSUE TITLE
The new Tetris - directional pad

### ISSUE THREAD

**Issue by celestius0** [mupen64plus-ae/mupen64plus-ae#669]
Hey so the first thing I wanna say is awesome job on the emulator! I tried to imagine making an app that emulated the N64 and it made my head hurt. I must be missing so.ething but how do I access the directional pad? Cand seem to find a way to enable it in the options.

**Comment by celestius0** [comment]
Sorry my keypad sucks. It should have read... "I must be missing something, but, how do I access the directional pad? Can't seem to find a way to enable it in the options."

**Comment by fzurita** [comment]
Select the game, go to settings, change the touchscreen profile to "Everything".
