### ISSUE TITLE
Transfer pak configuration

### ISSUE THREAD

**Issue by Dobled4** [mupen64plus-ae/mupen64plus-ae#670]
Hello... Sorry for my English isn't good... The app now can use transfer pak, but I don't know how configurate this... I select the ROM... But in pokemon stadium reconoce the game but do not the info ... I think I have to put something in RAM.... But I don't know what... Can you help me please?

**Comment by fzurita** [comment]
You need the "sav" file from the game. This is where emulators put save data for the game. I have no idea what all the different Gameboy emulators use as an extension for the file, but pizza boy for example use "sav"

**Comment by Dobled4** [comment]
I must put the save in RAM?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
Yeah

**Comment by Dobled4** [comment]
It not work :(

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
Which ROM are you using for the transfer Pak? Which file are you using for the RAM?

**Comment by Dobled4** [comment]
This... Thanks for help

[Imagen]



[Imagen]


[Imagen]



[Imagen]





Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
I don't see your pictures.  I think you have to login to github directly to post pictures.

**Comment by Dobled4** [comment]
I cant adjuntar imagen

**Comment by fzurita** [comment]
Can you write the file names?

**Comment by Dobled4** [comment]
ROM
/Pokémon - Yellow Version (UE) [C][!].gbc
RAM
/Pokémon - Yellow Version (UE) [C][!].sav

**Comment by fzurita** [comment]
Which Gameboy emulator did the files come from? They look right, did you switch player 1 to transfer Pak?

**Comment by Dobled4** [comment]
John GBC lite
Yes I change to transfer pak

**Comment by Dobled4** [comment]
:) now it work... I can use my pokemon ... Thank u... Just I need save correctly... And in a pokemon center... Lag the gb... But I can select my pkmn in battle ... Thank

**Comment by fzurita** [comment]
No problem!
