### ISSUE TITLE
Keyboard not support more of 2 keys

### ISSUE THREAD

**Issue by NGGiovanni** [mupen64plus-ae/mupen64plus-ae#671]
please fix that, i want for game of the legend of zelda !!!

**Comment by NGGiovanni** [comment]
in the game when I press more than two keys it will not

**Comment by fzurita** [comment]
What kind of keyboard are you using?

**Comment by fzurita** [comment]
This is probably a problem with your keyboard. I have asked other users and they are able to push more than one key at once.
