### ISSUE TITLE
Fdroid

### ISSUE THREAD

**Issue by ThaChillera** [mupen64plus-ae/mupen64plus-ae#672]
Hi all,

I was hoping an updated version of Mupen64 could be put on Fdroid. AFAIK the old git (on paulscode account) was linked to Fdroid (https://f-droid.org/wiki/index.php?title=paulscode.android.mupen64plusae&redirect=no) but after the move to this git Fdroid never was updated. is it possible to do this?

**Comment by fzurita** [comment]
Yeah, probably at this point. All the proprietary libraries have been taken care of except for the moga gamepad. It could be removed for the F-droid listing.

After publishing, the main obstacle is keeping the listing to to date, which is a shore on its own.

**Comment by ThaChillera** [comment]
So AFAIK the owner is supposed to do this, or can I attempt to add it myself? Also, I've noticed that since the transfer from the paulscode repo, there hasn't been a binary release on github, what happened? it might be an idea to start releasing those too?

**Comment by fzurita** [comment]
I'll go ahead and add it to F-droid tonight.

**Comment by fzurita** [comment]
The project as currently structured is not compatible with F-droid. These are the errors I get when building for their repository:
```
ERROR: Found binary at ndkLibs/soundtouch/source/SoundTouch/.vs/SoundTouch/v15/.suo
ERROR: Found shared library at ndkLibs/libs/release/x86/libsoundtouch.so
ERROR: Found shared library at ndkLibs/libs/release/x86/libsoundtouch_fp.so
ERROR: Found shared library at ndkLibs/libs/release/x86/libSDL2.so
ERROR: Found static library at ndkLibs/libs/release/x86/libpng.a
ERROR: Found static library at ndkLibs/libs/release/x86/libEGLLoader.a
ERROR: Found shared library at ndkLibs/libs/release/x86/libfreetype.so
ERROR: Found shared library at ndkLibs/libs/release/armeabi-v7a/libsoundtouch.so
ERROR: Found shared library at ndkLibs/libs/release/armeabi-v7a/libsoundtouch_fp.so
ERROR: Found shared library at ndkLibs/libs/release/armeabi-v7a/libSDL2.so
ERROR: Found static library at ndkLibs/libs/release/armeabi-v7a/libpng.a
ERROR: Found static library at ndkLibs/libs/release/armeabi-v7a/libEGLLoader.a
ERROR: Found shared library at ndkLibs/libs/release/armeabi-v7a/libfreetype.so
ERROR: Found shared library at ndkLibs/libs/debug/x86/libsoundtouch.so
ERROR: Found shared library at ndkLibs/libs/debug/x86/libsoundtouch_fp.so
ERROR: Found shared library at ndkLibs/libs/debug/x86/libSDL2.so
ERROR: Found static library at ndkLibs/libs/debug/x86/libpng.a
ERROR: Found static library at ndkLibs/libs/debug/x86/libEGLLoader.a
ERROR: Found shared library at ndkLibs/libs/debug/x86/libfreetype.so
ERROR: Found shared library at ndkLibs/libs/debug/armeabi-v7a/libsoundtouch.so
ERROR: Found shared library at ndkLibs/libs/debug/armeabi-v7a/libsoundtouch_fp.so
ERROR: Found shared library at ndkLibs/libs/debug/armeabi-v7a/libSDL2.so
ERROR: Found static library at ndkLibs/libs/debug/armeabi-v7a/libpng.a
ERROR: Found static library at ndkLibs/libs/debug/armeabi-v7a/libEGLLoader.a
ERROR: Found shared library at ndkLibs/libs/debug/armeabi-v7a/libfreetype.so
WARNING: Found JAR file at app/libs/com.bda.controller.jar
ERROR: Could not build app org.mupen64plusae.v3.alpha: Can't build due to 25 errors while scanning
INFO: Finished
```

I would have to make those 6 open source projects part of the build structure.

**Comment by fzurita** [comment]
I can disable those errors and make a pull request in the F-droid repository according to this it seems: https://f-droid.org/en/docs/Building_Applications/

All the native libraries except for the jar file come from https://github.com/mupen64plus-ae/mupen64plus-ae-deps. So I think they should be able to make an exception.

**Comment by fzurita** [comment]
I submitted a "merge request" in the fdroid repository:

https://gitlab.com/fdroid/fdroiddata/merge_requests/3017

**Comment by fzurita** [comment]
So, there seems to be a general lack of support in their gitlab repository. Not sure how long it will take to go in.

**Comment by fzurita** [comment]
I give up on this... They haven't even replied to my questions.

**Comment by Poussinou** [comment]
Sorry for this, @fzurita. F-Droid members are very busy, and the qualified members who are able to answer your questions are even more busy...

Please reopen both this issue and the Gitlab MR, somebody could have a look later, so that your hard work on the inclusion of this app in F-Droid reach his final goal !

(ping @Rudloff)

**Comment by fzurita** [comment]
Ok, thanks :)

**Comment by fzurita** [comment]
Done! Listing should be available in a few days.

**Comment by Poussinou** [comment]
Thanks for your patience, @fzurita :)

**Comment by ThaChillera** [comment]
will transferring from the play store version to the f-droid version mean i will lose my configuration etc?

**Comment by fzurita** [comment]
Only some configuration. You can transfer save state and other ROM specific data by renaming /sdcard/mupen64plus-fz to /sdcard/mupen64plus-ae

**Comment by fzurita** [comment]
Whoops I mean, it needs to be /sdcard/mupen64plus

It will be whatever folder the app creates when it first starts up.
