### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Randomllyin** [mupen64plus-ae/mupen64plus-ae#673]
I cant use multiplayer without a controller. Very bad for SM64 multiplayer.

**Comment by fzurita** [comment]
You mean that you want netplay?

**Comment by Randomllyin** [comment]
That or using touchscreen controlls to play as 2+ players

**Comment by fzurita** [comment]
Two people in the same touchscreen would be highly impractical. The is already an issue for netplay.

**Comment by Randomllyin** [comment]
THATS NOT WHAT I MEANT

**Comment by Randomllyin** [comment]
I MEANT 1 SET OF TOUCHSCREEN CONTROLLS

**Comment by fzurita** [comment]
I'm still not quite sure what you mean. Can you give me an example?

**Comment by Randomllyin** [comment]
Like the controls are 1 set for 2+ players like
P1 only: none
P2 only: none
Both     :  Up, Down, Left, Right, A, B, D-Pad, L, R, Z, C up, C down, C left, C right, start.
