### ISSUE TITLE
Can't customise virtual controllers 

### ISSUE THREAD

**Issue by Chomuske** [mupen64plus-ae/mupen64plus-ae#675]
Everytime I try to edit my touchscreen profile it just crashes and sends me back to the library.

**Comment by fzurita** [comment]
First of all, are you using the newest version? It can be found here:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Chomuske** [comment]
The one Iam using is this one: https://play.google.com/store/apps/collection/search_results_cluster_apps?clp=ggEOCgxONjQgZW11bGF0b3I%3D:S:ANO1ljKVaJY
And I just installed it from playstore, The UI in here seems better

**Comment by fzurita** [comment]
Ok, you are probably using a clone version of our app. The one I linked above is the official one.

**Comment by Chomuske** [comment]
Oh, thankyou for the quick response. I guess I'll try out the official one.

**Comment by Chomuske** [comment]
Oh, thankyou for the quick response. I guess I'll try out the official one.
