### ISSUE TITLE
Hydro Thunder on Mupen64 Plus AE

### ISSUE THREAD

**Issue by Justintime2010** [mupen64plus-ae/mupen64plus-ae#677]
Mupen64 Plus AE is not producing audio for Hydro Thunder. The game works and the App's Audio options is enabled, but I hear nothing. Other roms work and the app produces their sound, but not for Hydro Thunder. Please help fix this issue. I'm a big fan of Hydro Thunder.

I also tried this game on other emulators and they produce the game sound, but it comes out very staticky and slow. Again, the app can run the game, but it is not processing the audio.

![screenshot_2018-04-20-17-41-13](https://user-images.githubusercontent.com/38573254/39076637-134f1c72-44c2-11e8-9ab8-2926810e2672.png)

**Comment by loganmc10** [comment]
I just tested this on my phone and it works fine, where did you get mupen64plus AE from? The on screen controls look pretty old to me (mine look newer anyway)

**Comment by fzurita** [comment]
I really wonder if the old version should be taken down. People should really migrate to the newer version.

At the same time, the are at least 10 different other cloned, Mupen64plus FZ/AE in the play store. Taking down the old AE version would lead to the clones getting more downloads. Maybe if Paul would redirect users of the old app to the new app.

**Comment by Justintime2010** [comment]
I never knew what the newer version was. plus I paid money to buy the one i showed to get rid of the ads. I'll test it out and give you an update if it is works this time.

**Comment by fzurita** [comment]
The free version never had any add.

**Comment by Justintime2010** [comment]
Any sound issues, like static or sputtering? I'm playing on a dumb-down Android Tablet known as the Samsung Galaxy Nook Tab A6 which is sold at Barnes and Nobles, so anything can happen.

At this time, I would request to keep this thread open until I feel 100% that everything works, please.

**Comment by fzurita** [comment]
The game sounds perfect to me.

**Comment by Justintime2010** [comment]
okay, it works. I hear sound. Glad I finally got the help I needed. Is this new app the only app with coming updates, or will there be new apps coming soon?

**Comment by fzurita** [comment]
This is the only app that is currently being updated.
