### ISSUE TITLE
Can't start another game due to "Saving texture cache"

### ISSUE THREAD

**Issue by Princess120** [mupen64plus-ae/mupen64plus-ae#678]
When I touch resume on my games on my mupen 64 plus FZ emulator it  want open up.  It tells me to wait saving texture cache after I I was playing paper mario at first . The game stopped it want open back up.  I think it's a bug . I can't play non of my games I had extracted.  They all are saved on the emulator.  They all ok.  The problem  is play anymore.

**Comment by fzurita** [comment]
Are you using the latest version in the play store here?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Princess120** [comment]
I'm not sure it doesn't say I installed app recently today.

**Comment by fzurita** [comment]
If you are using the latest version, drag down the notification bar, find the Mupen64plus FZ notification, expand it, and choose "exit"

**Comment by Princess120** [comment]
OK.

**Comment by Princess120** [comment]
I don't see where it says exit

**Comment by fzurita** [comment]
Do you see stop?

**Comment by Princess120** [comment]
I am on my Alcatal onetouch pop 7 LTE tablet.

**Comment by fzurita** [comment]
Do you see either "stop" or "exit" in the notification? Keep in mind that you have to touch the notification and drag it down to expand it to see those options.

**Comment by Princess120** [comment]
I don't see stop nor exit

**Comment by fzurita** [comment]
Ok, do you see the notification at all? It should have a picture of the game you were playing.

**Comment by fzurita** [comment]
If you don't see the notification at all, you should be able to start playing another game without it telling you that it's "Saving texture cache".

**Comment by Princess120** [comment]
Here's the pic of the game I was playing.  No notification .

On Apr 22, 2018 12:02 AM, "Francisco Zurita" <notifications@github.com>
wrote:

Ok, do you see the notification at all? It should have a picture of the
game you were playing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/678#issuecomment-383353744>,
or mute the thread

**Comment by Princess120** [comment]
Ok.  I tried another game too.  It still says that.

**Comment by fzurita** [comment]
Ok, that's strange. I'm not sure why that's happening to your table. Try this:
Go to your phone settings, then applications, in there find "Mupen64Plus FZ", select it, and choose "Force Stop". If you can't find that option, then try restarting your tablet.
