### ISSUE TITLE
Certain ROMs on Mupen64Plus FZ

### ISSUE THREAD

**Issue by Justintime2010** [mupen64plus-ae/mupen64plus-ae#679]
I noticed that the app doesn't support ".rar" ROMs.  Will that soon change? There is a game I want to play called "Super Mario Last Impact", but the updated version is a .rar file.

I found a z64 version of the game, but it isn't the updated version and it's a bit buggy. I tried searching for a bbp_ppf zip file that may have the patches for the game, but I can't find it anywhere.

Can anyone help?

**Comment by fzurita** [comment]
A rar file is a compressed archive. You can extract the RAR file within a computer, copy the extracted file to your phone, and have Mupen64plus FZ load that file.

There is no planned support for RAR archives within the app due to lack of open source have library to extract rar5 archives.
