### ISSUE TITLE
F1 Pole Position 64 flickers

### ISSUE THREAD

**Issue by Panderner** [mupen64plus-ae/mupen64plus-ae#680]
There is a flicker during the game

**Comment by Panderner** [comment]
Glide64 fast. glide64 accurate is no flicker

**Comment by Panderner** [comment]
And also a bug on gliden64
![screenshot_2018-04-23-21-32-06](https://user-images.githubusercontent.com/37503397/39129956-7cf3fc78-473e-11e8-9b4c-24218bc3f812.png)

**Comment by Panderner** [comment]
Can I fix upgrade menu not show

**Comment by Panderner** [comment]
![screenshot_2018-04-23-21-34-46](https://user-images.githubusercontent.com/37503397/39130033-bc5dbfa2-473e-11e8-97eb-060e60202d18.png)

**Comment by fzurita** [comment]
Ok, Glide64mk2 has a very hacky way of doing frame skip. So, whenever you use Glide64-Fast, you may experience bugs like this. 

Please report the GLideN64 issue in the GLideN64 GitHub page here:
https://github.com/gonetz/GLideN64/issues/

In there mention which phone you have.

**Comment by Panderner** [comment]
How many devices that supports glide64mk2?

**Comment by fzurita** [comment]
I couldn't give you an exact number, but most of not all devices will support Glide64mk2.

**Comment by Panderner** [comment]
Do you fixed?

**Comment by fzurita** [comment]
No, this is not really an issue with the front end. For Glide64mk2, I would make an issue here: https://github.com/mupen64plus/mupen64plus-video-glide64mk2

For GLideN64, this is already a know issue, you can only fix it by setting "Copy color buffer to RDRAM" to sync mode.
