### ISSUE TITLE
Characters don't appear 

### ISSUE THREAD

**Issue by zombozo085** [mupen64plus-ae/mupen64plus-ae#682]
Hello everyone!
I am very new to this website so I hope for the best
Anyways when I play some games like biohazard 2 (restident evil 2) characters either don't appear or are hazy 
I will attach a link to a screenshot of what I can see in the comments
Any kind of help is appreciated
Thanks!

**Comment by zombozo085** [comment]
http://imgur.com/gallery/w3Hwvq8
Here's what I see on the screen

**Comment by zombozo085** [comment]
Also here's the settings I use

**Comment by zombozo085** [comment]
http://imgur.com/gallery/DHHu4ZF

**Comment by fzurita** [comment]
Does it work if you use the default Glide64-Accurate emulation profile. What if you use GLideN64-Medium?

**Comment by zombozo085** [comment]
Hello fzurita when I use the glide64 it's a bit better but the gliden64 is very bad I can't even see the characters

**Comment by fzurita** [comment]
GLideN64 is the best for this game, but it only works well with newer phones. Also, Glide64mk2 still has many bugs with that game. I would use the RSP-HLE instead of CXD4 for that game as well.

Which phone do you have?

**Comment by loganmc10** [comment]
@fzurita RE2 would have only started working in GLideN64 as of this commit: https://github.com/mupen64plus-ae/mupen64plus-ae/commit/4bda8d96732ec86837aab223065a7f3d9b970ecd

Is the play store version updated to that commit? and @zombozo085 are you using https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita and it is up to date?

**Comment by loganmc10** [comment]
Also, if GLideN64 is used, fragment depth write needs to be enabled for this game, I'm not sure which profiles enable that

**Comment by fzurita** [comment]
Yes, the play store version has the latest GLideN64.  @zombozo085, please try the GLideN64-Accurate emulation profile, that enables the needed option for RE2 to work.

**Comment by zombozo085** [comment]
Oh well my phone just crashed when I tried the gliden64 accurate @fzurita XD welp i appreciate the help. Will ps1 emulators work with the adreno 330 chips? Because resident evil 2 is also on ps1

**Comment by fzurita** [comment]
Yes, PS1 emulators mostly render in software, so it will work.

**Comment by zombozo085** [comment]
Thank you very much!
