### ISSUE TITLE
N64Android Emulator

### ISSUE THREAD

**Issue by Princess120** [mupen64plus-ae/mupen64plus-ae#683]
I just installed it yesterday. I played 2 games so far like Legend of Zelda The majoras mask it was messing up when I got far playing. The graphic of the game turned white and black. I restarted the game and it did the same  thing.  Paper Mario was fine when I playing, the graphics was so clear and then the game started messing up. The graphic picture kept flickering like  lightning. I can't barely see. There are graphic  issues causing me not to play anymore. I had tried different Nintendo emulators.  My games messes up on there too.

**Comment by fzurita** [comment]
Also, N64Android of not distributed by us, it's a clone of Mupen64plus FZ in the play store.
