### ISSUE TITLE
DK 64 Banana Fairy Bug

### ISSUE THREAD

**Issue by aintisaword** [mupen64plus-ae/mupen64plus-ae#685]
When trying to take a picture of the banana fairy in Gloomy Galleon it is behind a set of prison bars. Normally the camera turns to a smiley-face when it can see the fairy in full View. However, in this emulater it does not recognize the fairy at all so there is no way to take a picture of it.

**Comment by fzurita** [comment]
What version of the app are you using?

**Comment by fzurita** [comment]
I hope this version: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by aintisaword** [comment]
3.0.183

**Comment by fzurita** [comment]
Ok, have you tried switching the emulation profile to GLideN64-Medium?

**Comment by aintisaword** [comment]
Angry Lion worked, just barely, but it worked. Thanks a lot.
