### ISSUE TITLE
Is there a way to map hardware keys (and or virutal keys) to system functions?

### ISSUE THREAD

**Issue by Lion4K** [mupen64plus-ae/mupen64plus-ae#686]
Like Save State and Load State?

(sorry to post it here, I don't have a clue on where to post this)

(Android Version)

**Comment by fzurita** [comment]
Yes, go to settings then input. Enable the appropriate "mappable" key. Then follow the instructions I posted in the other issue you created.

**Comment by Lion4K** [comment]
Thanks!! gonna do this now!

**Comment by Lion4K** [comment]
Worked Awesomely Thanks!!

**Comment by fzurita** [comment]
Great!
