### ISSUE TITLE
Increment Slot reversal?

### ISSUE THREAD

**Issue by Lion4K** [mupen64plus-ae/mupen64plus-ae#689]
There is the "increment slot" button to be mapped but there isn't one to "word for the opposite of increment, sorry language barrier detected" which can be very useful specially with controllers with several extra buttons that can be used to map save and load states and the slot selection. 

![image](https://user-images.githubusercontent.com/10391955/40566591-cdbf2700-6047-11e8-8009-bf2748b7b0b3.png)

**Comment by jonathanmasseurca** [comment]
Pull request https://github.com/mupen64plus-ae/mupen64plus-ae/pull/937

**Comment by jonathanmasseurca** [comment]
Merged https://github.com/mupen64plus-ae/mupen64plus-ae/pull/939
