### ISSUE TITLE
Zelda MM, Gles2n64 incorrect texturing

### ISSUE THREAD

**Issue by mudge6** [mupen64plus-ae/mupen64plus-ae#69]
There is a part of Clock Town that does not render correctly (as seen in this screenshot)
![Screenshot_2013-02-26-15-09-02-1495310099](https://f.cloud.github.com/assets/3314555/198158/3afc1116-8051-11e2-8ee3-630579015142.png)
And the rest of clock town keeps flashing.

**Comment by fzurita** [comment]
Upstream issue.
