### ISSUE TITLE
Mupen64Plus FZ (N64 Emulator) v 3.0.183 (beta) Canceling the file scanning process can damage the game in android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [mupen64plus-ae/mupen64plus-ae#691]
#### Expected behavior
Supposedly, when the user press Cancel to cancel the scanning of the file, the ability to completely cancel the scanning process should be possible, and no problems occur.

#### Actual behavior
When pressing the Cancel feature to cancel the file scanning process. The canceled is not fully working, so the game / files contained in the Folder are corrupted. CoverArt by the game, displayed corrupted / blank. And the games can not be run completely.

#### How to reproduce
* Download game N64 (ROMS), Click here to [download Super Mario (64).zip](https://drive.google.com/file/d/1usu7QhkwTmfaSuCYUfBBRwLx4CXQL3s1/view?usp=drivesdkto)
**Make sure the file is stored in the Download folder, to make it easier when selecting the target folder, before scanning file.**

* Download and install the [Mupen64Plus FZ (N64 Emulator)](https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzuritaapp) on the Play Store. 

* Launch the Mupen64Plus FZ app, you will find 3 main menu. **Options, Search, and Reload.**https://img.esteem.ws/tb10o19xp8.jpg

* Select and open Reload menu / click Reload icon (Upper circular right arrow).https://img.esteem.ws/4f49bwdl9c.jpg

* Scroll down to the download folder, open folder.https://img.esteem.ws/48a628drc5.jpg

* You should view the **Super Mario (64) [!] .zip** file in the download folder.https://img.esteem.ws/a0yooj1wj4.jpg

* Enable all available feature. Then press OK. https://img.esteem.ws/2hiyndpt38.jpg

* When the file scanning process is in progress, you must press Cancel.https://img.esteem.ws/wjlqqpgruz.jpg

 * _**You will find the problem as I have explained.**_ https://img.esteem.ws/ru5tyvpbue.jpg

**Browser:Samsung Galaxy S6 edge**
**Operating system:Nougat 7.0**

#### Recording Of The Bug
https://youtu.be/4Tndh9mgxH8

**Comment by fzurita** [comment]
Thanks for the report, very thorough.

**Comment by ammarraisafti** [comment]
Yes, you are welcome. I really enjoy this application.

**Comment by fzurita** [comment]
This should hopefully be fixed here: 390cc56831997a20b0c1b81572b50930d9037dff I won't close it until I test with the latest release.

**Comment by fzurita** [comment]
Is this fixed for you?

**Comment by fzurita** [comment]
Presumed fixed until stated otherwise.
