### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by TheGoldfish11** [mupen64plus-ae/mupen64plus-ae#694]
I am using a ThinkPad Yoga 11e Chromebook and whenever I move the mouse the keyboard doesn't work. The only way to fix this issue is the exit the game and go back into it. This is a big issue and should be fixed.

**Comment by fzurita** [comment]
Go to profiles then select profiles. In there choose, "share controller". What's happening probably is that the mouse is being detected as the first player.

**Comment by TheGoldfish11** [comment]
Thanks! It worked :)
