### ISSUE TITLE
IME mapped buttons aren't processed on some devices

### ISSUE THREAD

**Issue by behelit** [mupen64plus-ae/mupen64plus-ae#695]
If you map buttons using a keyboard IME, for example the Wii mote IME, when you start the game, the mappings stop processing. i.e. If I press jump, the wiimote IME presses KEYCODE_BUTTON_X for example, which was previously mapped to N64 button Z, but the emulator doesn't press the corresponding N64 button.

I have found this to occur on Sony and Samsung devices but not on Nexus (N6/Pixel XL) devices.

Any ideas? I will try to dig through the code or debug, but some direction would be great

**Comment by fzurita** [comment]
I'm not sure why they would be happening. You can stay by looking here: https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/game/GameActivity.java#L1004

**Comment by behelit** [comment]
Thanks, I worked it out, or at least am getting closer to the problem.
It only occurs if any additional player mapping is turned on (i.e. Player 2 toggle is on).
This causes all input handling to die once the 'emulator' part is started.
You can even go to the mapping diagnostics and see that no input is received, however, forcing the onResume (by task switching) restores it back to normal, but this doesn't work for resuming the emulator, only the non emulator UI activities.

**Comment by fzurita** [comment]
Closing due to no updates.
