### ISSUE TITLE
Save issues with Mupen 64

### ISSUE THREAD

**Issue by jnanks94** [mupen64plus-ae/mupen64plus-ae#696]
Hi there,

I was in the middle of Super Mario 64 rom when it froze - I did a hard reboot (control alt delete) and when I went back in to the emulator all my progress was gone! :O 

Is there a way to go back to my prior saved game? 

Thanks!

**Comment by fzurita** [comment]
Open the game, once the game is open, bring up the in-game menu. In there select "load from auto save".  It will show you the last 4 automatic saves.
