### ISSUE TITLE
Dualshock 4 controller not working

### ISSUE THREAD

**Issue by TheGoldfish11** [mupen64plus-ae/mupen64plus-ae#698]
When I connect my DS4 Controller to my emulator, the emulator seems to not recognise any input. I've tried using the Controller Diagnostics and nothing happens when I press a button or move the joystick. Is the DS4 controller compatible with this emulator via Bluetooth? 
Thanks

**Comment by fzurita** [comment]
The controller is compatible as long as your device has proper drivers for it. Are you able to control the Android menus using your controller?

**Comment by TheGoldfish11** [comment]
No, but I can with my Joycons surprisingly.

**Comment by fzurita** [comment]
Ok, that means that your current device doesn't have proper drivers. There is not much this app can do about that. You may have better luck if you use a USB OTG cable.

**Comment by TheGoldfish11** [comment]
Ok thanks anyway, I guess I'll just have to use other controllers.
