### ISSUE TITLE
[RELATED TO ISSUE #692] - SDL audio plugin

### ISSUE THREAD

**Issue by ZacharyFoxx** [mupen64plus-ae/mupen64plus-ae#699]
Hi,

Sorry, I took long to reply in the issue #692.

My device is the OUYA, which Tegra 3 and I´m using a custom ROM, Lineage OS 11, based on KitKat.

I setted the sampling rate to "best for hardware" and I disable "Synchronize audio and video", but the difference of performance still huge and in some games, like Cruis'n Usa, these settings left the game playing worse.

Even in the same version, 121, there is difference in performance between use the SDL sound plugin or the SLES.

**Comment by fzurita** [comment]
Did you also disable audio time stretching?

**Comment by ZacharyFoxx** [comment]
Yeap! Believe me, I tried everything that you can imagine and more, like does not use an USB HUB and I didn't can find the setting "Floating point samples".

**Comment by fzurita** [comment]
If you disable audio by setting the audio plugin to "none-debug", does performance improve? Make sure you disable synchronize audio and video when you do that, otherwise there will be no frame limiter.

**Comment by ZacharyFoxx** [comment]
I'll try it tonight and I tell you after.

**Comment by ZacharyFoxx** [comment]
I tested using the setting "none-debug". Independently of the game, Cruis'n USA, GoldenEye, Pilotwings, they all ran well with this setting, keeping a good fps.

**Comment by fzurita** [comment]
Ok, I can do a more optimized audio SLES plugin that bypasses the sound touch library with lower quality audio. I won't bring back the SDL audio plugin though.

**Comment by ZacharyFoxx** [comment]
Hi. Great! I'll be thankful for this.
But, could you tell me why you don't want bring the SDL audio plugin back? I'm curious about it because the SDL audio plugin is lighter than SLES plugin and to you should be easiest put the SDL audio plugin back.

**Comment by fzurita** [comment]
SLES is lighter than SDL. SDL is wrapper around the native Android audio, which would be slower in my opinion. What could be making SLES slower for you could be the SoundTouch library that we use for resampling the audio. If we skip the SoundTouch library and let Android do the resampling it may be faster for you. So I will try that.

**Comment by ZacharyFoxx** [comment]
I got it! Again, thank you for all effort :D.

**Comment by fzurita** [comment]
Ok, done: 0b736b63789d14d98b1587e25f9a28f786f96d50
