### ISSUE TITLE
Add feature Scan File ROM in all folders, and feature Create shortcut game in the Mupen64Plus FZ

### ISSUE THREAD

**Issue by ammarraisafti** [mupen64plus-ae/mupen64plus-ae#700]
# Component
The feature components I want to suggest:
* Scan a ROM file in all folders
* Create game shortcuts

# Proposal Description
The suggestion of new features for this app crossed to my mind, when I see some friends or new users of this app having trouble doing the ROM file scanning process, or the user has trouble getting ROM files inside the folder. The reason,They forget where to put the ROM file they have moved to another folder. Another problem, some users of this app, often pause the game being played, because of busyness or other important things they should do. So users will feel very happy, if they can continue the game quickly and easily through shortcuts on the main screen of their device. Therefore, I will propose to developers to add some new features that are very interesting and and greatly pamper the user. And I hope developers can add features that I recommendation. 

**Scan a ROM file in all folders**
Features Scan a ROM files in all folders are very useful to users. I'm sure it's a very worthy feature to add. Due to the presence of feature Scan a files ROM in all folders, users can easily find all ROM files in their device storage. And their problem will be solved thanks to the presence of that feature.

**Create game shortcuts**
Features Create game shortcuts will also be very useful for users, because with the feature, users can add game shortcuts that are played to the main screen of their device. So they can easily and quickly to continue the game that has been played before. I'm sure, the presence of that feature is very pamper app users. And the feature will interest other users to use this app. 

# Mockup / Example
Examples of display images seen after the developer add both features I recommend in the Mupen64Plus FZ app.

The following is a sample image of the feature Scan file ROM in all folders. Preferably, the developer puts that feature in the file scanning menu section, or places it amongst the essential menu choices previously has provided.
Picture 1
![image](https://img.esteem.ws/40kki220qs.jpg)

Picture 2
![image](https://img.esteem.ws/d4rm6m6mdr.jpg)

The following is a sample image of the Create Shortcut game feature. Preferably, the developer places that feature in the library menu section and in the option menu section when the user pauses the game. And put it among the important menu choices that have been previously provided.
Picture 1
 ![image](https://img.esteem.ws/j5tye8m92o.jpg)

Picture 2
 ![image](https://img.esteem.ws/1dwol2qc45.jpg)

# Benefits
Benefit from both features I recommend.

- Feature Scan ROM files in all folders are an important and very interesting feature to use, because before scanning files, users can enable the feature to get all game ROM files located in separate folders on device storage, and allow users to select games want to play it. And very interesting, although when users download ROM files using different Browsers or stored in different folders, they will get the file ROM when doing the process of scanning ROM files.

- Feature Create Shortcut game is also a very useful and very interesting feature to use. Because every games it plays, can be added to the main screen. And users can enter easily to resume games that have been played before by simply clicking on the shortcuts that have been added. Users will be more attractive to play the game in their spare time and anywhere, because of the easy and quick access provided to continue the game.

- Overall, the Scan File ROM feature in all folders and the Create Shortcut feature of the game, is an important and very interesting feature for everyday use. And because these features are very important and useful. So, users of this application will continue to grow every day.

# Conclusion 
Both features I recommend will greatly help the users of the app and will greatly pamper the users of this app. Because both features are very needed by the user, and some of their problems will be solved thanks to the presence of that feature. So both features I recommend are very worth it adding or considered.

**Comment by fzurita** [comment]
Done: https://github.com/mupen64plus-ae/mupen64plus-ae/commit/cfdb54bbfc076adbaf9338a5bc7d413668df4233
