### ISSUE TITLE
Moto E4 Problem Unpacking Textures

### ISSUE THREAD

**Issue by br0kencartridge64** [mupen64plus-ae/mupen64plus-ae#701]
Hi. My name is Br0ken. Everytime I try to install a texture pack in Mupen64Plus FZ for Android, it has an error saying "problem Unpacking textures!" I've uninstalled it, reinstalled it and played with the settings and nothing is changing. Any help?

**Comment by fzurita** [comment]
Can you send me a link to the texture pack?

**Comment by br0kencartridge64** [comment]
Here you go. https://drive.google.com/file/d/0B7EF3X0mGqqGRllma2ZreFZQcmM/view

**Comment by fzurita** [comment]
What game is this for?

**Comment by br0kencartridge64** [comment]
Super Mario 64

**Comment by fzurita** [comment]
So that's not a valid texture pack. It has a bunch of zip files inside.
