### ISSUE TITLE
Detected problems with app native libraries - text relocations

### ISSUE THREAD

**Issue by Vester710** [mupen64plus-ae/mupen64plus-ae#702]
![n64 emulator text relocations error](https://user-images.githubusercontent.com/7035330/42471233-94b186de-8382-11e8-9ded-323465124ccc.png)

I'm using GPD XD Plus and whenever I open an N64 game from the launcher this error keeps popping up. I don't know what it means and how to fix so I'm reporting this issue here because I would really like to get this popup message to come off. Can someone help me out with this?

**Comment by fzurita** [comment]
Please use the latest Mupen64plus FZ from the play store, it has this issue fixed already. It can be found here: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita
