### ISSUE TITLE
Regarding Kirby 64: The crystal shards 

### ISSUE THREAD

**Issue by stand42** [mupen64plus-ae/mupen64plus-ae#703]
I've loaded up the game, free of cheats, and there's a problem with what I could jab in the dark to be the lack of a D pad, but I'm uneducated in this field. There's a copy of the text that pops up at the top left of the screen, I've tried more than one code so I believe it's how the emulator received the code. Also, in Aidyn Chronicles, could a cheat come out for adding EXP to all characters? Having the main character decked out and not being able to do the same with the others is a chore, but I'm just being picky.

**Comment by fzurita** [comment]
Please use this version of the app: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita 

It should fix the d-pad issue. If you can find such a cheat for aydin Chronicles, you can add it through the cheat manager.
