### ISSUE TITLE
Sorry, problem part two.

### ISSUE THREAD

**Issue by stand42** [mupen64plus-ae/mupen64plus-ae#704]
Pokemon stadium needs a d pad as well, is there a controls layout where one is present?

**Comment by fzurita** [comment]
As stated in the previous issue you made, use this version of the app, it's the latest:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by stand42** [comment]
How should I go about transferring data? I appreciate the help.

**Comment by fzurita** [comment]
It depends, what are you using right now?

**Comment by stand42** [comment]
I'm going from this to the updated app you sent me.

On Jul 14, 2018 7:47 AM, "Francisco Zurita" <notifications@github.com>
wrote:

It depends, what are you using right now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mupen64plus-ae/mupen64plus-ae/issues/704#issuecomment-405017993>,
or mute the thread
