### ISSUE TITLE
Legend of zelda: Ocarina of time Inside of Ganon Castle Crashes

### ISSUE THREAD

**Issue by Nashdelacruz** [mupen64plus-ae/mupen64plus-ae#705]
Im going to exit a orange crystal room at get crashed my game because will be lost my gameplay in inside of ganon castle

**Comment by fzurita** [comment]
Are you using cheats? If so, what cheats are you using?

**Comment by Nashdelacruz** [comment]
All quest are completed and infinite items and lifes

**Comment by fzurita** [comment]
Ok, try disabling those cheats and see if the crashing goes away.
