### ISSUE TITLE
The roms keep appearing after I delete them and the app. How do I stop this?

### ISSUE THREAD

**Issue by TheBupMasterToad64** [mupen64plus-ae/mupen64plus-ae#708]
I had sm64 on their once but I wanted to get a rom hack version. But it kept adding in Sm64. For specific reasons I was trying to download sm64 chaos edition by Kaze Emunaur.

**Comment by fzurita** [comment]
As long as you keep scanning the same folder that contains the sm64 rom, the app will keep finding the ROM. To get around this, select the specific file you want to add before hitting the ok button.
