### ISSUE TITLE
Ps4 controller not working still

### ISSUE THREAD

**Issue by chilipepper987** [mupen64plus-ae/mupen64plus-ae#710]
I see the latest release notes say that ps4 analog mapping is fixed but I am still having issues. My right stick maps to rx- for all 4 directions, and the L2/R2 triggers also seem to map to the r axis

**Comment by fzurita** [comment]
What version of the app ate you using? It should be this one:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by chilipepper987** [comment]
Ah, no I wasnt, thanks! Everything is working now. Sorry to bug you!
