### ISSUE TITLE
Problema de botones a,b ,<^> en majoras mask

### ISSUE THREAD

**Issue by radke01** [mupen64plus-ae/mupen64plus-ae#712]
Los botones amarillos , a y b no funcionan 
Todo estava bien asta q. Deje un tiempo de jugarlo. Despues de volver 
A jugar ya no funcionavan trate de mover algunas configuraciones pero nada 
Apenas estoy en el templo zora

**Comment by fzurita** [comment]
Has probado desinstalando y reinstalando la aplicación? Eso no hace perder tu progreso.

**Comment by radke01** [comment]
Bueno ahora lo intente 
Pero no funciono

**Comment by fzurita** [comment]
Estás ocupando cheats o algún hack con el ROM?
