### ISSUE TITLE
Crashing in version 3.0.194?

### ISSUE THREAD

**Issue by scMarth** [mupen64plus-ae/mupen64plus-ae#716]
I've gotten an update for Mupen64Plus FZ earlier today and Majora's Mask has crashed 4 times in the last hour, whereas it hasn't crashed at all before. Anyone else getting this issue?

App Version 3.0.194 (beta)

Version code: 194

**Comment by fzurita** [comment]
It's a known issue, a fix is on the way.

**Comment by scMarth** [comment]
Thanks for the fast reply! Glad I'm not crazy.
