### ISSUE TITLE
Jet Force Gemini crash

### ISSUE THREAD

**Issue by kage2051** [mupen64plus-ae/mupen64plus-ae#718]
Device: Lenovo Tab 4 Plus, SD625, 2/16 GB, Android 7.1.1
MP64+ FZ Ver: 3.0.202

Jet Force Gemini crashes with a black screen after exiting the last section or entering the goal door in Interior Goldwood. Happens in both JIT and Interpreter mode.

**Comment by fzurita** [comment]
Thanks for reporting, can you provide a save state that makes this easy to recreate? You can grab one from /sdcard/mupen64plus-fz/GameData/[GameName]

**Comment by kage2051** [comment]
Here it is:

[Jet Force Gemini_state.zip](https://github.com/mupen64plus-ae/mupen64plus-ae/files/2781012/Jet.Force.Gemini_state.zip)

**Comment by fzurita** [comment]
Thanks, I'll take a look and report upstream if necessary.

**Comment by fzurita** [comment]
Ok, I can reproduce. I'll report upstream.

**Comment by fzurita** [comment]
I created this issue upstream, any further updates will be there: https://github.com/mupen64plus/mupen64plus-core/issues/610
