### ISSUE TITLE
Mupen64Plus FZ version 3.0.202: Pokemon Stadium 2 crash

### ISSUE THREAD

**Issue by SimplyEarly** [mupen64plus-ae/mupen64plus-ae#719]
Everytime I enter in "Battle Now" on the menu screen of the game, after I chose the mode and difficulty, there will be an animation and then the app stops working. Regardless of the emulation plugin, the game keeps crashing. Please fix it!! I am using an lgk10 power Android 7

**Comment by fzurita** [comment]
I'm aware of this issue, fix will be coming soon

**Comment by fzurita** [comment]
In the meantime, you can revert to the last stable version:

3.0.187 from here

https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=Mupen64plus+FZ

**Comment by SimplyEarly** [comment]
Thanks for the help!!
