### ISSUE TITLE
Various glitches

### ISSUE THREAD

**Issue by Agentmass** [mupen64plus-ae/mupen64plus-ae#72]
I did run into some other graphical bugs. There are a ton of bugs in Mario Party 1 where the playing tiles are completely separated from the actual board. Also, toad appears completely off screen. Also, I found some other small minor texture bugs. In Super Mario 64, if Mario is far away from the camera, his poly count seems to cut in half. Screenshots are below.

Another minor bug is in most games where there is an actual image in the game the image has very faint lines going through the center. Minor bug though. You can see this bug if you were playing Mario Party 64 and you are going down the pipe to select a level.

The big issue is Mario Party 64 being almost unplayable because of the tiles being all over the place. 

Is there anyway to make images look more clear? I was looking at this gameplay video of Peache's Birthday Cake and the background map looks very clear and the one in the emulator does not.

http://www.youtube.com/watch?v=sFAXo-WN8qk

http://img15.imageshack.us/img15/8108/screenshot1wt.png
http://imageshack.us/photo/my-images/109/screenshot2ev.png/
http://imageshack.us/f/715/screenshot3cd.png/
http://imageshack.us/f/823/screenshot4st.png/
http://imageshack.us/f/833/screenshot5oh.png/
http://imageshack.us/f/209/screenshot6j.png/

I think most emulators including PC ones have these issues, besides maybe the Mario Party issues. So in my opinion, Mupen64 seems to be the best android N64 emulator.

Good job.

**Comment by gl91306** [comment]
also i just realized this was posted in 2013 lmao
