### ISSUE TITLE
On screen D-Pad glitch when using "Digital"

### ISSUE THREAD

**Issue by malek78i** [mupen64plus-ae/mupen64plus-ae#720]
As the title said, there is a bug in the on screen cursor (D-Pad) while using the "Digital" controller profile.

Here is a screenshot about the issue:
http://i63.tinypic.com/zjyma8.png

**Comment by fzurita** [comment]
What version of the app are you using?

**Comment by malek78i** [comment]
Version 3.0.202 (beta)

**Comment by fzurita** [comment]
Ok, in the screenshot, it looks like you have the angelic instead of digital selected. What game is that?

**Comment by malek78i** [comment]
No. I can't control the game with Digital :/

**Comment by fzurita** [comment]
I guess I'm confused, what is the issue?

**Comment by malek78i** [comment]
Seen the cursor at down left of the screenshot? When I click it, it moves somewhere else. Its too difficult to say.

**Comment by fzurita** [comment]
That's intended, go to settings, then touchscreen, disable relative touchscreen joystick.
