### ISSUE TITLE
problem in the last update with conker bfd

### ISSUE THREAD

**Issue by pipa11** [mupen64plus-ae/mupen64plus-ae#722]
After the last update, you leave the game at 5 seconds, I already tried changing to different profiles of the interpreter, but nothing.
this is the error that I get when I see the forced closure summary
  Thank you :*
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 30299, tid: 30351, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfde30cbc
    x0   00000000fde30cb8  x1   0000007725dbc2f0  x2   0000001d9f780000  x3   000000000000013b
    x4   0000000080031280  x5   00000000800312b0  x6   000000000000001b  x7   0000000080186e40
    x8   00000077224ba000  x9   008000400000fb87  x10  00000000ffffffff  x11  0080004000000000
    x12  000000002400ff01  x13  ffffffffffffffff  x14  0000000000000000  x15  0000000080030cba
    x16  0000000080030cb4  x17  0000000000000004  x18  0000000000000034  x19  0000000080030d50
    x20  00000000fffec586  x21  000000000001f70e  x22  0000000001000080  x23  00000000fb870000
    x24  0000000000000000  x25  00000000ffffffff  x26  00000000ffffffff  x27  000000000000013b
    x28  0000000000000000  x29  0000007724dbb000  x30  00000000ffffffff
    sp   00000077262f5f40  pc   0000007722f9c80c  pstate 0000000040000000

backtrace:
    #00 pc 00000000001e180c  <anonymous:0000007722dbb000>
    #01 pc 00000000fffffffb  <unknown>

**Comment by fzurita** [comment]
Hello, which game?

**Comment by pipa11** [comment]
oh sorry, with the conker Bad fur day, and the version of the emulator is 3.0.203

**Comment by fzurita** [comment]
Ok, which part of the game. Can you try version 3.0.204 that just came out?

**Comment by pipa11** [comment]
Now it works! Thanks, I'll tell you that the mistake of giving on entering the level of cat-fish and press any button
