### ISSUE TITLE
Crashing in OOT? Version 3.0.205

### ISSUE THREAD

**Issue by scMarth** [mupen64plus-ae/mupen64plus-ae#724]
I was playing OOT and so far it has crashed 5 times for me, happens 3 times in Kakariko Village. Not sure if that has anything to do with it. Could it be my settings or is this a known issue?

Version: 3.0.205 (beta)
Version code: 205

**Comment by fzurita** [comment]
It's not a known issue.

Are you using any cheats? 

Have you tried switching emulation profiles?

**Comment by scMarth** [comment]
I'm not using any cheats.

I have been using Glide64-Accurate emulation profile. I will try switching it and see if the problem goes away. Let me know if you have any recommendations for which ones I should use.

**Comment by fzurita** [comment]
Did switching emulation profiles help?

**Comment by scMarth** [comment]
Yes so far it hasn't crashed since I've switched to GlideN64-Medium

**Comment by fzurita** [comment]
Thanks for reporting back.
