### ISSUE TITLE
Majora's mask

### ISSUE THREAD

**Issue by Bonnie2737** [mupen64plus-ae/mupen64plus-ae#725]
download Majora's mask for Nintendo 64 and everything was very good the emulator is perfect ... but when I got objects the game was closed at first I thought it was something normal but it happened repeatedly.To the point that I was so frustrated that I could not keep up with that ... I would download other emulators but I like it very much please please fix that.

**Comment by fzurita** [comment]
Hello, thanks for reporting this. Can you provide a save state of where this is happening? Save states can be found in this path for Majora's mask. You can zip up this whole folder if you want and post it here.

/storage/emulated/0/mupen64plus-fz/GameData/ZELDA MAJORA'S MASK (U) 2A0A8ACB61538235BC1094D297FB6556

**Comment by Bonnie2737** [comment]
Well, actually I'm playing the game in Spanish I'm from Colombia and I
speak through English to understand each other.

I did not understand well what I have to do with that link, but no yes yes
this is what you ask ... The fault I'm getting is when you need the
magnifying glass of truth every time I get it closes It does not let me
move ... What I can do?

**Comment by fzurita** [comment]
Este es un problema con el emulador. Me gustaría poder arreglarlo por es díficil llegar a esa parte del juego. Adónde encontraste ese juego en español? Encontraste algún "Patch" para traducir el juego de inglés a español?

Puedes poner la carpeta de Majora's mask dentro de /sdcard/mupen64plus-fz/GaneData en un archivo zip y adjuntarlo a este "issue"?

**Comment by fzurita** [comment]
Por mientras, selecciona el juego, anda a opciones, cambia el perfil de emulación a GLideN64-Medium.
