### ISSUE TITLE
Bug in turok 2 after update 11 Feb 2019

### ISSUE THREAD

**Issue by dhanial** [mupen64plus-ae/mupen64plus-ae#727]
![screenshot_20190211-125548](https://user-images.githubusercontent.com/37980131/52547955-75edb800-2dfd-11e9-965e-d131e33dc7a4.png)
![screenshot_20190211-125212](https://user-images.githubusercontent.com/37980131/52547971-89008800-2dfd-11e9-8f96-634d760dac5c.png)

**Comment by fzurita** [comment]
What specifically is the bug? I need more detail.

**Comment by dhanial** [comment]
Sorry dev it's fix now, i'm just delete mupen folder in internal, so sorry
😅

**Comment by fzurita** [comment]
Ok
