### ISSUE TITLE
Conker's Bad Fur Day odd timing issues.

### ISSUE THREAD

**Issue by retrobenny** [mupen64plus-ae/mupen64plus-ae#729]
When using Count Per Operation of 1 which usually didn't run into this issue,playing the chapter named "Sweet Melody" can often-times desync the audio cues regardless whether or not time stretching is enabled,making this potentially a core issue with the 64bit core or an issue with other parts added to it such as DMA speeds maybe,if the original DMA speed was different.
(use "weldersbench" as a cheat to access all chapters)

The issue happens when either the singing voice plays endlessly after the cutscene,locking you out of attacking the boss or even without the singing part if you skip the first scene,where in both conditions if you pause,the music will still be playing.
Normally this problem would only happen frequently when using a 60fps cheat but now its happening cheatless at 30fps for some reason.

**Comment by fzurita** [comment]
Can you make an issue about this upstream? It seems like a core issue. You should provide a save state and the cheat code.
