### ISSUE TITLE
Help 2.0

### ISSUE THREAD

**Issue by oligarche** [mupen64plus-ae/mupen64plus-ae#731]
Wen I get 20 stars in sm64 last impac my game freezes and stars a saving texture cache thing. And never stops

**Comment by 007megaoof** [comment]
Put it on an different video plugin

**Comment by HaduDoKen** [comment]
when I enter the roms, the game goes black screen, but the sound remains in the background as if the game were normal but the screen was broken

**Comment by fzurita** [comment]
Does this happen for all games?

Have you tried switching emulation profiles?

**Comment by HaduDoKen** [comment]
Yes at all, emulation profiles?
i'm using google translator i'm brazilian if i was wrong was the translator


Em seg, 7 de out de 2019 10:10, Francisco Zurita <notifications@github.com>
escreveu:

**Comment by fzurita** [comment]
Which games?

**Comment by HaduDoKen** [comment]
In all that I have emulator the legend of zelda majoras mask and ocarina of
time

Em seg, 7 de out de 2019 10:15, Francisco Zurita <notifications@github.com>
escreveu:

**Comment by HaduDoKen** [comment]
In all that I have emulator the legend of zelda majoras mask and ocarina of
time

Em seg, 7 de out de 2019 10:17, Joao Gabriel <joaogabriel3859@gmail.com>
escreveu:

**Comment by HaduDoKen** [comment]
Haha I got emulation profiles and pressed something here and came back
ahhahaha

Em seg, 7 de out de 2019 10:17, Joao Gabriel <joaogabriel3859@gmail.com>
escreveu:

**Comment by fzurita** [comment]
Those games should run without issue. What phone do you have?

**Comment by HaduDoKen** [comment]
Alcatel

Em seg, 7 de out de 2019 10:23, Francisco Zurita <notifications@github.com>
escreveu:

**Comment by HaduDoKen** [comment]
The game is back to normal, I changed the emulation profiles thanks

Em seg, 7 de out de 2019 10:36, Joao Gabriel <joaogabriel3859@gmail.com>
escreveu:
