### ISSUE TITLE
Stratus xl gamepad is not maped well

### ISSUE THREAD

**Issue by 007megaoof** [mupen64plus-ae/mupen64plus-ae#732]

**Comment by 007megaoof** [comment]
I recntly got an Steelseries Stratus XL so I could play the rom's without cheating and the only button that seems to work is the back button. Is there any way to fix that?

**Comment by fzurita** [comment]
Yeah, go to profiles then controller. You can create a profile there and map buttons. Then go to profiles then select profiles to select the profile you created for controller 1.

**Comment by 007megaoof** [comment]
I already tried to do that. the only button it seems to reconize is the back button.

**Comment by fzurita** [comment]
Does that controller work within the Android environment? Can you use it to control menus? If not, that could mean that your Android device doesn't have proper drivers for that controller.

**Comment by 007megaoof** [comment]
I looked at some review's and the controller worked great for them however some people did have some issues with the controller.
The controller seems to not work for me  I do not know  but I think it has to do with diferent keycode's for the controller. I tried a key mapper app but It kept saying that The app did not reconize the device

**Comment by fzurita** [comment]
Try downloading a controller tester app from the play store. See if any of those apps recognize the keys.

**Comment by 007megaoof** [comment]
Okay. if that does not work I will tell you

**Comment by 007megaoof** [comment]
Nope

**Comment by fzurita** [comment]
Ok, so the problem is a lack of drivers within your phone for the controller. I will close since there is not much we can do about that.
