### ISSUE TITLE
Can't map wired Xbox 360 Trigger axis

### ISSUE THREAD

**Issue by VicoLee2000** [mupen64plus-ae/mupen64plus-ae#736]
Hello,
I am trying to map my wired Xbox 360 trigger axis to the Z button. It worked just fine in the beginning of March (last month) when I last used it. Since then the app got updated, and now it doesn't want to map. I tried re-plugging the controller and restarting the app. The triggers show up in the Controller Diagnostics, but when I try to map the Z button, it doesn't recognize the trigger being pushed. 
It apparently isn't my controller, and since it worked fine a month ago, I believe an update caused this issue. 
Thanks

Vico Lee

**Comment by VicoLee2000** [comment]
Update: I tried using the CoolN64 app, and it has the same problem. This is a Mupen64plus port right? I guess Mupen's update made this problem.

**Comment by fzurita** [comment]
Are you using this version of the app?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita
