### ISSUE TITLE
Emulator is not saving (or loading)

### ISSUE THREAD

**Issue by maththehuman** [mupen64plus-ae/mupen64plus-ae#738]
I just started to use mupen fz, and played ocarina of time a little bit. I saved in slot 0 and quit. later, i came back to play and loaded from slot 0, and nothing happened. i tryed to save in slot 1, 2, load from it, nothing again. i don't know if the app is not saving or anything else, but i think the auto-saving thing is not working too. can someone help me?

**Comment by fzurita** [comment]
That functionality is definitely working. I'd it possible that you may have deleted your /sdcard/mupen64plus-fz folder or done of the contents?
