### ISSUE TITLE
Zelda Majora' Mask 

### ISSUE THREAD

**Issue by Inazuka381** [mupen64plus-ae/mupen64plus-ae#741]
The Zelda Majora 'Mask is full of bugs:

- Whenever I try to add some texture, the game is reversed;

"The Deku bubbles are catching the whole game;

-FPS casts even with the game at minimum resolution (120x360);

-The game freezes in parts.

* done on Google Translate

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to GLideN64-Medium. Glide64mk2 had many issues with that game and unfortunately, it's not maintained. I don't plan to fix that plugin.

Also, Glide64mk2 issues belong here:

**Comment by Inazuka381** [comment]
The game is flipping when I put it in the Gliden64-Medium plugin. Sometimes
he gets stuck with a black or green stripe.

Em sáb, 25 de mai de 2019 17:30, Francisco Zurita <notifications@github.com>
escreveu:

**Comment by fzurita** [comment]
Go to settings then display and enable "fix upside down screen"
