### ISSUE TITLE
The Legend Of Zelda: OOT (Version of Mupen64Plus FZ: 3.0.222)

### ISSUE THREAD

**Issue by AlexOFodao** [mupen64plus-ae/mupen64plus-ae#745]
I'm brazilian, and i'm not so good in english, so, if you send me an answer about my question, I would be grateful if you could translate that answer into Portuguese of Brazil.

Anyway, in OOT, there's a bug when I collect the Lens of Truth and I use it on invisible walls, the game crashes, and I already tried to put GLideN64, and it did not work, please fix this bug!

**Comment by fzurita** [comment]
Sorry, there is not much I can do about this if your phone doesn't work
with GLideN64. I recommend a newer phone.

**Comment by AlexOFodao** [comment]
;-;

Em ter, 16 de jul de 2019 00:22, Francisco Zurita <notifications@github.com>
escreveu:
