### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Mztable** [mupen64plus-ae/mupen64plus-ae#747]
Just updated, I've tried reinstalling 3 times too no avail getting the "not installed properly" error

**Comment by fzurita** [comment]
What device are you intalling in? That error means that some essential files are missing.

**Comment by Mztable** [comment]
It worked before (Moto x4)

**Comment by fzurita** [comment]
For some reason the app is becoming corrupt in your device. Do you have enough storage space?

**Comment by Mztable** [comment]
Yes, I do

**Comment by Mztable** [comment]
It seems that the app data folder is gone

**Comment by fzurita** [comment]
Can you try clearing data for the application and trying again?

**Comment by Mztable** [comment]
Either that doesn't work or I'm doing it wrong

**Comment by fzurita** [comment]
Are you downloading the app from the Google play store or sideloading it?

**Comment by Mztable** [comment]
I would be using a playstore distribution

**Comment by fzurita** [comment]
Ok, just to make sure, are you using this?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

You should be using the Google play store version, otherwise you can get installation errors.

**Comment by Mztable** [comment]
Fixed it
