### ISSUE TITLE
Majoras Mask, Lens of Truth broken

### ISSUE THREAD

**Issue by fallenwalls** [mupen64plus-ae/mupen64plus-ae#75]
The lenses of truth actually does not reveal what it should.  I have run into a couple of things like cue bubbles from in game not appearing, or a few in game video black-outs. Those really haven't impeded game play too much, but the lenses of truth's lack of revealing paths certainly does.  If it's possible I would very much appreciate your attention on the matter.  Obviously, it is not life or death, but it would be appreciated.  

Thank you

**Comment by fzurita** [comment]
Upstream issue.

**Comment by fanyancat** [comment]
I have the same problem when I try to use lens of truth, I can't use them because the game stop, what can I do? I'm stuck :(

**Comment by fzurita** [comment]
That's a problem with Glide64. Switch the emulation profile to GLideN64-Medium to avoid the crash,
