### ISSUE TITLE
Emulator is closing in the middle of the game

### ISSUE THREAD

**Issue by hei18mm** [mupen64plus-ae/mupen64plus-ae#750]
I was playing the legend of Zelda:ocarina of Time, when I arrive to the shadow temple the app stopped and close, i tried again, and again later, it's been closing.

**Comment by fzurita** [comment]
Are you using any cheats? If so, try turning them off for the shadow temple.

**Comment by KainKnight** [comment]
Hello I am playing Zelda Ocarina of time and everytime I use the Eye of thruth to reveal a passage the game crashes. I am not using cheats BTW. Please help

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to
GLideN64-Medium.
