### ISSUE TITLE
Graphical issue with GlideN64-Accurate

### ISSUE THREAD

**Issue by Spycerliks** [mupen64plus-ae/mupen64plus-ae#752]
Hi, I'm having an issue with Resident Evil 2 (both NTSC-U / NTSC-J). I'm playing with GlideN64-Accurate and works fine the first time, but after I closed the app and tried to play it again, the 3D graphics looks weird, like in negative color. I tried reloading/reset the game and still happens. Also I changed to GlideN64-VeryAccurate and had the same problem.

Device: Samsung Galaxy A50

![Screenshot_20190913-200137_Mupen64Plus FZ](https://user-images.githubusercontent.com/9056982/64899720-273e2000-d663-11e9-9413-283175ad48c7.jpg)
![Screenshot_20190913-201301_Mupen64Plus FZ](https://user-images.githubusercontent.com/9056982/64899721-27d6b680-d663-11e9-829e-bea7af2337b0.jpg)

**Comment by fzurita** [comment]
That's interesting. Are you using the mupen64plus FZ version of the app? If so, can you try deleting this folder?

/storage/emulated/0/mupen64plus-fz/CoreConfig/UserCache/mupen64plus

**Comment by Spycerliks** [comment]
Yes, I'm playing with that app, last version. I deleted the folder and the graphics are normal again, but when I quit the app and replayed it, the same problem happened again. I hope this have a solution, but in the meantime, deleting the folder helps to play it normally.

**Comment by fzurita** [comment]
You can may be able to fix this by creating a custom

Go to profiles them emulation profiles. Select GLideN64-Very-Accurate and hit copy. Give it a name and hit ok. Disable "enable hardware per-pixel lighting" and go back to the game gallery. Select the game, go to settings, and change the emulation profiles to the one you created.

**Comment by Spycerliks** [comment]
It worked, now I can play it again. Thanks!
