### ISSUE TITLE
Toon Panic (Proto) not showing up

### ISSUE THREAD

**Issue by kage2051** [mupen64plus-ae/mupen64plus-ae#753]
On the latest build, the ROM of the aforementioned proto isn't recognized after updating the game library. It happens with all existent versions of the dump, no matter which extension they have.

Version: 3.0.222 (beta)

**Comment by fzurita** [comment]
It means that the ROM does not have a valid N64 header, so it's not being recognized by the app.

**Comment by kage2051** [comment]
There is a commit on this repository from April which recognizes non-headered ROMS based on GoodN64 metadata, however the FZ build is a few days behind that commit.

**Comment by fzurita** [comment]
Ok, thanks for reminding me about that. I forgot I had done that. Either way, it's fixed but I haven't updated the play store version yet. Next time I update that, you should have it. It should be pretty soon, Judy waiting on some GLideN64 fixes.
