### ISSUE TITLE
Lentes da verdade (Zelda Ocarina)

### ISSUE THREAD

**Issue by Ocarneiroz** [mupen64plus-ae/mupen64plus-ae#755]
Estava jogando Zelda Ocarina of Time, e já em um templo bem avançado (Shadow Temple), onde se precisa usa as Lentes da Verdade (item principal do templo), toda vez que eu ligo a lente o aplicativo sai do jogo, quando volta é pra uma parte bem antes. Pfvr não qro perder tudo que já conquistei, como faço p resolver esse bug?

**Comment by fzurita** [comment]
This is a known issue with certain GPU drivers. Select the game, go to settings, change the emulation profile top GLideN64-Medium.
