### ISSUE TITLE
Stuck controls

### ISSUE THREAD

**Issue by thegamer7383** [mupen64plus-ae/mupen64plus-ae#757]
When playing with a bluetooth xbox controller, the controls seem to get stuck every so often. I only find it to happen in this app. This makes playing really difficult.

**Comment by fzurita** [comment]
Stuck in what way? What phone do you have?

**Comment by thegamer7383** [comment]
For exame: When you go in circles, it does fine, then it gets stuck in a specific direction for so far up to a few seconds. It happens when I use the bluetooth controller. I also don't have any other controller to test it with.
I have a Samsung Galaxy J3

**Comment by fzurita** [comment]
Interesting, I'm not sure why that would happen. Do you have any other controllers handy that you can try?

**Comment by thegamer7383** [comment]
No. I only have one controller and it's that bluetooth controller.

**Comment by i-bruh** [comment]
maybe cuz ur controller is fake?

**Comment by thegamer7383** [comment]
Nope. It's real. I don't know why you think it's fake, but it's an actual controller. And the reason I know that is because it has everything an Xbox one controller has while additionally having bluetooth technology inside, and it connects normally to the Xbox one.

**Comment by i-bruh** [comment]
is the profile is Xbox on player 1/2/3/4

**Comment by fzurita** [comment]
Closing this for now since it was problem an issue with the phone compatibility with the Xbox one controller. I do trust that your controller was real, it's probably an issue with your phone handling that specific controller.
