### ISSUE TITLE
Keyboard problems

### ISSUE THREAD

**Issue by Wdecently** [mupen64plus-ae/mupen64plus-ae#758]
Hi everyone, I made a Github account just to make this post since i couldn't find anything similar to it. So wanted to play banjo kazooie for the first time, since i was excited about him being in smash. I've heard of him and wanted to play his original game, since Rare was really great before the microsoft buyout. I don't have any controllers that I can use well for this emulator, so I thought i could use my keyboard. I map all the buttons to keys that felt comfortable, and boot p the game. But after watching the intro and getting to the start screen, I pressed the enter (mapped to the start) button, and nothing happened. So i was like "Huh, i guess I'mm manually click the start button on the screen (I'm on a chromebook btw). I'm at the file select screen, and i press j (mapped to a), and nothing happens. I try moving to other save files using wasd, but nothing. Does the keyboard not work for this emulator, or am i dumb?

**Comment by fzurita** [comment]
It does work. I'm assuming you created an emulation profile by going to profiles then controller profiles.

After that, go to profiles then "select profiles" and make sure the profile is selected for controller 1. Also, in the same screen, select the multi-player option and make sure the keyboard is mapped to player 1.

**Comment by Wdecently** [comment]
Hi again. I tried this, and it still doesn't work. If you'd like, I can
either list my process in another email, or record myself going through the
process of me mapping the keyboard and whatnot. Though we don't have to do
that.

**Comment by fzurita** [comment]
Ok, interesting. Last reports I heard, it works ok. You are the first to say otherwise. I'll dig out a keyboard and see if I can reproduce the issue with the latest version.

**Comment by fzurita** [comment]
I just tried it on my wife's chrome pixelbook and everything worked ok with her keyboard.

Please make a video and I can probably spot what you are doing wrong.

**Comment by Wdecently** [comment]
Nevermind, I got it to work! Thank you anyways!
