### ISSUE TITLE
PS3 Controller stopped mapping

### ISSUE THREAD

**Issue by badboyjay85** [mupen64plus-ae/mupen64plus-ae#759]
Hi, I've been Playing Mupen64 on my Huawei P20 lite, using a PS3 controller. For some reason the app has stopped Mapping the PS3 Controller. It will only map the left stick and the L2 button, but that button is off when pressed and on when depressed. I've tried two separate controllers and different cables but still the same. I've tried a friends PS4 controller and it works fine so it's not the OTG cable either. My phone recently updated to EMUI 9 but I can't remember if it's worked since. Could this be a cause of the update or a bug?

**Comment by fzurita** [comment]
Does the controller work with other emulators? If it doesn't, then there is nothing I can do. It's possible that that the Android update may have removed some necessary driver.

**Comment by fzurita** [comment]
No response, closing.
