### ISSUE TITLE
Clearing game library without permission

### ISSUE THREAD

**Issue by Panderner** [mupen64plus-ae/mupen64plus-ae#762]
There's a bug where the game library clears sometimes without permission including cover arts

**Comment by fzurita** [comment]
Do you have any kind of SD card cleaner app on your phone? Those are known to do that.

There is nothing in this app that will do what you say.

**Comment by Panderner** [comment]
I don't use sd card cleaner apps but realme's clean storage delete all library including cover arts

**Comment by fzurita** [comment]
Ok, there is nothing I can do about an external app clearing app data.

Well, actually, there is something I can do, which is to make all game data private, but I don't exactly want to do that since it would require resigning a whole lot of stuff.

**Comment by Panderner** [comment]
Adding .nomedia to gallery cache prevents SD card cleaners from clearing game library

**Comment by fzurita** [comment]
I already have the hidden .nomedia file and appropriate.
