### ISSUE TITLE
NBA Jam 2000 crashes to load

### ISSUE THREAD

**Issue by Panderner** [mupen64plus-ae/mupen64plus-ae#763]
The NBA Jam 2000 crashes when I trying to load the game

**Comment by fzurita** [comment]
In can confirm this. An issue should be written upstream though since this is just a front end.

**Comment by Panderner** [comment]
> In can confirm this. An issue should be written upstream though since this is just a front end.
> 
> https://github.com/mupen64plus/mupen64plus-core

Retroarch's mupen64plus core works but mupen64plus fz crashes

**Comment by Panderner** [comment]
@fzurita Retroarch can boot the game but M64plus FZ Crashes

**Comment by fzurita** [comment]
It seems to be a dynarec issue. It boots fine with interpreter. Maybe they made some tweaks, I'll check it out.

**Comment by Panderner** [comment]
Oh I'm using dynarec the game is now working on latest version.
