### ISSUE TITLE
Oot Bug Sky always Turms Black

### ISSUE THREAD

**Issue by offmarc** [mupen64plus-ae/mupen64plus-ae#77]
Hi
I am using mupen64 ae latest version from google play store on a kindle fire hd. 
When playing oot with rice video plugin I have the following problem:
Minor:
- when game starts Nintendo and the Zelda logo is ditched or blurred and not shown properly

Major 
- the sky changes according to time in the hyrule land but always shortly after a change the whole sky just turns black no matter what time of the day it is
- when using a lot save and starting the game using the menu with start it is impossible to exit with start again. It just freezes then. 

Cheers
M

**Comment by fzurita** [comment]
Upstream issue.
