### ISSUE TITLE
Transfer Pak not working

### ISSUE THREAD

**Issue by mrex999** [mupen64plus-ae/mupen64plus-ae#775]
I'd like to know why Transfer Pal isn't working, or if there's some way to fix it, Pokemon Stadium 1 and 2 seem to load Pokemon RBYGS save files, but once I want to see if there's some changes in the GB/GBC games, I see no changes, it doesn't overwrite the GB/GBC save files.

**Comment by fzurita** [comment]
There is already an issue for this upstream:

https://github.com/mupen64plus/mupen64plus-core/issues/688
