### ISSUE TITLE
Request - Close App/Exit App

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#780]
Hi @fzurita, is it an idea and possible to add a Close App or Exit App button in the app to close it properly?

**Comment by fzurita** [comment]
No plans to do that. That is not the standard way to do things in Android apps and it really a bad practice.

Simply use the home button and swipe away the app from Android UI.

If you do that while in-game, you can use the notification to stop the service.

**Comment by bladeoner** [comment]
@fzurita thank you for your response and explanation.
