### ISSUE TITLE
Update SDL to 2.0.10

### ISSUE THREAD

**Issue by TacoTheDank** [mupen64plus-ae/mupen64plus-ae#781]
https://hg.libsdl.org/SDL

**Comment by fzurita** [comment]
I'm not sure what this would buy us. We barely use it right now.

**Comment by TacoTheDank** [comment]
I mean, obviously this isn't very important. It's just an issue as a reminder that a newer version is available.

**Comment by fzurita** [comment]
I have replaced SDL2 with a stub of it. It's only really being used for timers, mutexes, and semaphores.

45c38a855dddf80655d9192f5b7f05c29fb84cee

**Comment by TacoTheDank** [comment]
Ah, wonderful. Thank you :)
