### ISSUE TITLE
Texture pack is not loaded

### ISSUE THREAD

**Issue by i-bruh** [mupen64plus-ae/mupen64plus-ae#782]
So i was bored so i use my phone and then download a rom hack, so i add the texture pack but i cannot add it, it says "cannot unpack file" so i play original game instead of rom hack

**Comment by fzurita** [comment]
Can you send me a link to the texture pack? I can tell you why it doesn't work.

**Comment by i-bruh** [comment]
https://www.smwcentral.net/?p=section&s=sm64hacks&__cf_chl_jschl_tk__=781db4468f0df26c0c52d31e40dcdf7d2672051f-1576723939-0-AQUa3NnrzQ0MRn1fveeIHgTvRFCY7R1lJxBZmEEsEH5bNrGOxSz21iSj44TTW2mZysUfHnOF8EPZ2gJzxvBNDYEX_uueCFtek1uNs_ecRuXIKCPdyUCvWqO4JIiBOVCDcTmGh_AMeGuXe__1HqAdUotzy7TFXrVKJjkLfyBBTYgHdT6B4LlmfBr79xYlmfrH7HNcSrjabr60emgzMd2uHj13Ue5yooNE0McjAusiEwFmO7LtNX7-47tlzpBQ6I4dPayJDOJuz7MDRgeH9yqv7EMFv7f_8070zXVV9BJ6Vjcp

**Comment by i-bruh** [comment]
@fzurita

**Comment by fzurita** [comment]
That's the hack. What about the texture pack?

**Comment by i-bruh** [comment]
no link

**Comment by fzurita** [comment]
Ok, I can't help you figure out why the texture pack is not working without a copy of it.
