### ISSUE TITLE
Kirby 64 screen is glitchy

### ISSUE THREAD

**Issue by i-bruh** [mupen64plus-ae/mupen64plus-ae#783]
So i was first time playing kirby 64 and screen glitched like this 
![Screenshot_2019-12-18-16-52-52](https://user-images.githubusercontent.com/59009745/71076190-e0a71700-21b7-11ea-8bd0-c1e1d7069755.png)
I dont know how it got glitched, i dont  download a virus one, it dont glitch on my tv it was normal i hope theres an option for this glitch

**Comment by fzurita** [comment]
Try this, select the game, go to settings and change the emulation profile GLideN64-Medium.

**Comment by i-bruh** [comment]
im waiting for responses

**Comment by fzurita** [comment]
Ok, if GLideN64 doesn't give you enough performance then there is nothing I can do about the problem.
