### ISSUE TITLE
[ADVICE] Recommend settings

### ISSUE THREAD

**Issue by malek78i** [mupen64plus-ae/mupen64plus-ae#784]
Hey (again) :D

Can you recommend the best emulation settings for my phone, please?

Brand: LG
Model: K4 2017
CPU: Qualcomm® Snapdragon™ 210/212
GPU: Qualcomm® Adreno™ 304 @ 307 Mhz

Thank you in advance!

**Comment by fzurita** [comment]
Wow, that's a very low end phone. I wouldn't recommend the app really for that phone. But if you must, I would use either glide64mk2 emulation profiles or GlN64 emulation profiles. Your experience will suffer though.

**Comment by malek78i** [comment]
A low end phone!? Not at all. I had a previous phone and that was low end in my eyes. This one is a really better one in comparison to my old phone. Mupen64+ work on my new phone almost fine.
