### ISSUE TITLE
how do i use gameshark in mupen64++

### ISSUE THREAD

**Issue by spiritnorth** [mupen64plus-ae/mupen64plus-ae#785]
so i have read on how to do it  in mupen64+ but i dont know how to use it in mupen64++ so if you guys can help it will be accepted cause i do need all the help i can

**Comment by fzurita** [comment]
Select the game, go to settings, select "enable cheats". In there, you can select the cheats that have already been included or add your own cheats.

**Comment by spiritnorth** [comment]
hi i dont have that can you maybe be more like specific?

2020-01-02 15:03 GMT+01:00, Francisco Zurita <notifications@github.com>:

**Comment by spiritnorth** [comment]
i use mupen64++ if you dindint know that

2020-01-02 15:03 GMT+01:00, Francisco Zurita <notifications@github.com>:

**Comment by fzurita** [comment]
I don't know what mupen64++ is. I hope they are not linking to our repo. This is only for mupen64plus ae and mupen64plus fz.

**Comment by spiritnorth** [comment]
oh sorry then there is another mupen64 with dubble plus instead of one
sorry to bother you goodbye


Op do 2 jan. 2020 om 17:24 schreef Francisco Zurita <
notifications@github.com>:
