### ISSUE TITLE
Rice: Most texture upscaling modes are unusable

### ISSUE THREAD

**Issue by easyaspi314** [mupen64plus-ae/mupen64plus-ae#790]
Rice's "Texture upscaling/enhancement" setting has plenty of common filters. However, almost all of them render the game mostly if not entirely unplayable.

Here are some screenshots. The settings are the same as Rice-Accurate, with the only modification being the texture enhancement.

My internal resolution is 1920x1440.

Scale2X (I highly doubt the HUD textures are meant to look that way)
![Screenshot_20200208-152134](https://user-images.githubusercontent.com/6258309/74091615-4fea0a80-4a87-11ea-9014-b8f1261543bf.png)

2xSAI (note: the HUD is garbled)
![Screenshot_20200208-151421](https://user-images.githubusercontent.com/6258309/74091510-4b712200-4a86-11ea-84f2-15a1499c574f.png)

Note: Stadium 2 is not any more broken (than it usually is, but it is Stadium 2) with the above two, but it is definitely noticable with the other ones.

HQ2X
![Screenshot_20200208-151446](https://user-images.githubusercontent.com/6258309/74091518-63e13c80-4a86-11ea-80d3-050ec5957942.png)
![Screenshot_20200208-152453](https://user-images.githubusercontent.com/6258309/74091596-3ea0fe00-4a87-11ea-834a-a0d6d8b84356.png)

HQ4X
![Screenshot_20200208-151529](https://user-images.githubusercontent.com/6258309/74091527-7196c200-4a86-11ea-9734-dce2d4dc6a8c.png)
![Screenshot_20200208-152515](https://user-images.githubusercontent.com/6258309/74091603-452f7580-4a87-11ea-841d-e6954bc307ae.png)

Note that GlideN64's filters *seem* to work fine from initial tests.

Specs:
M64Plus FZ 3.0.232-free (aarch64)
Google Pixel 2 XL
Stock Android 10 (build QQ1A.200105.002)
Qualcomm Snapdragon 835
Qualcomm Adreno 540

**Comment by fzurita** [comment]
Yikes, that does look pretty terrible, but this is probably not the right place for this bug report. The bug report should probably be written upstream instead here: https://github.com/mupen64plus/mupen64plus-video-rice/issues

I don't really see it getting fixed though since I think, personally speaking, all plugins should be getting phased out in favor of either Angrylion or GLideN64. My guess is that it's trying to use some unsupported texture format.

**Comment by fzurita** [comment]
I created an issue upstream and pointed it to this: https://github.com/mupen64plus/mupen64plus-video-rice/issues/88
