### ISSUE TITLE
Sudden Low Graphics?

### ISSUE THREAD

**Issue by AH139** [mupen64plus-ae/mupen64plus-ae#791]
I recently updated the app, but something strange is happening. I have a Glide64-Accurate profile with the gliden64 video plugin and widescreen hack enabled as my main emulation profile. Recently, when I try to play any game, the resolution is kind of low, even though the resolution is set to native. However, when I enable the original Glide64-Accurate (without the widescreen hack), the resolution returns to normal. This hasn't happened since I updated the app, so I am very confused. Any help would be much appreciated!

With WS:
![Screenshot_20200208-222706_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74097653-8cd3f280-4ac3-11ea-963c-799c8ef56120.jpg)
![20200208_225157](https://user-images.githubusercontent.com/60836961/74097846-c4dc3500-4ac5-11ea-90af-f42f3290cd08.jpg)
Without WS:
![Screenshot_20200208-222723_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74097658-a5440d00-4ac3-11ea-9658-13cb74cd8592.jpg)
![20200208_225219](https://user-images.githubusercontent.com/60836961/74097850-d1608d80-4ac5-11ea-8248-546c62c8d116.jpg)
With WS:
![Screenshot_20200208-222838_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74097665-bdb42780-4ac3-11ea-9517-aa893926e63c.jpg)
![20200208_224936](https://user-images.githubusercontent.com/60836961/74097817-69aa4280-4ac5-11ea-9e1f-930a10cbb3e1.jpg)
Without WS:
![Screenshot_20200208-222856_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74097678-d6bcd880-4ac3-11ea-9323-cdfb152eb7fa.jpg)
![20200208_224952](https://user-images.githubusercontent.com/60836961/74097822-74fd6e00-4ac5-11ea-9876-0e23e9b90d4d.jpg)

**Comment by fzurita** [comment]
So you are saying that when in the latest version, disabling the widescreen hack increases the in-game resolution?

**Comment by AH139** [comment]
Yes. I tried switching over to the regular Glide64-Accurate profile, and disabling the widescreen hack in the edited profile. Both made the resolution back to normal (native).

**Comment by fzurita** [comment]
I can confirm that there is an issue GLideN64 widescreen mode. I'll fix it next update.

**Comment by AH139** [comment]
Thanks for the update, much, MUCH appreciated!

**Comment by fzurita** [comment]
Ok, fixed. a2d999d5a7529592b1f9663a67717a304d71b9ec

Next update to the play store will have it.
