### ISSUE TITLE
Animal Crossing problem. Black game menu [Japanese version] Help please

### ISSUE THREAD

**Issue by RuneinA** [mupen64plus-ae/mupen64plus-ae#792]
in animal crossing [Jap] there is a bug when opening the game menu, it comes out black, please fix it.😟

**Comment by RuneinA** [comment]
D;

**Comment by RuneinA** [comment]
![Screenshot_2020-02-09-13-21-23-860_com miui videoplayer](https://user-images.githubusercontent.com/60844000/74101941-25f41f00-4b3f-11ea-950d-fae6cb6a62bf.jpg)

**Comment by fzurita** [comment]
Hello, select the game, go to settings, change the emulation profile to GLideN64-Medium.

**Comment by RuneinA** [comment]
Thanks verte much It work!!!!!
