### ISSUE TITLE
Sudden Low Graphics (Again)?

### ISSUE THREAD

**Issue by AH139** [mupen64plus-ae/mupen64plus-ae#793]
Hello again(unfortunately). The newest update did seem to fix the issue I was having. However, Mario Kart 64's menu still looks fuzzy. I tried switching around profiles again and disabling some cheats to see if they were an influence, to no avail. I even looked at the European version of the game and it has the same issue. Sorry to ask for assistance again, but any help would be very appreciated!

US Version:
![Screenshot_20200209-174854_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74115538-8b0e3b80-4b64-11ea-89e7-936b75c8de7a.jpg)

European Version:
![Screenshot_20200209-174911_M64Plus FZ](https://user-images.githubusercontent.com/60836961/74115549-96f9fd80-4b64-11ea-9f15-0f2eda02859c.jpg)

**Comment by fzurita** [comment]
The update with the fix is not out yet. It will be out soon, hopefully next week sometime.

**Comment by AH139** [comment]
Oh, I'm sorry! I had assumed that the newest update was the one with the fix. I apologize if I came off as impatient! Thanks again for your help and clarification!
