### ISSUE TITLE
Donkey Kong 64 Instant death 

### ISSUE THREAD

**Issue by Sharktough96986** [mupen64plus-ae/mupen64plus-ae#794]
I'm playing Donkey kong 64 on mupen64plus when I Decide to turn on cheats (just infinite health) for a boss in frantic factory (Mad Jack.) Once I beat him, I turned off that cheat but then it crashed once I turned it off. Once I rebooted it I'm getting killed in one hit. I've tried turning the cheat on and off but now I can't see the melons (a health bar.) If anyone can help me please thank you.

**Comment by fzurita** [comment]
Using cheats can have unintended side effects like this unfortunately. I would load from a previous auto save by opening up the in-game menu and choose "Load from auto-save" and go to the earliest one possible and don't turn the cheat on.

If that doesn't work, start the game normally without the cheat and hope that the game was able to save correctly. Using save states within DK64 can corrupt in-game saves.
