### ISSUE TITLE
Add support for extracting textures

### ISSUE THREAD

**Issue by juamnitruh** [mupen64plus-ae/mupen64plus-ae#798]
When i updated the emulator, i was going to the folder to extract some textures, but i cant find the folder!

**Comment by fzurita** [comment]
See my response to your other issue you created.

**Comment by juamnitruh** [comment]
> See my response to your other issue you created.

That means i can't acess it? :( the thing is: when you go in the games .cfg file, you can extract the game's texture.

**Comment by fzurita** [comment]
Yeah, sorry, that's not supported right now. It's very rare that someone wants to extract textures in a phone instead of a computer.

Why do you need to extract textures in a phone?

**Comment by juamnitruh** [comment]
It's because i make sm64 bloopers on android. And i even made a tutorial of
how to extract textures on android in my channel. But now that i can't find
the folder, i can't extract the textures :( btw, when you try to load a
texture in the emulator, it doesnt work. I need to make it manually in the
emulator's folder, but now that i cant find it...
Em 19/02/2020 21:53, "Francisco Zurita" <notifications@github.com> escreveu:

**Comment by fzurita** [comment]
Go to tools then add textures to add your own textures. The textures must be in zip or 7zip format. At the root of the zip file must be a folder with the game header name containing all the textures.

Extracting textures is going to be more difficult. I can't think of a good way of doing it while keeping it compatible with later Android versions.

You can still download the older version here:
https://www.apkmirror.com/apk/francisco-zurita/mupen64plus-fz-n64-emulator/mupen64plus-fz-n64-emulator-3-0-222-beta-release/

I will keep this issue open to try to think of a way to allow extracting textures with later Android version while keeping common code with older versions.

**Comment by juamnitruh** [comment]
Thank you.
Em 19/02/2020 22:25, "Francisco Zurita" <notifications@github.com> escreveu:

**Comment by juamnitruh** [comment]
But i have still one question not aswered. So there is NO WAY to acess the
emulator's folder on the new version? I promisse i will not bother you.
Em 19/02/2020 22:25, "Francisco Zurita" <notifications@github.com> escreveu:

**Comment by fzurita** [comment]
There is no way to access it directly right now. You would need root access to your phone. The data is on private storage now in /data/data/.

The closest you will get us the Import/Export data screen under tools.

**Comment by juamnitruh** [comment]
Ok. Thank you for answering me.
Em 19/02/2020 22:36, "Francisco Zurita" <notifications@github.com> escreveu:

**Comment by strikersix23** [comment]
I might add something here if you have the space you can use [VM OS ](https://www.vmos.com/) which is an android 5.0 rooted envirment to acces the textures this does not use you actual phone system it is recomended at least to havs 6 gigs of storage and 3-4 gigs of ram

**Comment by fzurita** [comment]
Ok, done: d7513f96e78f39c9470908a48552685f5ca29030
