### ISSUE TITLE
Blurry MK64 Title Screen

### ISSUE THREAD

**Issue by AH139** [mupen64plus-ae/mupen64plus-ae#799]
Hello again!
I wasn't sure if the fix for GlideN64's widescreen hack was in a recent update, but just in case it wasn't, I still have a blurry Mario Kart 64 menu. I tried tweaking around with the Display options, and different profiles, but it's very clear to me now that there is an issue with GlideN64's widescreen hack. Once again I ask for your help, so any is much appreciated!

**Comment by fzurita** [comment]
Yeah, there were some issues, and I did address them. I'll double check that screen though.

**Comment by fzurita** [comment]
Can you post a screenshot with examples of the issue? I'm not seeing what the problem is. That screen looks pretty blurry to me even without the widescreen hack.

**Comment by AH139** [comment]
Okay, I'll try to.
With WS:
![Screenshot_20200224-070545_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75163588-5b1e7680-56d4-11ea-935d-49febf665122.jpg)
Without WS:
![Screenshot_20200224-070613_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75163620-65407500-56d4-11ea-9839-d7988bd4db39.jpg)

**Comment by fzurita** [comment]
Yep, I see it, widescreen has additional blurriness. I'll try to check is this is a front end issue or a plug-in issue.

**Comment by fzurita** [comment]
Definitely seems like a plug-in issue. It doesn't seem to be scaling some 2d images correctly when widescreen is enabled.

**Comment by AH139** [comment]
This may be just me, but I think I can also see this issue in Smash Bros, mainly on Captain Falcon's face.
With WS:
![Screenshot_20200225-095835_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75296524-4af4bd00-57e2-11ea-90f5-e1bac0afa357.jpg)
Without WS:
![Screenshot_20200225-095906_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75296529-4fb97100-57e2-11ea-8de0-02f5a79701fb.jpg)

**Comment by fzurita** [comment]
Try turning the resolution up

**Comment by AH139** [comment]
I already have it at Native. The highest resolution I could change without crashing the game was 4K, and it was still the same.

**Comment by AH139** [comment]
Yeah, it worked on Smash. Correct me if I'm wrong, but I think the app is able to put out a larger resolution without the WS, I guess. Just in case, I tried it on MK64 too, with no luck.

**Comment by AH139** [comment]
Update: I may have been wrong. I set Smash to 960 x 720, and changed from the Glide64 Fast with the GlideN64 plugin and WS enabled to the normal Glide64 Fast plugin, and I can see a clear difference in quality between the 2 (again mainly on Captain Falcon's face), even though the resolution is the same between the 2.
With WS:
![Screenshot_20200226-210357_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75414274-dd798700-58dc-11ea-9bad-bb5cdff6329e.jpg)
Without WS:
![Screenshot_20200226-210304_M64Plus FZ](https://user-images.githubusercontent.com/60836961/75414299-ec603980-58dc-11ea-899c-d08e750ecc42.jpg)

**Comment by fzurita** [comment]
All frontend issues related to this should had been addressed. Any remaining issues are plugin related, which is out of control of the front end.
