### ISSUE TITLE
Can't start a rom

### ISSUE THREAD

**Issue by moosje2003** [mupen64plus-ae/mupen64plus-ae#800]
I want to play paper mario and super mario rom hacks and the original games on tendo64
But i get the message mupen64a plus ae is not installed properly plz try reinstalling the app.
But when i did i stil didn't work
![Screenshot_20200229-181829_Tendo64](https://user-images.githubusercontent.com/61630365/75612011-eefea100-5b1f-11ea-94c0-3f671df33251.jpg)

**Comment by fzurita** [comment]
That is an unsupported fork of this app. It's a shame that they still link here for reporting issues.

I recommend you download the version of the app that I support here:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

If you still have the problem in that version, please make another issue.
