### ISSUE TITLE
Paper Mario texture glitch and lag with gliden64 extremely accurate

### ISSUE THREAD

**Issue by Michael18751** [mupen64plus-ae/mupen64plus-ae#802]
Can you fix it with the gliden64 extremely accurate plug in? (because it's the most accurate version) It displays a black border around the partner level up particles and lags the game hard.

If it's not possible to fix this or add the mips support to it then just close the issue.

![Screenshot_20200301-122846_M64Plus FZ](https://user-images.githubusercontent.com/53535277/75631561-95e34b80-5bb9-11ea-8f5c-3d125882c7bb.png)

Device: Virtual
Id: -1
Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
Class: BUTTON

Device: Exynos9610-Audio Headset Jack
Id: 1
Descriptor: f8baf94ae079ed28a5e8014ac2f7904b1ee0656f
Class: BUTTON

Device: gpio_keys
Id: 2
Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
Class: BUTTON

Device: sec_touchscreen
Id: 4
Descriptor: 0fa9d3d0d40f7f5b316320876742e00ad5eb1ba9
Class: BUTTON, POINTER
Axes: 8
  AXIS_X (touchscreen): ( 0.0 , 1079.0 )
  AXIS_Y (touchscreen): ( 0.0 , 2399.0 )
  AXIS_PRESSURE (touchscreen): ( 0.0 , 1.0 )
  AXIS_SIZE (touchscreen): ( 0.0 , 1.0 )
  AXIS_TOUCH_MAJOR (touchscreen): ( 0.0 , 2631.8054 )
  AXIS_TOUCH_MINOR (touchscreen): ( 0.0 , 2631.8054 )
  AXIS_TOOL_MAJOR (touchscreen): ( 0.0 , 2631.8054 )
  AXIS_TOOL_MINOR (touchscreen): ( 0.0 , 2631.8054 )

processor	: 0
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 5
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 6
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

processor	: 7
BogoMIPS	: 52.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd09
CPU revision	: 2

Board: exynos9611
Brand: samsung
Device: a51
Display: QP1A.190711.020.A515FXXU1ASKJ
Host: 21HH1G10
ID: QP1A.190711.020
Manufacturer: samsung
Model: SM-A515F
Product: a51nnxx

**Comment by fzurita** [comment]
It may be possible to fix if you create a custom emulation profile and you enable N64 depth compare. Please try that and let me know if it improves things.
