### ISSUE TITLE
Nightlys

### ISSUE THREAD

**Issue by strikersix23** [mupen64plus-ae/mupen64plus-ae#803]
Possible nightlys based off if github.

**Comment by fzurita** [comment]
It would be nice to have. It wouldn't be that hard to setup.

**Comment by strikersix23** [comment]
Thanks for the fast response. I would suggest
https://www.appveyor.com/

**Comment by strikersix23** [comment]
You could use Travis-ci artifacts

https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by bladeoner** [comment]
Nightly builds are available on the main page:
https://github.com/mupen64plus-ae/mupen64plus-ae

Clicking on the button "Mupen64Plus-AE passing", click the desired commit, and download the "apk" file under Artifacts.

**Comment by strikersix23** [comment]
Thank you for the nightlys it works Im going to close this issue and have a nice day!

**Comment by strikersix23** [comment]
I just looked at the files you might want to only compile debug varient or zip just the outputs/debug

**Comment by strikersix23** [comment]
But good job

**Comment by bladeoner** [comment]
@strikersix23, yes I know I will change that later.
