### ISSUE TITLE
[M64Plus FZ 3.0.238] Stuck on startscreen, storage permission dialog not appearing on Fire TV Stick 4K

### ISSUE THREAD

**Issue by Fereeze96** [mupen64plus-ae/mupen64plus-ae#804]
Hello,
I have the issue that M64Plus FZ 3.0.238 stays stuck on the startscreen on my Fire TV Stick 4K (updated to newest OS version available). The storage permission dialog does not appear like on the older M64Plus FZ 3.0.222 (beta), that works flawlessly. 
All versions after 3.0.222 (beta) have this issue on the fire tv stick.

Please fix this permission problem :)

p.s.

the fire tv stick 4k does **not** allow changing the storage permission settings manually. You must allow it the first time starting the app.

**Comment by fzurita** [comment]
The storage permission is automatically provided with Android 10 and newer as long as the application is being compiled with the latest SDK.

I have a few questions:
What Android version is the Fire TV 4K using?

How are you obtaining the APK that is being side loaded?

Is this a fresh install of the application or are using the app to the latest version?

If you are updating the app to the latest version from 3.0.222, then a migration process has to occur that can take a long time depending on how much data you have in the app. What is happening is that all your data is being copied to internal storage.

**Comment by Fereeze96** [comment]
> What Android version is the Fire TV 4K using?
Android 7.1

> How are you obtaining the APK that is being side loaded?
I downloaded M64Plus FZ 3.0.238 off google play store and installed it via usb flash drive.
Other versions I found from websites like apkmirror

> Is this a fresh install of the application or are using the app to the latest version?
Fresh install. I deleted all previous data before installation  

I noticed an error dialog with not installed properly or something. But it has something to do with the storage permission dialog

**Comment by fzurita** [comment]
Ok, not installed properly means that the app is missing essential data to work correctly so it won't work. Try following these directions to backup the APK:

https://www.reddit.com/r/AndroidTV/comments/c0rcmx/tutorial_how_to_backup_sideload_android_app
