### ISSUE TITLE
failed to open pokemon stadium 2

### ISSUE THREAD

**Issue by BryanBraixen** [mupen64plus-ae/mupen64plus-ae#805]
when opening the rom of pokemom stadium 2 failure appears when opening the rom and closes

**Comment by fzurita** [comment]
Try rescanning for ROMs using the bottom right button.

**Comment by BryanBraixen** [comment]
> Try rescanning for ROMs using the bottom right button.

it doesn't work look :(

**Comment by BryanBraixen** [comment]
![Screenshot_2020-03-16-07-30-14](https://user-images.githubusercontent.com/62227152/76763188-4162d300-6758-11ea-81a8-6c68f8d15a8e.png)

**Comment by BryanBraixen** [comment]
I just installed it, there is nothing that can go wrong with my phone, it is a fault with the emulator

**Comment by fzurita** [comment]
This error means that it's unable to find the ROM, or it's an invalid ROM. My guess is that is probably an invalid ROM.
