### ISSUE TITLE
Cmake build failed 

### ISSUE THREAD

**Issue by strikersix23** [mupen64plus-ae/mupen64plus-ae#807]
mupen64plus-video-angrylion-plus

Fails to build

Gives me an error 
C/C++ debug|x86 failed

**Comment by fzurita** [comment]
On latest commit, everything is building:

https://travis-ci.org/github/mupen64plus-ae/mupen64plus-ae/builds/657107404?utm_medium=notification&utm_source=github_status

Is this on Windows?

**Comment by strikersix23** [comment]
Yes its on windows

**Comment by bladeoner** [comment]
@strikersix23 now that the Nightly builds are available is this still necessary?

I saw in another issue that builds are not working on Windows:
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/814

**Comment by strikersix23** [comment]
This was posted in march the other post was in april
