### ISSUE TITLE
Game froze 

### ISSUE THREAD

**Issue by kimberley2020** [mupen64plus-ae/mupen64plus-ae#809]
Game froze and wont reload , tried reloading and just a black screen , dont want to reset and lose all my progress,  what can I do ? Tried closing game and reloading and closed app and reopened not working

**Comment by fzurita** [comment]
First of all, which app are you using?

Did you use any in-game saves? If the game is starting up in a frozen state, then the only way to recover is to start the game again and load from there last in-game save.

**Comment by fzurita** [comment]
Closing after no response.
