### ISSUE TITLE
Crashes when click settings

### ISSUE THREAD

**Issue by quest666scary** [mupen64plus-ae/mupen64plus-ae#811]
Recently when I try to click on "Settings", it immediatly crashes and returns me to the home screen. Every game I try to click on doesn't work. I need some help with it.

**Comment by fzurita** [comment]
Hello, what version of the app are you using?

This is the most official release on the play store:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

Any others are clones, scams, or outdated.

**Comment by fzurita** [comment]
This should be fixed now.
