### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by icemanyandy** [mupen64plus-ae/mupen64plus-ae#814]
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:150:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:151:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:153:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:155:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:168:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:172:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:181:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:189:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:190:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:191:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:192:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:199:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:220:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:222:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:223:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:231:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:233:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:235:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:236:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:251:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:252:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:255:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:256:20: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:258:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:259:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:274:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:275:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:277:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:278:21: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:285:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:287:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:303:19: error: constant expression expected
D:\MegaN64\mupen64plus-core\upstream\src\device\r4300\new_dynarec\arm\linkage_arm.S:304:20: error: constant expression expected

###     str    r10, [fp, #fp_cycle_count]

GLOBAL_FUNCTION(jump_vaddr):
    str    r10, [fp, #fp_cycle_count]
    ldr    r9,  [fp, #fp_next_interrupt]
    add    r10, r9, r10 /* Count */
    str    r10, [fp, #fp_cp0_regs + 36] /* Count */
    bl     get_addr_ht
    ldr    r10, [fp, #fp_cycle_count]
    mov    pc, r0

**Comment by fzurita** [comment]
Please try building from Linux instead. Windows build are not working right now.

**Comment by icemanyandy** [comment]
> t

thank you sir.

**Comment by bladeoner** [comment]
@icemanyandy Nightly builds are available on the main page:
https://github.com/mupen64plus-ae/mupen64plus-ae

Clicking on the button "Mupen64Plus-AE passing", click the desired commit, and download the "apk" file under Artifacts.

This way you don't have to compile it yourself unless you are trying to add new features.
