### ISSUE TITLE
No respeta las pulsaciones del boton B para mariokart64 y las de el analog up, down, left, right, B y Z para super mario 64 multiplayer

### ISSUE THREAD

**Issue by Tobiasz91** [mupen64plus-ae/mupen64plus-ae#815]
Buenas dias descargue esta app porque me gusto mucho su interfaz y que cuenta con las portadas de cada rom , pero cuando quiero jugar multiplayer con un segundo mando android, la aplicacion no respeta las pulsaciones de los botones asignados en el juego, por ejemplo en mariokart todo funciona bien solo el boton B no lo respeta y al oprimirlo en ocasiones activa el menu para salir del rom, si emulo el rom de super mario 64 multiplayer no funcionan los botones de la palanca analoga, el boton B, Z. 
Cabe mencionar que si utilizo el emulador megan64 v7.0 y mupen64 plus AE v2.4.4, los rom mencionados si funcionan correctamente en todos sus botones asignados utilizando el mismo segundo mando, estos ultimos emuladores los baje porque con ellos si puedo mapear y asignar la funcion de cada boton a mi gusto sin embargo no me gustan para jugar los rom en ellos, para poder conectar el segundo mando android al juego, utilize la app btcontroller para conectarlo mediamte bt o wifi segun mi gusto, podram ayudarme a solucionar mi problema? 
Nota: estaria bien que la app m64plus FZ tenga tambien la opción de poder mapear la funcion de cada boton al gusto del usuario. 

Saludos!

**Comment by fzurita** [comment]
Trata de seguir estás instrucciones para asignar botones a tu controlador:

http://www.paulscode.com/forum/index.php?topic=15812.0

Cuando termines anda a perfiles y seleccionar perfiles. Ahí selecciona "asignar jugadores automáticamente" y "todos los controladores de n64 emulados están siempre conectados.

**Comment by Tobiasz91** [comment]
Hola pero mi mando es mediante otro telefono android, yo estoy utilizando 2 huawei p30 pro para jugar, y segun entiendo las instrucciones que me mandaste son comprando un controlador myflash64 físicamente por lo que no me sirvió, hay una msnera de configurar los botones pero usando un mando android (telefono huaweip30pro)? Enviado desde mi Huawei de Telcel.El 25 abr 2020 5:26 a. m., Francisco Zurita <notifications@github.com> escribió:

Trata de seguir estás instrucciones para asignar botones a tu controlador:

http://www.paulscode.com/forum/index.php?topic=15812.0

Cuando termines anda a perfiles y seleccionar perfiles. Ahí selecciona "asignar jugadores automáticamente" y "todos los controladores de n64 emulados están siempre conectados.

**Comment by fzurita** [comment]
Esas instrucciones funcionan con cualquier celular o controlador.

**Comment by Tobiasz91** [comment]
Claro que si disculpame por mi in experiencia, segui las instrucciones al pie de la letra del enlace que me mandaste y si funciono correctamente y a la perfeccion, y los botones asignados ya no fallan, gracias por contestar rápidamente y por poner atención a los usuarios eso habla bien de ti como desarrollador. PD: para el mando 2 trate de usar la opción (asignar jugadores automaticos) como me dijiste pero esa no funciono, ya que el caracter que se movia era el del jugador 1, por lo que al final la deshabilite y mejor utilize la opción multijugador para asignar el mando 2. Te mandare una captura de lo seleccionado, de la recomendacion que me dijiste posiblemente yo marque algo mal. Muchas gracias por tu ayuda, independientemente de esta ultima opción, el principal problema que tenia si se arreglo, gracias zurita! Tobiasz91. Enviado desde mi Huawei de Telcel.El 25 abr 2020 10:49 a. m., Francisco Zurita <notifications@github.com> escribió:
Esas instrucciones funcionan con cualquier celular o controlador.

**Comment by Tobiasz91** [comment]
Claro que si disculpame por mi in experiencia, segui las instrucciones al pie de la letra del enlace que me mandaste y si funciono correctamente y a la perfeccion, y los botones asignados ya no fallan, gracias por contestar rápidamente y por poner atención a los usuarios eso habla bien de ti como desarrollador. 

PD: para el mando 2 trate de usar la opción (asignar jugadores automaticos) como me dijiste pero esa no funciono, ya que el caracter que se movia era el del jugador 1, por lo que al final la deshabilite y mejor utilize la opción multijugador para asignar el mando 2. Te mandare una captura de lo seleccionado, de la recomendacion que me dijiste posiblemente yo marque algo mal. 

Muchas gracias por tu ayuda, independientemente de esta ultima opción, el principal problema que tenia si se arreglo, gracias zurita!
