### ISSUE TITLE
I damaged my game with a cheat

### ISSUE THREAD

**Issue by RollerGM** [mupen64plus-ae/mupen64plus-ae#816]
I was curious about a hidden place in majora's mask in which I needed the mask of truth and I activated a cheat to have all masks, but then when I tried to remove it to go with the story, I wasn't able to do it and my game is screwed up, so I think I'll have to start from the beginning. Do you think there is any way to fix that or I'll definitely have to do everything all over again?

**Comment by fzurita** [comment]
Once you start the game, open up the in-game menu, and choose "load from autosave". It backs up a save state every time you exit a game. It's possible that you still have any autosave before you used the cheat.

Also, try saving the game within the game and use the start option instead the resume option. That will start the game from your latest in-game save.
