### ISSUE TITLE
No sepuede conectar mas de dos mandos utilizando celular

### ISSUE THREAD

**Issue by Tobiasz91** [mupen64plus-ae/mupen64plus-ae#817]
Buenas tardes, sin problemas puedo jugar con un segundo jugador, pero cuando quiero conectar un tercer mando (android) el emulador lo reconoce como si fuera el player 2!, aun dando de alta el tercer mando en la opcion de controlador y perfiles. Tendras algúna solucion a este issue, posiblemente yo este haciendo algo mal!

Saludos!

**Comment by fzurita** [comment]
Más de dos mandos debería estar funcionando bien.

Selecciona perfiles y después seleccionar perfiles. Ahí habilita "asignar jugadores automáticamente" y "todos los controladores de N64 emulados están siempre conectados"

**Comment by Tobiasz91** [comment]
Asi es como hice siguiendo lo que me describes pero no funciona, de esa forma que mencionas el segundo y tercer mando controlan el segundo jugador solamente y el tercero no se mueve. Te puedo mandar video de pantalla para que puedas apreciar mas detallado. En la opcion de controlador di de alta a cada celular como mando, y en perfiles mando 2 y 3 asigne el nombre del controlador de cada quien (tania y gabriel) pero no funciona! Ya vi que marcaste el reporte como closed pero en verdad no funciona. Enviado desde mi Huawei de Telcel.El 30 abr 2020 4:04 p. m., Francisco Zurita <notifications@github.com> escribió:

Más de dos mandos debería estar funcionando bien.

Selecciona perfiles y después seleccionar perfiles. Ahí habilita "asignar jugadores automáticamente" y "todos los controladores de N64 emulados están siempre conectados"

**Comment by fzurita** [comment]
Te creo que no te está funcionando, pero yo he probado eso muchas veces y se que funciona. Que versión del app estás ocupando? Debería ser está:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Tobiasz91** [comment]
Es correcto esta es la baje del playstore, mis celulares son 2 huawei p30 pro y un samsung, no se si a lo mejor tiene que ver que los 2 mandos estan conectados por bluetooth a mi celular que es el host (p30) Y ahi es porque falle la comunicación de intercambio de datos. Enviado desde mi Huawei de Telcel.El 30 abr 2020 5:20 p. m., Francisco Zurita <notifications@github.com> escribió:

Te creo que no te está funcionando, pero yo he probado eso muchas veces y se que funciona. Que versión del app estás ocupando? Debería ser está:

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by fzurita** [comment]
No entiendo estás ocupando celulares como controladores?

**Comment by Tobiasz91** [comment]
Asi es los dos conectados por bluetooth, solo con uno todo funciona bien pero ya con un tercero es donde ya radica el problema. Cres que sea por eso?, funciona bien con solo con controles fisicos? Enviado desde mi Huawei de Telcel.El 30 abr 2020 7:18 p. m., Francisco Zurita <notifications@github.com> escribió:

No entiendo estás ocupando celulares como controladores?

**Comment by fzurita** [comment]
Si, funciona bien con controladores físicos.
