### ISSUE TITLE
Mupen64 FZ Plus Bug - Mischief Makers

### ISSUE THREAD

**Issue by TheCheeseBear98** [mupen64plus-ae/mupen64plus-ae#818]
Noticed that on the level 5-7 "Inner Struggle"  the words on the bubbles are invisible, making it impossible to find the gold gem. Would like to know if theres a fix to make the words appear on that level.

**Comment by fzurita** [comment]
Yeah, select the game, go to settings, change the emulation profile to GLideN64-Medium.
