### ISSUE TITLE
build error - fatal error: 'asm_defines_gas.h' file not found

### ISSUE THREAD

**Issue by kakimsun** [mupen64plus-ae/mupen64plus-ae#819]
macOS Catalina ,  build error :   /mupen64plus-ae/mupen64plus-core/upstream/src/device/r4300/new_dynarec/arm/linkage_arm.S:69:10: fatal error: 'asm_defines_gas.h' file not found

**Comment by fzurita** [comment]
Make sure that the gawk and awk are present in your environment.
