### ISSUE TITLE
Error In Selecting Button Skins

### ISSUE THREAD

**Issue by IsAndres7w7** [mupen64plus-ae/mupen64plus-ae#821]
There is an error that does not allow adding the skins downloaded or created to the Mupen64Plus FZ emulator here is my screenshot option Selecting skin does not work I hope you fix this soon Regards: IsAndres7w7
![Screenshot_2020-05-15-09-12-30](https://user-images.githubusercontent.com/65406854/82060031-6ad2a900-968c-11ea-834c-8fb950628ed2.png)
![Screenshot_2020-05-15-09-12-36](https://user-images.githubusercontent.com/65406854/82060059-74f4a780-968c-11ea-92d2-b3fb55dad84d.png)
![Screenshot_2020-05-15-09-12-40](https://user-images.githubusercontent.com/65406854/82060088-81790000-968c-11ea-8f27-111d94e2953b.png)
![Screenshot_2020-05-15-09-12-44](https://user-images.githubusercontent.com/65406854/82060107-876ee100-968c-11ea-93fe-1eb84183dfa7.png)
If you notice I have select all the buttons but they do not appear on the screen

**Comment by fzurita** [comment]
It's not very intuative right now. Once you choose custom. Go to Tools, then import/export data. In there, choose "import touchscreen graphics". You will then have to choose a zip file containing the graphics. Also, the zip file must contain all the right files, if it doesn't, it won't work.

**Comment by fzurita** [comment]
These are the list of files that the code checks for:
```
        mValidSkinFiles.add("analog-back.png");
        mValidSkinFiles.add("analog-fore.png");
        mValidSkinFiles.add("analog.png");
        mValidSkinFiles.add("buttonL-holdL.png");
        mValidSkinFiles.add("buttonL-mask.png");
        mValidSkinFiles.add("buttonL.png");
        mValidSkinFiles.add("buttonR-holdR.png");
        mValidSkinFiles.add("buttonR-mask.png");
        mValidSkinFiles.add("buttonR.png");
        mValidSkinFiles.add("buttonS-holdS.png");
        mValidSkinFiles.add("buttonS-mask.png");
        mValidSkinFiles.add("buttonS.png");
        mValidSkinFiles.add("buttonSen-holdSen.png");
        mValidSkinFiles.add("buttonSen-mask.png");
        mValidSkinFiles.add("buttonSen.png");
        mValidSkinFiles.add("buttonZ-holdZ.png");
        mValidSkinFiles.add("buttonZ-mask.png");
        mValidSkinFiles.add("buttonZ.png");
        mValidSkinFiles.add("dpad-mask.png");
        mValidSkinFiles.add("dpad.png");
        mValidSkinFiles.add("fps-0.png");
        mValidSkinFiles.add("fps-1.png");
        mValidSkinFiles.add("fps-2.png");
        mValidSkinFiles.add("fps-3.png");
        mValidSkinFiles.add("fps-4.png");
        mValidSkinFiles.add("fps-5.png");
        mValidSkinFiles.add("fps-6.png");
        mValidSkinFiles.add("fps-7.png");
        mValidSkinFiles.add("fps-8.png");
        mValidSkinFiles.add("fps-9.png");
        mValidSkinFiles.add("fps.png");
        mValidSkinFiles.add("groupAB-holdA.png");
        mValidSkinFiles.add("groupAB-holdB.png");
        mValidSkinFiles.add("groupAB-mask.png");
        mValidSkinFiles.add("groupAB.png");
        mValidSkinFiles.add("groupC-holdCd.png");
        mValidSkinFiles.add("groupC-holdCl.png");
        mValidSkinFiles.add("groupC-holdCr.png");
        mValidSkinFiles.add("groupC-holdCu.png");
        mValidSkinFiles.add("groupC-mask.png");
        mValidSkinFiles.add("groupC.png");
        mValidSkinFiles.add("skin.ini");
```
