### ISSUE TITLE
Compile error Android Studio 3.6.3 and NDK 21

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#823]
Hi @fzurita, I'm getting the following error, when compiling with Android Studio 3.6.3 and NDK 21, I can download the appropriate version v20. Is is possible to get it to work with the latest NDK?

Thanks in advance.

> Configure project :ae-bridge
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.1.6352462

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ae-bridge'.
> NDK not configured. Download it with SDK manager. Preferred NDK version is '20.0.5594570'. Log: /home/shinotek/Downloads/mupen64plus-ae-master/ae-bridge/.cxx/ndk_locator_record.json

**Comment by fzurita** [comment]
Hmm, that's an odd one. The build should be working on work NDK21. I have Travis configured to use NDK21 and it's working ok.

**Comment by fzurita** [comment]
This is the Travis config:

https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/.travis.yml

There is probably some misconfiguration in your end.

**Comment by bladeoner** [comment]
@fzurita under File, Project Structure, Android NDK Location was not filled in.

I think it was using an old reference somewhere, it works now, thank you!
