### ISSUE TITLE
M64 PLUS FZ WILL NOT READ ANY FILES

### ISSUE THREAD

**Issue by Doctorbleachers** [mupen64plus-ae/mupen64plus-ae#825]
Download this nintendo 64 emulator a week ago and today 5/27/2020 i decided to fire it up 
looking into the settings i went to scan for my roms the roms did not appear in the app but when i exit the app i can see them in the folder. Then i tried going in the folder with the app 
closed and it would not give me an option so i figured it could be a promission problem and that was not the problem anyone have any ideas? The system i am on is Nvidia shield android.

**Comment by fzurita** [comment]
I have a NVidia shield and I don't have any problems searching for my ROMs.

Make sure you are using the "Refresh ROMs" option under the menu.
