### ISSUE TITLE
That damn banana fairy in gloomy galeon

### ISSUE THREAD

**Issue by mihailo26** [mupen64plus-ae/mupen64plus-ae#826]
So I play dk64 using my muppen64 on Android
Then when I tried to take a picture of the bana fairy in the jail cell no matter what it wouldn't work
Now I know what you gotta say "but just use another n64 plug-in besides glide64" but you have to remember that I'm playing dk64 on an ANDROID emulator. No matter what I did it didn't work. Please someone tell me how the hell am I supposed to fix this issue in mobile

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to GLideN64-Medium or Software renderer
