### ISSUE TITLE
That damn banana Fairy in gloomy galleon

### ISSUE THREAD

**Issue by mihailo26** [mupen64plus-ae/mupen64plus-ae#827]
So I was playing DK64 with my **_Android_** muppen64 emulator when I got to the point at the game where I had to take a photo of a banana fairy through the bars, no matter what I did it wouldn't respond. Remember I am na Android muppen64 user and a lack of an option to change from glide64 to something else just kills it for me
Please tell me how to fix this on Android

**Comment by fzurita** [comment]
Hello, I answered to your previous issue and closed it. This my response again:

Select the game, go to settings, change the emulation profile to GLideN64-Medium or Software renderer
