### ISSUE TITLE
Why is muppen64 replacing buttons

### ISSUE THREAD

**Issue by mihailo26** [mupen64plus-ae/mupen64plus-ae#828]
So I usually go and connect my games to my controller via Bluetooth with my controller profile and when I reconnect the controller again, for some reason the layout automatically changes (the dpad turns into the joystick and vias versa) I know this was a problem with the built in controllers but why does this keep happening Day by day
Please someone explain how to fix this issue

**Comment by fzurita** [comment]
I'm sorry, but it's hard to understand what you are asking here.

You can follow this guide to map controllers;

http://www.paulscode.com/forum/index.php?topic=15812.0
