### ISSUE TITLE
Hielp

### ISSUE THREAD

**Issue by mihailo26** [mupen64plus-ae/mupen64plus-ae#829]
You know in Banjo-tooie where you have to move super slowly by slightly pushing the stick for 2 jiggies, well the emulator doesn't allow my controller to do that, it only goes normally, even if you push slightly on the stick
If someone tells me how to do that I will be very thankful

**Comment by fzurita** [comment]
Is this with a real controller or touchscreen controller?

**Comment by mihailo26** [comment]
I'm using a Bluetooth controller so probably the former

**Comment by mihailo26** [comment]
Do you litteraly have no comment

**Comment by fzurita** [comment]
Does it work correctly when using the touchscreen controller?

**Comment by mihailo26** [comment]
Yes, but  I want to the same thing with my Bluetooth controller, like is
there an option in either the controller profile or the input settings

**Comment by fzurita** [comment]
The problem use probably that your Bluetooth controller is too sensitive. 

Go to profiles then controller. In there use the top right button to create a new profile. You will be able to map all the buttons there. Once done use the top right menu and adjust the x and y axis sensitivity to your liking. Go back to the main screen then go to profiles then select profiles. Select the profile you created.
