### ISSUE TITLE
External game data support missing when using Pro on Nvidia Shield TV

### ISSUE THREAD

**Issue by thebeardedchild** [mupen64plus-ae/mupen64plus-ae#830]
I bought the pro version specifically to use external game data support. This works on my phone (Galaxy S8+), but the options disappear when using my Nvidia Shield Android TV. 

When I open Settings > Data, the two options labeled "Game data storage location", and "External game data location" flash for a second, then disappear. 

My ROMs are on the external sdcard in my Shield, so I know the app can access the ext sd.

**Comment by fzurita** [comment]
This is a known issue and will be fixed in the next release.

**Comment by thebeardedchild** [comment]
> This is a known issue and will be fixed in the next release.

Awesome, that's a huge relief, thanks so much!
