### ISSUE TITLE
App fails to scan for ROMs - some sort of incompatibility with newer Android Versions(?)

### ISSUE THREAD

**Issue by BlueManThetys** [mupen64plus-ae/mupen64plus-ae#831]
When I try "Refresh ROMs" or otherwise use the File Picker, it will just... not work. An hourglass and a "Can't load content at the moment" message appears.
I previously didn't have this issue, so I'm assuming it has to do with some latest update screwing things up.

Note: I'm a Samsumg user.
![Screenshot_20200615-201833_Files](https://user-images.githubusercontent.com/36064175/84651737-6c221a80-af45-11ea-9753-91d692c49209.jpg)

**Comment by fzurita** [comment]
Have you tried pushing that "allow access to downloads" button?
