### ISSUE TITLE
App fails to scan for ROMs - some sort of incompatibility with newer Android versions(?)

### ISSUE THREAD

**Issue by BlueManThetys** [mupen64plus-ae/mupen64plus-ae#832]
When I try "Refresh ROMs" or otherwise use the File Picker, it will just... not work. An hourglass and a "Can't load content at the moment" message appears.
I had already enabled the app to view my files when I had first opened it, nonetheless I did try press on "Allow access to downloads" - but it did not work - still the same "Can't load content at the moment". I have also went to my settings to see whether the app was permitted to see my storage, and it says it is permitted to do so, and that it isn't denied any permissions.

Note: I'm a Samsumg user.
![Screenshot_20200615-201833_Files](https://user-images.githubusercontent.com/36064175/84651737-6c221a80-af45-11ea-9753-91d692c49209.jpg)
![Screenshot_20200615-213905_Permission controller](https://user-images.githubusercontent.com/36064175/84658383-c674a880-af50-11ea-8f95-e1a5204f7faa.jpg)

**Comment by fzurita** [comment]
Please don't make a new issue... Try clicking on the hamburger menu on the top left corner and selecting where your ROMs are stored. If you can't see that, use the top right button to make sure that external storage is displayed.

**Comment by BlueManThetys** [comment]
Thanks, the issue has been resolved.

Android's file navigator's UI was confusing for me it seems, with its "Downloads" section that is somehow separate from /sdcard/Download.
