### ISSUE TITLE
GlideN64 don't work for me

### ISSUE THREAD

**Issue by MX10-AC2N** [mupen64plus-ae/mupen64plus-ae#834]
Hi,
I use Mupen64plus-ae on android tv 9 with mali 450 for GPU and I can't use GlideN64, only work with other Glide64 or Gln64 or Rice..
Why cannot use GlideN64 ?
Can you make a new build (*.apk) maybe I use a old version..
Please help..
Thank a lot for all..

**Comment by fzurita** [comment]
This is probably an issue work your device. Good you try all the GLideN64 profiles?

The older version can be found here:

https://www.apkmirror.com/apk/francisco-zurita/mupen64plus-fz-n64-emulator/mupen64plus-fz-n64-emulator-3-0-222-beta-release/

**Comment by MX10-AC2N** [comment]
thanks, I will try with the older version if GlideN64 work on my device MX10-Tvbox.
