### ISSUE TITLE
Android Studio error before compiling

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#835]
Hi @fzurita I'm getting these errors in Android Studio before compiling, do you have any idea?

/home/user/Downloads/mupen64plus-ae-master/mupen64plus-video-angrylion-plus/upstream/CMakeLists.txt : C/C++ debug|x86 : CMake Error at /home/user/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Git (missing: GIT_EXECUTABLE)
Call Stack (most recent call first):
  /home/user/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/user/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindGit.cmake:83 (find_package_handle_standard_args)
  CMakeLists.txt:45 (find_package)

/home/user/Downloads/mupen64plus-ae-master/mupen64plus-video-angrylion-plus/upstream/CMakeLists.txt : C/C++ debug|x86 : Configuration failed.
executing external native build for cmake /home/user/Downloads/mupen64plus-ae-master/mupen64plus-video-angrylion-plus/upstream/CMakeLists.txt

Thanks in advance.

**Comment by fzurita** [comment]
I haven't had that error before, but it seems to suggest that CMake can't find git. So I'll as the follow-up question, do you have git installed?

**Comment by bladeoner** [comment]
Okay, seems you where right, I just build a new machine with Linux Mint 20, Git doesn't seem to be installed by default.

Thanks for your quick response and help!
