### ISSUE TITLE
The game locks up after a long time playing

### ISSUE THREAD

**Issue by GlimmerDS** [mupen64plus-ae/mupen64plus-ae#838]
They have been happening to me twice, I am playing very quietly and nothing else suddenly the game gets stuck and puts a black screen and it does not happen from there, the worst? that the autosave files are useless starting the game from a manual point that automatic

**Comment by fzurita** [comment]
What game is he having this issue?

**Comment by GlimmerDS** [comment]
> ¿Qué juego tiene este problema?

WWF No Mercy

**Comment by Kanan-Jarrus** [comment]
A mí me acaba de pasar con The Legend of Zelda ocarina of time, alguien sabe que puedo hacer?

**Comment by ferchon071256** [comment]
Igual a mi me pasó con Zelda

**Comment by fzurita** [comment]
For WWF no mercy, please try the "ignore TLB exceptions" option that was recently added. It can be found if you select the game, go to settings, then advanced.
