### ISSUE TITLE
M64 Plus FZ.  Metadata not downloading

### ISSUE THREAD

**Issue by xsxavier** [mupen64plus-ae/mupen64plus-ae#840]
Using M64 Plus FZ when importing Roms cover art and Metadata no longer seems to download, it get stuck for ages and afterwards nothing is added/found. Perhaps the metadata server is down? This is on a Nvidia shield 2017. I had no problems a few days ago on my other shield.

It is a decent amount of Roms at once, about 100.

**Comment by fzurita** [comment]
Yeah, server is down due to hardware failure. I ordered some replacement parts that's I should have by tomorrow.

**Comment by xsxavier** [comment]
Alright, thanks for the information and quick response!

**Comment by fzurita** [comment]
Server should be backup, let me know if there are any issues.
