### ISSUE TITLE
Error en Zelda ocarina of time

### ISSUE THREAD

**Issue by Kanan-Jarrus** [mupen64plus-ae/mupen64plus-ae#841]
Estaba haciendo la misión de entregar las gotas al goron gigante pero fallé, y al salir de kakariko el juego se quedaba congelado, aunque la música seguía avanzando, después de intertarlo varias veces noté que se quedaba así al intentar salir al páramo y solo de adulto, alguien que me pueda ayudar?

**Comment by fzurita** [comment]
Eso pasa si ocupas cheats. Tienes que siempre guardar dentro del juego y ocupa la opción de Iniciar en vez de Reanudar.
