### ISSUE TITLE
When I start any game, is in black screen

### ISSUE THREAD

**Issue by MiithStraker** [mupen64plus-ae/mupen64plus-ae#842]
Before it worked normally,The game starts with sound, but the screen it black. 
I tried to change the Video settings but the error continues.

**Comment by ceofzelda** [comment]
I'm also experiencing the same issue

**Comment by fzurita** [comment]
Instead of resuming a game, choose the start option.

**Comment by fzurita** [comment]
I didn't get any responses. I can't help troubleshoot without responses. So closing for now.

Also, there are known issues with the core that we can't do anything about when using save states instead of in-game saves.

Try to use the "start" instead of "resume" option to prevent such issues.
