### ISSUE TITLE
Cover art not downloading?

### ISSUE THREAD

**Issue by pelerin099** [mupen64plus-ae/mupen64plus-ae#843]
When importing new games, M64plus fz successfully will import each individual .n64 file but hangs on cover art downloads. Each download (internally) seems to time out, and each rom entry has [!] next to it. I have tried manually adding cover art, but it does not work. Any advice?

**Comment by fzurita** [comment]
Server is down right now. I'm working on it.

**Comment by fzurita** [comment]
Server should be backup, let me know if there are any issues.
