### ISSUE TITLE
Cheat codes freezing games

### ISSUE THREAD

**Issue by twiztedbeing** [mupen64plus-ae/mupen64plus-ae#844]
I can't seem to play 2 of my favorite games, banjo 1 and 2 with cheats because the moment a cutscene takes place. It freezes and can no longer play. Anyone have a fix for this?

**Comment by fzurita** [comment]
That is an unfortunate side effect of using cheats. You would have to find an updated version of the cheat that doesn't cause the game to freeze. Unfortunately that is not something I can provide.
