### ISSUE TITLE
Saves to all slots disappeared

### ISSUE THREAD

**Issue by PULFORDASH** [mupen64plus-ae/mupen64plus-ae#846]
On paper Mario I had saves to slot 0 and slot 1. Both are not working. Opening the rom from the library now produces a black screen.

Need to restart the game but I've no idea if I save it the whole thing will happen again.

**Comment by fzurita** [comment]
This is a known issue with that game. Save states are not reliable. Please use in-game saves and always choose the start option.

**Comment by PULFORDASH** [comment]
Thanks so much for replying and letting me know. I appreciate it.
