### ISSUE TITLE
Inserting Codes

### ISSUE THREAD

**Issue by DeadlyRiceGD** [mupen64plus-ae/mupen64plus-ae#847]
Is there a way to enter GameShark or a sort of game cheat code into a game while playing it?

**Comment by fzurita** [comment]
Select the game then go to cheats. In there, you can enable cheats and add your own cheats codes is you want.

**Comment by DeadlyRiceGD** [comment]
Do I put the code in address or value?

**Comment by DeadlyRiceGD** [comment]
Do I put the code in address or value?

**Comment by fzurita** [comment]
Each coffee has an address and a value. First 8 numbers are the address and next 4 are the value. Valid letters in each code are only ABCDEF.
