### ISSUE TITLE
In the cheat menu does the code go in address or value?

### ISSUE THREAD

**Issue by DeadlyRiceGD** [mupen64plus-ae/mupen64plus-ae#848]

**Comment by DeadlyRiceGD** [comment]
The code I have has letters in it but I can't enter them,  why?

**Comment by fzurita** [comment]
The only letters allowed are A, B, C, D, F. What is the code that you are trying to enter?

**Comment by fzurita** [comment]
Closing this since it's more of a question than an issue.
