### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by drwBR** [mupen64plus-ae/mupen64plus-ae#849]
It starts the game ok but aftes some instants the game crashes. I already tried the change profile thing to gliden64-medium. The issue is related to my phone samsung galaxy a 10 model almost for sure. Please help!

**Comment by fzurita** [comment]
Which game is it?

**Comment by drwBR** [comment]
First of all I like to express my admiration for your amazing work. I'm having a real great experience with your app.Thanks for replying. I just noticed that some games don't crash in this model of phone (samsung galaxy a 10)just now. But when I tested quake 1 and tony hawk pro skater 1 with both of them that crash issue happened. I tested  many emulation profiles and nothing changed. Many thx. Have a great week.
________________________________

**Comment by fzurita** [comment]
Ok, first of all, are you using this version of the app? https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

There are a lot of clones out there.

**Comment by drwBR** [comment]
M64PluFZ pro 3.0.238 - pro

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
Ok, I'm not seeing any crashes on those games, what specific version of the games are they and at what point are the games crashing?

**Comment by drwBR** [comment]
They crash at random points. But changing the emulation profile is helping and if I keep saving the game constantly the problem hurts way less. Also changing the emulation profile alows to solve a underwater bug issue on quake 1.
I don't know the version of the games. But on quake it says(u) [!] or (u) [o1]And tony hawk's pro skater is (u) (v1.0) [!].
Again, this only happened in this model of phone that I recently purchased.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
I do know that Adreno GPUs have some driver bugs that make the app crash. But it should only affect Glide64mk2 based emulation profiles. GLideN64 based profiles shouldn't crash.

**Comment by fzurita** [comment]
Is the latest version any better with the crashing?

**Comment by drwBR** [comment]
Can't find the latest version in the app store, could you please send me a link or something?
________________________________

**Comment by fzurita** [comment]
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by fzurita** [comment]
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita.pro

**Comment by drwBR** [comment]
Thank you very much, but it is still crashing. It is this shitty over priced piece of shit of phone. Your work is great. "Working" at work here. Lol. Have a good sunday.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
