### ISSUE TITLE
Widescreen hack?

### ISSUE THREAD

**Issue by twilde214** [mupen64plus-ae/mupen64plus-ae#850]
GlideN64 evidently supports a widescreen hack. How do we implement this in mupen64?

**Comment by fzurita** [comment]
It's already implemented, but you have to make a custom emulation profile. Go to profiles then emulation, select any of the GLideN64 ones and hit copy. Give it a name and hit ok. You will be able to edit parameters for GLideN64 there, including enabling the widescreen hack.

Once done, go back to the game list, select the game where you want the widescreen hack, go to settings, and change the emulation profile to the one you created.
