### ISSUE TITLE
Desligando

### ISSUE THREAD

**Issue by marcolmendes** [mupen64plus-ae/mupen64plus-ae#852]
No jogo Zelda: ocarina of the time, quando encontra as lentes da verdade, ela quando é usada desliga o app.

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to GLideN64-Medium.

**Comment by marcolmendes** [comment]
did not work!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fzurita** [comment]
I'm very sure that will work, it has worked for every case I have known so far. Select the game, go to settings, change the emulation profile to GLideN64-Medium.

Tenho certeza de que funcionará, funcionou para todos os casos que conheci até agora.  Selecione o jogo, vá em configurações, altere o perfil de emulação para GLideN64-Medium.

**Comment by marcolmendes** [comment]
Ok

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by marcolmendes** [comment]
[Image][Image][Image]
________________________________

**Comment by marcolmendes** [comment]
A imagem fica de cabeça pra baixo

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by marcolmendes** [comment]
[Image]
________________________________
