### ISSUE TITLE
in dk64 why cant i get the dk coins

### ISSUE THREAD

**Issue by sammybam88** [mupen64plus-ae/mupen64plus-ae#855]
in the training barrels I need to get them but donkey kong won't pick them up he just goes through

**Comment by fzurita** [comment]
Are you using any cheats?

**Comment by sammybam88** [comment]
no and it still won't collect

**Comment by fzurita** [comment]
Which version of the game are you using?

**Comment by fzurita** [comment]
I'm unable to reproduce this issue. Is this in the beginning area?

**Comment by fzurita** [comment]
Closing unless I get a response.
