### ISSUE TITLE
when I select a game and choose settings it crashes

### ISSUE THREAD

**Issue by jkrdud3** [mupen64plus-ae/mupen64plus-ae#857]
I've tried to select settings to fix another problem I had, but now settings makes the emulator crash

**Comment by fzurita** [comment]
Which version of the app are you using?

**Comment by fzurita** [comment]
It should be this one: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by jkrdud3** [comment]
I just uninstalled and reinstalled and I still got the same problem

**Comment by fzurita** [comment]
For all games or just that one game?

**Comment by jkrdud3** [comment]
I only have that one game.
p.s sorry for late reply just got back from work

**Comment by fzurita** [comment]
And which game is it?

**Comment by jkrdud3** [comment]
pokemon puzzle league

**Comment by jkrdud3** [comment]
I just downloaded another one and when i chose settings on that one the same thing happened

**Comment by fzurita** [comment]
Which device and Android version do you have? This still allow me to find the automatic crash report.

**Comment by fzurita** [comment]
Are you on a chromebook?

**Comment by jkrdud3** [comment]
yes

**Comment by fzurita** [comment]
Ok, that's probably why. I need to get a hold of a chromebook to
investigate why that is happening.

**Comment by fzurita** [comment]
This should be fixed now.
