### ISSUE TITLE
Pilotwings 64

### ISSUE THREAD

**Issue by Omie666** [mupen64plus-ae/mupen64plus-ae#859]
Hey guys thanks for such great work. Huuuge fan here. I swear I searched uo and down for years but i have always had a problem with Pilotwings64 theres a black square undeeneath the handglider once gliding over terrain. It makes the game unplayable. Any solutions here that i may have overlooked?

**Comment by fzurita** [comment]
Select the game, go to settings, and change the emulation profile to at least GLideN64-Accurate.

**Comment by fzurita** [comment]
No problem!
