### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by Luckychris2445** [mupen64plus-ae/mupen64plus-ae#868]
Every time I load up a game it crashes and sends me back to the menu.

**Comment by fzurita** [comment]
First, is this the app you are using?

https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

Next, is it with all games? Have you tried changing emulation profiles?

**Comment by Luckychris2445** [comment]
Yeah I use it and tried fixing the profiles but that doesnt work

**Comment by Luckychris2445** [comment]
and yea its all games

**Comment by fzurita** [comment]
What phone do you have? Has this issue always been there or something new?

**Comment by Luckychris2445** [comment]
Im using a chrome book and yes its new

**Comment by fzurita** [comment]
Ok. Which chromebook do you have?

**Comment by Luckychris2445** [comment]
Samsung Notebook

**Comment by Luckychris2445** [comment]
![image](https://user-images.githubusercontent.com/69257011/97762498-1e1a4780-1adf-11eb-99d2-7e1e4b34196b.png)

**Comment by fzurita** [comment]
Ok, I have been trying the app on chromebooks, and I have not had any issues. But there are so many devices or there, issues inevitably show up.

I will see if I can find your crash report on Google play.

**Comment by fzurita** [comment]
Well, I found your crash reports. It's definitely something I'm not experiencing here.

All I can think of is that your installation is corrupt. If you already have game data, go to Tools-->Import/Export Data, and choose "export game data". That will save all your game data so that you don't lose it. Then, uninstall, then reinstall the application. After that, import the GameData that got exported.

**Comment by Luckychris2445** [comment]
Ight thanks

**Comment by ludvigng** [comment]
Same here. Tried reinstalling the app, still crashes regardless of emulation profile used. Tried Majora's Mask and Ocarina of Time. Running on a chromebook, Asus flip C213, stable channel, board reef.

**Comment by fzurita** [comment]
Yeah, I have narrowed this down to chromebooks that run the app in a 32 bit x86 environment. This is very hard to find devices to test with, but I'm trying to find something.

**Comment by ludvigng** [comment]
> Yeah, I have narrowed this down to chromebooks that run the app in a 32 bit x86 environment. This is very hard to find devices to test with, but I'm trying to find something.

Shouldn't that be most of them at the moment though? I think 64-bit support is set for whenever they update to android 11 at the moment, except for pixel devices, but I could absolutely be wrong.

**Comment by fzurita** [comment]
The pixelbook I have runs apps in a 64 bit x86 Android environment.

**Comment by fzurita** [comment]
Can you please try the latest version in the play store to see if the problem was addressed?

**Comment by ludvigng** [comment]
> Can you please try the latest version in the play store to see if the problem was addressed?

Yes, updated this morning now everything seems to be in order. Tried Ocarina of Time, Majora's Mask and Perfect Dark, with both Glide64 and GlideN64. No issues that I could see.

Thank you very much!
