### ISSUE TITLE
Super Mario 64 Europe artbox is wrong

### ISSUE THREAD

**Issue by azoreseuropa** [mupen64plus-ae/mupen64plus-ae#869]
I used Europe version and it downloaded wrong art box. The art box is American version. can you fix it ? The Europe version supposed to be like this: 

![unnamed](https://user-images.githubusercontent.com/16481778/97800947-b40db980-1c28-11eb-81d2-e15e6852d581.png)

**Comment by fzurita** [comment]
Yeah, the app doesn't currently make a distinction for cover art between different region games other than Japanese games,

**Comment by azoreseuropa** [comment]
> Yeah, the app doesn't currently make a distinction for cover art between different region games other than Japanese games.

What should I do ? I can't find the wrong one so I can replace it in android.

**Comment by fzurita** [comment]
Select the game, go to settings, and you can change the cover art there.

**Comment by azoreseuropa** [comment]
> Select the game, go to settings, and you can change the cover art there.

Thank you! It works!
