### ISSUE TITLE
Some games just keep crashing no matter the profile i use

### ISSUE THREAD

**Issue by gabolos** [mupen64plus-ae/mupen64plus-ae#871]
I have a Samsung Galaxy A01 with Android 10, I've tried everything but most games just keep crashing, the only game that works fine with no issues is Mario 64, F-Zero X crashes before I finish the first lap of Mute City. I dont know why it happens, I had a really old phone before and that worked perfectly, but now that I have a much more capable phone, it just doesn't

**Comment by fzurita** [comment]
Can you give me an example of a game that crashes?

**Comment by fzurita** [comment]
Actually, go to profiles then "select profile". Try changing your default emulation profile to GLideN64-Medium.

**Comment by gabolos** [comment]
GLideN64 medium is too laggy on my phone but doesn't seem to crash. All the other profiles do. Guess I'll just give up

**Comment by fzurita** [comment]
Try going to settings then display and turn off the hybrid filter.

**Comment by gabolos** [comment]
It is turned off

**Comment by fzurita** [comment]
Ok. Did it improve performance with GLideN64?

**Comment by gabolos** [comment]
Not at all actually

**Comment by fzurita** [comment]
Yeah, unfortunately there is not much I can do. Your phone probably has poor GPU drivers. The best I can say is to try different emulation profiles until you find one that doesn't crash and doesn't have too many bugs.
