### ISSUE TITLE
Bug in Perfect Dark in Mupen64 FZ

### ISSUE THREAD

**Issue by DarkSoul-12** [mupen64plus-ae/mupen64plus-ae#872]
I found a bug in perfect dark using the glide64 plugin, when some guard punch me or make a close attack, the game runs ultra slow at 1fps, this not happen in other video plugin or in the beta 3.0.222 version, someone knows how to fix it, cuz is Glide64 the best plugin for my phone

**Comment by fzurita** [comment]
Unfortunately, glide64mk2 is obsolete and no longer being updated. The only plugin actively bring worked on is GLideN64. Your only option is to try GLideN64-Fast out GLideN64-Medium if you want to avoid the slow down.
