### ISSUE TITLE
Can't overwrite mupen64plus-ae?

### ISSUE THREAD

**Issue by spotanjo3** [mupen64plus-ae/mupen64plus-ae#873]
Every time I want to update mupen64plus-ae.. I have to uninstalled it and reinstall a new one. Can't you do something about overwrite it instead of uninstall it first and install a new update ?

**Comment by fzurita** [comment]
This probably means that our nightly builds are using a different signing key each time. It shouldn't be too difficult to address.

**Comment by fzurita** [comment]
All builds after this commit will now use the same signing key: a9eeab6daddac36a19ce7c8915af97fa3e15901f
