### ISSUE TITLE
Query - Which version should offer the best performance for devices without GLES1.3 support

### ISSUE THREAD

**Issue by pootinanny** [mupen64plus-ae/mupen64plus-ae#876]
Currently I've been testing multiple builds and it seems that builds from between June 2018 and July 2019 seem to net the best performance on older devices (GLES1.2 locked, with android 6 or 8).

I was wondering if later builds become too reliant on hardware rendering with more up to date chipsets, or if there is something you can pinpoint that may be the cause of the lower performance on newer builds?

I'm wanting to rebase to an older build, then slowly see what additonal performance i can net by stripping out functions the hardware can't support.

**Comment by fzurita** [comment]
This depends a lot and what plugins you are using. If you have been using glide64mk2 for the video plugin, then that really has never changed.

The core has changed a good amount, doodle when it comes to timing. Improved timing can make performance worse.

If you are using GLideN64 video plugin, then that has been improving in accuracy at the cost of performance.

It would be good if you could pin point which commit exactly made performance much worse.
