### ISSUE TITLE
fatal error: 'asm_defines_gas.h' file not found

### ISSUE THREAD

**Issue by RodrigoZid** [mupen64plus-ae/mupen64plus-ae#877]
When I go to Build -> Make Project, I get this error:

fatal error: 'asm_defines_gas.h' file not found

**Comment by fzurita** [comment]
Make sure you have gawk installed.

**Comment by RodrigoZid** [comment]
It worked, but now I'm having a lot of errors in the linkage_arm64.S file:

error: index must be an integer in range [-256, 255].

GLOBAL_FUNCTION (jump_vaddr):
     str w20, [x29, #fp_cycle_count]
     ldr w18, [x29, #fp_next_interrupt]
     add w20, w18, w20 / * Count * /
     str w20, [x29, # fp_cp0_regs + 36] / * Count * /
     bl get_addr_ht
     ldr w20, [x29, #fp_cycle_count]
     br x0

**Comment by fzurita** [comment]
Can you post your whole build log as a text document?
