### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#882]
@fzurita after the PR yesterday I looked into the build, I saw your Github Workflow also downloaded NDK 22:
https://github.com/mupen64plus-ae/mupen64plus-ae/runs/1622663849?check_suite_focus=true

I wanted to remove this and reduce the compilation time but after doing a test run where I only added TEST to the README.md it failed like my PR of yesterday. It seems something goes wrong with the debug.keystore:

Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/root/.android/debug.keystore": null

Test run:
https://github.com/bladeoner/mupen64plus-ae/runs/1625620187?check_suite_focus=true

Are you using a Github secret or something or does it get the information from the machine?

**Comment by fzurita** [comment]
I'm using a github secrets. It looks like the secrets can't be used by people outside the organization. It actually kind of makes sense since it would be a security vulnerability otherwise.

**Comment by bladeoner** [comment]
Is it not better for now to not use the debug keystore defined and revert to use the debug keystore from the machine itself?

I know that then we loose the ability to update the emulator directly, but now it's more difficult to test code and send in PR's not only for me but also if others want to do that. Besides that, this is a nightly build, with a nightly build it's not strange to put a little bit more effort to get it working then with a release.

**Comment by fzurita** [comment]
You can define the secret yourself easily. Just define ```DEBUG_KEYSTORE``` with the debug.keystore contents covered to base64.

It's a small extra step, I don't see it as difficult.

**Comment by fzurita** [comment]
Well, I have an easier answer. If ```DEBUG_KEYSTORE``` is not defined, then we can use the one from the machine itself.

**Comment by bladeoner** [comment]
Thank you, I think that is a good solution, I will look into that later, right now I'm testing a build with the DEBUG_KEYSTORE defined.

If it works I will send in some changes which reduces the "Install" step time from almost 2 minutes to 16 seconds.

**Comment by bladeoner** [comment]
@fzurita I was trying to add the DEBUG_KEYSTORE but I didn't manage to get it working.
What did you add to the DEBUG_KEYSTORE secret the SHA1 or the converted base64 value?

I also don't know why the PR is giving an error on uploading the file that there is a / in the filename.
Do you have an idea?

**Comment by fzurita** [comment]
I used this command:
```base64 --wrap=0 debug.keystore > encodedData.txt```

Then I put the contents of encodedData.txt to the secret.

**Comment by fzurita** [comment]
About your error. It appears that ```$(echo ${GITHUB_REF#refs/heads/})``` is not producing the expected output. It's supposed to produce the branch name (```keystore``` for you), but for you, it's output this: ```mupen64plus-ae-refs/pull/883/merge-d5845c786```

I'm not sure why it's not working from your branch when it produces the correct output when perform commits in separate branches.

**Comment by bladeoner** [comment]
Maybe I shouldn't use the name keystore, on my branch it completed succesful.

I will look if I can add the secret, thank you for your help and patience.

**Comment by fzurita** [comment]
I used this way to get the branch name: https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions

Also, it's no problem.

**Comment by fzurita** [comment]
hmmm, there does appear to be a pitfall in the way I'm retrieving the branch name. If you look at the some of the comments to the answer I used, the describe the exact same problem you are having. If you want, you can fix that. They give the answer right in the comments.

**Comment by bladeoner** [comment]
I just opened a new PR with the optimizations I was trying to send in yesterday, the build completed successfully, I hope it will complete successfully in the PR.

I will look into the error I had another moment, need some time to test that.

**Comment by bladeoner** [comment]
It seems the PR failed I think because the debug keystore is not the same, under my branch it completed successfully:
https://github.com/bladeoner/mupen64plus-ae/actions/runs/453445452

It didn't do that earlier today.

**Comment by bladeoner** [comment]
@fzurita I just added the change:
Old value:        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
New value        echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})

Three builds are running two will fail and the third one has this change, I hope it will work.
