### ISSUE TITLE
Faces gone from characters, Super Smash 64

### ISSUE THREAD

**Issue by Sulpexus** [mupen64plus-ae/mupen64plus-ae#887]
Can you please fix this or tell me how to fix it
Donkey Kong, Captain Falcon and Samus are not affected to this bug

![Screenshot_20210107-022157](https://user-images.githubusercontent.com/77094417/103863793-75b0d280-508f-11eb-85e5-827b68664204.png)

![Screenshot_20210107-022142](https://user-images.githubusercontent.com/77094417/103863940-b9a3d780-508f-11eb-8de0-90ffee4b7e9b.png)

![Screenshot_20210107-022247](https://user-images.githubusercontent.com/77094417/103863953-c1637c00-508f-11eb-8e76-2c140d21c8d8.png)

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to
GLideN64-Fast or GLideN64-Medium.

**Comment by Sulpexus** [comment]
I  tried the profiles and they did not work

**Comment by fzurita** [comment]
Ok. Are you using the latest M64Plus FZ in the play store?

**Comment by Sulpexus** [comment]
I have the latest version

**Comment by fzurita** [comment]
Ok, have you tried all different emulation profiles? Maybe one will work for you. But it sounds like you're phone has compatibility issues.

**Comment by Sulpexus** [comment]
I have tried all of them. They had their faces the first time I used the rom

**Comment by fzurita** [comment]
Oh, are you using any cheats?

**Comment by Sulpexus** [comment]
No, but I'm trying to see if It works if I uninstall and reinstall

**Comment by Sulpexus** [comment]
Now it works. I probably messed with it to much and it broke
