### ISSUE TITLE
Super Mario 64 black screen

### ISSUE THREAD

**Issue by Sulpexus** [mupen64plus-ae/mupen64plus-ae#889]
The game worked 2 days ago
When I load it all the controls work and I hear sound, but the screen is black and my fps says 0

**Comment by fzurita** [comment]
Hmm, nothing has changed. First, are you using the latest m64plus FZ? Have you tried "start" instead of "resume"?

**Comment by fzurita** [comment]
Also, have you tried to restart your phone?

**Comment by fzurita** [comment]
No response, so closing.
