### ISSUE TITLE
File Picker Crashes

### ISSUE THREAD

**Issue by TekSoup** [mupen64plus-ae/mupen64plus-ae#890]
I try to add games and it crashes. I made the default folder hiearchy and it still wont work. Thanks

**Comment by fzurita** [comment]
Hello,

What device and Android version are you using?

Are you using the latest version of the app?

 The default folder hierarchy doesn't exist any more.

Are you able to share the logcat after the crash by going to Tools then logcat?

**Comment by TekSoup** [comment]
Sorry to bother, your program from store works, i was pointed here from m64 plus fz pro emulator. Sorry

**Comment by fzurita** [comment]
M64plus fz pro is also by me. It may not work correctly though if it's a pirated version. The pirated versions don't always include all the right assets.

**Comment by TekSoup** [comment]
Android 10, samsung tab s7+ oh ok. No i just bought on play store, i own all my stuff, no pirate here.

**Comment by fzurita** [comment]
Ok, so the pro version doesn't work (crashes) when opening the file picker but the free version does work?

**Comment by TekSoup** [comment]
Not your fault, this Files app is the problem. So its google or samsung. I just tried adding a picture of my reciept to one drive, and it keeps crashing.

**Comment by fzurita** [comment]
Oh, ok, gotcha. Thanks for reporting back.
