### ISSUE TITLE
Add an option to not have to use your IP address for

### ISSUE THREAD

**Issue by RockinRay3305** [mupen64plus-ae/mupen64plus-ae#892]
So I wanna play games online with random people however I don't wanna give ppl my IP address. Please add a way to use a fake IP or at least another way to join without giving someone our IP addresses.

**Comment by fzurita** [comment]
The only way to do that would be to host the netplay server outside your phone. Which would not really be feasible.

The best I can do is allow entering some kind of code to join a game instead of an ip. Someone with a packet sniffer could still get your IP address even if I do that.

**Comment by fzurita** [comment]
The code feature has been added, but currently it requires a UPnP router. Also, not all UPnP routers are compatible.
