### ISSUE TITLE
Ocana of time: Start delay

### ISSUE THREAD

**Issue by Dellruph** [mupen64plus-ae/mupen64plus-ae#895]
No  ocarina of time, quando aperto "Start" demora uns 8 segundos para abrir o menu Start (o normal é 1 segundo). Já testei a mesma rom em diferentes emuladores, e nenhum apresentou esse problema.

**Comment by fzurita** [comment]
Selecciona el juego, anda a opciones, y cambia el perfil de emulacion a GLideN64-Medium.
