### ISSUE TITLE
Lag en ocarina of time 

### ISSUE THREAD

**Issue by 0dinQ** [mupen64plus-ae/mupen64plus-ae#896]
En la reciente actualización 3.0.274 e tenido problemas con el lag 
Usando el perfil de emulación GlideN64 Very-accurate ,es bastante inestable y no puedo usar texturas ya que se pone peor y en la versión anterior no presentaba esos problemas .

 Alguna solución?

**Comment by fzurita** [comment]
Que versión tenías antes de 3.0.274?

No han habido cambios mayores en GLideN64 en varios meses.

**Comment by 0dinQ** [comment]
Pues tengo la versión de paga y no se cual era la anterior a 3.0.274 se actualizan las aplicaciones solas ..justo ayer estaba probando texturas en oot y me iban sin problemas y después de actualizar me va mal

**Comment by fzurita** [comment]
Es posible que cambiaste una configuración?

Anda a opciones y después pantalla. Asegúrate que la resolución no esté más alta que 640x480.

Que celular tienes?

**Comment by 0dinQ** [comment]
La resolución está en ese tamaño y no tengo efectos de pantalla 
Y mi celular es un one plus 6t

**Comment by fzurita** [comment]
Entonces deberías tener buen rendimiento. Has probado reiniciando tu celular?

**Comment by 0dinQ** [comment]
Si lo hice y la única solución que encontré es usar Glide64-accurate pero sin poder usar texturas ya que ningun glide que soporte texturas me va bien 

El lag que me da en el juego es en menú , zonas con agua y más cuando interactuó con ella algunas y algunas zonas con iluminación

**Comment by fzurita** [comment]
Hmm, anda a opciones y después pantalla. Desactive "vídeo multi-hilo para GLideN64". Cómo va eso?

**Comment by 0dinQ** [comment]
Me va un poco mejor ..pero mejor intentaré desinstalar e instalar.
Gracias :))
