### ISSUE TITLE
Start Button

### ISSUE THREAD

**Issue by MatteoGxD** [mupen64plus-ae/mupen64plus-ae#897]
In Paper Mario, pressing start button takes usually takes you to game menu. In MY case, it exits the game without saving. I tried everything! Restart, force stop, clear cache! I dont wanna reinstall it again, i have almost completed the 1st chapter!

**Comment by fzurita** [comment]
Hello, what phone do you have?

Have you tried switching emulation profiles? For example, select the game, go to settings, and try different emulation profiles there.

**Comment by MatteoGxD** [comment]
> Hello, what phone do you have?
> 
> Have you tried switching emulation profiles? For example, select the game, go to settings, and try different emulation profiles there.

So, my phone is Xiaomi Redmi Note 9 Pro, and this never happened before. I have all custom settings, and my profile is Gilde64 Fast.

**Comment by fzurita** [comment]
Ok, have you tried switching the profile to something else?

**Comment by fzurita** [comment]
Closing issue due to no response.
