### ISSUE TITLE
My Rom dosent lode

### ISSUE THREAD

**Issue by luigibros644** [mupen64plus-ae/mupen64plus-ae#898]
My Rom dosent lode An i don't now what to do

**Comment by fzurita** [comment]
What kind of error are you getting?

**Comment by luigibros644** [comment]
I manged to Rim my Roma it was hard but i did it

ned, 28. feb 2021. 03:51 Francisco Zurita <notifications@github.com> je
napisao/la:

**Comment by luigibros644** [comment]
Stuped atou correct

ned, 28. feb 2021. 09:00 Damjan Milutinović <damjandolac@gmail.com> je
napisao/la:
