### ISSUE TITLE
Many issues regarding emulating Donkey Kong 64 Tag Anywhere Mod (v4)

### ISSUE THREAD

**Issue by gogobarril** [mupen64plus-ae/mupen64plus-ae#899]
First of all, thanks to everyone involved with this project. I understand that this Mod is technically **not advised to be used in emulators**, but I wanted to play this game again :c

I'm currently emulating [Donkey Kong 64 TA Mod (v4)](https://www.romhacking.net/hacks/4961/), I patched the [U] rom myself using Lunar IPS. Made sure my [SHA1 checks with the corresponding values before and after applying the patch,](https://www.reddit.com/r/donkeykong/comments/gyrj9p/dk64_swap_anywhere_patch/) resulting in "63a50257bbfef891b362483154f3f1b50f25162d" as the final SHA1. I then used the android emulator (M64Plus FZ Pro) to play the game, for quite some time (reached Fungi Forest boss lol) but then encountered a glitch that forced me to restart the game. Upon loading again, I realize it wasn't saving my progress (no EEP file found on my Google Drive/exporting the game data), so I had to load my last save state to recover my progress.

After a lot of digging online, I found out I have to edit the mupen64plus.ini config file and add the new entry since my Modded Rom now has new Md5 and CRC's. Since I couldn't do it on my android device, I did so in my windows computer, adding this to the end of the file: 

[3296F0787CC274372CED292CF1ACF065]
GoodName=DONKEY KONG 64 TA MOD V4
CRC=77303BA3 C2838723
RefMD5=9EC41ABF2519FC386CADD0731F6E868C

(RefMD5 being the original Donkey Kong 64 [U] so that it can generate the required 16Kbit EEP file)

I was then able to load the same Modded Rom and also load the save state from my android device. However, no EEP save file was generated from mupen64plus on my windows machine. I then loaded the ROM again and a EEP file was created once the game reached the Rareware logo, but it was a new file, it didn't carry my progress from the save state. After a lot of trying to update the EEP file from my save state (pressing "Save Game" from the menu many times, getting a Golden Banana, etc.) it just wouldn't update the file, but restarting the game and starting an empty save file (going through that long demo lol) and later playing the mini games sure updated the EEP file constantly.

I have so many questions! I feel so frustrated too
1. Is there any way (without rooting) to update the mupen64plus.ini file on android? so that I can add the entry for the modded Rom.
2. Is there any way to create an EEP file that is equivalent to my save state data? Something like running it on windows and using a command or something that forces the game to save.
3. Can I convert or edit a save state file so that I can use it on other emulators to maybe generate an EEP file?
4. Is there a way to edit the MD5 and CRC values to the original ROM values so that I can trick Mupen64 into saving?

I apologize if my english is a bit rusty.
I'm providing a copy of my save state [DONKEY KONG 64 TA MOD V4.zip](https://github.com/mupen64plus-ae/mupen64plus-ae/files/6056192/DONKEY.KONG.64.TA.MOD.V4.zip), not sure I can provide the modded rom however.

**Comment by fzurita** [comment]
To answer your questions.
1. No there isn't, but I can add that ROM so that it's in the database in the next release.
2. There is a known issue with DK64 where if save states are used at any point in the game, then the game is unable to save to EEP any more until a new game is started without save states.
3. Not that I'm aware of, you may be able to manually hex edit a EEP file to get what you want, but that's way beyond what I can do.
4. No, there isn't, but I can the ROM you asked for in the mupen64plus.ini in the next version.

**Comment by fzurita** [comment]
I added the game to the data based. A build is in progress. You can grab a development build to try it out from here:

https://github.com/mupen64plus-ae/mupen64plus-ae/runs/1996524050

Once the build is done, you can click on "artifacts" to download it.
