### ISSUE TITLE
Mupen64plus Ae not installed properly

### ISSUE THREAD

**Issue by GachaLloyd** [mupen64plus-ae/mupen64plus-ae#900]
Everybody had this happened.
Whenever you try to play games on this n64 emulator, it says "Mupen64Plus-AE is not installed properly. Please try to reinstall the app."
i even searched this problem on youtube.
nothing showed up.

**Comment by fzurita** [comment]
What's the name of the app that you are using? You really shouldn't be seeing that on the latest version of the official app.

**Comment by GachaLloyd** [comment]
> What's the name of the app that you are using? You really shouldn't be seeing that on the latest version of the official app.

i was using tendo 64.
it was named that way.

**Comment by fzurita** [comment]
Ok, that's a clone of our app. Use this instead: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by GachaLloyd** [comment]
> Ok, that's a clone of our app. Use this instead: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

thanks!

**Comment by GachaLloyd** [comment]
> Ok, that's a clone of our app. Use this instead: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

By the way, People say that the older version of Mupen64plus has the ability to remove Mario's M logo and also add a new savestate on super mario 64, but i need a bit of a help here.
so when i installed the world savestates, 
where do i put those file savestates at?
i cant seem to find the .Mupen64plus-Fz 
file..

**Comment by fzurita** [comment]
It's more complicated due to Android 11 limitations. In Android 11, everything has to be stored in internal private storage.

First create a save state in the game to get the initial files to be generated. Then, go to Tools, then import/export data. There export game data. That will create a mupen64plus-fz folder where you choose.

The mupen64plus-fz will contain all the same stuff as it used and you can modify it. After you are done, import it back by going to Tools, then import/export data, then import game data.

**Comment by GachaLloyd** [comment]
> It's more complicated due to Android 11 limitations. In Android 11, everything has to be stored in internal private storage.
> 
> First create a save state in the game to get the initial files to be generated. Then, go to Tools, then import/export data. There export game data. That will create a mupen64plus-fz folder where you choose.
> 
> The mupen64plus-fz will contain all the same stuff as it used and you can modify it. After you are done, import it back by going to Tools, then import/export data, then import game data.

now this is more helpful, thank you so much!
