### ISSUE TITLE
Unable to export save file 

### ISSUE THREAD

**Issue by Maxpower2727** [mupen64plus-ae/mupen64plus-ae#901]
Hello, I'm unable to export a save file. I get the attached screen when I tap the "export" button and it doesn't do anything. 
![Screenshot_20210305-154910_Files](https://user-images.githubusercontent.com/80131069/110177351-71244400-7dca-11eb-888e-b55931138345.jpg)

**Comment by fzurita** [comment]
Pick a different folder, it will give you an option to export once a different folder is picked. This is an issue with Android 11.

**Comment by Maxpower2727** [comment]
Thanks, that worked.
