### ISSUE TITLE
Xbox Controller stopped working

### ISSUE THREAD

**Issue by melovenmnms** [mupen64plus-ae/mupen64plus-ae#902]
My Xbox One controller stopped working in the games. I have verified that it is not the controller, and I can even us the controller to navigate the mupen64 menu systems. However, when I load a game (Paper Mario 64) the L2 and R2 buttons, the d-pad and both joysticks stop responding. Any suggestions? My phone (Samsung s20) did an update last night, but I haven't used the emulator in about 3 weeks so I am not sure if that is the cause.

**Comment by fzurita** [comment]
This is a known issue with Android 11, not with the app. See here for workarounds:

https://issuetracker.google.com/issues/163120692?pli=1
