### ISSUE TITLE
(Enhancement) Hide Built in Cheats

### ISSUE THREAD

**Issue by SQUISHY6094** [mupen64plus-ae/mupen64plus-ae#904]
Just like the Emulation Profile or the Controller Settings, There would be a "Hide Built-Ins" button for The Cheat settings. Allowing users to easily find their custom cheat codes without having to scroll through a large list.

**Comment by jonathanmasseurca** [comment]
https://github.com/mupen64plus-ae/mupen64plus-ae/pull/932
