### ISSUE TITLE
Majoras mask Bug

### ISSUE THREAD

**Issue by Dellruph** [mupen64plus-ae/mupen64plus-ae#905]
No templo da floresta quando entro na porta ao norte da sala com uma flor gigante, o jogo crasha tentei de tudo, mudar plugin, configurar plugin, mexer no vídeo, nada resolveu. É IMPOSSÍVEL progredir no jogo assim.

**Comment by fzurita** [comment]
Traduzido: Olá, você está usando um hack de ROM? A tradução em português não é compatível com o app.
