### ISSUE TITLE
Posted it on reddit, as well as asked to the creator, but there are issues with SM64 Rom hacks

### ISSUE THREAD

**Issue by Quix64** [mupen64plus-ae/mupen64plus-ae#906]
Hi, so posting this here, I'm using an M64Plus Fz, to check an issue i have with the sm64 rom hacks, glide64, while it runs the games pretty well, has graphical issues, I'm going to link some of them

https://cdn.discordapp.com/attachments/818304611336192004/829810309908398181/Screenshot_20210408-150605_M64Plus_FZ.jpg https://cdn.discordapp.com/attachments/818304611336192004/829810310222315580/Screenshot_20210408-150622_M64Plus_FZ.jpg https://cdn.discordapp.com/attachments/818304611336192004/829810310722486293/Screenshot_20210408-150721_M64Plus_FZ.jpg https://cdn.discordapp.com/attachments/818304611336192004/829811023367634944/Screenshot_20210408-151213_M64Plus_FZ.jpg

Well, i tried to use the rice plugin, but well it's laggy, while it works with the graphics, the lag is now there, GLn64 has lag and graphical glitches too, GlideN64 doesn't even work, and same with the software render, i was wondering if you could do two things, one, try to see if there's a fix with Glide64 with graphica, or two, see of there's a way to improve the rice plugin to be a lot less laggy, i will appreciate that

**Comment by fzurita** [comment]
I'm not planning on improving support for ROM hacks. The ROM hacks that you have mentioned don't really work on console. They were coded for specific video plugins and emulators in mind. 

What kind of phone do you have? If Rice is laggy then it may just be your phone.
