### ISSUE TITLE
Zelda's texture bug

### ISSUE THREAD

**Issue by JotaroJoe** [mupen64plus-ae/mupen64plus-ae#907]
There's a texture bug on zelda's face in zelda OOT when I use glide64 emulator

**Comment by fzurita** [comment]
Can you post a screenshot? What device do you have? Glide64mk2 is known to have many bugs in many games, but it's not actively maintained, so not many fixes for it are done. So your best course of action is to try a different video plugin by switching emulation profiles.

**Comment by JotaroJoe** [comment]
> Can you post a screenshot? What device do you have? Glide64mk2 is known to have many bugs in many games, but it's not actively maintained, so not many fixes for it are done. So your best course of action is to try a different video plugin by switching emulation profiles.

Strange things happens. The bug is just gone, the zelda's face is now back to normal. anyway, here's another bugs that I found while I was playing

![Screenshot_20210507-141558_M64Plus FZ](https://user-images.githubusercontent.com/71591308/117414167-082f8880-af41-11eb-9216-579966c32067.jpg)
![Screenshot_20210507-142658_M64Plus FZ](https://user-images.githubusercontent.com/71591308/117414177-0b2a7900-af41-11eb-981d-83700a2adc84.jpg)

**Comment by JotaroJoe** [comment]
I tried another emulations too. And It's more buggy than the emulator I use before. This time I use gln64 and rice. They has the same bugs. Here's the bugs that I found

![Screenshot_20210507-135352_M64Plus FZ](https://user-images.githubusercontent.com/71591308/117414453-58a6e600-af41-11eb-86a5-0801e4e34132.jpg)

**Comment by JotaroJoe** [comment]
I tried gliden64 too and the result is not bad, but everytime I entered the load profile menu, the game's laggy. I've got 10/60 fps. I tried every version of gliden64, from fast to very accurate one and the result is they has the same issue

**Comment by fzurita** [comment]
Yeah, GLideN64 is going to be slower. It needs a faster device, but it will give you the best results. You can also use the software renderer emulation profile and that will be the most accurate but it will have the worst performance on slower devices. Which phone do you have? Also, are you using m64plus FZ?

**Comment by JotaroJoe** [comment]
> Yeah, GLideN64 is going to be slower. It needs a faster device, but it will give you the best results. You can also use the software renderer emulation profile and that will be the most accurate but it will have the worst performance on slower devices. Which phone do you have? Also, are you using m64plus FZ?

Samsung A10, yes I use M64plus FZ

**Comment by fzurita** [comment]
I will go ahead and close this issue since I don't plan on fixing it. It's also an issue with the upstream plugin. GLideN64 is the future, I just hope that lower end devices catch up to the performance needed.
