### ISSUE TITLE
Donkey Kong 64 not saving on SRAM.

### ISSUE THREAD

**Issue by matheusstaffa** [mupen64plus-ae/mupen64plus-ae#908]
After playing for some hours the game stopped saving on the .eep file and everytime i need to save, i have to use only save states. Is there anyway to make the game save properly? I Attached the save states files.[Donkey Kong 64 (U) [!].zip](https://github.com/mupen64plus-ae/mupen64plus-ae/files/6459683/Donkey.Kong.64.U.zip)

**Comment by fzurita** [comment]
Which version of DK64 are you using? If it's the tag anywhere version, it's because the game is not in the database yet.

**Comment by danielristic** [comment]
Just the regular no-intro European version of the game.

**Comment by fzurita** [comment]
Gotcha, yeah, once the game gets into that state, it's hard to recover. The only way to save from then on is save states.

I believe this is triggered in that game when using save states due to some bug in the save state system that has not been found.

**Comment by danielristic** [comment]
Got it, thanks for the explaination!
