### ISSUE TITLE
Toy Story 2 Graphic Error

### ISSUE THREAD

**Issue by ShadowLinkMan** [mupen64plus-ae/mupen64plus-ae#91]
I was testing some games I had to see if they would work and I tried running toy story 2.  I switched it to the gles2rice plugin to get it working and when I entered the game I noticed that the bottom half of the screen was glitchy but worked, but the top half was as if a picture was pasted over it and other times was fine .  Wanted know if there was a fix or not.

**Comment by fzurita** [comment]
Upstream issue
