### ISSUE TITLE
Issue with Quake 64

### ISSUE THREAD

**Issue by Blurrypinkfloydian** [mupen64plus-ae/mupen64plus-ae#919]
Whenever I go underwater the game screen freezes, that usually results in me dying since I'm unable to see what's happening

**Comment by Blurrypinkfloydian** [comment]
Btw If you're wondering i use M64 Plus FZ

**Comment by Blurrypinkfloydian** [comment]
And my phone Is a Xiaomi Redmi note 10

**Comment by fzurita** [comment]
Select the game, go to settings, change the emulation profile to GLideN64-Medium.
