### ISSUE TITLE
Nuclear Strike 64 does not run!

### ISSUE THREAD

**Issue by flohtod** [mupen64plus-ae/mupen64plus-ae#92]
The game "Nuclear Strike 64" does not run. 
It is working till the point in the game I want to start the mission. 
The rest before is running without problems or stops or something like that.
I have tested it with 2 versions of rom: .v64 and .z64. For both the same problem: stopping of emulation on the same point of game.
I have got a Galaxy S1 with CM 10.1. Is my old phone the reason?

**Comment by fzurita** [comment]
Upstream issue
