### ISSUE TITLE
Perfect Dark weapon change stutter

### ISSUE THREAD

**Issue by Nejsplitter** [mupen64plus-ae/mupen64plus-ae#920]
When switching weapons the game stutters slightly on default count per op(you will notice it if you turn in a circle while weapon switching), on count per op 1 the weapon switching is flawless, my device is a snapdragon 765g with adreno 620, did the original n64 lag when switching weapons in perfect dark ? im wondering does mupen actually use the count per op exactly as the n64 did, maybe its somwer between 1 and 2 and is it possible to set custom count per op like 1 and half?

**Comment by fzurita** [comment]
Good question, I'm not sure about how it ran on the original N64, this is the first I hear of this stutter.

Count per op is really an approximation since the core is not cycle accurate. It's not possible right now to have a count per op that is in between two numbers, although it may possible in the future.

**Comment by Nejsplitter** [comment]
@fzurita i just realised the weapon switching is flawless on original hardware and it is most likely a cycle accuracy thing on mupen, because if i switch count per op to 1 the issue goes away just like an n64 but on count per op 1 its not accurately resembling an n64 either as it is too fast, maybe @goenetz could say something too ?

**Comment by fzurita** [comment]
I doubt gonetz would have much to say. You will probably see this in other video plug-ins well. Based on your description, it seems purely like a cycle accuracy issue.

**Comment by Nejsplitter** [comment]
understood, thank you for the fast replies and thanks for your work :)
