### ISSUE TITLE
Yoshi's story graphics glitch with gliden64, has abismal frame rate when using software renderer

### ISSUE THREAD

**Issue by Blurrypinkfloydian** [mupen64plus-ae/mupen64plus-ae#921]
Hi i write again because although i mainly have a issue with Yoshi's story i also have issues with software renderer working marvelously except for the absurdly low frame rate and slowdowns, which i find unusual since it's less graphically demanding than other emulation profiles, anyways my issue with Yoshi's story is that the gliden64 profiles basically don't work with Yoshi's story, it has glitched graphics rendering it unplayable, and while software renderer has none of these issues it has the frame rate problem i mentioned

**Comment by fzurita** [comment]
The software renderer actually has much higher requirements than all other video plugins.

Can you post screenshots of the issue you are seeing?

**Comment by Blurrypinkfloydian** [comment]
Hold on

**Comment by Blurrypinkfloydian** [comment]
![Screenshot_2021-07-29-20-52-31-196_org mupen64plusae v3 fzurita](https://user-images.githubusercontent.com/87978611/127579710-8aadce94-e81f-4ad0-924d-6f5c86fbe453.jpg)

**Comment by Blurrypinkfloydian** [comment]
![Uploading Screenshot_2021-07-29-20-52-17-665_org.mupen64plusae.v3.fzurita.jpg…]()

**Comment by fzurita** [comment]
OK, it looks like you are using Glide64 based on the glitches I see here. Try using Glide64-Accurate or GLideN64-Medium.

**Comment by Blurrypinkfloydian** [comment]
I will update you

**Comment by Blurrypinkfloydian** [comment]
Chose glide 64 accurate and this happened
![Uploading Screenshot_2021-07-29-21-00-40-722_org.mupen64plusae.v3.fzurita.jpg…]()

**Comment by Blurrypinkfloydian** [comment]
![Uploading Screenshot_2021-07-29-21-00-40-722_org.mupen64plusae.v3.fzurita.jpg…]()

**Comment by Blurrypinkfloydian** [comment]
![Screenshot_2021-07-29-21-00-40-722_org mupen64plusae v3 fzurita](https://user-images.githubusercontent.com/87978611/127580262-1def13d4-5230-4197-a225-be53c66450aa.jpg)

**Comment by fzurita** [comment]
Which version of the app are you using? I'm not seeing those glitches with the latest version.

**Comment by Blurrypinkfloydian** [comment]
Same issue in medium mode, tho it is limited to one part of the level, and medium also runs slower

**Comment by Blurrypinkfloydian** [comment]
I tried out rice accurate and it pretty much fixed all my issues, except now there's this weird square outlines everywhere in the screen

**Comment by Blurrypinkfloydian** [comment]
![Screenshot_2021-07-29-21-11-38-810_org mupen64plusae v3 fzurita](https://user-images.githubusercontent.com/87978611/127580908-981db032-4a23-459c-baee-aed8d7fde4b8.jpg)

**Comment by Blurrypinkfloydian** [comment]
Also nvm i still see a good chunk missing you

**Comment by fzurita** [comment]
Go to "About" then "App version". Which certain of the app do you have?

**Comment by Blurrypinkfloydian** [comment]
3.0.288

**Comment by fzurita** [comment]
It could be a bug with your gpu driver. Which phone do you have?

**Comment by Nejsplitter** [comment]
based on the users previous issue, they have mentioned they use a xiaomi redmi note 10 which uses a snapdragon 678 with adreno 612 gpu

**Comment by Nejsplitter** [comment]
based on the users previous issue, they have mentioned they use a xiaomi redmi note 10 which uses a snapdragon 678 with adreno 612 gpu

**Comment by fzurita** [comment]
Thanks, and that's a really underpowered GPU.

I'm not sure why that phone has issues. 

@Blurrypinkfloydian go to settings then display. Change the resolution to 320x240. Do you still get the issue with all the plugins?

**Comment by Blurrypinkfloydian** [comment]
Hmmm hold on

**Comment by Blurrypinkfloydian** [comment]
It seems to have fixed it, i guess i have a really shitty GPU lmao, i own a budget phone tho so it's no surprise.
