### ISSUE TITLE
mario tennis slowdown

### ISSUE THREAD

**Issue by Nejsplitter** [mupen64plus-ae/mupen64plus-ae#925]
the game runs flawlessly and smoothly at native res, fps stays constant, when i put the native res at 2x or higher the fps stays constant however the game slows down(no stutteron audio) like frame skipping when the ball effects come on yet fps stays constant.
its only during the ball effects that it, frame skip type slowdown for a second (only visually), the fps stays constant even during this short moment which is strange.

snapdragon 765g adreno 620 android 11

**Comment by fzurita** [comment]
That's a demanding game. Which video plugin are you using? There is probably not much I can do either way.

**Comment by Nejsplitter** [comment]
@fzurita gliden64, the thing is ther is absolutely no slowdown like in other games wher audio is garbled and video is skippy , its different its like frame skip slowdown while the ball effects are on only and only in 2x or higher, will i record it

**Comment by Nejsplitter** [comment]
it confuses me because for slowdowns im used to the audio stuttering too so i accept it but this one im not sure

**Comment by Nejsplitter** [comment]
hmmmm interesting, iv just got the same result with goldeneye when i put it at 4x i think it maybe a gpu thing but why is the sound flawless ?

**Comment by fzurita** [comment]
If you set the game speed to 250%, does the game go below 100% speed when the slowdown happens?

**Comment by Nejsplitter** [comment]
il check...

**Comment by Nejsplitter** [comment]
sound stretching is off, i just put it to 250 speed and it went below 100% in them instances with effects

**Comment by fzurita** [comment]
OK, your GPU is just not keeping up.

**Comment by Nejsplitter** [comment]
interesting, sound is flawless at normal speed with frame skip type slowdown during ball effects yet stutters at 250 and goes under 100%

**Comment by fzurita** [comment]
It will stutter if you turn off audio time stretching.

**Comment by Nejsplitter** [comment]
yes its the gpu , that 250 speed test nailed it, thank you francisco, can i just ask you here real quick also, do you know games like perfect dark that have internal hires options, is it best just to leave them off and just use gliden64 own native res upscales ?

**Comment by fzurita** [comment]
Yeah, leave the game's high res option off.

**Comment by Nejsplitter** [comment]
thank you
