### ISSUE TITLE
Goldeneye fog error

### ISSUE THREAD

**Issue by Nejsplitter** [mupen64plus-ae/mupen64plus-ae#926]
Gliden64 very accurate, sd765g andreno620, android 11

only the assets have the correct distance fog texture but the environment should have it too
![Screenshot_2021-08-05-01-29-16-200](https://user-images.githubusercontent.com/85600282/128273024-d583ae76-6c02-4128-8541-f60966e96619.jpg)

**Comment by Nejsplitter** [comment]
when i change rspe from hle to parallel its correct

![Screenshot_2021-08-05-01-41-20-781](https://user-images.githubusercontent.com/85600282/128273458-2b3ade1d-2ff0-4670-98d4-661e6bf9a332.jpg)

**Comment by gonetz** [comment]
Yes, you opened an issue about it:
https://github.com/gonetz/GLideN64/issues/2547
