### ISSUE TITLE
Goldeneye menu texture

### ISSUE THREAD

**Issue by Nejsplitter** [mupen64plus-ae/mupen64plus-ae#928]
![Screenshot_2021-08-06-01-41-15-232](https://user-images.githubusercontent.com/85600282/128439794-f4c925be-b6a4-4e8e-bdf9-da88a61c3919.jpg)
on initial startup the menus are always fine but after completing or failing a mission and returning to menu the textures are wrong, even saving a savestate on the error moment then closing the emulator and loading that savestate fixes the texture.

SD765g, adreno 620, android 11, M64PlusAE, Gliden64 very accurate

**Comment by fzurita** [comment]
I'm not seeing this problem. Do you see it with GLideN64-Fast?

**Comment by Nejsplitter** [comment]
hmm interesting, and you are using gliden64 very accurate with hle too ? heres my settings, sorry i couldnt find the cfg file lol 

![Screenshot_2021-08-06-15-03-56-537](https://user-images.githubusercontent.com/85600282/128522634-eb431f7a-dcf7-4445-9cd1-fcaa75cfcaa5.jpg)
![Screenshot_2021-08-06-15-04-08-090](https://user-images.githubusercontent.com/85600282/128522661-b89988e9-ca66-40f4-8a5f-9e7a6c53a264.jpg)
![Screenshot_2021-08-06-15-04-38-774](https://user-images.githubusercontent.com/85600282/128522671-3c45141b-e4c1-4e28-9264-cc35c3210e36.jpg)
![Screenshot_2021-08-06-15-04-56-756](https://user-images.githubusercontent.com/85600282/128522691-a512f7d1-5626-416a-bb65-ca639a2c3fde.jpg)
![Screenshot_2021-08-06-15-05-04-769](https://user-images.githubusercontent.com/85600282/128522710-dc6925aa-da44-4874-960e-891b3f431de0.jpg)

**Comment by Nejsplitter** [comment]
i tried again just now, start the game, menu is fine, start a mission and quit the mission-menu is wrong so i do a savestate on wrong menu and close emulator and load save state and texture is fine, this is strange

**Comment by fzurita** [comment]
OK, try disabling N64 depth comparte. I believe it causes the issue you see.

**Comment by Nejsplitter** [comment]
nice work man, but that led me into another issue, disabling depth compare deals with the original issue but now on some levels without depth compare its possible to see assets through assets

**Comment by fzurita** [comment]
Can you take a screenshot of that?

**Comment by Nejsplitter** [comment]
![Screenshot_2021-08-06-18-32-18-456](https://user-images.githubusercontent.com/85600282/128550078-cfec552d-a092-46a4-b5f3-f1cd695ef6f6.jpg)
![Screenshot_2021-08-06-18-32-37-688](https://user-images.githubusercontent.com/85600282/128550091-30354290-e87f-4a31-8519-f31d20b2509c.jpg)
on the first image its possible to see through the wall slightly at certain angle with depth compare off, on second image its possible to see through the ground texture through the little downward ramp

**Comment by fzurita** [comment]
Gotcha, yeah, N64 depth comparte does need to be improved to try to prevent the type of situation you describe.

**Comment by Nejsplitter** [comment]
i think its best if its left to on by default as it still works really well and will provide to optimal experience for most users i think

**Comment by Nejsplitter** [comment]
understood, well we found the problem anyway

**Comment by Nejsplitter** [comment]
understood, so do we look at both issues here as depth compare issues or seperate issues? cheers

**Comment by fzurita** [comment]
Technically speaking, these are upstream issues. So it's probably better if issues are made in the GLideN64 github page.

They should also be separate issues.

**Comment by Nejsplitter** [comment]
understood, thanks man
