### ISSUE TITLE
Controller issue after change

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#938]
Hi @fzurita I hope you are doing fine.

After yesterdays change "[Change scaling of input x and y axis to -1.0 to 1.0](https://github.com/mupen64plus-ae/mupen64plus-ae/commit/8c4153fe7b30fabba0c1e63fa8ec0d604c196967)" my 8bitdo SN30 Pro+ controller stops functioning.

What happens is that the analog sticks seems to be locked at some point and then you cannot use it for a moment and then it works and it stops and so on.

**Comment by fzurita** [comment]
OK, thanks for reporting this. I will take a look.

**Comment by fzurita** [comment]
Fixed: 89641c725c7df1630efcb684ccf3a8a929f97e24
