### ISSUE TITLE
No escucho el juego en mis auriculares, help. 

### ISSUE THREAD

**Issue by Bluemarieeee** [mupen64plus-ae/mupen64plus-ae#941]
No puedo escuchar el juego en el emulador en mis auriculares. No sé si sea por la rom (Majora's Mask) o por el emulador.

**Comment by fzurita** [comment]
Y se escucha bien sin los auriculares?

Has probado conectando los auriculares antes de comenzar el juego?

**Comment by Bluemarieeee** [comment]
Si lo he probado, incluso los conecté y puse música, la quité, volví a probar y nada

**Comment by fzurita** [comment]
Puedes hacer unas pruebas? Conecta los auriculares antes de empezar el juego y oportuna su hay sonido.

Conecta los auriculares después de comenzar el juego y prueba su hay sonido.

Que celular tienes?

**Comment by Bluemarieeee** [comment]
Huawei Y9s

**Comment by fzurita** [comment]
Just to make sure, are you using this app? https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Bluemarieeee** [comment]
Of course @fzurita

**Comment by Bluemarieeee** [comment]
Tuve que borrar la rom de la aplicación y volverla a permitir dentro de la app, no se como pero al parecer eso lo arregló.
