### ISSUE TITLE
Graphics problem.

### ISSUE THREAD

**Issue by master1274** [mupen64plus-ae/mupen64plus-ae#981]
Star Wars Episode I - Racer (U) [!]  Dark areas. GlideN64 Very Accurate. The rest of the settings are default. The only problem is AE build, in FZ absent. 
[Device:]
![Star Wars Episode I - Racer (U)  !  (FZ)](https://user-images.githubusercontent.com/20639709/144737225-43098e49-e980-4899-bae2-18443f037f68.png)
![Star Wars Episode I - Racer (U)  !  (AE)](https://user-images.githubusercontent.com/20639709/144737232-a65dbec0-1cbc-49d3-8c10-13d40611c3a4.png)
 NVIDIA Virtual Mouse
Id: -3
Descriptor: 5345c6da1d26ddaf0af78bf97d14a420216933cb
Class: BUTTON, POINTER
Axes: 3
  AXIS_X (mouse): ( 0.0 , 1919.0 )
  AXIS_Y (mouse): ( 0.0 , 1199.0 )
  AXIS_PRESSURE (mouse): ( 0.0 , 1.0 )

Device: Virtual
Id: -1
Descriptor: a718a782d34bc767f4689c232d64d527998ea7fd
Class: BUTTON

Device: gpio-keys
Id: 2
Descriptor: 485d69228e24f5e46da1598745890b214130dbc4
Class: BUTTON

processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc0f
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc0f
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc0f
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc0f
CPU revision	: 3

Hardware	: tn8
Revision	: 0000
Serial : XXXX
Processor	: ARMv7 Processor rev 3 (v7l)

Board: unknown
Brand: nvidia
Device: shieldtablet
Display: NRD90M.1928188_1065.2559
Host: mobile-u64-710
ID: NRD90M
Manufacturer: NVIDIA
Model: SHIELD Tablet
Product: wx_un_do

**Comment by fzurita** [comment]
Is the problem present in GLideN64-Accirate?

**Comment by fzurita** [comment]
I created an issue upstream:

https://github.com/gonetz/GLideN64/issues/2615
