### ISSUE TITLE
External Storage Support (Android 11)

### ISSUE THREAD

**Issue by mrdeathjr28** [mupen64plus-ae/mupen64plus-ae#986]
My external usb devices dont detected in mupen64plus-ae using android 11 maybe scooped storage related issue?

**Comment by fzurita** [comment]
That would be an OS level issue. I have no control over what the built in Android file browser chooses to display.

Sometimes there are options to show external storage in the built in OS file browser, make sure you have those enabled.

**Comment by mrdeathjr28** [comment]
yeah in other emus appear correctly maybe this topic can stay related (dolphin issue with scooped storage):

https://bugs.dolphin-emu.org/issues/12764#change-743465

**Comment by fzurita** [comment]
Well, most other emulators don't use scoped storage.

**Comment by killerz298** [comment]
Is this issue being worked on or am I missing an easy fix to this? My Nvidia Shield just got updated to Android 11 and now I can't get this app to see my external storage which is where my ROMs are stored. The only option it gives me is to store the ROMs on the Shield itself, which doesn't have enough space. Seems like this is happening to many apps with the Android 11 update. Any info would be appreciated. 

https://www.reddit.com/r/ShieldAndroidTV/comments/s3jg2b/android_11_application_issues/

**Comment by fzurita** [comment]
Yeah, I'll release an update today with SAF file browser support enabled for Android TV. I had it disabled before for Android TV because of poor user experience. I have no choice now since Android 11 requires it.

**Comment by killerz298** [comment]
Many thanks. I'm currently looking for a way to rollback this update on the Shield and go back to Android 9 which worked fine for me. I don't see any additional benefits while using this new version anyway.

**Comment by fzurita** [comment]
If you are still on Android 11, feel free to try again.

**Comment by killerz298** [comment]
> If you are still on Android 11, feel free to try again. I just released an update.

Yeah, still on it. Looking for a way to revert this nonsense. Your fix worked within the emulator itself. I needed to hook up my actual keyboard with touchpad to enable the option but it worked. However, the frontends like Arc Browser or Launchbox can no longer pull up the emulator to start the game so I'll have to wait for them to get their act together or revert back to Android 9. Thanks for the quick response. At least I can pull up the gamed directly using the emulator now.
