### ISSUE TITLE
Castlevania: Legacy of Darkness (USA) - Invincible-after-one-attack (even if it misses) enemy bug

### ISSUE THREAD

**Issue by TTLTTLR** [mupen64plus-ae/mupen64plus-ae#989]
Current emulator version: 3.0.303 (beta)-free

On a previous version of the emulator I started the game and got halfway through the Forest of Silence (in Cornell Mode), but as I was checking out some cheat codes it auto-updated and the all/infinite-items code, which apparently causes key items to become unusable, became enabled (though I hadn't enabled it; the cheat settings sort of got messed up by that update, but fortunately the last few haven't caused this sort of problem), and the effects of the code couldn't be undone through the use of save states, so I restarted from a state I had saved when I first loaded the game up, and after entering the deck of the ship in the Foggy Lake, I encountered a game-breaking bug: The skeleton that appears standing on a door in the floor becomes invulnerable to attacks after a hit is attempted on it (even if it misses). I did hit it on the first try a lot of times, but regardless of whether I use the primary or secondary attacks or throw an axe at it or slide into it, only the head comes off (tried using the maximum-powerup codes too, but still just the head). If I use the primary or secondary attacks it just "dodges" left or right, and if I use an axe (or probably any sub-weapon) it just disappears as if it had hit a wall. As it needs to be defeated in order to proceed, the game has become unfinishable; I restarted again (from the same save state) and the problem persists.

**Comment by fzurita** [comment]
Can you use the "start" option without any cheats and without any save states and see if you have the same problem?

**Comment by TTLTTLR** [comment]
Yeah, it worked! 👍
