### ISSUE TITLE
Issues accessing files on Android 11

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#992]
Hi @fzurita,

I know you are using a Nvidia Shield TV as well, did you upgrade yours already to Nvidia Shield Experience 9.0?

It seems that file access has changed in Android 11 on the Nvidia Shield TV you cannot Access the roms if they are located on a usb disk used as a internal drive or the internal drive itself.

Do you know how we can work around this issue?

https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481782/shield-experience-upgrade-90-known-issues/

Thanks in advance.

**Comment by fzurita** [comment]
Check the latest version of the app. I was forcing the legacy file browser in Android TV even when the underlying OS is Android 11 because the user experience with a controller was terrible when using the SAF file browser.

In the latest update I force the user to use the SAF file browser for all devices that have an underlying OS of Android 11 or higher. This will be a somewhat poor experience since now you require a mouse hooked up to the device to browse for files on Android 11.

**Comment by bladeoner** [comment]
Thanks for your quick response, I am using the latest version but I didn't know a mouse is required to move around in the SAF file browser, I will to test that.

**Comment by bladeoner** [comment]
@fzurita I tried to create a new folder or put a file in the Documents folder but I cannot find roms using the SAF file browser, any idea?

**Comment by fzurita** [comment]
Can you show me a video of what you are doing?

I have been able to use it ok and other users have been able to as well.

Have you tried this app to get to the menus on the left side?
https://play.google.com/store/apps/details?id=com.nvidia.shield.remote

**Comment by bladeoner** [comment]
I think I found the issue, the format option in the Nvidia Shield TV doesn't seem to have formatted the USB drive correctly I formatted the drive outside the Nvidia Shield and I am still testing it, takes some time.

I didn't use the Nvidia Shield Remote before, thanks for the tip.

I will let you know how it goes.

**Comment by bladeoner** [comment]
Even after reformatting and do a factory reset I cannot see the folder created from the Shield on de PC and visa versa.

For now I will close the issue because I think it is a bug in the Shield.

**Comment by bladeoner** [comment]
@fzurita I think what I'm experiencing is fixed with the following in de Nvidia Shield experience 9.0 hotfix:
Resolves issue with connecting to SHIELD over local network does not show content in adopted storage

https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481434/shield-experience-upgrade-90-hotfix-image/

I tried browsing in the SAF file explorer using the Nvidia Shield remote app but I don't see the files copied to the external hdd which is configured to be used as an internal drive.
When I remove the external harddrive I can see the files so it seems the map structure of the internal storage and the external hdd doensn't match like the issue describes.

**Comment by fzurita** [comment]
Ok, interesting. I'm not sure what I can do from my side.

**Comment by bladeoner** [comment]
At this point I think we can only wait for the update to be released.

I wanted to ask, what folder does the SAF file browser use by default?

**Comment by fzurita** [comment]
It's usually the root of your internal storage.

**Comment by bladeoner** [comment]
Is it an idea to see if it can be redirected to for example the Documents folder?

**Comment by bladeoner** [comment]
@fzurita the issue I was experiencing has been resolved with the Nvidia Shield experience 9.0 hotfix release 3:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481434/shield-experience-upgrade-90-hotfix-image/

**Comment by fzurita** [comment]
Great, good to know.
