### ISSUE TITLE
File size increased a lot

### ISSUE THREAD

**Issue by bladeoner** [mupen64plus-ae/mupen64plus-ae#997]
@fzurita I'm not sure why but the filesize increased from around 30 MB to 84 MB is that correct?

**Comment by bladeoner** [comment]
It seems to have something to do after this commit:
[Update to the latest Android Studio version](https://github.com/mupen64plus-ae/mupen64plus-ae/commit/5dc63d4249a53e861a65e6ad7236fcb5d29d04f5)

**Comment by fzurita** [comment]
Thanks for letting me know. I'll look into it.

**Comment by fzurita** [comment]
This seems to be a bug with the latest Android Studio gradle version. It seems like even in a release build debug versions of libraries are being included no matter what I do...

**Comment by bladeoner** [comment]
@fzurita it seems that with the last [commit](https://github.com/mupen64plus-ae/mupen64plus-ae/commit/79af453cf8cd7c942c9bd15841d8c13511b4125c) you fixed the size it is now around 30 MB, thanks!
