### ISSUE TITLE
Grabados de la tumba Darmani se sobreponen en Majora's Mask 

### ISSUE THREAD

**Issue by caldivargas** [mupen64plus-ae/mupen64plus-ae#999]
Al llegar a la tumba de Darmani los grabados de su tumba se superponen en su cuerpo al usar la lente de la verdad, había leído que el los perfiles glide64 no muestran ciertas hadas del pico nevado así que cambie a gliden64-medium, sin embargo el defecto solo ocurre en gliden64, mientras que en glide64 se muestea correctamente.

![IMG_20220201_062721](https://user-images.githubusercontent.com/78030406/151968283-e53c7083-f401-4853-8099-914d073a067c.jpg)
![IMG_20220201_062456](https://user-images.githubusercontent.com/78030406/151968325-2848dd17-5c46-4ae8-808a-4d486cbd40e6.jpg)

M64plus FZ última versión gratuita
Render resolution: 640x480
Dispositivo: Oneplus3T
Snapdragon 821 6Gb ram Adreno 530

Rom: Legend of Zelda, The - Majora's Mask (Europe) (GameCube).z64 con parche de Aroenai, ozidual.(arregla bugs de crasheo y reemplaza ciertas texturas que habían sido modificadas en gamecube https://www.romhacking.net/hacks/2962/ )

**Comment by fzurita** [comment]
Si, parece como un problema. Puedes mandarme una guardo de estado del juego?

**Comment by caldivargas** [comment]
#![Screenshot_20220201-073521.jpg](https://user-images.githubusercontent.com/78030406/151978059-2c99a9de-5413-4ad4-8469-0627c3abcc4e.jpg)

¿Toda la carpeta?

**Comment by caldivargas** [comment]
https://drive.google.com/file/d/1RO4uqbhcoU57nRbLzI-HbLlUO7vYawIb/view?usp=drivesdk

**Comment by fzurita** [comment]
Si gracias, ojalá que sea justo en ese lugar.

**Comment by caldivargas** [comment]
Tengo otra pregunta, recomiendas alguna información para comprender las opciones de configuración de gliden64, sólo encontré un blog (http://gliden64.blogspot.com/2019/04/public-release-40.html?m=1) pero quiero comprender mejor la categoría de las opciones de Frame Buffer para mejorar mi experiencia jugable. Ya que tengo entendido que Majora's mask hace uso extensivo de el.

**Comment by fzurita** [comment]
Si copias el GLideN64-Very-Accurate, ese tiene todas las opciones recomendadas habilitadas. Quizás cambiaría las opciones de "copiar bufer de color a RDRAM" a modo sincronizado. Pero, dependiendo en tu dispositivo, eso puede hacer juegos correr más lento.

**Comment by caldivargas** [comment]
Si, baja el rendimiento, al usar el lente de la verdad produce tirones hasta 12 o 10 fps, el Gliden64-medium con ciertas opciones del Acurrate estaba funcionando a 20-19 fps estables con tirones puntuales en el audio.¿Las opciones por default del audio son las más precisas o las más rápidas? 

Ahora toca entender como se puede solucionar ese error gráfico,¿tendrá algo que ver la profundidad? ¿Hay una mejora del glide64 final que no ha sido implementada en el gliden64?
